### ISSUE TITLE
Can't find running on windows directions in english anymore

### ISSUE THREAD

**Issue by stupidAppiumGuy** [appium/appium#10103]
http://appium.io/slate/en/master/#running-on-windows.md is a broken link now, which is the link I used from this page : http://appium.io/getting-started.html

I can still find the chinese version : https://appium.io/docs/cn/appium-setup/running-on-windows/.... But sadly I cannot read chinese
:/

**Comment by imurchie** [comment]
Sorry about that. Try http://appium.io/docs/en/drivers/android-uiautomator2/

**Comment by dpgraham** [comment]
I'll look into this. You can refer to this for now: https://github.com/appium/appium/blob/71fac8d2759b18bb2a506a5c8359bfdf41a6443b/docs/en/appium-setup/running-on-windows.md

**Comment by dpgraham** [comment]
I think the link provided (http://appium.io/getting-started.html) is outdated now and you should be reading this link: http://appium.io/docs/en/about-appium/getting-started/?lang=en

I figured this out because when you navigate to `https://appium.io` and click `Get started` it takes you to the latter link.

@stupidAppiumGuy Is that a bookmarked link you're using?
