### ISSUE TITLE
Android Hybrid App-Chrome-Tab-Unable to identify elements in web-view 

### ISSUE THREAD

**Issue by NavdeepKGill** [appium/appium#10193]
In android emulator having set the compatible chrome and chromedriver, I'm not able to find web-elements? 

* Appium version :1.7.2

* OS version  and Platform used to run Appium: Android:7.1.1
* Run on emulator/simulator:

Certain pages of my app loads in chrome custom tab, and I get following available contexts on loading such a page:

[**NATIVE_APP, WEBVIEW_com.google.android.gms, WEBVIEW_app-pckg, WEBVIEW_chrome**]
On switching to WEBVIEW_chrome, I'm getting more than 1 window handles. I iterate through each one of them to find my element. But all goes for a fail here, after switching contexts and searching all available windows, I'm not able to window with my expected page source.

Do I need to get some property enabled for webview debugging? I've discussed regarding setting getWebContentsDebuggingEnabled as true, but as per the developer this property can be associated with app specific web-views WEBVIEW_app-pckg and not the chrome tab one.

ChromeDriver Logs:[Log File](https://gist.github.com/NavdeepKGill/0c7256ce2caadf2a4cd476dbdf90a96f)

**Comment by mykola-mokhnach** [comment]
Are you able to debug webviews manually via chrome remote debugging?

**Comment by mykola-mokhnach** [comment]
Aslo, full Appium server log is needed

**Comment by NavdeepKGill** [comment]
Yes I'm able to debug the webviews in chrome inspector.
[Appium Servers Logs](https://gist.github.com/NavdeepKGill/2d8a54a7eafa217d13f03659567087f6)

**Comment by mykola-mokhnach** [comment]
How about attaching the full log?

**Comment by NavdeepKGill** [comment]
https://gist.github.com/NavdeepKGill/2d8a54a7eafa217d13f03659567087f6

**Comment by NavdeepKGill** [comment]
@mykola-mokhnach  Any findings on this one?

**Comment by abhilashsiyer** [comment]
I am running into the same problem. As per my analysis, the problem is because of change of package. When you switch the context to Chrome tab, then the package is changed to com.android.chrome. If appium provides us with a support to change the package then we should be good. I tried the same using POSTMAN and posting the same URL’s as done by appium. When I use my native resource package then I get Unknown Error Failed to open web page, If I use resource package as com.android.chrome then I get a valid response.

**Comment by mykola-mokhnach** [comment]
Closed as inactive
