### ISSUE TITLE
Katalon mobile not working due to UIautomator2 issue

### ISSUE THREAD

**Issue by SheenuJ** [appium/appium#10467]
## The problem

I am trying to run katalon studio in my android device but it gives me " Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id" . My WebUI for katalon works fine. I am trying to run apk of a hybrid app in my nexus device.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable): NA ( running katalon for the first time)
* Desktop OS/version used to run Appium: Windows 8
* Node.js version (unless using Appium.app|exe): 8.10.0
* Mobile platform/version under test: Nexus 5x android 7.1.2
* Real device or emulator/simulator: Real device nexus 5x
* Appium CLI or Appium.app|exe: it is appium server. I installed node.js and then from command prompt installed appium server through commmand ( npm -g install appium)

## Details

Appium] Welcome to Appium v1.7.2
[Appium] Non-default server args:
[Appium]   port: 59585
[Appium]   loglevel: info
[Appium]   chromeDriverPort: 59586
[Appium]   tmpDir: C:\Users\pkjain\AppData\Local\Temp\\Katalon\Appium\Temp1522751112277
[Appium] Appium REST http interface listener started on 0.0.0.0:59585
[HTTP] --> GET /wd/hub/status {}
[HTTP] <-- GET /wd/hub/status 200 15 ms - 72 
[HTTP] --> GET /wd/hub/status {}
[HTTP] <-- GET /wd/hub/status 200 4 ms - 72 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\pkjain\\Downloads\\android-rottentomatoes-demo-debug.apk","autoGrantPermissions":true,"automationName":"uiautomator2","deviceName":"LGE Nexus 5X (Android 7.1.2)","fullReset":false,"newCommandTimeout":1800,"noReset":true,"platform":"ANDROID","platformName":"Android","udid":"01a5d8bd3ad19b45"},"capabilities":{"desiredCapabilities":{"app":"C:\\Users\\pkjain\\Downloads\\android-rottentomatoes-demo-debug.apk","autoGrantPermissions":true,"automationName":"uiautomator2","deviceName":"LGE Nexus 5X (Android 7.1.2)","fullReset":false,"newCommandTimeout":1800,"noReset":true,"platform":"ANDROID","platformName":"Android","udid":"01a5d8bd3ad19b45"},"firstMatch":[{"platformName":"android"}]}}
[Appium] Merged W3C capabilities {"desiredCapabilities":{"app":"C:\\Users\\pkjai... into desiredCapabilities object {"app":"C:\\Users\\pkjain\\Downloads\\android-r...
[Appium] Creating new AndroidUiautomator2Driver (v0.11.0) session
[Appium] Capabilities:
[Appium]   app: C:\Users\pkjain\Downloads\android-rottentomatoes-demo-debug.apk
[Appium]   autoGrantPermissions: true
[Appium]   automationName: uiautomator2
[Appium]   deviceName: LGE Nexus 5X (Android 7.1.2)
[Appium]   fullReset: false
[Appium]   newCommandTimeout: 1800
[Appium]   noReset: true
[Appium]   platform: ANDROID
[Appium]   platformName: android
[Appium]   udid: 01a5d8bd3ad19b45
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform.
[BaseDriver] Session created with session id: b19e06cf-cf31-4704-bc28-15b9fc311bdc
[BaseDriver] Using local app 'C:\Users\pkjain\Downloads\android-rottentomatoes-demo-debug.apk'
[AndroidDriver] Java version is: 1.8.0_102
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[AndroidDriver] Using device: 01a5d8bd3ad19b45
[ADB] Checking whether adb is present
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\pkjain\.katalon\tools\android_sdk\build-tools\28.0.0\aapt.exe
[ADB] Extracting package and launch activity from manifest
[ADB] Getting device platform version
[ADB] Checking whether aapt is present
[ADB] Using apksigner.bat from C:\Users\pkjain\.katalon\tools\android_sdk\build-tools\28.0.0\apksigner.bat
[ADB] Checking whether zipalign is present
[ADB] Using zipalign.exe from C:\Users\pkjain\.katalon\tools\android_sdk\build-tools\28.0.0\zipalign.exe
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\pkjain\\.katalon\\tools\\android_sdk\\platform-tools\\adb.exe -P 5037 -s 01a5d8bd3ad19b45 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''

**Comment by mykola-mokhnach** [comment]
The application under test is supposed to be already installed if `noReset` is set to `true`. Also, it is recommended to explicitly set appActivity/appWaitActivity capabilities for such configuration.

**Comment by SheenuJ** [comment]
I tried both the things. Installed my app in the device before starting spy mobile object in my device. And also set appWaitActivity in (Project > Settings > Execution > Default > Mobile > Android). Still it is giving me the same error.

**Comment by mykola-mokhnach** [comment]
Are you able to start the same activity by name by providing it to `adb shell am start` command?

**Comment by SheenuJ** [comment]
So ya i was able to start the app through adb shell am start -n com.package.name/com.package.name/MainActivity

I have set under  (Project > Settings > Execution > Default > Mobile > Android)
Name : MainActivity
Type: String
Value: com.package.name

Still not able to do it.

**Comment by SheenuJ** [comment]
[Appium] Welcome to Appium v1.7.2
[Appium] Non-default server args:
[Appium]   port: 62192
[Appium]   chromeDriverPort: 62193
[Appium]   tmpDir: C:\Users\pkjain\AppData\Local\Temp\\Katalon\Appium\Temp1523019442975
[Appium] Appium REST http interface listener started on 0.0.0.0:62192
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.2","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 72 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.2","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 4 ms - 72 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"MainActivity":"com.irco.ASair360","app":"C:\\Users\\pkjain\\Downloads\\android-rottentomatoes-demo-debug.apk","autoGrantPermissions":true,"automationName":"uiautomator2","deviceId":"01a5d8bd3ad19b45","deviceName":"LGE Nexus 5X (Android 7.1.2)","fullReset":false,"newCommandTimeout":1800,"noReset":true,"platform":"ANDROID","platformName":"Android","udid":"01a5d8bd3ad19b45"},"capabilities":{"desiredCapabilities":{"MainActivity":"com.irco.ASair360","app":"C:\\Users\\pkjain\\Downloads\\android-rottentomatoes-demo-debug.apk","autoGrantPermissions":true,"automationName":"uiautomator2","deviceId":"01a5d8bd3ad19b45","deviceName":"LGE Nexus 5X (Android 7.1.2)","fullReset":false,"newCommandTimeout":1800,"noReset":true,"platform":"ANDROID","platformName":"Android","udid":"01a5d8bd3ad19b45"},"firstMatch":[{"platformName":"android"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"MainActivity":"com.irco.ASair360","app":"C:\\Users\\pkjain\\Downloads\\android-rottentomatoes-demo-debug.apk","autoGrantPermissions":true,"automationName":"uiautomator2","deviceId":"01a5d8bd3ad19b45","deviceName":"LGE Nexus 5X (Android 7.1.2)","fullReset":false,"newCommandTimeout":1800,"noReset":true,"platform":"ANDROID","platformName":"Android","udid":"01a5d8bd3ad19b45"},null,{"desiredCapabilities":{"MainActivity":"com.irco.ASair360","app":"C:\\Users\\pkjain\\Downloads\\android-rottentomatoes-demo-debug.apk","autoGrantPermissions":true,"automationName":"uiautomator2","deviceId":"01a5d8bd3ad19b45","deviceName":"LGE Nexus 5X (Android 7.1.2)","fullReset":false,"newCommandTimeout":1800,"noReset":true,"platform":"ANDROID","platformName":"Android","udid":"01a5d8bd3ad19b45"},"firstMatch":[{"platformName":"android"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1523019449476 (18:27:29 GMT+0530 (India Standard Time))
[Appium] Merged W3C capabilities {"desiredCapabilities":{"MainActivity":"com.irc... into desiredCapabilities object {"MainActivity":"com.irco.ASair360","app":"C:\\...
[Appium] Creating new AndroidUiautomator2Driver (v0.11.0) session
[Appium] Capabilities:
[Appium]   MainActivity: com.irco.ASair360
[Appium]   app: C:\Users\pkjain\Downloads\android-rottentomatoes-demo-debug.apk
[Appium]   autoGrantPermissions: true
[Appium]   automationName: uiautomator2
[Appium]   deviceId: 01a5d8bd3ad19b45
[Appium]   deviceName: LGE Nexus 5X (Android 7.1.2)
[Appium]   fullReset: false
[Appium]   newCommandTimeout: 1800
[Appium]   noReset: true
[Appium]   platform: ANDROID
[Appium]   platformName: android
[Appium]   udid: 01a5d8bd3ad19b45
[BaseDriver] The following capabilities were provided, but are not recognized by appium: MainActivity, deviceId, platform.
[BaseDriver] Session created with session id: aba8fec3-31da-480b-801e-06b3b57f2e1f
[BaseDriver] Using local app 'C:\Users\pkjain\Downloads\android-rottentomatoes-demo-debug.apk'
[debug] [UiAutomator2] Checking whether app is actually present
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_102
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: 01a5d8bd3ad19b45
[ADB] Checking whether adb is present
[debug] [ADB] Setting device id to 01a5d8bd3ad19b45
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","getprop","ro.build.version.sdk"]
[debug] [ADB] Current device property 'ro.build.version.sdk': 25
[debug] [ADB] Device API level: 25
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from C:\Users\pkjain\.katalon\tools\android_sdk\build-tools\28.0.0\aapt.exe
[ADB] Extracting package and launch activity from manifest
[debug] [ADB] badging package: com.codepath.example.rottentomatoes
[debug] [ADB] badging act: com.codepath.example.rottentomatoes.BoxOfficeActivity
[debug] [AndroidDriver] Parsed package and activity are: com.codepath.example.rottentomatoes/com.codepath.example.rottentomatoes.BoxOfficeActivity
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","getprop","ro.build.version.release"]
[debug] [ADB] Current device property 'ro.build.version.release': 7.1.2
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","wm","size"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","wm","density"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","getprop","ro.product.model"]
[debug] [ADB] Current device property 'ro.product.model': Nexus 5X
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","getprop","ro.product.manufacturer"]
[debug] [ADB] Current device property 'ro.product.manufacturer': LGE
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","am","force-stop","io.appium.uiautomator2.server"]
[ADB] Checking whether aapt is present
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","pm","list","packages","io.appium.uiautomator2.server"]
[debug] [ADB] App is installed
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","pm","list","packages","io.appium.uiautomator2.server.test"]
[debug] [ADB] App is not installed
[debug] [ADB] Getting package info for io.appium.uiautomator2.server
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","dumpsys","package","io.appium.uiautomator2.server"]
[debug] [ADB] Checking app cert for C:\Users\pkjain\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] 'C:\Users\pkjain\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-debug-androidTest.apk' doesn't exist
[ADB] Using apksigner.bat from C:\Users\pkjain\.katalon\tools\android_sdk\build-tools\28.0.0\apksigner.bat
[debug] [ADB] Zip-aligning 'C:\Users\pkjain\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-debug-androidTest.apk'
[ADB] Checking whether zipalign is present
[ADB] Using zipalign.exe from C:\Users\pkjain\.katalon\tools\android_sdk\build-tools\28.0.0\zipalign.exe
[debug] [ADB] Signing 'C:\Users\pkjain\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-debug-androidTest.apk' with default cert
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: Error: Trying to proxy a session command without session id
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","shell","am","force-stop","com.codepath.example.rottentomatoes"]
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","forward","--remove","tcp:8200"]
[debug] [ADB] Running 'C:\Users\pkjain\.katalon\tools\android_sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","01a5d8bd3ad19b45","forward","--remove","tcp:8200"]
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\pkjain\\.katalon\\tools\\android_sdk\\platform-tools\\adb.exe -P 5037 -s 01a5d8bd3ad19b45 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''

**Comment by Gehad99** [comment]
[35m[Appium][39m Welcome to Appium v1.9.1
[35m[Appium][39m Non-default server args:
[35m[Appium][39m   port: 50905
[35m[Appium][39m   loglevel: info
[35m[Appium][39m   chromeDriverPort: 50906
[35m[Appium][39m   tmpDir: C:\Users\Gihad\AppData\Local\Temp\\Katalon\Appium\Temp1550060202364
[35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:50905
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m
[35m[HTTP][39m [90m{}[39m
[35m[HTTP][39m [37m<-- GET /wd/hub/status [39m[32m200[39m [90m13 ms - 67[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m
[35m[HTTP][39m [90m{}[39m
[35m[HTTP][39m [37m<-- GET /wd/hub/status [39m[32m200[39m [90m1 ms - 67[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[35m[HTTP][39m [90m{"desiredCapabilities":{"AppWaitActivity":"*","MainActivity":"com.vis.meinvodafone.view.activity.launch.VfLaunchBaseActivity","app":"D:\\mein vodafone\\com.vis.meinvodafone.dev.apk","autoGrantPermissions":true,"automationName":"uiautomator2","deviceId":"290a1834a43f7ece","deviceName":"samsung SM-N960F (Android 8.1.0)","fullReset":false,"newCommandTimeout":1800,"noReset":true,"orientation":"PORTRAIT","platform":"ANDROID","platformName":"Android","udid":"290a1834a43f7ece","unicodeKeyboard":true},"capabilities":{"desiredCapabilities":{"AppWaitActivity":"*","MainActivity":"com.vis.meinvodafone.view.activity.launch.VfLaunchBaseActivity","app":"D:\\mein vodafone\\com.vis.meinvodafone.dev.apk","autoGrantPermissions":true,"automationName":"uiautomator2","deviceId":"290a1834a43f7ece","deviceName":"samsung SM-N960F (Android 8.1.0)","fullReset":false,"newCommandTimeout":1800,"noReset":true,"orientation":"PORTRAIT","platform":"ANDROID","platformName":"Android","udid":"290a1834a43f7ece","unicodeKey[39m
[35m[Appium][39m Could not parse W3C capabilities: 'deviceName' can't be blank
[35m[Appium][39m Trying to fix W3C capabilities by merging them with JSONWP caps
[35m[BaseDriver][39m The capabilities ["AppWaitActivity","MainActivity","app","autoGrantPermissions","automationName","deviceId","deviceName","fullReset","newCommandTimeout","noReset","orientation","platform","udid","unicodeKeyboard"] are not standard capabilities and should have an extension prefix
[35m[Appium][39m Creating new AndroidUiautomator2Driver (v1.19.0) session
[35m[Appium][39m Capabilities:
[35m[Appium][39m   AppWaitActivity: *
[35m[Appium][39m   MainActivity: com.vis.meinvodafone.view.activity.launch.VfLaunchBaseActivity
[35m[Appium][39m   app: D:\mein vodafone\com.vis.meinvodafone.dev.apk
[35m[Appium][39m   autoGrantPermissions: true
[35m[Appium][39m   automationName: uiautomator2
[35m[Appium][39m   deviceId: 290a1834a43f7ece
[35m[Appium][39m   deviceName: samsung SM-N960F (Android 8.1.0)
[35m[Appium][39m   fullReset: false
[35m[Appium][39m   newCommandTimeout: 1800
[35m[Appium][39m   noReset: true
[35m[Appium][39m   orientation: PORTRAIT
[35m[Appium][39m   platform: ANDROID
[35m[Appium][39m   udid: 290a1834a43f7ece
[35m[Appium][39m   unicodeKeyboard: true
[35m[Appium][39m   platformName: android
[35m[BaseDriver][39m The following capabilities were provided, but are not recognized by appium: AppWaitActivity, MainActivity, deviceId, platform.
[35m[BaseDriver][39m Session created with session id: 6895b808-cf4e-4db2-af68-a4387dbb392b
[35m[BaseDriver][39m Using local app 'D:\mein vodafone\com.vis.meinvodafone.dev.apk'
[35m[AndroidDriver][39m Java version is: 1.8.0_181
[35m[ADB][39m Checking whether adb is present
[35m[ADB][39m Found 1 'build-tools' folders under 'C:\Users\Gihad\.katalon\tools\android_sdk' (newest first):
[35m[ADB][39m     C:/Users/Gihad/.katalon/tools/android_sdk/build-tools/28.0.3
[35m[ADB][39m Using adb.exe from C:\Users\Gihad\.katalon\tools\android_sdk\platform-tools\adb.exe
[35m[AndroidDriver][39m Retrieving device list
[35m[AndroidDriver][39m Using device: 290a1834a43f7ece
[35m[ADB][39m Using the alternative activity name detection method because of: Could not find apkanalyzer.bat in C:\Users\Gihad\.katalon\tools\android_sdk\platform-tools\apkanalyzer.bat,C:\Users\Gihad\.katalon\tools\android_sdk\emulator\apkanalyzer.bat,C:\Users\Gihad\.katalon\tools\android_sdk\tools\apkanalyzer.bat,C:\Users\Gihad\.katalon\tools\android_sdk\tools\bin\apkanalyzer.bat,C:\Users\Gihad\.katalon\tools\android_sdk\build-tools\28.0.3\apkanalyzer.bat. Do you have the Android SDK installed at 'C:\Users\Gihad\.katalon\tools\android_sdk'?
[35m[ADB][39m Checking whether aapt is present
[35m[ADB][39m Using aapt.exe from C:\Users\Gihad\.katalon\tools\android_sdk\build-tools\28.0.3\aapt.exe
[35m[ADB][39m Extracting package and launch activity from manifest
[35m[ADB][39m Package name: 'com.vis.meinvodafone.dev'
[35m[ADB][39m Main activity name: 'com.vis.meinvodafone.view.activity.launch.VfLaunchBaseActivity'
[35m[ADB][39m Getting device platform version
[35m[ADB][39m Using apksigner.bat from C:\Users\Gihad\.katalon\tools\android_sdk\build-tools\28.0.3\apksigner.bat
[35m[ADB][39m Checking whether zipalign is present
[35m[ADB][39m Using zipalign.exe from C:\Users\Gihad\.katalon\tools\android_sdk\build-tools\28.0.3\zipalign.exe
[35m[ADB][39m io.appium.uiautomator2.server was successfully uninstalled
[35m[ADB][39m io.appium.uiautomator2.server.test was successfully uninstalled
[35m[AndroidDriver][39m setDeviceLanguageCountry requires language or country.
[35m[AndroidDriver][39m Got language: 'null' and country: 'null'
[35m[ADB][39m Successfully extracted 2234 strings from 'D:\mein vodafone\com.vis.meinvodafone.dev.apk' resources for '(default)' configuration
[35m[UiAutomator2][39m Starting uiautomator2 server 1.18.0
[35m[UiAutomator2][39m Using UIAutomator2 server from 'C:\Users\Gihad\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v1.18.0.apk' and test from 'C:\Users\Gihad\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
[35m[UiAutomator2][39m Running command: 'adb -s 290a1834a43f7ece shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner'
[35m[UiAutomator2][39m Waiting up to 20000ms for UiAutomator2 to be online...
[35m[AndroidDriver][39m Screen already unlocked, doing nothing
[35m[UiAutomator2][39m UiAutomator2 did not start the activity we were waiting for, 'com.vis.meinvodafone.dev/com.vis.meinvodafone.view.activity.launch.VfLaunchBaseActivity'. Starting it ourselves








please advice .. the app. keep on crashing everytime i tend to run it on katalon and heres the log am gettin

**Comment by imurchie** [comment]
Seems like something Katalon might know more about.
