### ISSUE TITLE
xpath not working on iOS for Hybrid App with appium 1.7.1. Same works on appium 1.6.4

### ISSUE THREAD

**Issue by vsadineni1** [appium/appium#10519]
## The problem
With appium 1.7.1, my test is failing to find the element with the xPath. The same test is working with appium 1.6.4 and can successfully return response element.

This is a consistent behavior.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1. I could not try appium 1.7.2 as it has another issue in locating the element.
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4
* Desktop OS/version used to run Appium: I used SauceLabs Mac OSX. I can repro the same issue on my Max OS Sierra  10.13.3 with appium 1.7.1 installed
* Node.js version (unless using Appium.app|exe): v9.3.0
* Mobile platform/version under test:  iOS 10.3
* Real device or emulator/simulator: iPhone 6 Simulator, iPad 6 Simulator. Test fails on both
* Appium CLI or Appium.app|exe:

## Details

I am testing a Hybrid app on iPhone 6 Simulator. One of the steps in the test is trying to locate an element using xPath. 
This step is failing with appium 1.7.1 but successfully works with appium 1.6.4.

## Link to Appium logs
I have pasted the sections of the appium log that is related to the xPath search. Also provided the SauceLabs recording links for full logs

https://gist.github.com/vsadineni1/9369459548ff3851ac52f2fccc067c0c

@imurchie

**Comment by vsadineni1** [comment]
Thank you @mykola-mokhnach 

Pardon my ignorance. One clarification question, how is xcode related to appium versions?
Does every version of appium uses a different xcode?

**Comment by mykola-mokhnach** [comment]
I mean this part of the functionality does not depend on Appium, since it acts as a proxy. WebDriverAgent itself (with several modifications) is forked from https://github.com/facebook/WebDriverAgent and XCTest is based on the Xcode SDK, which is currently active on the machine under test. This means if you have any problems in this area then it is very unlikely that something can be fixed or changed in Appium. You should look for a solution either on WDA or on the Apple side.

I'd also try appium@beta, since it contains the most recent patches and fixes.

**Comment by vsadineni1** [comment]
@mykola-mokhnach One more question. 
What is the relation between appium version & Web Driver Agent?
Does each version of appium has a different Web Driver agent?

**Comment by vsadineni1** [comment]
I tried this on appium 1.8.0 beta. I do not see the issue. I will keep an eye for this release.
