### ISSUE TITLE
deviceName is optional instead of mandatory (Android and iOS)

### ISSUE THREAD

**Issue by budtmo** [appium/appium#10943]
## The problem

Appium Server can be connected to Selenium Hub, but we still need to specify deviceName in Capabilities (it is mandatory) to be able to execute Appium test so I do not see a huge benefit for using Selenium Hub. Is there any plan to make deviceName optional for both OS (Android and iOS)? For example we can just need specify target version of Android / iOS instead and Selenium Hub / Appium Server will find available node for us.

## Environment
* Appium version 1.8,1
* Desktop OS/version used to run Appium: -
* Node.js version (unless using Appium.app|exe): 7.10.1
* Mobile platform/version under test: Android and iOS
* Real device or emulator/simulator: real device and simulator
* Appium CLI or Appium.app|exe: CLI

**Comment by imurchie** [comment]
That would require a change to the mobile protocol specification (https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#desired-capabilities). Not to say it could not be done, but right now it is just implementing that spec.

**Comment by butomo1989** [comment]
Thank you @imurchie for quick response. 

I will create an issue / feature request to Selenium repository then. If it is ok, I would like to keep this issue open and link both issues.

**Comment by imurchie** [comment]
Sounds good.

**Comment by jlipps** [comment]
I'm not sure how this is a limitation. "iPhone" and "Android" are valid deviceNames. If you pass them into an Appium server which is connected to just one iOS or Android device it will use that one. Or maybe I'm not understanding the problem.

**Comment by butomo1989** [comment]
Hi @jlipps , 

Thank you for your reply. I would like to have 1 Selenium Grid that contains for example 4 Appium servers. Each Appium Server contains multiple Android or iOS devices / emulators. To be able to execute the test, I need to give specific deviceName as a mandatory parameter. what I would like to have is an optional deviceName and if I give only platformName and version to Selenium Grid/Appium Server, it will find the available node for me without knowing the deviceName.

**Comment by Jiurong-Yang** [comment]
Hi @butomo1989 , there is already a solution for your problem. You can start your appium node server with default-capabilities and that will eliminate the requirement for passing in these desired capabilities during driver instantiation. For example 

you can start your appium server like this

appium -U <UDID> --default-capabilities '{"platformName": "IOS", "platformVersion:"10.2", "deviceName": "iphone 7"}' (Also all of your node configuration stuff)

If you have these default capabilities the only thing you need in the dc is "app". If you want to specify a specific device make sure you have "applicationName" set. And if you are running a single grid for both IOS and Android you should probably pass the platformName/platform anyways to avoid getting a server of the wrong platform. The reason you might need platformName and platform is due to appium and selenium uses different keyworks for this value for some reason. So if you want to run a selenium server in the grid as well you'll also need the platform dc.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-base-driver/pull/363

**Comment by rajpatel1234asite** [comment]
https://github.com/appium/appium/issues/10943?new_signup=true#issuecomment-400578686

> Thank you for your reply. I would like to have 1 Selenium Grid that contains for example 4 Appium servers. Each Appium Server contains multiple Android or iOS devices / emulators. To be able to execute the test, I need to give specific deviceName as a mandatory parameter. what I would like to have is an optional deviceName and if I give only platformName and version to Selenium Grid/Appium Server, it will find the available node for me without knowing the deviceName.

@budtmo  Did you found the solution for this implementation?
