### ISSUE TITLE
[UiAutomator2] [UIAutomator2] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner} 

### ISSUE THREAD

**Issue by cuhavp** [appium/appium#10993]
## The problem

[UiAutomator2] [UIAutomator2] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner} 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): v9.8.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Samsung A5
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
https://gist.github.com/cuhavp/4d0271eade29faa3e26de7925065a7fd

**Comment by mykola-mokhnach** [comment]
Can you try appium@beta and attach the resulting server log?

**Comment by oldstone** [comment]
FYI. I ran into the same error
`java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner} from pid=28208, uid=28208 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server`
and solved the issue by manually uninstall previously installed appium-uiautomator2-server and appium-uiautomator2-servertest
`adb uninstall io.appium.uiautomator2.server
adb uninstall io.appium.uiautomator2.server.test`

**Comment by cuhavp** [comment]
thanks @oldstone 👍 it's work!!!

**Comment by prakashpqa** [comment]
Thanks @oldstone ... It worked

**Comment by capcelsoricardo** [comment]
Many thanks! @oldstone

**Comment by abhi2717** [comment]
> FYI. I ran into the same error
> `java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner} from pid=28208, uid=28208 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server`
> and solved the issue by manually uninstall previously installed appium-uiautomator2-server and appium-uiautomator2-servertest
> `adb uninstall io.appium.uiautomator2.server`
> `adb uninstall io.appium.uiautomator2.server.test`

Thanks a lot.Finally sort it out
