### ISSUE TITLE
Desired Capability "connectHardwareKeyboard" not work

### ISSUE THREAD

**Issue by romansvesh** [appium/appium#11007]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: macOS 10.13.5
* Node.js version (unless using Appium.app|exe): 10.6.0
* Mobile platform/version under test: IOS 10.3.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: tested with appium cli and appium desktop 1.6.2

## Details

send_keys not work (see logs).
"connectHardwareKeyboard": "False" - not work
There is only one way to fix send_keys: uncheck in handly in Simulator -> Hardware -> Keyboard -> Connect Hardware Keyboard
But I think "connectHardwareKeyboard": "False" must work
 too.

## Link to Appium logs

https://gist.github.com/romansvesh/af466277f531715e8628dadf05c2ae61

`Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}","sessionId":"44EE4BEB-E7FD-475A-9F70-6305DB7067BB","status":13}`

**Comment by mykola-mokhnach** [comment]
This stopped working since recent xCode releases. Simulator simply ignores the changed setting from its plist file and applies the default one each time after restart. Closed as third party issue.

**Comment by rostik404** [comment]
@mykola-mokhnach, hello!

> This stopped working since recent xCode releases

Is there any issue in xCode about this problem? Or maybe some notes in the changelog about this? And do you have some workaround to redefine capability `connectHardwareKeyboard` automatically? This is a real problem for testing now, cause I don't see any way to hide a keyboard in my tests on IOS platform.

**Comment by KazuCocoa** [comment]
Probably the below affects this. (But I observed `connectHardwareKeyboard` did not work without the below case as well before) https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBConfiguration.m#L255-L266

`Keyboard is not present` error might occur (potentially it is occasionally). The software keyboard was necessary to avoid the error. The software keyboard preference does not work on Xcode 13 and iOS 15, so you could try if `connectHardwareKeyboard` works for you with Xcode 13 and `appium@rc`. (or manually remove the lines)

**Comment by rostik404** [comment]
> Probably the below affects this

But why didn't you make an option for toggling software keyboard? It seems like not every user wants to have a software keyboard with force.

> so you could try if connectHardwareKeyboard works for you with Xcode 13 and appium@rc

So, in xcode 13 this code https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBConfiguration.m#L255-L266 is not working, so I can try to switch off the software keyboard with `connectHardwareKeyboard` capability, right? Is it any way to switch off it for xcode 11 (ios13)?

**Comment by rostik404** [comment]
Also, the strange thing, that appium ignores simulator system settings
![2021-08-13_15-07-18](https://user-images.githubusercontent.com/8089139/129354984-a2f80022-98aa-42c7-bd70-0739bf76a002.png)

**Comment by rostik404** [comment]
@KazuCocoa

**Comment by KazuCocoa** [comment]
> But why didn't you make an option for toggling software keyboard? It seems like not every user wants to have a software keyboard with force.

This was because when I added this configuration, the hardware keyboard option via capabilities no longer worked then. Afaik, the option was a workaround for an old issue then. The `Keyboard is not present` was more issue for us that needed to enable software keyboard to fix it.

> Also, the strange thing, that appium ignores simulator system settings

I guess iOS simulator handles 
 https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBConfiguration.m#L264 call rather than simulator plist. It is how the simulator works thing. I haven't noticed this point configuration.

As a workaround, you can remove the below line in your local.
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBConfiguration.m#L264

Let me try to make it optional this or next weekend.

**Comment by KazuCocoa** [comment]
It seems `connectHardwareKeyboard` works only when appium launches a simulator since it changes plist. It cannot work dynamically. https://github.com/appium/WebDriverAgent/pull/524 and https://github.com/appium/appium-xcuitest-driver/pull/1327 can avoid turning on the software keyboard preference.

**Comment by mykola-mokhnach** [comment]
> It seems connectHardwareKeyboard works only when appium launches a simulator since it changes plist

@KazuCocoa This was the case in older Appium versions. Now we use `defaults` CLI to change Simulator preferences, so it should also work while simulator is running.

**Comment by KazuCocoa** [comment]
mm, i remember the change, but I tested with current master branches... (The Xcode was 13 beta 5)

**Comment by rostik404** [comment]
> appium/WebDriverAgent#524 and appium/appium-xcuitest-driver#1327 can avoid turning on the software keyboard preference.
@KazuCocoa, cool, thank you! Looking forward to trying this option in my project!

**Comment by rostik404** [comment]
@KazuCocoa, thanks for your fix, connectHardwareKeyboard option works now! But software keyboard still be visible and I cannot switch it off automatically :(
There is an option "Toggle software keyboard" in the simulator which can hide software keyboard. I'm trying to select it automatically. So, I need to press ⌘K in my test, but I cannot do this. According to w3c documentation https://w3c.github.io/webdriver/webdriver-spec.html#keyboard-actions, the button ⌘ (Command or Meta) has \uE053 code. So, I'm writing in my test smth like this:
```
await this.browser.keys(['\uE053', 'K']);
```
and getting mouse emoji (lol) in my input instead of hiding the keyboard. http://www.iemoji.com/view/emoji/193/animals-nature/mouse-face
Also, I tried to do this using actions, but it didn't work too:
```
await this.browser.actions([{
            type: 'key',
            id: 'keyboard',
            actions: [
                    { type: 'keyDown', value: '\uE053' },
                    { type: 'keyDown', value: 'K' },
                    { type: 'keyUp', value: '\uE053' },
                    { type: 'keyUp', value: 'K' },
                ],
              }]);
```

Do you have any idea how to select this option by webdriver?
![2021-08-17_17-30-04](https://user-images.githubusercontent.com/8089139/129805534-a15dbe80-6127-4562-8bd7-daecbbbf79dc.png)

**Comment by jlipps** [comment]
You can't use send keys to simulate key presses on the macOS host. To do what you'd want you should use AppleScript instead.

**Comment by KazuCocoa** [comment]
> But software keyboard still be visible and I cannot switch it off automatically :(

Yea, it depends on your environment.
My last change `appium:forceSimulatorSoftwareKeyboardPresence` was if appium makes keyboard preference only software keyboard. `false` means appium does nothing since it seemed the opposite value in WDA did not mean turn software keyboard off.

I don't know since, but simulators can keep both software keyboard and hardware keyboard on...

Afaik, as jlipps commented, only apple script can change the value via GUI.

**Comment by rostik404** [comment]
Oh, thank you, guys, I'll try apple script.

**Comment by rostik404** [comment]
@KazuCocoa @jlipps Hi!
Folowing your adwice, I'm gonna run applescript to toggle software keyboard on simulator start.
I don't see better way then decorate xcrun binary and run applescript after simctl running. I see, that your [simctl wrapper](https://github.com/appium/node-simctl/tree/master) has an option to redefine xcrun binary path, but this option is not exposed in appium and I cannot pass it through browser capabilities\env\etc. You are creating simulator without passing xcrun path option https://github.com/appium/appium-ios/blob/main/packages/ios-simulator/lib/simulator-xcode-6.js#L51
So, I'm gonna add environ to redefine [XCRUN_BINARY](https://github.com/appium/node-simctl/blob/58798cb24403fdafe8f591b267cd95b266a31941/lib/simctl.js#L6). What do you think?

**Comment by KazuCocoa** [comment]
It seems ok for me with your concrete use case. Feel free to create a pr to accept an environment variable, too. We're happy to review it.
