### ISSUE TITLE
dragFromToForDuration does not drag to wished location iOS WebView

### ISSUE THREAD

**Issue by vytran9599** [appium/appium#11002]
The dragFromToForDuration would click on the element, but would not drag it to the desired location. I am using an iOS simulator and automating a webapp. Every other mobile gestures such as tap, alert, and doubleTap works fine. Is there a way to resolve this?

**Comment by vjmaiky** [comment]
please post logs

**Comment by mykola-mokhnach** [comment]
The mentioned gesture is executed on WebDriverAgent side and there is nothing on appium side to change that behaviour. Try to enable additional debugging in your application in order to see which events and at which coordinates are generated. Otherwise report an issue to https://github.com/facebook/WebDriverAgent

Closed as third party issue.
