### ISSUE TITLE
Write data in excel sheet under appium  issue 

### ISSUE THREAD

**Issue by RohitrajElpis** [appium/appium#11411]
hi i am trying to  write data in excel sheet but it is throwing error message . i am able to read data from excel sheet but i am not able to write data . i have attached 
1. appium server  log's
2. console out error message 
3. code for writing data in excel sheet

**Please do need full help ASAP** 
**after runing i was getting error and excel sheet got corrupted** 

[appium-server-logs.txt](https://github.com/appium/appium/files/2410711/appium-server-logs.txt)
![image](https://user-images.githubusercontent.com/43004068/45951505-4d694b00-c021-11e8-90e2-4115b9807614.png)
![image](https://user-images.githubusercontent.com/43004068/45951525-5f4aee00-c021-11e8-9882-16b028661b68.png)

**Comment by mykola-mokhnach** [comment]
Please do not spam the tracker with unrelated stuff otherwise we'll have to switch your account to readonly mode

**Comment by RohitrajElpis** [comment]
hi @mykola-mokhnach  i will be carefull , but can you please what type of issue we need to ask here.

**Comment by mykola-mokhnach** [comment]
This is the place for server issues. For example if you see some unexpected exception traces in the server log (nit the client one) and the problem has not been reported/described yet. Or some functionality, that was working properly earlier is broken after server update. 

Clients, for example the java one, have their own issue trackers.

And the forum we have for general questions/HowTos, however it is also not recommended to flood it, otherwise other participants may start complaining.

**Comment by RohitrajElpis** [comment]
oho sorry @mykola-mokhnach i will be careful next time , i need to learn that's why i use to ping to get response fast in discussion i am getting response late . i will use for issue and all appium forum and for server issue i will ask doubt here.

**Comment by mykola-mokhnach** [comment]
Usually nobody responds fast. You have to be ready to get response in days or no response at all. For fast response it would be easier to hire a consultant ;)
