### ISSUE TITLE
Test Failure with unknown error

### ISSUE THREAD

**Issue by EricDusseau** [appium/appium#11468]
## The problem

When attempting to run test suite, app will install and uninstall several times in simulator before ultimately failing. 

## Environment

* Appium version - 1.9.1
* Mac OS High Sierra 10.13.6 mac mini
* Running a Simulator iOS 12
* Appium installed and running in jenkins

## Link to Appium logs

https://gist.github.com/EricDusseau/dc40c19228db58bce9e5cb7ba6c9a71a

**Comment by imurchie** [comment]
What is your test script doing? From the logs, it is all client-side. First, trying to search by css-selector, which doesn't work because it is not a valid strategy in a native app. Then it stops the app, uninstalls, installs, and tries the same again.

All of this is, as far as the logs can tell, the test script sending in commands to do so.

**Comment by dpgraham** [comment]
Yeah, that's an issue with the Selenium clients. They convert selectors to CSS selectors. I still need to put in a PR to the Selenium project to not do that when the remote end is Appium.

Can you try using an Appium client? The Appium clients extend the Selenium client and they correct this problem.

**Comment by mykola-mokhnach** [comment]
This is client-side issue. Make sure you use the recent version of appium python client, which has the patch.

**Comment by EricDusseau** [comment]
Thanks all, what ultimately fixed the issue was updating to a later version of selenium on the machine that was seeing this issue.
