### ISSUE TITLE
Recommendation: Keep npm-shrinkwrap.json committed permanently

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#11535]
Since we use Greenkeeper now, I think we should commit the npm-shrinkwrap.json and leave it permanently and use the `greenkeeper_lockfile` library to keep the shrinkwrap up-to-date

Reasons for this:

1. Determinism. No need for `rm -rf node_modules && npm install` for appium@beta releases. We can just publish a new beta every time `npm-shrinkwrap.json` or `lib/` changes.
1. Consistency between beta releases and full releases. The full release will have the same dependencies as whatever the last beta release was, giving us assurance that what we have tested in the latest beta will be the same as what gets released.
1. Spares us the inconvenience of adding/removing the shrinkwrap whenever we do a release
1. Dependency changes will be tracked in source control, better enabling us to identify when a dependency change caused a bug (can use `git bisect` to find commits that caused bugs)
1. Can cherry-pick dependency updates. Example case: if an update to `appium-xcuitest-driver` fixes a bug, and we _only_ want that bugfix in an Appium patch release, we can cherry-pick the Greenkeeper commit that updates `appium-xcuitest-driver` into a feature branch and leave out any other updates that may not be ready for release.

The drawback to this is that we would have to do beta releases much more often. But my recommendation for that is that we just add a stage to the Appium CI that does the beta release for us. It could check that the commit has changes to either `/lib` or `npm-shrinwrap.json`, and if so, run `npm run release-beta`.

I can put in a PR for this myself, if we decide to take this approach, but I wanted to hear other people's thoughts on this first.

**Comment by imurchie** [comment]
Thinking further about automating npm publish on packages in our tree...I don't think this is a good idea, because of Greenkeeper. Take, for instance, the situation of dependence

- appium
    - appium-ios-driver
        - appium-remote-debugger

All of which require `lodash`. So when `lodash` is updated, right now Greenkeeper kicks off 3 jobs, testing all the packages with an updated `lodash`. If, then, everything goes well, and all `package-lock.json` files are updated and the packages are published, there would then be a cascade of updates, since on the publish of `appium-ios-driver` Greenkeeper will update `appium`, and in the publishing of `appium-remote-debugger` it will update `appium-ios-driver`. If all goes well `appium` and `appium-ios-driver` will then be published again and, again, `appium` will be updated for the new `appium-ios-driver`. Finally, `appium` is published a final time.

This is just for this simple case. A package like `appium-support` would cause a cascade that would take days to resolve, and end up with dozens of versions of `appium` published.

**Comment by dpgraham** [comment]
@imurchie Yeah, there would be problems with the CI being overloaded.

It probably wouldn't be too onerous for us to just publish a beta every day. Or we could even change the `appium/appium` job that publishes the zip to a cron job that publishes a zip and publishes a beta daily.

**Comment by imurchie** [comment]
As an aside, since we now have a minimum npm at 6, we can switch to straight `package-lock.json` and do away with `npm-shrinkwrap.json` (which is just a rename of the former anyway).

**Comment by dpgraham** [comment]
They're actually different. The files are the same format, but `package-lock.json` only installs the exact package versions if you install it using `npm ci`. Installing Appium globally won't give fixed package versions.

**Comment by dpgraham** [comment]
I had the idea of using `package-lock.json` in source control and using `npm ci` to install packages in CI to keep consistency. But then when we do a release (beta or GA), do something like:

```
# Prepublish
npm --production ci # Install what is prescribed by package-lock.json
rimraf package-lock.json # Remove the package lock
npm --production shrinkwrap # Shrinkwrap the production dependencies

# Postpublish
git reset --hard HEAD # Or something like this to get rid of changes
```
