### ISSUE TITLE
Setting 'setWaitForSelectorTimeout' is not supported

### ISSUE THREAD

**Issue by RStrizhak** [appium/appium#11554]
## The problem

Can't set [WaitForSelectorTimeout](https://developer.android.com/reference/android/support/test/uiautomator/Configurator#setWaitForSelectorTimeout(long)) using:
driver.configuratorSetWaitForSelectorTimeout(1000);

## Environment

* Appium version: 1.9.1 (issue is reproduced from version 1.8.1)
* Last Appium version that did not exhibit the issue (if applicable): 1.8.0
* Desktop OS/version used to run Appium: MacOS Sierra 10.13.1
* Node.js version (unless using Appium.app|exe): v10.10.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe: both
* <appium-java-client.version>6.0.0-BETA1</appium-java-client.version>

## Link to Appium logs
[logs here](https://gist.github.com/RStrizhak/083985891d547488690353824c1b87c8)

Thanks.

**Comment by mykola-mokhnach** [comment]
This error is expected, because UIA2 want key name to be equal to 

[waitForSelectorTimeout](https://github.com/appium/appium-uiautomator2-server/blob/a1ca0f2adbe9189d43e4cdb39efd1af1378e1828/app/src/main/java/io/appium/uiautomator2/model/settings/WaitForSelectorTimeout.java#L23) 

and the client sends `setWaitForSelectorTimeout` instead. 

Please report this issue to the corresponding client tracker, since it is not a server issue.
