### ISSUE TITLE
Unable to scroll and find element on Appium 1.9.1 on ios

### ISSUE THREAD

**Issue by rakeshmanjunath1** [appium/appium#11608]
## The problem

Unable to find element on Appium 1.9.1 on ios

## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.2
* Desktop OS/version used to run Appium: Mac 10.13.6 Xcode 10.0
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: Real device

## Details

The appium is able interact with elements that are visible but not able to scroll the entire page and find the elements. This works on appium 1.7.2

## Link to Appium logs

https://gist.github.com/rakeshmanjunath1/af0e4a16795e24f3c92a45b155dd706a

## Code To Reproduce Issue [ Good To Have ]

Press(MobileBy.IosNSPredicate("wdType == 'XCUIElementTypeCell' AND wdName == 'General'"), eClickOrTap.Tap);
                WaitForProperty(MobileBy.IosNSPredicate("wdType == 'XCUIElementTypeNavigationBar' AND wdName == 'General'"), eMobileGUIElementAttribute.Displayed, "true", MobileLib.Constants.TIMEOUT_MED);
                Press(MobileBy.IosNSPredicate("wdType == 'XCUIElementTypeCell' AND wdName == 'Background App Refresh'"), eClickOrTap.Tap);
                WaitForProperty(MobileBy.IosNSPredicate("wdType == 'XCUIElementTypeNavigationBar' AND wdName == 'Background App Refresh'"), eMobileGUIElementAttribute.Displayed, "true", MobileLib.Constants.TIMEOUT_MED);

**Comment by mykola-mokhnach** [comment]
The attached log does not contain any details

**Comment by Dan-Maor** [comment]
I've noticed this change as well after the latest merge with Facebook's code in one of my scenarios.

On an iPhone 6s plus, ios 12.1.1:
1) Create a session for the Settings app.
2) Find the table element.
3) Attempt to use scroll on it to reach one of the bottom elements (Developer, for example).

Looks like the issue is related to this change (Once reverted scroll works properly):
https://github.com/facebook/WebDriverAgent/pull/879

Investigating.
