### ISSUE TITLE
iOS Alerts are dismissed with AutoAcceptAlerts

### ISSUE THREAD

**Issue by nemue** [appium/appium#11984]
## The problem

When I use "AutoAcceptAlerts" or "iosDriver.switchTo().alert().accept();" alerts are actually dismissed.
I've seen there has already been a similar issue 2013: https://github.com/appium/appium/pull/1254

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.10.0 (1.10.0.20181230.2) (probably 2 versions earlier)
* Last Appium version that did not exhibit the issue (if applicable): –
* Desktop OS/version used to run Appium: Mac OS 10.13.6
* Node.js version (unless using Appium.app|exe): v8.11.4
* Mobile platform/version under test: iOS 11.4
* Real device or emulator/simulator: iPhone 6S Plus
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

**Comment by mykola-mokhnach** [comment]
The logic behind it is pretty simple. Since XCUTest does not explicitly say which alert button accepts it WDA simply assumes the first one does this: https://github.com/appium/WebDriverAgent/blob/a6c7f38c59a8b18f89c23ce4dd9777dfc272e1e8/WebDriverAgentLib/FBAlert.m#L126

You can either modify your application code to follow this approach or modify WDA locally and change the logic there/ Otherwise there is nothing that can be changed there on Appium side.
