### ISSUE TITLE
Appium 1.10.1 : Appium session with NOKIA 5 device is not getting created with diffrent issues in logs

### ISSUE THREAD

**Issue by pankajigec26** [appium/appium#11992]
## The problem

Appium session is not getting created , Multiple issues in logs

## Environment

* Appium version (or git revision) that exhibits the issue: 1.10.1
* Last Appium version that did not exhibit the issue (if applicable): 1.7.1
* Desktop OS/version used to run Appium: WIndows 7 
* Node.js version (unless using Appium.app|exe):  8.9.4
* Mobile platform/version under test: 8.1 Android 
* Real device or emulator/simulator: Nokia 5 Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/pankajigec26/169363c5f886336310ace490f3ca0883

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by KazuCocoa** [comment]
mmm...

```
[debug] [UiAutomator2] [UIAutomator2] 1) startServer(io.appium.uiautomator2.serv
er.test.AppiumUiAutomator2Server)
[debug] [UiAutomator2] [UIAutomator2] java.lang.NoSuchMethodError: No static met
hod getInstance(Landroid/content/Context;I)Lio/appium/uiautomator2/server/Server
Instrumentation; in class Lio/appium/uiautomator2/server/ServerInstrumentation;
or its super classes (declaration of 'io.appium.uiautomator2.server.ServerInstru
mentation' appears in /data/app/io.appium.uiautomator2.server-47Y9D5APfMs5BfXlE0
OBZA==/base.apk)
[debug] [UiAutomator2] [UIAutomator2]   at io.appium.uiautomator2.server.test.Ap
piumUiAutomator2Server.startServer(AppiumUiAutomator2Server.java:29)
[debug] [UiAutomator2] [UIAutomator2]   at java.lang.reflect.Method.invoke(Nativ
e Method)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.model.FrameworkMeth
od$1.runReflectiveCall(FrameworkMethod.java:50)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.internal.runners.model.Refl
ectiveCallable.run(ReflectiveCallable.java:12)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.model.FrameworkMeth
od.invokeExplosively(FrameworkMethod.java:47)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.internal.runners.statements
.InvokeMethod.evaluate(InvokeMethod.java:17)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner.runLea
f(ParentRunner.java:325)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.BlockJUnit4ClassRun
ner.runChild(BlockJUnit4ClassRunner.java:78)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.BlockJUnit4ClassRun
ner.runChild(BlockJUnit4ClassRunner.java:57)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner$3.run(
ParentRunner.java:290)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner$1.sche
dule(ParentRunner.java:71)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner.runChi
ldren(ParentRunner.java:288)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner.access
$000(ParentRunner.java:58)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner$2.eval
uate(ParentRunner.java:268)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner.run(Pa
rentRunner.java:363)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.Suite.runChild(Suit
e.java:128)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.Suite.runChild(Suit
e.java:27)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner$3.run(
ParentRunner.java:290)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner$1.sche
dule(ParentRunner.java:71)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner.runChi
ldren(ParentRunner.java:288)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner.access
$000(ParentRunner.java:58)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner$2.eval
uate(ParentRunner.java:268)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runners.ParentRunner.run(Pa
rentRunner.java:363)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runner.JUnitCore.run(JUnitC
ore.java:137)
[debug] [UiAutomator2] [UIAutomator2]   at org.junit.runner.JUnitCore.run(JUnitC
ore.java:115)
[debug] [UiAutomator2] [UIAutomator2]   at android.support.test.internal.runner.
TestExecutor.execute(TestExecutor.java:59)
[debug] [UiAutomator2] [UIAutomator2]   at android.support.test.runner.AndroidJU
nitRunner.onStart(AndroidJUnitRunner.java:262)
[debug] [UiAutomator2] [UIAutomator2]   at android.app.Instrumentation$Instrumen
tationThread.run(Instrumentation.java:2082)
[debug] [UiAutomator2] [UIAutomator2] FAILURES!!!
[debug] [UiAutomator2] [UIAutomator2] Tests run: 1,  Failures: 1
```


Could you give us logcat as well?
It helps us to dig into error logs further.

**Comment by mykola-mokhnach** [comment]
I saw similar issues before. Try to reset the device/remove all the leftovers manually. Or you could try Appium@beta, where the installation logic has been improved

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/search?q=%22No+static+method+getInstance%22&unscoped_q=%22No+static+method+getInstance%22&type=Issues

**Comment by ndeztea** [comment]
I have the similar issue with the latest appium version 1.10.0, can't connect to android it seems the adb is broken, and the device can't be found then. I am using driver UiAutomator2

The error 
`Code:
  * features/support/env.rb
Default Timeout 30
Requesting config for platform => android & Environment ==> staging & Browser if any ==> 
[DEPRECATION] Appium::Driver.new(opts) will not generate global driver by default.If you would like to generate the global driver dy default, please initialise driver with Appium::Driver.new(opts, true)
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET (Selenium::WebDriver::Error::UnknownError)
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET`

The log
`[AndroidDriver] Performing fast reset on 'com.happyfresh.staging'
[debug] [ADB] Getting install status for com.happyfresh.staging
[debug] [ADB] Running '/Users/dimas/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.56.101\:5555 shell dumpsys package com.happyfresh.staging'
[debug] [ADB] 'com.happyfresh.staging' is installed
[debug] [ADB] Running '/Users/dimas/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.56.101\:5555 shell am force-stop com.happyfresh.staging'
[debug] [ADB] Running '/Users/dimas/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.56.101\:5555 shell pm clear com.happyfresh.staging'
[debug] [AndroidDriver] Performed fast reset on the installed 'com.happyfresh.staging' application (stop and clear)
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Running '/Users/dimas/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.56.101\:5555 shell ps'
[debug] [ADB] Running '/Users/dimas/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.56.101\:5555 shell am force-stop io.appium.uiautomator2.server'
[UiAutomator2] Starting uiautomator2 server 2.7.0
[UiAutomator2] Using UIAutomator2 server from '/Users/dimas/.npm-global/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v2.7.0.apk' and test from '/Users/dimas/.npm-global/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Running command: 'adb -s 192.168.56.101:5555 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner'
[UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [UiAutomator2] [UIAutomator2] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner} from pid=8579, uid=8579 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server
[debug] [UiAutomator2] [UIAutomator2] 	at android.os.Parcel.readException(Parcel.java:1942)
[debug] [UiAutomator2] [UIAutomator2] 	at android.os.Parcel.readException(Parcel.java:1888)
[debug] [UiAutomator2] [UIAutomator2] 	at android.app.IActivityManager$Stub$Proxy.startInstrumentation(IActivityManager.java:5075)
[debug] [UiAutomator2] [UIAutomator2] 	at com.android.commands.am.Instrument.run(Instrument.java:408)
[debug] [UiAutomator2] [UIAutomator2] 	at com.android.commands.am.Am.runInstrument(Am.java:232)
[debug] [UiAutomator2] [UIAutomator2] 	at com.android.commands.am.Am.onRun(Am.java:125)
[debug] [UiAutomator2] [UIAutomator2] 	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
[debug] [UiAutomator2] [UIAutomator2] 	at com.android.commands.am.Am.main(Am.java:95)
[debug] [UiAutomator2] [UIAutomator2] 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [UiAutomator2] [UIAutomator2] 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
[debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_STATUS: id=ActivityManagerService
[debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_STATUS: Error=Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner} from pid=8579, uid=8579 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server
[debug] [UiAutomator2] [UIAutomator2] INSTRUMENTATION_STATUS_CODE: -1
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running '/Users/dimas/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.56.101\:5555 shell am force-stop com.happyfresh.staging'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/dimas/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.56.101\:5555 forward --remove tcp\:8200'
[debug] [ADB] Device API level: 26
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1547783261277 (10:47:41 GMT+0700 (Western Indonesia Time))
`
