### ISSUE TITLE
UiAutomator2 is deleting appium-uiautomator2-server-debug-androidTest.apk

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#12180]
(moved from https://github.com/appium/appium/issues/12166)

Issue reported by @oivzhich

Steps to reproduce:

1) re-installed appium 
`npm uninstall -g appium && npm i -g appium`
2) ls -l /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/
`-rw-rw-r-- 1 jenkins jenkins  545600 Oct 26  1985 appium-uiautomator2-server-debug-androidTest.apk`
`-rw-rw-r-- 1 jenkins jenkins 2200616 Oct 26  1985 appium-uiautomator2-server-v3.1.1.apk`
3) Launching appium tests using **Java11** and getting error:
`[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1550258706807 (22:25:06 GMT+0300 (Moscow Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Could not sign with default certificate. Original error Command '/usr/lib/jvm/java-11-oracle/bin/java -jar /usr/lib/node_modules/appium/node_modules/appium-adb/jars/sign.jar /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk --override' exited with code 1
[debug] [W3C]     at ADB.apkSigningMethods.signWithDefaultCert (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:124:13)`

4) Launching tests one more time and getting error
`[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1550258927866 (22:28:47 GMT+0300 (Moscow Standard Time))
[debug] [W3C] Encountered internal error running command: Error: /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk file doesn't exist.
[debug] [W3C]     at ADB.apkSigningMethods.signWithDefaultCert (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:106:11)`

**Comment by mykola-mokhnach** [comment]
- I would like to see the full log first
- Why `sign.jar` is still used? This tool is still there because of legacy reasons. apksigner ought to be executed instead. Perhaps we have to simply disable the usage of sign.jar for higher Java version and simply throw an error, since it anyway was not designed to work with newer versions.

**Comment by oivzhich** [comment]
@mykola-mokhnach , @dpgraham this is the full log
`[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"https://build.coople.com/android-builds/test-worker-v3/android_v3_qa3.apk","appPackage":"com.coople.android.worker.debug","clearSystemFiles":true,"appWaitActivity":"com.coople.android.worker.screen.*","deviceName":"Android","newCommandTimeout":300,"automationName":"UiAutomator2","autoGrantPermissions":true,"unicodeKeyboard":true,"platformName":"Android","udid":"ce07182754f76b0405","maxDuration":2000,"resetKeyboard":true},null,{"firstMatch":[{"appium:app":"https://build.coople.com/android-builds/test-worker-v3/android_v3_qa3.apk","appium:appPackage":"com.coople.android.worker.debug","appium:appWaitActivity":"com.coople.android.worker.screen.*","appium:autoGrantPermissions":true,"appium:automationName":"UiAutomator2","appium:clearSystemFiles":true,"appium:deviceName":"Android","maxDuration":2000,"appium:newCommandTimeout":300,"platformName":"android","appium:resetKeyboard":true,"appium:udid":"ce07182754f76b0405","appium:unicodeKeyboard":true}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1550475863739 (10:44:23 GMT+0300 (Moscow Standard Time))
[BaseDriver] The capabilities ["maxDuration"] are not standard capabilities and should have an extension prefix
[Appium] Creating new AndroidUiautomator2Driver (v1.27.0) session
[Appium] Capabilities:
[Appium]   maxDuration: 2000
[Appium]   platformName: android
[Appium]   app: https://build.coople.com/android-builds/test-worker-v3/android_v3_qa3.apk
[Appium]   appPackage: com.coople.android.worker.debug
[Appium]   appWaitActivity: com.coople.android.worker.screen.*
[Appium]   autoGrantPermissions: true
[Appium]   automationName: UiAutomator2
[Appium]   clearSystemFiles: true
[Appium]   deviceName: Android
[Appium]   newCommandTimeout: 300
[Appium]   resetKeyboard: true
[Appium]   udid: ce07182754f76b0405
[Appium]   unicodeKeyboard: true
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"appium:max... and MJSONWP desired capabilities {"app":"https://build.coopl... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"appium:max...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: maxDuration.
[BaseDriver] Session created with session id: 04e454e4-9c0c-4297-be89-52396ec94556
[BaseDriver] Using downloadable app 'https://build.coople.com/android-builds/test-worker-v3/android_v3_qa3.apk'
(node:18823) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[debug] [BaseDriver] Last-Modified: Thu, 14 Feb 2019 10:22:48 GMT
[debug] [BaseDriver] Content-Type: application/vnd.android.package-archive
[debug] [BaseDriver] 'https://build.coople.com/android-builds/test-worker-v3/android_v3_qa3.apk' (20.27 MB) has been downloaded to '/tmp/2019118-18823-1ei2vde.7jko/appium-app.apk' in 2.378s
[debug] [BaseDriver] Approximate download speed: 8.52 MB/s
[debug] [UiAutomator2] Checking whether app is actually present
[AndroidDriver] Java version is: 11.0.2
[ADB] Checking whether adb is present
[ADB] Cannot sort build-tools folders ["24.0.0","debian"] by semantic version names.
[ADB] Falling back to sorting by modification date. Original error: Invalid Version: debian
[ADB] Found 2 'build-tools' folders under '/usr/lib/android-sdk' (newest first):
[ADB]     /usr/lib/android-sdk/build-tools/24.0.0
[ADB]     /usr/lib/android-sdk/build-tools/debian
[ADB] Using adb from /usr/lib/android-sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: ce07182754f76b0405
[debug] [ADB] Setting device id to ce07182754f76b0405
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 26
[debug] [ADB] Device API level: 26
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Using the alternative activity name detection method because of: Could not find apkanalyzer in /usr/lib/android-sdk/platform-tools/apkanalyzer,/usr/lib/android-sdk/emulator/apkanalyzer,/usr/lib/android-sdk/tools/apkanalyzer,/usr/lib/android-sdk/tools/bin/apkanalyzer,/usr/lib/android-sdk/build-tools/24.0.0/apkanalyzer,/usr/lib/android-sdk/build-tools/debian/apkanalyzer. Do you have the Android SDK installed at '/usr/lib/android-sdk'?
[ADB] Checking whether aapt is present
[ADB] Using aapt from /usr/lib/android-sdk/build-tools/24.0.0/aapt
[ADB] Extracting package and launch activity from manifest
[ADB] Package name: 'com.coople.android.worker.debug'
[ADB] Main activity name: 'com.coople.android.worker.screen.splash.SplashActivity'
[debug] [AndroidDriver] Parsed package and activity are: com.coople.android.worker.debug/com.coople.android.worker.screen.splash.SplashActivity
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 wait-for-device'
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell dumpsys package io.appium.settings'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('2.14.0' >= '2.14.0')
[debug] [ADB] There is no need to install/upgrade '/usr/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell 'pgrep --help; echo $?''
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell pgrep \^appium\\.settings\$'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell appops set io.appium.settings android\:mock_location allow'
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Enabling Unicode keyboard support
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell settings get secure default_input_method'
[debug] [AndroidDriver] Unsetting previous IME io.appium.android.ime/.UnicodeIME
[debug] [AndroidDriver] Setting IME to 'io.appium.settings/.UnicodeIME'
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell ime enable io.appium.settings/.UnicodeIME'
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell ime set io.appium.settings/.UnicodeIME'
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is installed
[debug] [ADB] Getting package info for 'io.appium.uiautomator2.server'
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('3.1.1' >= '3.1.1')
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[debug] [ADB] Checking app cert for /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.1.1.apk
[ADB] Cannot use apksigner tool for signature verification. Original error: Could not find apksigner in /usr/lib/android-sdk/platform-tools/apksigner,/usr/lib/android-sdk/emulator/apksigner,/usr/lib/android-sdk/tools/apksigner,/usr/lib/android-sdk/tools/bin/apksigner,/usr/lib/android-sdk/build-tools/24.0.0/apksigner,/usr/lib/android-sdk/build-tools/debian/apksigner. Do you have the Android SDK installed at '/usr/lib/android-sdk'?
[debug] [ADB] Defaulting to verify.jar
[debug] [ADB] '/usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.1.1.apk' is already signed.
[debug] [ADB] Checking app cert for /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] '/usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' does not exist
[debug] [ADB] Signing '/usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' with default cert
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [WD Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [UiAutomator2] Resetting IME to 'io.appium.android.ime/.UnicodeIME'
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell ime set io.appium.android.ime/.UnicodeIME'
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 shell am force-stop com.coople.android.worker.debug'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s ce07182754f76b0405 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1550475869092 (10:44:29 GMT+0300 (Moscow Standard Time))
[debug] [W3C] Encountered internal error running command: Error: /usr/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk file doesn't exist.
[debug] [W3C]     at ADB.apkSigningMethods.signWithDefaultCert (/usr/lib/node_modules/appium/node_modules/appium-adb/lib/tools/apk-signing.js:106:11)
[HTTP] <-- POST /wd/hub/session 500 5365 ms - 769
[HTTP]
`

**Comment by mykola-mokhnach** [comment]
> Cannot use apksigner tool for signature verification. Original error: Could not find apksigner in /usr/lib/android-sdk/platform-tools/apksigner,/usr/lib/android-sdk/emulator/apksigner,/usr/lib/android-sdk/tools/apksigner,/usr/lib/android-sdk/tools/bin/apksigner,/usr/lib/android-sdk/build-tools/24.0.0/apksigner,/usr/lib/android-sdk/build-tools/debian/apksigner. Do you have the Android SDK installed at '/usr/lib/android-sdk'? [debug] [ADB] Defaulting to verify.jar

This is the real problem. Install the recent Android SDK

**Comment by dpgraham** [comment]
Can you try again with a more recent Android SDK. If the problem persists, then I'll leave the issue open.

**Comment by 18070592371** [comment]
I also have this problem.

**Comment by kbalakumar99** [comment]
I am installing 'appium settings apk' using adb command(to use unicode keyboard) and then run appium test. Facing same error.

adb -s emulator-5554 install /appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk

Is there any error in doing above ?

**Comment by KazuCocoa** [comment]
Can you see "BUILD SUCCESSFUL" message on the result message?
```
$ cd /appium/node_modules/io.appium.settings/
$ npm run build
```

If so, you probably can see `/appium/node_modules/io.appium.settings/app/build/outputs/apk/debug/settings_apk-debug.apk` after that. Appium generates apks used by appium modules. If something error happens or removed by antivirous (for example), you should resolve the environment.

**Comment by 18070592371** [comment]
@KazuCocoa 
You mean, just shut down the firewall?

**Comment by kbalakumar99** [comment]
Hi,
I am running appium and emulator inside docker container. 
The settings app installation error occurs very first time only. It runs for the second time.
How could I debug this?

**Comment by KazuCocoa** [comment]
Not sure if your case is an antivirus. If you could build the apk no issue, maybe something happened after npm install command, I assumed.
@18070592371 

@kbalakumar99 
Only make sure if the file exists, below steps are enough, I think. In general, you can see the `settings_apk-debug.apk` after npm install command.
1. ssh to the container
2. ensure the apk exists after npm install command

You can track what happens in appium log, too. You can see push actions etc for the setting app in the appium log.

**Comment by kbalakumar99** [comment]
I will try and send you the logs

**Comment by 18070592371** [comment]
@KazuCocoa 
![image](https://user-images.githubusercontent.com/37534431/55284936-046cc780-53b3-11e9-8d2f-b62d5b39f9a0.png)
![image](https://user-images.githubusercontent.com/37534431/55284939-15b5d400-53b3-11e9-9e11-3c492222fabc.png)
APK file exists, I just run APPIUM code, will automatically help me delete APK, resulting in APPIUM prompt can not find appium-uiautomator2-server-debug-androidTest.apk file

**Comment by 18070592371** [comment]
@KazuCocoa 
Can you help me look at 12413, which affects the progress of my work. I suspect it's the BUG of APPIUM.

**Comment by KazuCocoa** [comment]
Can you share your full server log with `automationName: uiautomator2`?

Is 12413 about UIA2? If UIA1, it not work fine for over Android OS 6.0. (deprecated module)
If it is UIA2, you do not have this deleting app issue, right?

**Comment by 18070592371** [comment]
@KazuCocoa 
Yes, I use ui2. But waiting a few minutes with elements will make APPIUM sleep for no reason.

**Comment by 18070592371** [comment]
@KazuCocoa 
[log.txt](https://github.com/appium/appium/files/3026258/log.txt)
![image](https://user-images.githubusercontent.com/37534431/55285368-574b7c80-53bd-11e9-9933-1193806e5db8.png)

**Comment by kbalakumar99** [comment]
@KazuCocoa 
Kindly check these logs. 

First-time appium throws 

> [debug] [W3C] java.lang.IllegalArgumentException: Unknown id: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME

But it runs perfectly for the second time

https://gist.github.com/kbalakumar99/351cdc1221144856b5821aadd21d0d85#file-unicode-error-log

**Comment by kbalakumar99** [comment]
> @KazuCocoa
> Kindly check these logs.
> 
> First-time appium throws
> 
> > [debug] [W3C] java.lang.IllegalArgumentException: Unknown id: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
> 
> But it runs perfectly for the second time
> 
> https://gist.github.com/kbalakumar99/351cdc1221144856b5821aadd21d0d85#file-unicode-error-log

In order to avoid this first time issue, I am installing settings apk manually before running test.

But this time I am getting different error. 

> [debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/home/android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/home/android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp\:8200' exited with code 1'; Stderr: 'adb: error: listener 'tcp:8200' not found'; Code: '1''
[UiAutomator2] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/home/android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_pre_p_apps'
[debug] [ADB] Running '/home/android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy_p_apps'
[debug] [ADB] Running '/home/android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell settings delete global hidden_api_policy'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1554100185077 (06:29:45 GMT+0000 (GMT))
[debug] [W3C] Encountered internal error running command: Error executing adbExec. Original error: 'Command '/home/android/sdk/platform-tools/adb -P 5037 -s emulator-5554 push /home/android/.nvm/versions/node/v11.13.0/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.4.0.apk /data/local/tmp/appium_cache/02df6e49ef686c7e87be1bd47bd76ba13524fb68.apk' exited with code 1'; Stderr: ''; Code: '1'
[debug] [W3C] Error: Command '/home/android/sdk/platform-tools/adb -P 5037 -s emulator-5554 push /home/android/.nvm/versions/node/v11.13.0/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v3.4.0.apk /data/local/tmp/appium_cache/02df6e49ef686c7e87be1bd47bd76ba13524fb68.apk' exited with code 1
[debug] [W3C]     at ChildProcess.proc.on.code (/home/android/.nvm/versions/node/v11.13.0/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:94:19)
[debug] [W3C]     at ChildProcess.emit (events.js:193:13)
[debug] [W3C]     at maybeClose (internal/child_process.js:1001:16)
[debug] [W3C]     at Socket.stream.socket.on (internal/child_process.js:405:11)
[debug] [W3C]     at Socket.emit (events.js:193:13)
[debug] [W3C]     at Pipe._handle.close (net.js:614:12)
[HTTP] <-- POST /wd/hub/session 500 12937 ms - 1327

**Comment by KazuCocoa** [comment]
It seems failed to push/install the apk to the device in caching logic...

```
[debug] [ADB] Running '/home/android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ls -t -1 /data/local/tmp/appium_cache'
[debug] [ADB] The count of applications in the cache: 0
[ADB] Caching the application at '/home/android/.nvm/versions/node/v11.13.0/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk' to '/data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk'
[debug] [ADB] Running '/home/android/sdk/platform-tools/adb -P 5037 -s emulator-5554 push /home/android/.nvm/versions/node/v11.13.0/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk'
[AndroidDriver] Ignored error while installing Appium Settings helper: 'Error executing adbExec. Original error: 'Command '/home/android/sdk/platform-tools/adb -P 5037 -s emulator-5554 push /home/android/.nvm/versions/node/v11.13.0/lib/node_modules/appium/node_modules/io.appium.settings/apks/settings_apk-debug.apk /data/local/tmp/appium_cache/728413456b86856a2003edeb524d6bd577ca6418.apk' exited with code 1'; Stderr: ''; Code: '1''. Manually uninstalling the application with package id 'io.appium.settings' may help. Expect some Appium features may not work as expected unless this problem is fixed.
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
```

Can you try with Appium 1.11.0 if you have a chance?
@kbalakumar99

----

Current beta has retry logic in the push/install. It probably helps this case, too.

**Comment by susanma** [comment]
I had run into this issue with appium 10.  Found a clunky way to fix it.
From a command prompt run:

adb uninstall io.appium.settings
adb uninstall io.appium.unlock
adb kill-server
adb start-server  //these last two may not be necessary but at this point it can't hurt.

uninstall and reinstall appium

Try running again.  It may take running it a couple of times to get it completely working but hopefully this will help you.

**Comment by benfr1** [comment]
this is DEFINITELY a file based issue. so from installation.
I had a working 1.12, upgraded to 1.14  and the issue magically reoccured !
I will never upgrade appium again !! :)
solution : I had another machine on which a working appium 1.12 was installed.
I copied the whole root node_modules directory of that server to the other, and again eveything worked. pfff

**Comment by hijazi** [comment]
I'm still having the original issue with a fresh npm appium install with webdriverio.
I've just created a thread here: https://discuss.appium.io/t/uiautomator2-is-deleting-appium-uiautomator2-server-debug-androidtest-apk/29186
to follow up on it, please if you can help it would be appreciated.
