### ISSUE TITLE
Appium For Mac Doesn't do PNG images correctly within screenshots

### ISSUE THREAD

**Issue by kimjunte** [appium/appium#12229]
https://github.com/appium/appium-for-mac/issues/52

**Comment by mykola-mokhnach** [comment]
The server code seems to return the image in TIFF format instead of PNG: https://github.com/appium/appium-for-mac/blob/2356957dc73b6275262c918ca8f4184ef4a25af0/AppiumForMac/Server/Handlers/AfMHandlers.m#L256

Also, I don't see any reason why the clipboard interaction is needed in order to take a screenshot.

**Comment by kimjunte** [comment]
Thank you for looking into the issue, I made a temporary fix with the correct file type.

**Comment by michaelelcat** [comment]
@kimjunte Saw your previous thread which linked to this. What was your temporary fix? I

**Comment by mykola-mokhnach** [comment]
@kimjunte You're welcome to create a pull request with a fix for the Appium repository

**Comment by kimjunte** [comment]
Apologies for late reply:

I've changed my output image file to have the '.tif' format.

Didn't change anything within the appium branch so no pull repository necessary. [Although if you could show me how I would love to contribute to the Appium project]

Once I've got the binary data of the image, I've change my output file to have the '.tif' instead of '.png'
