### ISSUE TITLE
ECONNREFUSED error when trying to run on iOS Simulator

### ISSUE THREAD

**Issue by iBolom** [appium/appium#12434]
## The problem
After complete setup Appium with all dependencies installed and run 'appium' command in terminal everything works. When i run Eclipse project, iOS Simulator is starting and getting this error in command line:
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}

## Environment

* Appium version v.1.12.1
* Last Appium version that did not exhibit the issue (if applicable): /
* Desktop OS/version used to run Appium: Mojave 10.14.4
* Node.js version (unless using Appium.app|exe): 6.4.1
* Npm or Yarn package manager: /
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: both

## Code To Reproduce Issue [ Good To Have ]

  public void setupAppium() throws MalformedURLException {
    //2
    final String URL_STRING = "http://127.0.0.1:4723/wd/hub";
    url = new URL(URL_STRING);
    
    //3
    capabilities = new DesiredCapabilities();
    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone Simulator");
    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
    capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "12.1");
    capabilities.setCapability(MobileCapabilityType.APP, "/Users/bojan/Desktop/UI Testing Appium/AppiumUITestProject/build/Release-iphonesimulator/AppiumUITestProject.app");
    capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
    capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
    capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
    capabilities.setCapability("useNewWDA", true);
    //4
    driver = new IOSDriver<IOSElement>(url, capabilities);
    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
    driver.resetApp();
  }

Can someone help me with this problem ? I spent a lot of time to fix it but couldn't :/

**Comment by mykola-mokhnach** [comment]
Please attach the full server log

**Comment by iBolom** [comment]
https://gist.github.com/iBolom/0436a966d5a4f89291e94ce567700a33

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2019-04-03 17:38:02.623 xcodebuild[16908:1362690] Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." UserInfo={NSLocalizedFailureReason=Failed to load Info.plist from bundle at path /Users/bojan/Library/Developer/CoreSimulator/Devices/1FBDF554-10B3-45EA-B9CA-232C987BFDC5/data/Library/Caches/com.apple.mobile.installd.staging/temp.5Xd1zZ/extracted/Payload/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7ffd34c7c900 {Error Domain=MIInstallerErrorDomain Code=35 "Failed to load Info.plist from bundle at path /Users/bojan/Library/Developer/CoreSimulator/Devices/1FBDF554-10B3-45EA-B9CA-232C987BFDC5/data/Library/Caches/com.apple.mobile.installd.staging/temp.5Xd1zZ/extracted/Payload/WebDriverAgentRunner-Runner.app" UserInfo={LegacyErrorString=PackageInspectionFailed, FunctionName=-[MIBundle _validateWithError:], SourceFileLine=38, NSLocalizedDescription=Failed to load Info.plist from bundle at path /Users/bojan/Library/Developer/CoreSimulator/Devices/1FBDF554-10B3-45EA-B9CA-232C987BFDC5/data/Library/Caches/com.apple.mobile.installd.staging/temp.5Xd1zZ/extracted/Payload/WebDriverAgentRunner-Runner.app}}, NSLocalizedRecoverySuggestion=Failed to load Info.plist from bundle at path /Users/bojan/Library/Developer/CoreSimulator/Devices/1FBDF554-10B3-45EA-B9CA-232C987BFDC5/data/Library/Caches/com.apple.mobile.installd.staging/temp.5Xd1zZ/extracted/Payload/WebDriverAgentRunner-Runner.app, NSLocalizedDescription=This app could not be installed at this time.}

This is the real problem. Are you able to compile and deploy webdriveragent manually from Xcode?

**Comment by mykola-mokhnach** [comment]
Also, are you able to start the app manually on simulator? Checking the device logs might also sched some light on why the app crashes

**Comment by iBolom** [comment]
I can run the app manually on simulator without crashing because i created an empty Tabbed project so it can't crash. Also i can run WebDriverAgentRunner from Xcode manually on device.

**Comment by mykola-mokhnach** [comment]
Enable `showIOSLog` cap to see the system logs and attach the updated gist

**Comment by iBolom** [comment]
When i put this flag to true, it works! 👍

**Comment by iBolom** [comment]
Here is the gist file when i include this flag:
https://gist.github.com/iBolom/c4614137455cea1e24890740761c31a9

**Comment by mykola-mokhnach** [comment]
Looks like a race condition problem. Although I'm not sure if there is anything to change on Appium side

**Comment by iBolom** [comment]
Maybe to set this flag to true by default i am not sure who is responsible for that but if that is on Appium side, this can be temporary solution.

**Comment by mykola-mokhnach** [comment]
> Maybe to set this flag to true by default i am not sure who is responsible for that but if that is on Appium side, this can be temporary solution.

I think it is some local issue in how xctest interacts with the application under test. As for the current application startup flow I'd rather keep everything as is.

**Comment by AswinMadathilUST** [comment]
I am having the same issue with the same configuration and setting showIOSLog to true won't  give me any luck. Could you pls hep me on this. My Appium version is 1.12.1 and Xcode version is 10.2

**Comment by mrk-han** [comment]
This is happening to me as well with 1.13, xcode 10.2, and 12.2 iOS simulator. Going to get logs and attach asap

**Comment by TC-rGangal** [comment]
Seeing the same issue. version details : 
Appium version: 1.13.0
Xcode version: 10.1
iOS Simulator version: 10.1

**Comment by takn** [comment]
I'm seeing the same thing running on mojave

**Comment by shamprasadrh** [comment]
> This is happening to me as well with 1.13, xcode 10.2, and 12.2 iOS simulator. Going to get logs and attach asap
> 
> ![image](https://user-images.githubusercontent.com/22263679/60055606-2624d480-96ac-11e9-8f30-9e1cd8d870c9.png)
> After enabling this, things seemed to go smoothly… but didn’t appear when I started the appium server from the command line.

Hi How did you get this dialog?

**Comment by rutushah** [comment]
Same  issue is coming with me, I am not able to start my .app file through appium it shows following error.

1. Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100} 

2. An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2021-12-17 17:15:10.514 xcodebuild[6078:125178] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphonesimulator14.2-x86_64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphonesimulator14.2-x86_64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7ffd8942fe00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} ** TEST BUILD FAILED ** 2021-12-17 17:15:10.551 xcodebuild[6078:125132] IDETestOperationsObserverDebug: Writing diagnostic log for test session to: /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-D2FB48E7-2E17-4487-9AA2-A631E03B1384/WebDriverAgentRunner-A2A231BB-4034-4870-99DE-063466D123E0/Session-WebDriverAgentRunner-2021-12-17_171510-UHd668.log 2021-12-17 17:15:10.553 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: (C760AE5F-1079-416C-B83F-7F80C9E27A62) Beginning test session WebDriverAgentRunner-C760AE5F-1079-416C-B83F-7F80C9E27A62 at 2021-12-17 17:15:10.553 with Xcode 12B45b on target <DVTiPhoneSimulator: 0x7ffd89a4c360> { SimDevice: iPhone 11 Pro (7310564F-6C3B-47BD-AC4C-3ADC647F55D8, iOS 14.2, Booted) } (14.2 (18B79)) 2021-12-17 17:15:10.579 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: (C760AE5F-1079-416C-B83F-7F80C9E27A62) Finished requesting crash reports. Continuing with testing. *** If you believe this error represents a bug, please attach the result bundle at /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult 2021-12-17 17:15:14.683 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: 4.147 elapsed -- Testing started completed. 2021-12-17 17:15:14.684 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start 2021-12-17 17:15:14.684 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: 4.147 sec, +4.147 sec -- end Test session results, code coverage, and logs: /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult Testing failed: Building for iOS Simulator, but the linked and embedded framework 'RoutingHTTPServer.framework' was built for iOS. Building for iOS Simulator, but the linked framework 'CocoaAsyncSocket.framework' was built for tvOS + tvOS Simulator. Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS. Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS. Building for iOS Simulator, but the embedded framework 'RoutingHTTPServer.framework' was built for iOS. WebDriverAgentRunner: WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-

my appium version is 1.12.1
xcode version 12.2
macOS 10.15.7 
Can someone help me how to solve this error?

**Comment by npesudip** [comment]
i am alos getting same error
