### ISSUE TITLE
Wait until wifi is connected

### ISSUE THREAD

**Issue by zuzeac** [appium/appium#12502]
## The problem ( More like a new feature)

Is there a method to wait until the connection state is Connected then continue with the test execution?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.12.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.14
* Node.js version (unless using Appium.app|exe): 11.6.0
* Npm or Yarn package manager: 6.5.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

I'm turning off the wifi then I turning on again. And I need to move forward with the steps after the wifi is connected. The problem is that the steps are executed before the device is connected. It takes some second since I turn on the wifi and it connects again.
 I found this command and I will try to executed based on my needs:
adb shell dumpsys wifi | grep "mNetworkInfo"
But I was thinking, maybe we can add something like this in Appium waitUntil(ExpectedCondition.etc..)

**Comment by mykola-mokhnach** [comment]
I think we could add such info (wifi state, and, probably, the AP name) into device_details endpoint

**Comment by mykola-mokhnach** [comment]
Since the recent appium@beta you can use `mobile: deviceInfo` endpoint in UIA2 to get the information about the state of all device networks. The given endpoint should return a map whose `networks` key will include the list of available networks with their properties. Check https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/handler/GetDeviceInfo.java, https://developer.android.com/reference/android/net/NetworkInfo and https://developer.android.com/reference/android/net/NetworkCapabilities.html for more details on the available entries.

**Comment by zuzeac** [comment]
Thank you very much :)
