### ISSUE TITLE
Can we override capabilities at runtime in IOS - Appium

### ISSUE THREAD

**Issue by AdarshKumarGM** [appium/appium#12812]
Hello,

I have certain set of desired capabilities which I am already using to start my native app. However, there seems to be a situation in my test, where in ( for example: email address ), I will require to override the capabilities which has already been set. 

Is this possible?  I am looking at Javascript / if any other functions available for me to look at.

**Appium Version:** 1.13.0
**IOS Simulator:** iPhone X (Version: 12.1)

Can you please help

**Comment by mykola-mokhnach** [comment]
Selenium API assumes the capabilities are set per sessions and there is no way to change them after the session has already been started.

Although, there is probably another workaround to your problem. But it is not possible to advice more since not many details have been provided. Feel free to use Appium forum to ask questions.
