### ISSUE TITLE
Appium service runs in the power shell of windows. Sometimes Stuck

### ISSUE THREAD

**Issue by dtboy1995** [appium/appium#12858]
**Appium service runs in the `powershell` of windows. It executes some programs and sometimes does not respond. But it can continue to execute by pressing a key at will in the `powershell`. It looks like the terminal console is stuck. Is this a bug on the windows command line or a related problem of `appium`? How to solve this problem?**

### Any help would be appreciated

**Comment by mykola-mokhnach** [comment]
Sorry, but there will be no response to such issues description unless it is described properly.

**Comment by dtboy1995** [comment]
@mykola-mokhnach thanks for reply
At some point when the command is executed, the terminal that started appium is stuck and needs to press any key to continue.

**Comment by KazuCocoa** [comment]
Could you attache Appium logs, CPU usage etc?
We could assume when such behaviour happens in what sequence etc from it.

**Comment by dtboy1995** [comment]
@KazuCocoa thanks

I feel like a bug in the Windows console, or something else, because I will encounter a similar situation in my usual development. Simply speaking, the terminal is stuck, and I need to press some buttons to let him continue executing. It's a strange phenomenon, but I don't know why.

**Comment by dtboy1995** [comment]
I want to ask a fundamental question. Is it recommended to use appium in Windows? Because I don't think there will be any stuck problem under * nux.

**Comment by KazuCocoa** [comment]
@dtboy1995 
I would recommend you to use *nix first, personally.

Mostly we develop on macOS because of iOS support.
I also have experience on Linux for Android (on CI and local machines)., a couple of times on Windows (but it is not recent years)
For us, easy to find issues on *nux systems. Appium itself, node and adb environment etc as well.

I got questions about running on Windows x Android. They were able to run Appium on windows, but they sometimes had issues on Windows like permission issues, PATH or adb issues.
(I haven't heard your case tho...)

**Comment by dtboy1995** [comment]
@KazuCocoa Thank you for your reply. I will find out the problem first

**Comment by babusekaran** [comment]
@dtboy1995 you can try upgrading your `powershell`  and see if there is any improvement 

Download -> https://github.com/PowerShell/PowerShell/releases

**Comment by dtboy1995** [comment]
@babusekaran thanks, a lot i'll try it

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. Please let us know if you have more findings on that
