### ISSUE TITLE
Initial URL safari iOS real device

### ISSUE THREAD

**Issue by kolyakrasnik** [appium/appium#12882]
## The problem

I'm testing deep links via browser. After creating a new safari driver, safari opens with the link, that was executed before and redirects from safari browser to Appstore (in my case).
So, after start up I'm getting Appstore instead of browser and seeing timeout in the logs ```Webkit response timeout: 5000```. Is it a way to start browser with predefined URL on real device? 

## Environment

 - iOS real device
 - appium: 1.13.0-beta.3

## Appium logs
https://gist.github.com/kolyakrasnik/ba6b4a6ae6161bbf1e6e248bfee379e1

**Comment by umutuzgur** [comment]
@kolyakrasnik You can do that with `safariInitialUrl`. However, this is no longer possible with iOS 12.2 and above as Apple deprecated this functionality

**Comment by kolyakrasnik** [comment]
@umutuzgur ```safariInitialUrl``` works for simulators only and we use 12.3.1 iOS real devices for testing. That's why I asking.

**Comment by umutuzgur** [comment]
@kolyakrasnik It also works for real devices but the documentation is wrong. However, this is not helpful in your case since the device is 12.3.1. You can try automating safari as a native app instead of a browser with the `bundleId` capability and set the bundleId to `com.apple.mobilesafari`. Then, you can give it a try to set the url in safari and maybe that would be a workaround in your case

**Comment by umutuzgur** [comment]
Closing since a workaround is offered
