### ISSUE TITLE
Is it possible to run chrome browser on IOS Simulator using appium

### ISSUE THREAD

**Issue by Sourabh25** [appium/appium#12999]
## The problem

Is it possible to run chrome browser on IOS Simulator using appium ios driver? 
If yes, Could you please share the capabilities I need to have.

Thanks

**Comment by KazuCocoa** [comment]
The bundle id to run with is `com.google.chrome.ios`
https://discuss.appium.io is a more helpful place for such questions

**Comment by Sourabh25** [comment]
I am getting the below exception:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: App with bundle identifier 'com.google.chrome.ios' unknown

Could you please update. Also I want to keep the status open for this until this is resolved. Thanks

**Comment by KazuCocoa** [comment]
Ah, you use a simulator.
Technically cannot since you must install the app on your simulator.
(No way to install it)

For real device, it should work if your env has the bundle id's Google chrome.

This is not Appium issue.
No way to resolve it with Appium side since no way to install it in simulators.
