### ISSUE TITLE
Encountered internal error running command: Error: zipAlignApk failed Selendroid

### ISSUE THREAD

**Issue by Phoenix124** [appium/appium#13112]
## The problem

I'll try to automate Android API 16 with Selendroid 

## Environment

* Appium version 1.13.0
* MacOS
* Node.js version 10.15.3
* Npm 6.11.2
* Mobile platform Android API 16
* Emulator
* Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/Phoenix124/be8572828669c03884b912562525b12a

**Comment by umutuzgur** [comment]
Hi @Phoenix124. We are discontinuing the Selendroid driver in Appium with the next release, FYI

**Comment by Phoenix124** [comment]
@umutuzgur btw, what automation use to automate Android API 16?
UiAutomator1?

**Comment by mykola-mokhnach** [comment]
UiAutomator1 only works since API 18

If this is really needed then I would try to setup a machine with older Android SDK, install Appium 1.6 or close to it, downgrade the API client to that version and then it would probably work. Although, I wouldn't expect much support there, because the tech is very old and gets deprecated (or already got) everywhere.

**Comment by Phoenix124** [comment]
@mykola-mokhnach thanks for info

**Comment by mykola-mokhnach** [comment]
Closed as inactive
