### ISSUE TITLE
"Name" Field Missing In Images Inside CollectionView

### ISSUE THREAD

**Issue by ajschwieterman** [appium/appium#13397]
## The problem

Before iOS 13, I was able to get the image element I was looking for by finding the name of the image using the _name_ attribute of the element.  These images were inside a CollectionView. 
 After installing iOS 13, the name attribute is missing from the image elements, and I can't find the specific image element I'm looking for.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.14.0 and v1.15.0
* Last Appium version that did not exhibit the issue (if applicable): v1.14.0
* Desktop OS/version used to run Appium: macOS Mojave v10.14.6
* Node.js version (unless using Appium.app|exe): v12.10.0
* Npm or Yarn package manager: v6.10.3
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
The page source is generated by XCTest and we don't have much influence to that. Consider reporting the problem to Apple

**Comment by nGervasyuk** [comment]
The same problem not for Image type only.
In 11 Xcode (with 12/13 iOS) the name of 'value 'attribute is missing.
Fixed by adding accessibility label for element to Xcode project, but it always works correct.
![Снимок экрана 2019-10-11 в 11 22 46](https://user-images.githubusercontent.com/20280571/66636356-b49c7200-ec19-11e9-8e16-ac7e2c741c70.png)

**Comment by ajschwieterman** [comment]
Thank you for the responses.  I had the development team add an accessibilityIdentifier to each element I was looking for, and the _name_ field showed up again in Appium.
