### ISSUE TITLE
[iOS 12.x<]Unable to launch URL and interact with the Safari browser

### ISSUE THREAD

**Issue by sasasa42** [appium/appium#13450]
## The problem

While trying to run the automation on a Safari browser, to launch the url and to interact with the elements, it is not successful. It just gets hung without any progress.

## Environment

*Appium version : 1.15.1
*Last Appium version that did not exhibit the issue (if applicable): 1.15.1
*Desktop OS/version used to run Appium: 10.14.6
*Node.js version (unless using Appium.app|exe): 12.11.1
*Npm or Yarn package manager: 6.11.3
*Mobile platform/version under test: iOS
*Real device or emulator/simulator: Real device
*Appium CLI or Appium.app|exe: Appium CLI

## Details

It is working perfectly fine when run on iOS 11.2.6, but the moment I run any iOS versions above like 12.4.1 or 13.1, it just does not launch the url on iOS 12.4.1, but on iOS 13.1, it launches the url, but does not identify any elements in the browser session.

## Link to Appium logs

https://gist.github.com/sasasa42/95f027a816d4602cb65e0edb19f33623
https://gist.github.com/sasasa42/998b47499792647b2ee693518d6eb771

**Comment by mykola-mokhnach** [comment]
Have you tried appium@beta?

**Comment by sasasa42** [comment]
No. I have not tried it. We only have v1.15.0-beta.1 right?

**Comment by umutuzgur** [comment]
@sasasa42 I'm seeing that you are passing a platformVersion,11.2.6, which is not the same as the device's version in your capabilities. It is breaking then how we start safari since you have an iOS 13 device. If you remove it, it should work as expected

**Comment by sasasa42** [comment]
It is correct only. The platform Version is what was working before. I don't think there is anything wrong there. this is actually an issue itself.

**Comment by TetianaMarchenko** [comment]
I have exactly the same issue. I've been trying to solve it for two days in a row, no luck. Any update about this issue?

**Comment by mykola-mokhnach** [comment]
@imurchie It looks like we need to verify the actual SDK version for Simulators rather than the operating system version.

**Comment by imurchie** [comment]
Can you please try the latest beta of Appium, ensuring that the installed version of `appium-remote-debugger` is `6.3.0`
```
npm uninstall -g appium
npm install -g appium@beta

npm ls -g appium-remote-debugger
```
The last ought to output something like:
```
$ npm ls -g appium-remote-debugger
/Users/isaacmurchie/.nvm/versions/node/v10.16.3/lib
└─┬ appium@1.16.0-beta.1
  ├─┬ appium-ios-driver@4.4.0
  │ └── appium-remote-debugger@4.5.0
  ├─┬ appium-xcuitest-driver@3.3.0
  │ └── appium-remote-debugger@6.3.0
  └─┬ appium-youiengine-driver@1.2.1
    └─┬ appium-xcuitest-driver@2.133.1
      └── appium-remote-debugger@5.7.0
```
The listing of `appium-remote-debugger` under `appium-xcuitest-driver` should be `6.3.0`.

**Comment by sasasa42** [comment]
@mykola-mokhnach , I tried with the Appium beta 1.16. It is not able to launch the url in the browser, it keeps trying to find a web view. PFB the link to the logs:
https://gist.github.com/sasasa42/4381e46e952e414860050f2073321233

**Comment by imurchie** [comment]
@sasasa42 Can you try what is described here: https://github.com/appium/appium/issues/13361#issuecomment-551965421

**Comment by sasasa42** [comment]
Yes @imurchie. It just hangs. PFB the logs:
https://gist.github.com/sasasa42/aff39c77ea74571a71fbdc0880e4f815
https://gist.github.com/sasasa42/7c5e95815109c63578c1823f84653d38

**Comment by imurchie** [comment]
I have published, in the latest Appium beta, the results of all of my experimentation. For my tests things are much better, hopefully for others as well.

- `appium-xcuitest-driver` should be at least v3.6.0
- `appium-ios-device` should be at least v1.2.1
- `appium-remote-debugger` should be at least v6.7.0

**Comment by nanoscopic** [comment]
This doesn't work for me on the latest head versions of everything. It is clearly broken. Why does this have a 'NeedsInfo' tag? The comments above describe the situation clearly.

I am easily able to launch Safari myself directly through WDA, so there doesn't seem to be a technical limitation; Appium is simply not doing what it should.

**Comment by imurchie** [comment]
The "NeedsInfo" tag is relevant because each iteration of work on this might change the output into the logs, adding more information to try to get to the bottom of the problem.

As it stands I have no idea if anyone has tried with the latest versions of the packages, or what the situation is when they have. There is no new information and so there is nothing more that we can do.

The technical limitation is not launching Safari. That is, and always has been, a simple task.

**Comment by nanoscopic** [comment]
Both myself and another person above stated that they did try the latest versions of the packages.

The situation remains that the Safari browser is not launched. There is also a problem sometimes detecting that the browser is already open in certain conditions, but that is not the way I am viewing this ticket. So I agree perhaps what issue is being addressed should be stated more clearly.

The latest version does detect webview if Safari is already open, on all IOS versions, most of the time. The issue I am concerned about is why Safari is not being launched, nor brought to foreground if running and minimized. If minimized that is detected but it fails to bring it to the foreground...

I agree that it should be simple for Safari to be launched, which is why I am wondering why it has been that way for some time now. The fix should be easy. I would fix it myself but I am unfamiliar with the codebase and with how Safari is being launched currently.

Problem from my point of view:
1. Git clone latest WDA from Appium. Build it and run it against phone.
2. Git clone latest Appium. Npm build and run it; configured against Selenium Grid Hub.
3. Send basic capabilities to Selenium Grid Hub and basic code just to open a URL.
4. Browser fails to open.
4b. Launch browser manually first
5. Script then works

That I believe has been described above; perhaps unclearly, but is the problem. It occurs for me on both 12.x and 13.x ios real devices.

Additional details which I don't think particularly matter:

I'm using these capabilities:
`apabilities.setCapability("platformVersion", "12.3.1");
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("deviceName", "iPhone");
capabilities.setCapability("browserName", "Safari");
capabilities.setCapability("webDriverAgentUrl", "http://localhost:8100");`

I'm not letting Appium run WDA itself; am starting it myself hence specifying the webDriverAgentUrl.

I get these output many times in loop from Appium until the moment I manually launch Safari:
`[debug] [XCUITest] No web frames found.
[iOS] Could not find any webviews yet, refreshing/retrying
[debug] [iOS] Retrieving contexts and views
[debug] [XCUITest] Selecting by url: false
[debug] [RemoteDebugger] Sending connection key request
[debug] [RemoteDebugger] Sending '_rpc_reportIdentifier:' message (id: 69)
[debug] [RemoteDebugger] Sending to Web Inspector took 4ms
[debug] [RemoteDebugger] Selecting application
[debug] [RemoteDebugger] No applications currently connected.
[debug] [XCUITest] No web frames found.`

**Comment by imurchie** [comment]
Alright, sorry, I got this ticket mixed up with another, vis-a-vis opening Safari.

Do you have `noReset` set to `false`? I once found that accidentally going through the real device reset flow while performing a Safari test stopped Safari from launching. The only thing I could do to get it to work again was restart the phone, then set the `noReset` capability to `false`.

**Comment by imurchie** [comment]
But in that case (just tried it) WDA fails to start a session, logging `Failed to launch com.apple.mobilesafari application`. 

What are you complete capabilities?

**Comment by sasasa42** [comment]
@imurchie After get the latest beta, the issue now lies with signing. I am unable to proceed to launch the WDA itself.PFB the log:
https://gist.github.com/sasasa42/2228a8652ac908c7d60d204474678bd5

**Comment by mykola-mokhnach** [comment]
Unfortunately, there is nothing to do in order to fix signing from Appium side. You can only setup it on your side. Follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
