### ISSUE TITLE
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}

### ISSUE THREAD

**Issue by apple-tester** [appium/appium#13585]
## The problem

Simulator crashes upon executing Java application and appium proceeds to display 
`[WD Proxy] Got an unexpected response with status undefined: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100`

I cannot proceed with testing since its saying that connection is being refused..

## Environment
* Appium: 1.13.0-beta.3
* Desktop OS: Mac 10.14.3 (Mojave)
* Node Version: v12.12.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details
- Tried uninstalling/installing vers. 12, 14 and latest versions of appium, all not working
- Tried adding `showXcodeLog`
- Executing `mkdir -p Resources/WebDriverAgent.bundle` and `./Scripts/bootstrap.sh -d`
- Tried every solution presented related to this :( Help

## Link to Appium logs

See FULL Appium logs here 
https://gist.github.com/apple-tester/bf88c2b0c136b5692193d62509a8cfea

## Code To Reproduce Issue [ Good To Have ]

		DesiredCapabilities caps = new DesiredCapabilities();
		caps.setCapability("platformName","iOS");
		caps.setCapability("platformVersion","12.4");
		caps.setCapability("deviceName", "iPhone 8");
		caps.setCapability("showXcodeLog", true);
		caps.setCapability("<sample ipa file here>");

		URL url = new URL("http://127.0.0.1:4723/wd/hub");
		IOSDriver driver = new IOSDriver(url, caps);

**Comment by mykola-mokhnach** [comment]
> [XCUITest] Simulator architecture appears to be unsupported by the '/var/folders/v_/7wgdf2r972dgvds1c3wp35200000gn/T/20191012-19781-51dnr4.xbd1y/Payload/calculator.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
> [XCUITest] Don't be surprised if the application fails to launch.

Seems like you need to get a proper build from the developers

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by rutushah** [comment]
[XCUITest] ** TEST EXECUTE FAILED **
[XCUITest] Testing started
[XCUITest] Quitting and uninstalling WebDriverAgent
[XCUITest] Shutting down sub-processes
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] xcodebuild error message:
[XCUITest] 
[XCUITest] 2021-12-17 17:15:10.514 xcodebuild[6078:125178] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphonesimulator14.2-x86_64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphonesimulator14.2-x86_64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7ffd8942fe00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[XCUITest] ** TEST BUILD FAILED **
[XCUITest] 2021-12-17 17:15:10.551 xcodebuild[6078:125132]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[XCUITest] /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-D2FB48E7-2E17-4487-9AA2-A631E03B1384/WebDriverAgentRunner-A2A231BB-4034-4870-99DE-063466D123E0/Session-WebDriverAgentRunner-2021-12-17_171510-UHd668.log
[XCUITest] 2021-12-17 17:15:10.553 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: (C760AE5F-1079-416C-B83F-7F80C9E27A62) Beginning test session WebDriverAgentRunner-C760AE5F-1079-416C-B83F-7F80C9E27A62 at 2021-12-17 17:15:10.553 with Xcode 12B45b on target  {
[XCUITest] 		SimDevice: iPhone 11 Pro (7310564F-6C3B-47BD-AC4C-3ADC647F55D8, iOS 14.2, Booted)
[XCUITest] } (14.2 (18B79))
[XCUITest] 2021-12-17 17:15:10.579 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: (C760AE5F-1079-416C-B83F-7F80C9E27A62) Finished requesting crash reports. Continuing with testing.
[XCUITest] *** If you believe this error represents a bug, please attach the result bundle at /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult
[XCUITest] 2021-12-17 17:15:14.683 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: 4.147 elapsed -- Testing started completed.
[XCUITest] 2021-12-17 17:15:14.684 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[XCUITest] 2021-12-17 17:15:14.684 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: 4.147 sec, +4.147 sec -- end
[XCUITest] Test session results, code coverage, and logs:
[XCUITest] 	/Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult
[XCUITest] Testing failed:
[XCUITest] 	Building for iOS Simulator, but the linked and embedded framework 'RoutingHTTPServer.framework' was built for iOS.
[XCUITest] 	Building for iOS Simulator, but the linked framework 'CocoaAsyncSocket.framework' was built for tvOS + tvOS Simulator.
[XCUITest] 	Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS.
[XCUITest] 	Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS.
[XCUITest] 	Building for iOS Simulator, but the embedded framework 'RoutingHTTPServer.framework' was built for iOS.
[XCUITest] 	WebDriverAgentRunner:
[XCUITest] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult. (Underlying Error: Cannot launch simulated executable: no file found at /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app))
[XCUITest] ** TEST EXECUTE FAILED **
[XCUITest] Testing started
[XCUITest]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:501:15)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[BaseDriver] Event 'newSessionStarted' logged at 1639779320029 (17:15:20 GMT-0500 (EST))
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[MJSONWP] xcodebuild error message:
[MJSONWP] 
[MJSONWP] 2021-12-17 17:15:10.514 xcodebuild[6078:125178] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphonesimulator14.2-x86_64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphonesimulator14.2-x86_64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7ffd8942fe00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[MJSONWP] ** TEST BUILD FAILED **
[MJSONWP] 2021-12-17 17:15:10.551 xcodebuild[6078:125132]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[MJSONWP] /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-D2FB48E7-2E17-4487-9AA2-A631E03B1384/WebDriverAgentRunner-A2A231BB-4034-4870-99DE-063466D123E0/Session-WebDriverAgentRunner-2021-12-17_171510-UHd668.log
[MJSONWP] 2021-12-17 17:15:10.553 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: (C760AE5F-1079-416C-B83F-7F80C9E27A62) Beginning test session WebDriverAgentRunner-C760AE5F-1079-416C-B83F-7F80C9E27A62 at 2021-12-17 17:15:10.553 with Xcode 12B45b on target  {
[MJSONWP] 		SimDevice: iPhone 11 Pro (7310564F-6C3B-47BD-AC4C-3ADC647F55D8, iOS 14.2, Booted)
[MJSONWP] } (14.2 (18B79))
[MJSONWP] 2021-12-17 17:15:10.579 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: (C760AE5F-1079-416C-B83F-7F80C9E27A62) Finished requesting crash reports. Continuing with testing.
[MJSONWP] *** If you believe this error represents a bug, please attach the result bundle at /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult
[MJSONWP] 2021-12-17 17:15:14.683 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: 4.147 elapsed -- Testing started completed.
[MJSONWP] 2021-12-17 17:15:14.684 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[MJSONWP] 2021-12-17 17:15:14.684 xcodebuild[6078:125006] [MT] IDETestOperationsObserverDebug: 4.147 sec, +4.147 sec -- end
[MJSONWP] Test session results, code coverage, and logs:
[MJSONWP] 	/Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult
[MJSONWP] Testing failed:
[MJSONWP] 	Building for iOS Simulator, but the linked and embedded framework 'RoutingHTTPServer.framework' was built for iOS.
[MJSONWP] 	Building for iOS Simulator, but the linked framework 'CocoaAsyncSocket.framework' was built for tvOS + tvOS Simulator.
[MJSONWP] 	Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS.
[MJSONWP] 	Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS.
[MJSONWP] 	Building for iOS Simulator, but the embedded framework 'RoutingHTTPServer.framework' was built for iOS.
[MJSONWP] 	WebDriverAgentRunner:
[MJSONWP] 		WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2021.12.17_17-15-08--0500.xcresult. (Underlying Error: Cannot launch simulated executable: no file found at /Users/zodha-qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app))
[MJSONWP] ** TEST EXECUTE FAILED **
[MJSONWP] Testing started
[MJSONWP]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:501:15)
[HTTP] <-- POST /wd/hub/session 500 272539 ms - 3973
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 2 ms - 57
[HTTP] 

I am getting this error, can someone help me to solve this?

**Comment by mykola-mokhnach** [comment]
@rutushah 

> [MJSONWP] Building for iOS Simulator, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS.

Try to perform `clean project` action on WebDriverAgent sources in xCode. Also, make sure you use the mots recent server version
