### ISSUE TITLE
app cannot be opened because apple cannot check it for malicious software

### ISSUE THREAD

**Issue by rajkumar-cp** [appium/appium#13683]
## The problem

When i try to install application to simulator using appium i'm receiving an error saying  app cannot be opened because apple cannot check it for malicious software

## Environment

Appium version (or git revision) that exhibits the issue: 1.15.1
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: 10.15.1 (mac)
Node.js version (unless using Appium.app|exe): 13.2.0
Npm or Yarn package manager: 6.13.1
Mobile platform/version under test: 13.0
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe: Installed through command line as well as app file was also installed.
![mac issue](https://user-images.githubusercontent.com/39653778/70167158-21009280-16ec-11ea-9fab-36c60437a5a1.png)

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
I cannot understand what the error above has to do with Appium.

**Comment by rajkumar-cp** [comment]
@mykola-mokhnach 

This issue can be closed as this is related to apple.

Note: This was resolved by running the below command in the terminal window

sudo spctl --master-disable

**Comment by omkara120** [comment]
I also have faced the same issue on my simulator after update to MacOS Catalina.

sudo spctl --master-disable : This terminal trick disables important security aspects of Gatekeeper, which leaves your Mac vulnerable to malware. 

So I searched more about this, and It turns out that, if you download app using some browser then it adds a flag which is considered a security threat in Catalina, 

2 Solutions - 
1. You should download the app file by some another way like scp or airdrop 

2 Running Following command : xattr -dr com.apple.quarantine <.app file path>
    it will disable check only for your app file
