### ISSUE TITLE
Impossible to upload files in safari, iOS

### ISSUE THREAD

**Issue by Nikikuzi** [appium/appium#13722]
## The problem

Impossible to upload files to form like this - http://the-internet.herokuapp.com/upload

element.send_keys("path_to_file") returns {ElementNotVisibleException}Message: The object is in an invalid state.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1, 1.16.0-rc.1
* Desktop OS/version used to run Appium: MacOS
* Mobile platform/version under test: iOS 12.4, 13.2
* Real device or emulator/simulator: Simulator

**Comment by mykola-mokhnach** [comment]
Unfortunately such functionality is not supported. Duplicate of https://github.com/appium/appium/issues/13156

**Comment by lorenpan** [comment]
Is there any updated for this problem? If the latest version of appium could support upload files with safari on ios?

**Comment by jlipps** [comment]
As the issue says, the functionality is not supported and there is no plan to support it. The way to automate file upload is to perform the same steps that a user would. There is no "upload" API.

**Comment by valsky4** [comment]
This is not cool, as it is one of the most frequently used commands with browsers. Imagine how much more user-friendly it would be if you could do this with Appium instead of going through the entire process of context switching, all the clicking for a single upload... @jlipps any plans to do it in future or it's still nope.

**Comment by jlipps** [comment]
I can't think of any way it'd even be technically possible to implement this, especially for mobile.
