### ISSUE TITLE
iOS 13.4 - Remote Debugger - 'Target.exists' was not found

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#14098]
## The problem

iOS 13.4-beta web tests are failing. `Target.exists` method is now undefined.

## Environment

* Appium version (or git revision) that exhibits the issue: _master_
* Mobile platform/version under test: _iOS 13.4-beta_ 
* Real device or emulator/simulator: simulator

## Details

The method `Target.exists` in webkit is no longer defined (https://github.com/appium/appium-remote-debugger/blob/master/lib/rpc/remote-messages.js#L432) and it's breaking remote-debugger functionality.

## Link to Appium logs

Azure Logs: https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=8557&view=logs&j=a20989dd-70e3-5e12-518f-c73c69d5e980&t=ed41bafa-6c42-5894-c554-a8426314af02

## Code To Reproduce Issue [ Good To Have ]

See DETAILS section above ^

**Comment by dpgraham** [comment]
Fixed on re-running it.

**Comment by imurchie** [comment]
This is actually a real bug. It only manifests every once in a blue moon, because the promise for that method is resolved as soon as it is sent. So that has to take so long that the response can get back in and the promise gets rejected. Very low chance of it, and it only happens when a protocol changes.

Which is what happened. WebKit removed the `Target.exists` method ([rev](https://trac.webkit.org/browser/webkit/trunk/Source/JavaScriptCore/inspector/protocol/Target.json?rev=251227), [diff](https://trac.webkit.org/changeset?reponame=webkit&new=251227%40trunk%2FSource%2FJavaScriptCore%2Finspector%2Fprotocol%2FTarget.json&old=238192%40trunk%2FSource%2FJavaScriptCore%2Finspector%2Fprotocol%2FTarget.json)), and that change made its way into iOS 13.4.

I will open a PR in a moment to fix this.

**Comment by imurchie** [comment]
This should be fixed with `appium-remote-debugger@8.9.0`
