### ISSUE TITLE
iOS Keyboard not showing when doing click() or send_key on real device

### ISSUE THREAD

**Issue by olubukolaaborode** [appium/appium#14184]
## The problem

I am trying to type into a text field but the textfield wouldn't open when I use click() or send_key()

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.0
* Desktop OS/version used to run Appium: Mac Catalina
* Mobile platform/version under test: iOS / iOS 13.4.1
* Real device or emulator/simulator: iPhone X 

## Details

I got an error when I used click() or send_key("text")
**selenium.common.exceptions.InvalidElementStateException: Message: Error Domain=com.facebook.WebDriverAgent Code=1 "The on-screen keyboard must be present to send keys" UserInfo={NSLocalizedDescription=The on-screen keyboard must be present to send keys}**

**Comment by mykola-mokhnach** [comment]
Is the keyboard opened if the field is tapped manually?

**Comment by olubukolaaborode** [comment]
@mykola-mokhnach yes, it opens when tapped manually

**Comment by mykola-mokhnach** [comment]
It might be you need to wait for a while until the keyboard is visible after tap if the device is too slow. Also make sure the correct element is located/tapped. Otherwise I don't have any good solutions except of reporting the issue to Apple.

In appium@beta there is a possibility to send keys via W3C actions, which could enter a text even if the keyboard is hidden.

**Comment by olubukolaaborode** [comment]
@mykola-mokhnach The W3C actions didn't solve it. Appium isn't clicking the field when the xpath or ID is used. 
So I had to use self.driver.find_element_by_name for it to work.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
