### ISSUE TITLE
Lost connection to DTServiceHub

### ISSUE THREAD

**Issue by Shioriberms** [appium/appium#14358]
## The problem

We have 2 iOS devices of the same version (12.4.1) running on one PC with different appium server ports and wdaLocalPorts. One is sometimes getting the error "Lost connection to DTServiceHub".

## Environment

* Appium version (or git revision) that exhibits the issue: 16.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOs Catalina
* Node.js version (unless using Appium.app|exe): 13.8
* Npm or Yarn package manager: 6.4.2
* Mobile platform/version under test: iOS 12.4.1
* Xcode version: 11.3.1
* Real device or emulator/simulator: Real Device

## Details

To give a background, the test we are performing is on Safari. Unfortunately, the one who wrote the code started the session as a native app and so we have to switch context to Webview to perform some of the actions on the website. 

I'd like to know the possible reasons for getting the error "Lost connection to DTServiceHub". 
The error usually happens towards the end of the test (about 4 mins).

We tried replacing the device that gets the error. However, we still encountered it on the first test run of the new device (see logs). This time during the first parts of the test. The next runs so far are okay after replacing the lightning cable. Could it be a simple cable problem?

## Link to Appium logs
Latest logs:
https://gist.github.com/Shioriberms/4bea73e99e1610b9e5c6f46fb78a74cb

## Code To Reproduce Issue [ Good To Have ]

        DESIRED_CAPS = {}
        DESIRED_CAPS["platformName"] = "iOS"
        DESIRED_CAPS["browserName"] = "Safari"
        DESIRED_CAPS["safariInitialUrl"] = "https://www.google.com"
        DESIRED_CAPS["platformVersion"] = "12.4.1"
        DESIRED_CAPS["udid"] = "xxxxx"
        DESIRED_CAPS["deviceName"] = "xxxxx"
        DESIRED_CAPS["automationName"] = "XCUITest"
        DESIRED_CAPS["wdaLocalPort"] = 8739
        self.driver = webdriver.Remote('http://localhost:4739/wd/hub', DESIRED_CAPS)

**Comment by mykola-mokhnach** [comment]
This error happens somewhere on the lower connection levels, which we cannot control. I would try to upgrade the device and SDK to the most recent version first. Perhaps it is a bug in SDK. Also carefully check the device and xcode logs. They might bring some hints as well.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by AbstractVoid** [comment]
I was getting this issue as well. Turns out it was a memory overload on the device that was crashing the web driver agent, and the web driver agent interpreted it as "losing connection to DTServiceHub". In my case, I had a video recording process also running on the device, which was just too much for the device to handle.

If you're experiencing this issue, it would be good to look into the specs of your device and/or what other processes the device is running on top of the web driver agent. Hope that helps.

**Comment by thethiagosena** [comment]
I was having the “TimeoutError: Timed out waiting for connection to DTServiceHub after 15.0 seconds.” Often. Have searched online for a solution but could find. However, I have done the following and have solved. After that, I have a hypothesis why it happened:

1.	I use OneDrive. I turned it on and waited it to completely sync the files
2.	I had created a new single file, with the initial “Hello, world!”. Don’t change anything! The preview wont work yet.
3.	Run the application like it is ready. Wait the iPhone simulator initialize for complete, and the app shows the “Hello, world!”.
4.	Close the app on simulator
5.	Close the simulator
6.	Close the Xcode
7.	Restart the Mac

It should work!


In my case I was re-thinking what have I done since the last time the Xcode´s Preview was working. Turns out I have tried to run the app simulation on simulator and it was taking too long and I just closed the simulator without it has been completely on. My hypothesis is that, closing it down wrongly maybe had messed up with some Xcode configurations and when I turned on and off correctly this time it has been fixed.

Now I can use my previews normally!

Hope it helps!
