### ISSUE TITLE
iOS simulator(safari): is there ability to use constant name of webview context?

### ISSUE THREAD

**Issue by DudaGod** [appium/appium#14392]
## The problem

For native context we have `NATIVE_APP` but webview context name constantly generated new. I want to reduce the number of requests for webview context name. Is it possible?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.16.0
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 8.6.0
* Npm or Yarn package manager: npm@6.2.0
* Mobile platform/version under test: Safari 13
* Real device or emulator/simulator: iOS simulator
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

https://gist.github.com/DudaGod/584b1ed749cca86df5208639333ade37

**Comment by KazuCocoa** [comment]
No, for now.

Current WebView name is WEBVIEW plus the process id. The process id is necessary to communicate with it over safari web inspector. So, _the process id is different_ means _the WebView is different WebView process from the previous one_.
Appium could handle the webview name as simply `WEBVIEW`, without the process id, but it must be only one WebView case. Appium cannot guarantee the application under test has only one WebView, so the naming logic becomes like below then. It does not make so much sense than current case for me since users should consider only WEBVIEW name case.
- only one WebView by Web Inspector => WebView
- More than one WebView by Web Inspector => WebView plus the process id (current way)

---

If you wanted to change proper WebView with a request, you can try out execute_driver https://appiumpro.com/editions/85-batching-appium-commands-using-execute-driver-script-to-speed-up-tests . As the script, you can put two requests, get webcontext and set it, as a request.

**Comment by DudaGod** [comment]
> Appium could handle the webview name as simply WEBVIEW, without the process id, but it must be only one WebView case.

It suits me, because I open site in mobile safari browser and it has only one webview. But it doesn't work for me =(

My code:
```
const webdriverio = require('webdriverio');

const browser = webdriverio.remote({
    host: 'localhost',
    port: '4444',
    path: '/wd/hub',
    desiredCapabilities: {
        platformName: 'iOS',
        platformVersion: '13.3',
        version: '13.0',
        deviceName: 'iPhone 11',
        browserName: 'safari',
        automationName: 'XCUITest'
    }
});

(async () => {
        await browser.init();
        await browser.url('http://yandex.ru/search/touch?text=лучшие фильмы 2019');

        const contexts = await browser.contexts();
        console.log('contexts:', contexts);

        await browser.context('NATIVE_APP');
        await browser.pause(1000);
        await browser.context('WEBVIEW');

        await browser.end();
    } catch (e) {
        console.log('erorr:', e);
        await browser.end();
    }
})();
```

Appium log - https://gist.github.com/DudaGod/0744ce08a0712a099c626f68219bbdbc.

> If you wanted to change proper WebView with a request, you can try out execute_driver https://appiumpro.com/editions/85-batching-appium-commands-using-execute-driver-script-to-speed-up-tests . As the script, you can put two requests, get webcontext and set it, as a request.

I look at this, thank you.

**Comment by KazuCocoa** [comment]
Sorry, I mean we will be able to potentially add such WEBVIEW naming, but it hasn't in Appium code.

**Comment by DudaGod** [comment]
Sorry, my English is bad, so I didn't understand you correctly =)
Anyway, thank you. I appreciate your help. I close it.
