### ISSUE TITLE
 Original error: JAVA_HOME is not set currently. Please set JAVA_HOME.

### ISSUE THREAD

**Issue by Ad1991** [appium/appium#14408]
Appium
This is my .bash_profile:

export M2_HOME=/usr/local/apache-maven/apache-maven-3.6.0
export M2=$M2_HOME/bin
export PATH=$M2:$PATH
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home
export JDK_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home
export PATH=$PATH:$JAVA_HOME/bin
export PUBLIC_PATH_PREFIX=/p
export PATH=${PATH}:/usr/local/mysql/bin
export ANDROID_HOME=/Users/<username>/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME:$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export NODE_PATH=usr/local/bin/node
export PATH=${PATH}:/usr/local/lib/node_modules/npm/bin

## The problem:
When ever i try to run the program, Im getting this error " Original error: JAVA_HOME is not set currently. Please set JAVA_HOME."

Im running it on MAC for Android Simulator
Can someone please help me on it

**Comment by mykola-mokhnach** [comment]
Have you checked the actual process env like it is described in https://github.com/appium/java-client/blob/master/docs/environment.md ?

**Comment by AlpBilgin** [comment]
As seen in the mention above I am experiencing something similar. My JAVA_HOME is set. But the piece of code that manages apk signing .jars can't use it properly.

Could it be that Java dependency version was bumped up and its not compatible with 8 anymore?

**Comment by mykola-mokhnach** [comment]
What exactly have you tried from that tutorial to resolve the issue?

**Comment by AlpBilgin** [comment]
I still don't know what exactly went wrong, but I fixed it through brute force:

1) Install openJDK to a location that MacOS doesn't know about
2) Force Appium process (in my case a useragent) to use the OpenJDK path instead of the built-in MacOS JDK managers path
3) Reload useragent, restart computer.

My observations:

I guess Java installation of MacOS is flaky.
1.15.1 uses an executable and not a jar to sign apk files. That's why the "possible" flakiness of MacOS java manager didn't make a difference before

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
