### ISSUE TITLE
Appium Monorepo Proposal

### ISSUE THREAD

**Issue by christian-bromann** [appium/appium#14441]
I propose to move Appiums core packages into a single repo to streamline the development of all non driver packages. I reviewed the packages in the Appium GitHub org and identified the following packages to be included:

* appium-remote-debugger
    * Dependencies:
        * appium-base-driver
        * appium-ios-device
        * appium-support
    * DevDependencies
        * appium-ios-simulator
* appium-support
* node-simctl
    * Dependencies:
        * appium-support
        * appium-xcode
* appium-xcode
    * Dependencies:
        * appium-support
* appium-adb
    * Dependencies:
        * appium-support
    * DevDependencies
* appium-ios-simulator
    * Dependencies:
        * appium-support
        * appium-xcode
* appium-base-driver
    * Dependencies:
        * appium-support
* appium-doctor
    * Dependencies:
        * appium-support
        * appium-adb
* appium-idb
    * Dependencies:
        * appium-support
* appium-ios-device
    * Dependencies:
        * appium-support
* eslint-config-appium

## Setup

The setup of the mono repo should be aligned to Lernas best practices. To avoid unnecessary complexity I recommend to not include Appiums gulp plugins and rather use NPM scripts. For example to watch all packages and compile them on file change we could use a [custom script](https://github.com/webdriverio/webdriverio/blob/master/scripts/watch.js) that watches all packages at the same time.

I also recommend to switch from the current test stack (Mocha / sinon) to Jest. It comes with an assertion and mocking library built in and can remove a lot dependencies and helper packages such as `appium-test-support`. It also simplifies tracking the coverage across the whole repository.

## Package Naming Convention

The ability to pin versions of inter dependencies turns out to be very valuable when developing in a mono repo setup. Therefor I recommend to move all packages into an `@appium` namespace, e.g.:

- `appium-remote-debugger` -> `@appium/remote-debugger`
- `node-simctl` -> `@appium/node-simctl`

This allows us to start at v2.0 across all packages and pin them to each other. At the same time it simplifies the transition to Appium 2.0.

## Testing Strategies

I am not much familiar with what is being tested in the packages mentioned above but ideally they should not need a different environment other than Node.js. For example the `appium-adb` package should not need ADB to test its functionality. It is up to the driver to ensure that their commands work on the actual environment they are suppose to control. Given that there will be a lot of tests to be run they need to run fast and should not require any special dependencies to keep it simple to execute for collaborators.

## Transition

Transitioning from the current setup to the desired will be the most challenging part. The advantages of streamlining the development need to be evaluated and compared if it is worth cost of transitioning. I propose that all contributions to the packages mentioned above need to be proposed with 2 separated PRs. One to the original source (e.g. this master branch or subpackage repo master) and one to the new setup source (e.g. this v2.0 branch).

This might ultimately make contributions a bit more difficult given that 2 PRs need to be proposed but it guarantees that the functionality between the packages stays the same. Given the type of patch that is proposed, porting the functionality can be done by the Appium core team and deferred to a later point in time.

**Comment by mykola-mokhnach** [comment]
I would rather split repos by platform. E.g. android-related stuff, ios-related-stuff and the common stuff

**Comment by KazuCocoa** [comment]
I read the above 👍 
I would second for the mykola's suggestion since most case to fix platform issues. A change for Android platform can separate from iOS's one.
So, I imagine something like Appium (support, base-driver), Android(each driver and -adb etx), iOS(remote-debugger, simctl, etc) and other platforms such as macOS, Windows, Youi and tizen etc

**Comment by christian-bromann** [comment]
Please note that all driver continue to stay in their current repositories as they are developed individually. The goal is to streamline the development of the non driver packages which will not be dependant on any special environment other than Node.js.

**Comment by jlipps** [comment]
I think I agree with @mykola-mokhnach and @KazuCocoa that platform-specific ios or android stuff should maybe be isolated to separate monorepos focused on those platforms, or even brought entirely under driver packages. so for example, we only support one ios driver at the moment, so there's not a lot of reason for separate repos for all the ios related stuff. it could all be in a monorepo along with the xcuitest driver.

likewise for android, though we support two android drivers moving forward (uia2 and espresso). but still, they could both be part of one monorepo. in the case of uia2 and espresso, there is so much shared code and logic that it makes sense to have them be in the same repo, since the same people would plausibly work on both.

what do you think about this @christian-bromann?

as far as possible, each driver should just be one repo with the main driver along with any supporting packages.

**Comment by christian-bromann** [comment]
I agree. Based on that I suggest to make the following repositories:

---

### `appium/appium` (this repo)

* appium-support (`@appium/support` on NPM)
* appium-base-driver (`@appium/base-driver` on NPM)
* appium-doctor (`@appium/doctor` on NPM)
* eslint-config-appium (`@eslint-config-appium on NPM)

### `appium/ios`

* appium-remote-debugger (`@appium/remote-debugger` on NPM)
* node-simctl (`node-simctl` on NPM)
* appium-xcode (`@appium/xcode` on NPM)
* appium-ios-simulator (`@appium/ios-simulator` on NPM)
* appium-idb (`@appium/idb` on NPM)
* appium-ios-device (`@appium/ios-device` on NPM)

### `appium/android`

* appium-adb (`@appium/adb` on NPM)

---

It seems like it makes kind of sense to include the drivers into the platform repositories given that we would e.g. only have 1 package in the Android one. Maybe I am missing some packages here? I think the arguments against doing that would be the fact that the build pipelines could become too long. I am not entirely sure what kind of tests are executed in drivers but if there are any e2e tests I wonder if they can be setup in a way that they would only run if certain files are changed.

Some questions remain:
- Do we want to rename `eslint-config-appium`? If not we can't really pin the versions to each other.
- Do we want to rename `node-simctl` to `@appium/node-simctl`? It doesn't seem to me that this package is very Appium specific and it can also be used by non Appium use cases. If not we have the same problem was with `eslint-config-appium`
- Do we want to include drivers into the platform mono repos? If so, what would we do with drivers like [appium-mac-driver](https://github.com/appium/appium-mac-driver)? If not, do we want to start with `appium-adb` being the only Android package or is the some more shared code that we can extract from current drivers?
- Are we ok getting rid of `appium-test-support` and use Jest instead?
- Are we ok getting rid of gulp and `appium-gulp-plugins` and use NPM and JS scripts in the mono repos (see [WebdriverIO example](https://github.com/webdriverio/webdriverio/tree/master/scripts))

**Comment by mykola-mokhnach** [comment]
> Do we want to rename eslint-config-appium? If not we can't really pin the versions to each other.

This module is only used as a transpilation helper. I assume it would be safe to rename it

> Do we want to rename node-simctl to @appium/node-simctl? It doesn't seem to me that this package is very Appium specific and it can also be used by non Appium use cases. If not we have the same problem was with eslint-config-appium

I vote for leaving it as is. In npm I can observe that other modules have dependencies on it. This module, like some others (teen_process, for example) is a part of common shared infrastructure.

> Do we want to include drivers into the platform mono repos? If so, what would we do with drivers like appium-mac-driver? If not, do we want to start with appium-adb being the only Android package or is the some more shared code that we can extract from current drivers?

We should think about how much extendable such architecture would be. Let say we have a platform monorepo with a driver and a third party wants to add another one.

> Are we ok getting rid of appium-test-support and use Jest instead?

I'm not ok with that. mocha is not deprecated and it works as expected for us. Also, I would like to see the transition steps and the main point here - who is going to finalize the changes and support them in the future. It's a huge amount of work. With the current state of things we might end up with the project in a half-done state and broken tests

> Are we ok getting rid of gulp and appium-gulp-plugins and use NPM and JS scripts in the mono repos (see WebdriverIO example)

Same as above. I would avoid touching something that already works properly unless there is a guarantee we have a "stable" maintainer for it.

**Comment by mykola-mokhnach** [comment]
Another task for me - we need to decouple node-simctl from appium-support and appium-xcode. This must be a separate module without unnecessary dependencies

**Comment by jlipps** [comment]
👍 overall to this proposal, makes a lot of sense to me. Specific points:

> Do we want to rename eslint-config-appium? If not we can't really pin the versions to each other.

Pretty sure this is following conventions for eslint packages, but I'm OK renaming it.

> Do we want to rename node-simctl to @appium/node-simctl?

Agree with @mykola-mokhnach that maybe leaving it as is is a good idea for now. It's not intended to be Appium-specific. If we want to change it, I guess we publish a new deprecated version at least pointing people to the renamed one.

> Do we want to include drivers into the platform mono repos? If so, what would we do with drivers like appium-mac-driver? If not, do we want to start with appium-adb being the only Android package or is the some more shared code that we can extract from current drivers?

IMO each driver should be its own repo, since each driver will now be its own independent extension to Appium. I think it makes it easier to manage issues etc in this way. As far as appium-adb being the only Android package, I think that's OK for now. I also think that once we remove the appium-android-driver repo, we will need a place to put a lot of the logic that's shared between the appium android drivers. it might make sense to move that into something like appium-android-base-driver, inside the android monorepo.

> Are we ok getting rid of appium-test-support and use Jest instead?

My feeling is similar to @mykola-mokhnach's on this. There is a ridiculous number of tests that are written and working, and it would be a major project to migrate. If we had a bigger team I would say let's go for it, but right now I'm not sure who would lead this charge and make sure it gets done in a reasonable amount of time.

> Are we ok getting rid of gulp and appium-gulp-plugins and use NPM and JS scripts in the mono repos

There's an awful lot of logic bundled up in appium-gulp-plugins. At a minimum, each package uses the complicated transpilation chain, and some test helpers. It could be that the world has modernized to such an extent that we don't need this complicated chain, and maybe some simple npm scripts with babel and mocha could work. But have a read through the appium-gulp-plugins code to get an idea of everything that we'd need to make sure we have if we move away from it.

**Comment by boneskull** [comment]
FWIW, I will be able to assist in ensuring Mocha meets the needs of Appium.  From what I can tell, switching to Jest is often more work than expected.

**Comment by mykola-mokhnach** [comment]
@jlipps would it be ok to close this feature request as resolved based on the current Appium v2 state?

**Comment by jlipps** [comment]
Yes!
