### ISSUE TITLE
Cannot tap coordinates on macOS and Windows desktop apps

### ISSUE THREAD

**Issue by dariuszteooh** [appium/appium#14525]
## The problem

I am trying to test a Unity app on Windows and macOS. Because the app is rendered in Unity, I cannot use XPath to locate elements - I have to rely on image recognition and that has a side effect of not having WebElements to interact with normally. I cannot just do:
```
WebElement el = driver.findElementBy(image);
el.click();
```

Because locating elements by image is not supported in Windows and Mac drivers. My only option is to rely on coordinates given to me from OpenCV. However, clicking those coordinates fails. Different errors are shown on both platforms. On Mac it is: 
`org.openqa.selenium.UnsupportedCommandException: Could not find selector (post_touch_perform:data:) for path '/session/20OYkTrk/touch/perform'.`
On Windows: 
org.openqa.selenium.WebDriverException: Missing Command Parameter: element

## Environment

* Appium version (or git revision) that exhibits the issue: 1.17.1
* Desktop OS/version used to run Appium: macOS Catalina, Windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

macOS logs: https://gist.github.com/dariuszteooh/e9443ee1c27de1854a68fc52d738d27c
Windows logs: https://gist.github.com/dariuszteooh/7b72a93e156842224f82520ab0bc643d

## Code To Reproduce Issue [ Good To Have ]

```
public void tapCoordinates(int x, int y) {
        PointOption pointOption = new PointOption().withCoordinates(x, y);
        new TouchAction<>(driver).tap(pointOption).perform();
    }
```

**Comment by mykola-mokhnach** [comment]
MacOS server does not implement the `/touch/perform` endpoint, so the error seems to be expected. Though it does implement `/moveto` and `/click` [endpoints](https://github.com/appium/appium-for-mac/blob/6a60be0bdc67a05146dc00696a4855ae7f966526/AppiumForMac/Server/Handlers/AfMHandlers.m#L898), but I've never used this stuff, so cannot suggest much on it. 

Regarding the Windows driver: Here is the list of supported APIs https://github.com/microsoft/WinAppDriver/blob/master/Docs/SupportedAPIs.md

Although, it's very hard to say what works there and what's not for me, since its not open-source.

**Comment by dariuszteooh** [comment]
Thanks @mykola-mokhnach. Is it possible to use the `/click` endpoint on a Mac without an element?

**Comment by mykola-mokhnach** [comment]
Like I said - no idea. Feel free to investigate the source code.
