### ISSUE TITLE
Error with WebDriverAgentRunner and Xcode 11.6

### ISSUE THREAD

**Issue by nikoskyr** [appium/appium#14577]
## The problem

Actually this is not an issue, more a question of how the Webdriveragentrunner works with the Xcode 11.6. To be more specific, I used to run once the following command and then close the terminal session. Everything worked perfectly and I didn't face any issue.
`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<id>' clean build test`

Then I upgraded to the latest Xcode version 11.6 and I faced many problems with the execution (please check the error logs). The only thing that solved the problem was the fact that I didn't close the terminal in one of my attempts to investigate the issue. Thus, I would like to ask you, what is the correct usage of the Webdriveragentrunner app.

## Environment

* Appium version (or git revision) that exhibits the issue: **v1.18.0-beta.1**
* Desktop OS/version used to run Appium: **macOS Catalina** 
* Mobile platform/version under test: **iOS 13.6 and iOS 13.4.1**
* Real device or emulator/simulator: **iPhone XS**
* Appium CLI or Appium.app|exe: **Appium.app**

## Link to Appium logs

https://gist.github.com/nikoskyr/76bb47e5621300dbd4c5c07dc0fe771f

**Comment by mykola-mokhnach** [comment]
> Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor.

Make sure that WDA sources are signed properly and/or your xcconfig file content is valid

**Comment by nikoskyr** [comment]
Yes, I saw this error log as well, but it used to run before I upgrade to Xcode 11.6. Maybe something broke in the process?

**Comment by mykola-mokhnach** [comment]
No idea. Try to build WDA sources from Xcode manually and check what is missing

**Comment by nikoskyr** [comment]
Manually the WDA sources are being built correctly and without any errors. The "problem" lies when I close the terminal after the command "xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<id>' clean build test".

**Comment by amokmen** [comment]
> The "problem" lies when I close the terminal...

I already killed a lot of time to understand this. It's not a problem, it's "by design" behavior from Apple. You/Appium could interact with WDARunner at device only if there is active Xcode/xcodebuild connection/session from macOS. No connection - no answers from WDARunner and even you could not start it manually at device.

To remove this limitation, you must sign WDARunner (as any usual app) with certificate type "iOS Distribution". If WDARunner signed with such certificate, there would be no need to maintain active **testing** session between desktop Xcode/xcodebuild and WDARunner at mobile device.

**Comment by nikoskyr** [comment]
Thanks @amokme, your explanation was very good and solved many questions I had. That's why I mentioned it as a "problem" because I couldn't understand the exact behaviour.
