### ISSUE TITLE
It's slow on iOS 13 when building the tree of springboard at the first time

### ISSUE THREAD

**Issue by aelam** [appium/appium#14751]
## The problem

It's slow on iOS 13 when building the tree of springboard at the first time, usually it takes more than minutes when I call `:8100/source`

I tested on the *latest WDA*

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.15.6
* Node.js version (unless using Appium.app|exe): v10.0.0
* Npm or Yarn package manager: 5.6.0
* Mobile platform/version under test: iOS 13.6
* Real device or emulator/simulator:Real device  iPhone 8 Plus
* Appium CLI or Appium.app|exe:  Appium.app

## Details

1. `iproxy 8100 8100`
2. access localhost:8100/source
3. it will take more than 1 minute to get the result

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and provide the required details

**Comment by aelam** [comment]
@mykola-mokhnach  updated

**Comment by mykola-mokhnach** [comment]
- 1.15.1 is not the latest version
- The server log is missing
- Page generation is done by xctest, we cannot influence this operation much. You could try to exclude some attributes from the resulting XML as possible workaround: https://github.com/appium/appium/issues/13595#issuecomment-554256741

**Comment by aelam** [comment]
@mykola-mokhnach  actually I didn't start Appium, I used the latest WDA project, ran in Xcode 11, and check the :8100/source  interface  in chrome.

**Comment by mykola-mokhnach** [comment]
Then feel fee to skip the first comment. The other two are still relevant.

**Comment by Dan-Maor** [comment]
I remember seeing this happening on my end as well, indeed specifically with iOS 13.

According to the syslog (from what I remember) - testmanagerd attempts to create an automation session against SpringBoard, however SpringBoard fails to respond after 60 seconds, thus testmanagerd gives up and carries on without an automation session and the operation still succeeds.

Last time I remembered seeing it (I don't test against SpringBoard that much) was when I used Xcode 11.3.1, though I didn't play with it that much since, and I wonder whether Apple has since resolved it.

I'm pretty sure that attempting to use a similar functionality through a regular XCUI test (go to SpringBoard, `[XCUIApplication alloc] initWithBundleIdentifier:@"com.apple.springboard"]` and call `debugDescription` on it) will result in the same behavior, though I didn't test it at the time (may be the same as calling `source` with type `description`, might be worth a check).

Given that that what's hanging is a connection between the tested application and testmanagerd (which is part of the developer image) I'm not sure that this is something that can be resolved with an Xcode update, however it _might_ be resolved with a more updated OS.

@aelam - aside from the logs requested by @mykola-mokhnach , which OS version and Xcode version are you using? (last time I checked it I was testing against 13.3).

**Comment by aelam** [comment]
@Dan-Maor    Did you have two xctest bundles on iPhone when you tried `[XCUIApplication alloc] initWithBundleIdentifier:@"com.apple.springboard"]`, Like you have WDA runs on iPhone, then you have this test runnning on iPhone too.   I highly doubt two  xctest bundles could cause this problem

**Comment by Dan-Maor** [comment]
I didn't test the scenario I mentioned, however I'm assuming it will have the same effect. 

What I meant was using an entirely new project, not WDA, without WDA installed, and attempt this scenario.

**Comment by Dan-Maor** [comment]
I've tested the scenario on my device (currently on 13.6) and looks like the issue might have been fixed at some point (I'll need to look around for a 13.3 device to verify). Both a regular XCUI test where the information is pulled from a SpringBoard `XCUIApplication` works, and it looks like testmanagerd is able to get an automation session from SpringBoard as well (can be seen when enabling verbose logging in WDA).

Which exact versions of iOS & Xcode are you using?

**Comment by aelam** [comment]
I tested on iOS 13 and Xcode 11.3.1, my secanrio may be different from you. 
I run two wda with different ids,  then check the duration of source api, it would reproduce somehow. Then kill two,  then it can happen everytime  I'll try yours tomorrow

**Comment by Dan-Maor** [comment]
But which specific 13 version?

**Comment by aelam** [comment]
iOS 13.6 and  iOS 14.
In addition, it seems  if run with xcode 10 the result is fast

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
