### ISSUE TITLE
Incorrect screenshots in iOS / Landscape orientation

### ISSUE THREAD

**Issue by rg-software** [appium/appium#14855]
## The problem

I use the following code to take screenshots of my iOS app:

```
ssBuff = driver.get_screenshot_as_base64()
array = numpy.frombuffer(base64.b64decode(ssBuff), dtype='uint8')
img = cv2.imdecode(array, 1)
cv2.imwrite(f'zz_{counter}.jpg', img, [cv2.IMWRITE_JPEG_QUALITY, 80])

```

It worked perfectly in Appium v1.17.x. After moving to Catalina I had to upgrade Appium to v1.18.3. What happens now is the picture is turned 90 degrees to the left and squeezed as if it is in portrait. In other words, this is what I expect and this is what I see, check the attached picture.

I would really appreciate any help with this issue. Thanks.

![Clipboard01](https://user-images.githubusercontent.com/13718460/97797891-4ed7b980-1c64-11eb-8861-2fb5044e2ec5.png)

**Comment by KazuCocoa** [comment]
Could you share the appium log?
We'd like to know information like Xcode, OS versions etc which affect the auto-detection.
It would also be nice if you know the result of orientation api.

As a quick workaround, you can control the orientation for screenshot by `screenshotOrientation` settings API manually.
https://appium.io/docs/en/advanced-concepts/settings/

**Comment by rg-software** [comment]
Thank you for your reply. Reading `driver.orientation` returns `'LANDSCAPE'`, so this is seemingly fine. Attaching some piece of the log that should have relevant information (but might include more than necessary).
OS: Catalina 10.15.7, Xcode 12.1

[appium.zip](https://github.com/appium/appium/files/5470554/appium.zip)

**Comment by KazuCocoa** [comment]
What the result of `save_screenshot`? I mean do not call `numpy` to save the image.

I tested with landscape mode against iOS 14.2 beta with Xcode 14.2 beta via save_screenshot.
Then, it worked expectedly. (I do not have 14.1 real device for now, so it could potentially iOS 14.1 and Xcode 14.1 issue though.)


iOS returns HEIC format since iOS 12. Appium converts the format to PNG with `UIImagePNGRepresentation` as the result of screenshot commands. https://github.com/appium/WebDriverAgent/pull 
If `numpy` referred some metadata and iOS changed them, it could be an issue, I assume

**Comment by rg-software** [comment]
I tried `driver.save_screenshot('output.jpg')` -- the same result unfortunately.

However, I found what helps:
`driver.update_settings({'screenshotOrientation': 'portrait'})`

Hope it will help to debug the issue!

**Comment by KazuCocoa** [comment]
Thanks.

It seems some combination issues are there, I guess.
We've introduced `screenshotOrientation` setting to care such cases, Appium cannot do auto-detect fully because of some reasons like environment combinations, Xcode versions, OS versions and device models, and real or simulator.

I'll take a look a bit further, but glad to hear `screenshotOrientation` helped your case.

**Comment by KazuCocoa** [comment]
I tried to take screenshots with both orientations with my iPad (14.2) and another iPhone (14.1).
But they worked well, unfortunately. I have no way to debug more with my devices.

https://github.com/appium/WebDriverAgent/blob/ace463a1dd838d646f6cab1aac9b6494cd7917a0/WebDriverAgentLib/Utilities/FBImageUtils.m#L49-L105 is probably relevant code in your case.
It is welcome to dig the cause more on your environment.
