### ISSUE TITLE
app reset when go to background

### ISSUE THREAD

**Issue by inbalvasserman** [appium/appium#14905]
hi,
I'm using python and when perform: driver.background_app(3) the app go to background for few seconds and when it comes back it reset the app instead of continue from where it was.

## Environment
* Appium version: 1.18.3 (also on 1.7.1)
*Appium python client version: 1.0.2
* Desktop OS/version used to run Appium: win10
* Mobile platform/version under test: android 8.1
* Real device:

my capabilities:
            "platformName": "Android",
            "platformVersion": "8.1.0",
            "deviceName": "xxx",
            "automationName": "uiautomator2",
            "applicationName": "xxx",
            "appPackage": xxx,
            "appActivity": xxx,
            "autoGrantPermissions": True,
            "noReset": True,
            "fullReset": False,
            "dontStopAppOnReset": True,
            "newCommandTimeout": 300,
            "clearDeviceLogsOnStart": True,
            "resetOnSessionStartOnly": False

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help nothing without the server logs.
Also, there might be cases where application state is not restored because the instrumentation does not have full information about the activity being restored. In such case the most obvious workaround would be to just simulate clicking the app icon like a normal user would do it.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
