### ISSUE TITLE
driver.get() opening Siri on real iOS device.

### ISSUE THREAD

**Issue by heychirag** [appium/appium#14996]
In reference to https://github.com/appium/appium/issues/14497

I am trying to open a **Deeplink** in an app but Siri is opening up. Is there a workaround for Native apps?

**Comment by KazuCocoa** [comment]
Afaik, _Open Safari -> type the custom scheme/app link in the search field -> enter key_ could be.

Siri was the most stable way to open such custom scheme/app link on iOS in our experience, but the behaviour depended on Siri behaviour. The other way is oepn the scheme/link via Safari browser because Apple does not provide APIs, so we should do like this workaround. (For simulator, Apple provides a CLI to open a link, but it does not work on a real device.)

https://discuss.appium.io/ also might help if other persons find another workaround.
