### ISSUE TITLE
About the problem of getting the layout video app elements  blocking in ios autotesing

### ISSUE THREAD

**Issue by woodywang0** [appium/appium#15092]
mykola-mokhnach comment : Such errors usually happen if the application under test is hogging the main event loop (for example by constantly running continuous animations), so XCTest is unable to do its job. This is XCTest-related issue and we could do nothing on Appium side to workaround it.

I found that it was testing other short video apps : zynn(kuaishou) or instagram ,  the  WebDriverAgent \ wda  and XCTest in using auto testing, it is works .
I don't understand why ,can someone explain reason?

**Comment by mykola-mokhnach** [comment]
I assume because developers of such apps do respect the limitations required by XCTest and the developers of your application application under test don't do that. But this is only an assumption, the real reason could only be found while investigating the app sources and measuring it using Xcode instruments.

Closed as not an issue
