### ISSUE TITLE
Maximum session can start at the same time 

### ISSUE THREAD

**Issue by nhunh585** [appium/appium#15125]
## The problem

As described in this section: https://appium.io/docs/en/advanced-concepts/parallel-tests/ 
We can run multiple sessions at the same time. The question is: how many sessions (for Android, iOS) can start at the same time ?

**Comment by KazuCocoa** [comment]
Theoretically, it's up to your machine resources.
e.g. file descriptors, memory, CPU power

I tested around 10 to 15 devices (mixed emulators/simulators and real devices) long before with ruby_core_lib's test suites on a Macbook Pro. Emulators/simulators could reach memory/CPU high usage easier than only real devices rather than Appium itself.

**Comment by mykola-mokhnach** [comment]
Actually ADB only allows to server up to 15 devices: https://stackoverflow.com/questions/9924274/maximum-number-of-devices-connected-to-an-adb-server

Some tricks/workarounds are required in order to connect more than that.

**Comment by amedvedjev** [comment]
10 android + 10 ios phones on one macMini are OK.
