### ISSUE TITLE
[iOS] runAppInBackground(duration) is not working - org.openqa.selenium.WebDriverException: [...] Original error: timeout of 240000ms exceeded

### ISSUE THREAD

**Issue by aciupi** [appium/appium#15181]
## The problem

When calling `driver.runAppInBackground(Duration duration)` with parameter =! -1, I got an error:

> org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded

The app was successfully going to the background, but after `duration` time instead of activating the app, we got an error. It seems that there is a problem with putting the app to the foreground after `duration`, as calling `runAppInBackground` with parameter -1 is working.

The workaround for that is:

1. Call driver.runAppInBackground with -1, use wait for the required time (extend capability `newCommandTimeout` if needed) and then use `driver.activateApp`
2. Catch exception:
```
try {
        driver.runAppInBackground(duration)
    } catch (e: WebDriverException) {
        if (e.message!!.contains(Regex("An unknown server-side error occurred while processing the command. " +
                "Original error: Could not proxy command to the remote server. Original error: timeout of \\d+ms exceeded"))) {
            mobileDriver.activateApp(bundleId).also {
                logger.warn("iOS issue occurred during running the app in background, trying to activate the app")
            }
        } else {
            throw e
        }
    }
```

## Environment

* Appium version: 1.20.2
* Xcode: 12.4 (12D4e)
* Last Appium version that did not exhibit the issue (if applicable): 1.20.1
* Last Xcode version that did not exhibit the issue: 12.2
* Desktop OS/version used to run Appium: MacOS BigSur 11.1, Catalina 10.15.5
* Node.js version (unless using Appium.app|exe): v15.11.0
* Mobile platform/version under test: iOS 13.5, iOS 14.3
* Appium CLI or Appium.app|exe:

## Link to Appium logs

[GIST](https://gist.github.com/aciupi/a146672cfa0d59774ece5c001bd2c5b0)

## Code To Reproduce Issue [ Good To Have ]

Just call `driver.runAppInBackground(Duration duration)` with parameter different than -1.

**Comment by mykola-mokhnach** [comment]
The timeout issue has been fixed in appium@beta: https://github.com/appium/appium-base-driver/pull/460

In general, it makes sense to not background the app for long (long means more than 60 seconds), because the way Selenium API works. This endpoint blocks until the timeout expires, which means the client does not receive any HTTP response from it and thus may (and will) raise read timeout. The value of this timeout differs for different clients, but for Appium server it is set to 4 minutes. There is also he command timeout, which may kill the server if no command is sent within the given timeout. That is why the most viable strategy for keeping your app in background for longer duration would be:
- Call background app with -1 (this API call returns the response immediately)
- Start the waiting loop on the client side. Send some lightweight request (for example a status one) periodically to the server, so the server knows the client is still talking to it and no timeout happens
- Activate the app after the loop finishes
