### ISSUE TITLE
[driver.url()] Error: Missing parameter: appIdKey

### ISSUE THREAD

**Issue by heychirag** [appium/appium#15325]
## The problem

Unable to get Webview URL.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0-beta.0
* Last Appium version that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Appium: macOS 11.3
* Node.js version (unless using Appium.app|exe): v14.15.5
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: iOS 14.5.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/heychirag/123b888e32754b74307c3b213b55a0d1

## Code To Reproduce Issue [ Good To Have ]

Switch to Webview context and try and get it's URL.

**Comment by anhhanuman** [comment]
get the same issue on iOS 14.5 on the Ionic Cordova App, and I'm not trying to get its URL. Could you suggest a workaround solution @mykola-mokhnach before beta version?

Many thanks

`[debug] [35m[RemoteDebugger][39m Executing atom 'find_element' with 'args=["css selector","app-overview div.search-area mobi-area",null]; frames='
[debug] [35m[RemoteDebugger][39m Executing 'find_element' atom in default context
[debug] [35m[XCUITest][39m Error received while executing atom: Missing parameter: appIdKey
[debug] [35m[W3C (5b71d79b)][39m Encountered internal error running command: Error: Missing parameter: appIdKey
[debug] [35m[W3C (5b71d79b)][39m     at checkParams (/Users/mvanh/Documents/Projects/Automation/node_modules/appium/node_modules/appium-remote-debugger/lib/utils.js:173:11)
[debug] [35m[W3C (5b71d79b)][39m     at RemoteDebuggerRealDevice.execute (/Users/mvanh/Documents/Projects/Automation/node_modules/appium/node_modules/appium-remote-debugger/lib/mixins/execute.js:121:3)
[debug] [35m[W3C (5b71d79b)][39m     at RemoteDebuggerRealDevice.executeAtom (/Users/mvanh/Documents/Projects/Automation/node_modules/appium/node_modules/appium-remote-debugger/lib/mixins/execute.js:27:28)
[debug] [35m[W3C (5b71d79b)][39m     at runMicrotasks (<anonymous>)
[debug] [35m[W3C (5b71d79b)][39m     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[35m[HTTP][39m [37m<-- POST /wd/hub/session/5b71d79b-834b-4f96-80ea-1faaa6cd94db/element [39m[31m500[39m [90m2 ms - 607[39m
[35m[HTTP][39m [90m[39m`

**Comment by mykola-mokhnach** [comment]
There are no workarounds for now. Most likely Apple did some changes to the WebKit protocol and the remote debugger protocol requires some updates. Feel free to create a PR that fixes it.

**Comment by Dan-Maor** [comment]
We found a general issue with iOS 14.5+ during our testing where any attempt to open a remote debugger connection to a webview in a hybrid application that is not a WKWebView causes the target app to crash completely, even when using Apple's Safari Web Inspector. 

Not sure about Cordova since I don't have a test application for it.

@heychirag @anhhanuman can you please try to see whether you can connect to the hybrid section of your applications without it crashing? I have a feeling Apple are to blame here, but just want to make sure.

**Comment by heychirag** [comment]
@Dan-Maor I think switching to Webview context is working, but when it tries to do `AppiumDriver.getUrl()`, the app crashes.

**Comment by Dan-Maor** [comment]
Pretty much the same behavior we saw in our tests.

Can you please check whether using the Safari Web Inspector causes it to crash as well? If that's the case then I don't think there's anything that can be done from Appium's side.

**Comment by anhhanuman** [comment]
I removed most of the Appium capabilities relating to Safari, but the running test script is crashed. I have to run the test script again and it works.

Yes, you're right @Dan-Maor, `Safari Web Inspector causes it to crash` I encountered this crash too, have to open the app and Safari Web Inspector again

I think the community experienced this [issue 13072](https://github.com/appium/appium/issues/13072) before. I'm new to Appium, better to listen to everyone than creating PR. Was this issue relating to this topic @mykola-mokhnach please?

**Comment by anhhanuman** [comment]
I removed most of the Appium capabilities relating to Safari, but the running test script is crashed. I have to run the test script again and it works.

Yes, you're right @Dan-Maor, `Safari Web Inspector causes it to crash` I encountered this crash too, have to open the app and Safari Web Inspector again

I think the community experienced this [issue 13072](https://github.com/appium/appium/issues/13072) before. I'm new to Appium, better to listen to everyone than creating PR. Was this issue relating to this topic @mykola-mokhnach please?

**Comment by haskellpointersauce** [comment]
I have noticed this behavior as well when using `UIWebView`, but I do not see it occurring when I use a `WKWebView`.

I have created an iOS app to reproduce the issue along with a test written against the Java Appium client which can reproduce it. My understanding is that the issue is the remote debugger is crashing when trying to connect to the session for the deprecated view and I wouldn't expect Apple to fix this because `UIWebView` has been deprecated since iOS 12.0.

Here's the reproduction repository: https://github.com/haskellpointersauce/WebViewMenagerie

**Comment by jlipps** [comment]
thanks for the repro @haskellpointersauce! and the info about UIWebView deprecation. somehow I missed that along the way. so the best path for affected users is to ask their developers to update to WKWebView (which Apple has already been suggesting).

**Comment by anhhanuman** [comment]
The ionic team said that they are no longer use the `UIWebView`. They are using the `WKWebView`
But, I run the test script on the new Capacitor app, the script is not broken. On the other hand, the script failed for the ionic app do. Might be the problem from the Ionic 

https://ionicframework.com/docs/v3/wkwebview/

**Comment by jlipps** [comment]
That's funny I just saw a tweet from @mlynch talking about getting all of this stuff working. Not sure if he ran into this issue and resolved it?

**Comment by mlynch** [comment]
@jlipps I haven't run into this yet but I've yet to test on a physical device. Also I'm using Capacitor, not Cordova ([Capacitor](https://capacitorjs.com/) is Ionic's ground-up custom native runtime that replaces Cordova).

Capacitor uses WKWebView and if this is limited to just UIWebView, then it's not really a meaningful issue because Apple blocks apps that use UIWebView so it's pointless to invest time in fixing it imo

**Comment by jlipps** [comment]
Thanks for chiming in @mlynch !

> But, I run the test script on the new Capacitor app, the script is not broken

Looks like this is confirmation for what you are saying as well. I think we have enough evidence here to say that the issue is related to Apple's not supporting UIWebView with any developer tools. It's been known for some time and now we have the first actual slippage due to trying to use the old thing. The recommendation is to move to WKWebView!
