### ISSUE TITLE
Double-quoted include "HTTPResponse.h" in framework header, expected angle-bracketed instead. #15111

### ISSUE THREAD

**Issue by TheStrivingWhite** [appium/appium#15357]
#15111 
1.  downloaded the latest appium
2. downloaded the latest WebDriverAgent
2. Execute the following command
gem install cocopoads,
rm -rf ~/Library/Developer/Xcode/DerivedData/
pod deintegrate
pod update
3.  Pod update indicates that there is no podfile
4. After execution, rerun the project, or the same error
5. There is no webdriver agent in  /Applications/Appium.app/Contents/Resources/app/node_modules
6. How to run it on the mobile phone

**Comment by KazuCocoa** [comment]
> downloaded the latest WebDriverAgent

Do you mean the latest https://github.com/appium/WebDriverAgent? It no longer has carthage, so the title's error should not happen. (The linked #15111 is old one which could happen the title's error) 
If still the issue happens, please update the description with description about your environment, which version of Appium etc (we already addressed necessary data as an issue template)
`pod` command etc also expected result so far since it no longer has carthage.

Your comment confused me since you tried `appium`, Appium Desktop and vanilla Appium/WebDriverAgent.

I assume you wanted to run a test on an iOS device/simulator.
Then, we'd suggest you to take a look at some getting started and Appium forum.

https://appium.io/docs/en/about-appium/getting-started/
https://appium.io/docs/en/drivers/ios-xcuitest/index.html
https://github.com/appium/appium-xcuitest-driver
https://discuss.appium.io/
