### ISSUE TITLE
Implementation UITestingUITests failed appear during the execution of appium webdriveragentrunner 

### ISSUE THREAD

**Issue by wangyuqi7** [appium/appium#15414]
## The problem

Implementation UITestingUITests appear during the execution of appium webdriveragentrunner .

## Environment

Appium version (or git revision) that exhibits the issue:1.20.2
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: 10.15.7
Mobile platform/version under test: Xcode version: 12.1
Real device or emulator/simulator: ios 14.1
Appium CLI or Appium.app|exe:

## Details

![image](https://user-images.githubusercontent.com/70121135/119289089-8055b800-bc7c-11eb-9bd5-150c4d268b46.png)

## Link to Appium logs

 t =      nans Suite Set Up
2021-05-24 10:13:26.888669+0800 WebDriverAgentRunner-Runner[3036:1579473] [User Defaults] Couldn't write values for keys (
    KeyboardAutocorrection
) in CFPrefsPlistSource<0x2802dc580> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2021-05-24 10:13:26.896891+0800 WebDriverAgentRunner-Runner[3036:1579473] [User Defaults] Couldn't write values for keys (
    KeyboardPrediction
) in CFPrefsPlistSource<0x2802dc580> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2021-05-24 10:13:26.897812+0800 WebDriverAgentRunner-Runner[3036:1579473] [User Defaults] Couldn't write values for keys (
    KeyboardShowPredictionBar
) in CFPrefsPlistSource<0x2802dc580> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2021-05-24 10:13:26.899825+0800 WebDriverAgentRunner-Runner[3036:1579473] [User Defaults] Couldn't write values for keys (
    DidShowGestureKeyboardIntroduction
) in CFPrefsPlistSource<0x2802dc580> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Test Case '-[UITestingUITests testRunner]' started.

**Comment by KazuCocoa** [comment]
Could you attach the Appium server log as well to understand the context more?
For example, after what action the WDA stopped.

**Comment by mykola-mokhnach** [comment]
Could you please explain are trying to achieve? I don't observe any issues in the report above

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by KazuCocoa** [comment]
Please try out the latest xcuitest driver since ios 17 would not have a reference to the line for now

**Comment by wenbai1999** [comment]
> Please try out the latest xcuitest driver since ios 17 would not have a reference to the line for now

Thank you KazuCocoa. Please let me know how I should instal the latest xcuitest driver on my mac.

**Comment by KazuCocoa** [comment]
Appium v2 and each drier are independent in Appium v2. You can download the latest xcuitest driver with `appium` command https://appium.io/docs/en/2.2/cli/extensions/
e.g. `appium driver uninstall xcuitest` then `appium driver install xcuitest`

**Comment by wenbai1999** [comment]
To install and upgrade xcuitest driver
I went to https://github.com/appium/appium-xcuitest-driver, cloned it. Then go to .appium directory on my mac
appium driver install xcuitest
appium driver update xcuitest 

Thank you. It works now.

**Comment by wenbai1999** [comment]
Hi Kazuaki,

I encountered this problem https://discuss.appium.io/t/appium-terminates-session-abruptly/35714/3
But after I set
caps.setCapability("commandTimeouts", "600000");

I still get this error in Appium server. This happens when I logout and log back in a page. This doesn’t happen when I first login at this page.

Thank you,

Wen



Matched '/alert/text' to command name 'getAlertText'

***@***.*** (efd33715)] Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/6AA43AE6-6B8A-4E04-8025-A4D6F0956C40/alert/text] with no body

[Xcode] 2023-12-14 11:35:28.205582-0500 WebDriverAgentRunner-Runner[4364:1797741] Getting the most recent active application (out of 1 total items)

[Xcode]

[Xcode]   t = 145607.22s Get all elements bound by index for: Elements matching predicate 'elementType IN {7, 5, 46}'

[Xcode]

[Xcode]   t = 145607.22s   Requesting snapshot of accessibility hierarchy for app with pid 5070

[Xcode]

[Xcode]   t = 145607.26s   Find: Descendants matching type Any

[Xcode]

[Xcode]   t = 145607.26s   Find: Elements matching predicate 'elementType IN {7, 5, 46}'

[Xcode]

***@***.*** (efd33715)] Got response with status 404: {"value":{"error":"no such alert","message":"An attempt was made to operate on a modal dialog when one was not open","traceback":""},"sessionId":"6AA43AE6-6B8A-4E04-8025-A4D6F0956C40"}

[W3C] Matched W3C error code 'no such alert' to NoSuchAlertError

From: Kazuaki Matsuo ***@***.***>
Date: Monday, December 11, 2023 at 1:53 PM
To: appium/appium ***@***.***>
Cc: Wen Bai ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [appium/appium] Implementation UITestingUITests failed appear during the execution of appium webdriveragentrunner (#15414)

Appium v2 and each drier are independent in Appium v2. You can download the latest xcuitest driver with appium command https://appium.io/docs/en/2.2/cli/extensions/<https://urldefense.com/v3/__https:/appium.io/docs/en/2.2/cli/extensions/__;!!Nw6c7o_sdRo!ViX_1YONGDGBVTuT-_UzlAxho90pN9PBDuCYyldwNYXw2CWEJbZU0GDo3kw2xhRALkGhukE_FsRCfrr7ZyGF$>
e.g. appium driver uninstall xcuitest then appium driver install xcuitest
