### ISSUE TITLE
WebDriverAgent runner cannot be activated with activateApp

### ISSUE THREAD

**Issue by nikoskyr** [appium/appium#15576]
## Problem

Hello. I am trying to activate the WebDriverAgent app in iOS with no luck. What I want to do is open it and set something to clipboard and then bring my own app back.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.21**
* Desktop OS/version used to run Appium: **MacOS**
* Mobile platform/version under test: **iOS 14.6**
* Real device or emulator/simulator: **iPhone XS**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

Before the iOS 14.6 I could set something to clipboard, without activating the WebDriverAgent, even thought the documentation advised for the opposite. Now after the upgrade, I followed the instructions to bring the WDA in foreground but a timeout occurs and nothing happens. Also, the same happens if I try to activate another app with the activateApp command, after the first timeout.

## Link to Appium logs

https://gist.github.com/nikoskyr/41063dd279f6ee410b6f25ccf32da140

## Code To Reproduce Issue [ Good To Have ]
`driver().activateApp("com.facebook.WebDriverAgentRunner");`
I also tried to change the WDA bundleId but the same problem happened.

**Comment by mykola-mokhnach** [comment]
You could try to tap WDA icon on the springboard screen as a possible workaround

**Comment by mykola-mokhnach** [comment]
Also I assume the runner bundle is different. For me the freshly compiled package looks like:
<img width="1005" alt="bundle" src="https://user-images.githubusercontent.com/7767781/123421196-d6d84e00-d5bc-11eb-8d98-806ab1602192.png">

**Comment by nikoskyr** [comment]
@mykola-mokhnach Thanks for the prompt response.

As you can see I have the same bundleId as yours
![Screenshot 2021-06-25 at 3 47 46 PM](https://user-images.githubusercontent.com/1266329/123427039-cc25b500-d5cc-11eb-8a02-ffa62f5ce4a0.png)

I will try the aforementioned workaround you proposed, but I think this will be a little bit time consuming in the whole process.

**Comment by KazuCocoa** [comment]
What about adding `.xctrunner` at the end?

**Comment by nikoskyr** [comment]
> What about adding `.xctrunner` at the end?

Unfortunately, I have tried different WDA bundleIds which all had the same result i.e the timeout. 

For example 
com.facebook.WebDriverAgentRunner
com.facebook.WebDriverAgentRunner.xctrunner

I was wondering if someone else had the same problem or it’s just me and my setup

**Comment by KazuCocoa** [comment]
I haven't tried with 14.6, but I have the version's device. Let me try later. (maybe tonight)
Let me put a link https://github.com/appium/WebDriverAgent/issues/330 when I tried the same thing before.
Then, multiple iOS versions had no issue.

**Comment by KazuCocoa** [comment]
I tried with some iOS versions (15, 14.6 and 12.5.4), iPad 15 and Xcode versions (10.3, 12.4 and 13).
Then, probably not sure since, but XCTest framework changed the behavior.
It seems `launch` and `activate` which are the endpoint of XCTest in WDA cannot launch the WDA process itself.
e.g. https://developer.apple.com/documentation/xctest/xcuiapplication/2873317-activate

For instace, in the below line worked very slowly. Once they succeeded, `launch` and `activate` method by XCTest started to re-install WDA apps. The process was stopped. So, it seems 'activate the app process' seems broken or changed the behavior from Apple's documentation.
current master: https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Routing/FBSession.m#L202
A bit old one: https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Routing/FBSession.m#L213
I also tried WDA in 1.17.0.

Anothe thisng. When i called the below `activateAppInfo` command when I manually bring WDA app forward by tapping the app icon, it returned the spring board instead of the WDA bundle id.

```
> @driver.execute_script 'mobile:activeAppInfo'
=> {"processArguments"=>{"env"=>{}, "args"=>[]}, "name"=>"", "pid"=>49, "bundleId"=>"com.apple.springboard"}
```

I installed another WDA as different bundle id. Let assume this another one is WDA B. The former is WDA A.
When I launched an appium session with the WDA A, the A was able to activate the WDA B. But WDA A was not able to activate the WDA A itself.

So, not sure since, but it seems XCTest framework itself behaved differently...
For now, the blow steps are probably solid way.

1. launch spring board: `@driver.activate_app 'com.apple.springboard'`
2. Open WDA: `@driver.find_element :accessibility_id, 'WebDriverAgentRunner-Runner'` and click it

I'll add this way in the documentation

**Comment by nikoskyr** [comment]
@KazuCocoa thanks a lot for the detailed description of the problem. It is now understandable how the "problem" introduced at first place. 

So at the time being the only solution-workaround is to launch the springboard and then open the WDA. 
I think we can close this issue!!

**Comment by KazuCocoa** [comment]
thanks for this report. I didn't think this activate WDA itself did not work via activate api...
