### ISSUE TITLE
Appium does not support Android .aab file format

### ISSUE THREAD

**Issue by Devapal** [appium/appium#15591]
OS: Android

My application is a cordova application . Now that the play store is recommending to upload .aab file instead of .apks, my team started doing that. From the test automation standpoint, I see that Appium does not support .aab ? Is there a way around it to run Appium with .aab instead of .apk ?

**Comment by KazuCocoa** [comment]
I guess you mean giving `.aab` file as `app` capability instead of `.apks` as http://appium.io/docs/en/writing-running-appium/android/android-appbundle/
In my current understanding, we have no way to install `.aab` directly to a device for testing https://developer.android.com/guide/app-bundle/test, so we should prepare `apks` via bundletools as the above. It was part of preparing the test app, so we did not create `apks` itself inside Appium before.

So, we guide users to prepare `apks` from their `aab` properly as a baseline to test the App Bundle so far.

**Comment by mykola-mokhnach** [comment]
Yes, .aab file on their own are not supported by Appium. These must be first transformed to either .apks or .apk format as mentioned in 
https://stackoverflow.com/questions/53040047/generate-apk-file-from-aab-file-android-app-bundle
https://stackoverflow.com/questions/54844007/how-to-generate-full-apk-file-including-dynamic-feature-module/54907000#54907000

One of the most important steps in this transformation is also the package signing step.

The reason for the above is that .aab file itself is only suitable for Play Store upload, but cannot be installed on a device without appropriate preliminary steps.

**Comment by Devapal** [comment]
Thank you. Looks like I might have to extract the .apk and move on with Appium testing.
