### ISSUE TITLE
How to inspect element if app disable screen sharing and screenshot?

### ISSUE THREAD

**Issue by mostafa-raafat** [appium/appium#15865]
Currently when i try to use appium inspector i get loading screen cause some apps tend to use FLAG_SECURE for safety reasons, so that the screen can not be captured or recorded. In such cases I'm not able take Screen dump via UiAutomator viewer. How to see identify the element in such a cases. How to appium automate such apps ?

**Comment by mykola-mokhnach** [comment]
Unfortunately there is no way to workaround that. Earlier (I assume before API version 25) there was a bug in Android that allowed to take instrumentation screenshots even if the above flag is enabled. In newer Android SDKs the bug was fixed by Google and no workarounds are working anymore.
If you still need you tests to take screenshot then either ask app developers to add a backdoor to the app, which disables this flag or use special build flavour for your automated tests without the flag enabled.

**Comment by mostafa-raafat** [comment]
@mykola-mokhnach i don't want to take a screenshot I just want to inspect elements with appium-desktop and currently I'm getting loading screen because appium-inspector depends on screen sharing.

**Comment by mykola-mokhnach** [comment]
I don't see any difference. The screenshot in AD is not created by magic, but uses the same API.
