### ISSUE TITLE
apks file produced with bundletool's --local-testing flag is not installed properly

### ISSUE THREAD

**Issue by rg-software** [appium/appium#15887]
## The problem

An `apks` file produced with `bundletool`'s `--local-testing` flag is not installed properly.

## Environment
* Appium 1.21

## Details

The official way to install an `aab` file with Appium is to transform it into an `apks` archive. If the original `aab` file uses dynamically loaded assets, the `apks` file should be created with `bundletool`'s `--local-testing` flag [as per documentation](https://developer.android.com/studio/command-line/bundletool).

If I understand correctly, Appium _"only installs the minimum set of resources, following the behavior of the appbundle feature"_. In practice it means that additional assets aren't installed and cannot be loaded.

Android docs suggest installing apks by running `bundletool install-apks`, and in this case all necessary files are installed.

Thus, I wanted to:

1) Ask whether there is a simple workaround to install the missing apks;
2) Propose to install `apks` with `bundletool` rathen than with `adb`.

**Comment by mykola-mokhnach** [comment]
At the time we were working on this feature the functionality of bundletool was quite limited. So we had to basically mimic some of its behaviours in order to still provide features we have for vanilla .apk files.
Basically, to support these dynamic resources we just need to push them to a special place, where the system could find them later (e.g. mimic the original bundle tool behaviour): https://github.com/google/bundletool/blob/a7bcb5392a2fc074fd11551b7663643d1dbb0f1d/src/main/java/com/android/tools/build/bundletool/commands/InstallApksCommand.java#L194

Another option would be to use bundletool as is. I assume it's already at the stage, where we have the necessary functionality there that we previously had using vanilla adb commands.

Marking as a feature request for now. Feel free to start working on it @rg-software

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't have any aab which I could use for testing, so here is my "blind" implementation for the feature: https://github.com/appium/appium-adb/pull/578/files

You could use it as a starting point for your implementation and testing.

**Comment by rg-software** [comment]
Thank you, will take a look.

**Comment by rg-software** [comment]
@mykola-mokhnach, I tried your version on three different devices, and I think it works just fine. Thanks again, I don't really see how to improve it further. Thanks again!

**Comment by mykola-mokhnach** [comment]
Cool, thanks for testing it. I'll merge it as soon as it is approved by other maintainers

**Comment by mykola-mokhnach** [comment]
The patch has been merged and published to appium@beta
