### ISSUE TITLE
Is possible to select the module loaded in webview?

### ISSUE THREAD

**Issue by posjkh22** [appium/appium#15911]
## The problem

I use appium for testing the hybrid app.

But I can not take screenshot in webview context with appium inspector.

I think it's because the wrong module is loaded on webview

I can see the two module in webview on chrome inspector.

I want to inspect the **test** (I change the target name for personal information).

But, I think the second target is loaded on webview.

Is any parameter to set the webview target in capability configurations?

![image](https://user-images.githubusercontent.com/25768191/135188583-7bc3d22b-4c16-43a3-992d-16d06d7e8d4f.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): 1.22.0
* Desktop OS/version used to run Appium: Mac/11.3.1
* Node.js version (unless using Appium.app|exe): 14.16.1
* Real device or emulator/simulator: real device

**Comment by KazuCocoa** [comment]
Could you attach the full appium log which has the result of https://appium.io/docs/en/commands/context/get-contexts/ or https://github.com/appium/appium-uiautomator2-driver#mobile-getcontexts ?


I cannot remember when I saw, but if the WebView was a chrome custom tab, you may need to do:

```
driver.set_context('WebView_XXXX')  # change the context to the webview (attach to chrome browser)
driver.window_handles  #=> then, chromedriver returns available tabs/windows in the chrome browser instance
driver.switch_to_window('a window_handle')
```

This is because the chrome browser is a single instance (process). The process has multiple tabs.

**Comment by posjkh22** [comment]
Oh, thanks for your help. it works! I switched the window in webview.
