### ISSUE TITLE
How do you actually use appium-xcuitest-driver?

### ISSUE THREAD

**Issue by krischik** [appium/appium#16203]
## The problem

I have read the documentation for setting up real device config for iOS:

https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

It's starts off with setting up developer ids but I'm at a loss as what the appium-xcuitest-driver is actually good for. Is this an application I need to install, a library I have to add to my add, a what?

The main README isn't much help either:

https://github.com/appium/appium-xcuitest-driver

Could you please start the README by explaining what this „driver“ is actually good for.

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't have experts in writing documentation. Feel free to add the necessary details to the README if you feel these are necessary.

**Comment by krischik** [comment]
Which part of _„I'm at a loss as what the appium-xcuitest-driver is actually good for“_ didn't you understand that you suggest that I write documentation for you?

**Comment by jlipps** [comment]
@krischik the appium xcuitest driver is for use with appium as a platform automation driver. there are various options for appium training and documentation out there that will explain what drivers are and how to use them. (see [this article](https://appiumpro.com/editions/89-understanding-appium-drivers-and-how-to-choose-which-one-to-use) for example). at this moment, this repo's README assumes you know all of that information and is designed to provide different information. as @mykola-mokhnach said, the README could be improved for your case, but that was not the design goal of this README as it was written.

there is a plan with the release of Appium 2.0 to make driver READMEs more comprehensive since they will become more like standalone projects, but for now, that's not the purpose of this README. however, it's open to anyone who has the time and knowledge to add details to this README that might help someone with your context.
