### ISSUE TITLE
Update e2e tests in appium-xcuitest-driver for W3C compatibility

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#16403]
Since the base driver and other dependencies have been bumped for compatibility with Appium2 it is necessary to update driver integration tests at https://github.com/appium/appium-xcuitest-driver/tree/master/test/functional for W3C compatibility. This includes:

- Replace wd usage with webdriverio
- Update all session creation calls to use W3C capabilities format
- Replace all jsonwp calls with W3C alternatives, for example these that should use W3C actions API
- Make the CI run pass

Currently all integration tests are disabled completely and don't work.

**Comment by mwakizaka** [comment]
I'm trying to fix [TouchIDExample.app](https://github.com/appium/appium-xcuitest-driver/tree/master/test/assets/TouchIDExample.app) in some way in order to update https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/basic/touch-id-e2e-specs.js. it may take a while since I'm not familiar with react native.

**Comment by mykola-mokhnach** [comment]
Linking @rerorero

**Comment by rerorero** [comment]
Hi @mwakizaka san ✋  are you working on the rest? I see some tests are still commented out.
https://github.com/appium/appium-xcuitest-driver/tree/master/test/functional/web
Because I've touched the test code recently, I could help you with it so please feel free to tell me. If you're going to handle all the rest, maybe I will look into https://github.com/appium/appium/issues/16402

**Comment by mwakizaka** [comment]
Hi, @rerorero san. Thank you for contacting. 
I saw you've bumped up Xcode version. It's awesome!

> are you working on the rest?

Although I haven't had enough time to addressing the tests, I would like to update them one by one soon. So I appreciate it if you leave them to me. 

> I could help you with it so please feel free to tell me

Thank you for reaching me out! I'll let you know if there's something difficult.

**Comment by rerorero** [comment]
Great, I'm kinda new to Appium and still getting used to the code and I think I have nothing to teach you. I just wanted to see if you're willing to complete the rest of the work 🙂 Thank you for your great work!
