### ISSUE TITLE
element.is_displayed broken in beta?

### ISSUE THREAD

**Issue by tking16** [appium/appium#16503]
Just a heads up, I think there's been an update to the beta version of 1.2.23 in which calling `is_displayed` will fail the test. Now all my tests are failing with 

`AttributeError: type object 'Command' has no attribute 'IS_ELEMENT_DISPLAYED'`

```
self = <appium.webdriver.webelement.WebElement (session="a637a5cd-ef3d-4e52-9062-b3b11f3ec29d", element="68000000-0000-0000-C26B-000000000000")>

    def is_displayed(self) -> bool:
        """Whether the element is visible to a user.

        Override for Appium
        """
>       return self._execute(RemoteCommand.IS_ELEMENT_DISPLAYED)['value']
```

Hope that helps

**Comment by mykola-mokhnach** [comment]
I assume this might be happening because the downstream selenium lib has dropped JWP endpoints. We probably would need to add some workaround for the Appium client as we still use the stuff. @KazuCocoa Are there any more APIs that experience similar issues?

**Comment by KazuCocoa** [comment]
yes, i noticed it in https://github.com/appium/python-client/pull/685 yesterday.
The cause is python selenium client 4.1.0 dropped non-W3C commands.

We need to add them in our appium cleint since we still use them like ruby does https://github.com/appium/python-client/pull/685#issuecomment-1050228318

I'm thinking to push a new python client with selenium 4.0 only as a workaround soon. (hopefully tonight or this weekend)

Then, will add commands that are dropped from 4.1.0 into appium python client.

Current workaround is specify selenium client version as 4.0.x.

**Comment by mykola-mokhnach** [comment]
yeah, that's weird that such a major change has been done after a minor version bump. I did not see any of these items being deprecated earlier 😕

**Comment by KazuCocoa** [comment]
Python client 2.1.3 restricts the selenium version

**Comment by vvelusamy1** [comment]
did anyone tried with 2.1.3 and found it working?

**Comment by zgovedar** [comment]
Sorry but just to be clear, the solution is to upgrade to Appium client 2.1.4 and keep Selenium below 4.1.0?

**Comment by vvelusamy1** [comment]
Just upgrade appium Python client and it will take care of rest.

**Comment by zgovedar** [comment]
Thanks @vvelusamy1
