### ISSUE TITLE
SetPasteboard of WebDriveragent not work on IOS15+

### ISSUE THREAD

**Issue by focalism** [appium/appium#16526]
## The problem

`/wda/setPasteboard ` did not work on IOS15+

## Environment

* WebDriveragent:latest
* Device: iPad mini 2019(IOS15.1), iPad 2021(IOS15.0)

## Details

I found the new feature for Pasteboard on IOS15
![image](https://user-images.githubusercontent.com/10719644/156958713-6bab0c60-cd54-4413-b9d4-61d5d782f54f.png)

**Comment by KazuCocoa** [comment]
What about bringing WDA as foreground in `set clipboard` API call?
Since iOS 13, get clipboard requires it. I quickly checked in my local a real device, then as same, when I activate WDA as foreground, set clipboard worked. https://appium.io/docs/en/commands/device/clipboard/get-clipboard/index.html

It seems like the doc should address the foreground thing for the set clipboard as well.

https://github.com/appium/appium-xcuitest-driver/blob/5675b01cb18b252e5e8d1688bb51844d47d290ea/lib/commands/clipboard.js#L11-L16

This is only for real devices.

**Comment by focalism** [comment]
It's work! Thanks
