### ISSUE TITLE
StaleElementReferenceException occurs when calling getText() on Android toast messages

### ISSUE THREAD

**Issue by autouser88** [appium/appium#16534]
## The problem

Trying to assert the text within a toast message on Android using the WebElement getText() method results in a Stale Element Reference Exception.

## Environment

* Appium version: Appium 2.0.0-beta.25 with UiAutomator2@2.0.3
* Desktop OS used to run Appium: Mac Monterey 12.2.1
* Node.js version (unless using Appium.app|exe): 14.15.4
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android API 30
* Real device or emulator: Nexus 5X emulator
* Appium CLI or Appium.app|exe: CLI

## Details

Calling getText() on a toast element (android.widget.Toast) that has already been found, results in the driver searching the page source again for the element, which has disappeared by the time getText() is called.  The exception isn't actually thrown; it cannot be caught in a try/catch, and the app hangs; however, the exception is mentioned in the appium logs.

## Link to Appium logs

[Appium log](https://gist.github.com/autouser88/198a22fe8292abef66cda470c13e92d2)

**Comment by mykola-mokhnach** [comment]
These toast elements are added "artificially" and only exist in xpath tree for maximum 3 seconds. That's said it is only possible to request them using xPath locators. Calling element methods on them won't work because they don't represent "real" UI elements. Check 

https://github.com/appium/appium-uiautomator2-server/blob/d3cd4a3baa4209d02afcdd2fc0007717890bf138/app/src/main/java/io/appium/uiautomator2/model/NotificationListener.java
https://github.com/appium/appium-uiautomator2-server/blob/fa0b11af387b2935f7ab6e38d53279c3cf3f0f34/app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java#L229
https://github.com/appium/appium-uiautomator2-server/blob/2317e8602eb93f9b43113c0bb06ac340790cd083/app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java#L448

for more details

**Comment by StephanB75** [comment]
I worked around this by doing a getPageSource and parse the xml for the element afterwards.

**Comment by mykola-mokhnach** [comment]
> I worked around this by doing a getPageSource and parse the xml for the element afterwards.

This would work, but I find it redundant to parse the whole xml on the client side. Double check the above links, the necessary text verifications could be done using simple xpath queries.

**Comment by Auto81** [comment]
Have been able to replicate this behaviour whilst trying to get all toast messages within a 30 second window

```
Scenario: Toasting
    Given we wait for '1' seconds
    And we trigger 10 toasts
    Then the following toast messages should display
      | toast          |
      | Toast number 6 |
```

Java code looping for 30 seconds
`getDriver().findElement(By.xpath("//android.widget.Toast")).getText()`

Appium log gist
[https://gist.github.com/Auto81/0b4c2ff34fe03752ec717c9912604ecf](url)

https://user-images.githubusercontent.com/48491431/157420097-e120a783-9594-49ee-aea2-4af1dc8a4ee2.mov

**Comment by jlipps** [comment]
Can you adjust the length of time the toasts stay on the screen (in the app source code, for a test build) so that you have a greater chance of catching it on screen?

**Comment by Auto81** [comment]
Same thing happens when they are set to their max duration. 

Real use case is when 4 or 5 toasts stack, given their time sensitive nature, we just try and capture them all in a given time frame, then assert against the captured texts.

Seems to work reliably on Appium 2.0 when its a new server session and device boot up

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
