### ISSUE TITLE
NPM & Brew espresso driver dependency version does not support Jetpack Compose

### ISSUE THREAD

**Issue by calhamnorthway-pela** [appium/appium#16858]
## The problem

The Appium, NPM & Brew packages are using version 1.45.x of the `appium-espresso-driver` when the jetpack compose functionality isn't supported until version >= 1.46.x

This means that automated testing of Jetpack Compose using the current NPM and Brew packages isn't possible as far as I can tell and requires users to fork, or clone your repo and build locally to use this functionality.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS Monterey 12.2.1
* Node.js version (unless using Appium.app|exe): 18.0.0
* Npm or Yarn package manager: 8.6.0
* Mobile platform/version under test: Android API 32
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Proposed Solution

Re-build and release a new version of Appium on NPM and Brew with updated dependencies so that people can start automated testing on jetpack compose

**Comment by mykola-mokhnach** [comment]
This is the expected behaviour. All officially supported drivers have their major versions bumped, so they are not compatible to EOLed Appium1. Consider switching to [Appium2](https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli), which could be installed via npm as "appium@next". The team is not responsible for packaging it via brew. I suppose you need to contact someone else who maintains that.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
