### ISSUE TITLE
Local instalations do not detect drivers installed in user home directory

### ISSUE THREAD

**Issue by nextlevelbeard** [appium/appium#17085]
1. Delete/uninstall drivers in the user home directory
2. Install global beta.40
3. Install a local beta.40
4. Install drivers with the global Appium
5. Start a local Appium

The global drivers should be loaded by the local installation, they are not.

**Comment by jlipps** [comment]
Can you define "user home directory" and "local Appium" please?

but yeah, I think this may be the expected behavior. If you have a local package.json with Appium installed as a dependency, that is where Appium will look for drivers. The solution is just to include your drivers as NPM dependencies. NPM will manage your drivers and Appium for you. 

It's a completely different use case than letting `appium driver` manage your driver installs, and mixing them is not a good idea.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
