### ISSUE TITLE
INSTRUMENTATION_RESULT: shortMsg=Process crashed

### ISSUE THREAD

**Issue by soloweyDev** [appium/appium#17266]
## The problem
When trying to connect Appium Inspector to the emulator, a crash occurs.
[debug] [35m[Instrumentation][39m INSTRUMENTATION_RESULT: shortMsg=Process crashed.

Settings Appium Inspector:
localhost:4723/wd/hub
Capability:
{
  "platformName": "Android",
  "appium:deviceName": "Galaxy_Nexus_API_23",
  "appium:automationName": "uiautomator2"
}

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Windows 10 Pro (21H2)
* Node.js version (unless using Appium.app|exe): 16.16.0
* Npm or Yarn package manager: -
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator Galaxy_Nexus API_23
* Appium CLI or Appium.app|exe: -

## Details

1. I'm running emulator Galaxy Nexus with API 23. Start app.
2. I'm running Appium Server GUI for Windows. I configure the host - localhost, port - 4723. I press the button "Start Server v1.22.2".
3. I'm running Appium Inspector for Windows. I configure the Remote Host - localhost, Remote Port - 4723, Remote Path - /wd/hub, Desired Capabilities:
{
  "platformName": "Android",
  "appium:deviceName": "Galaxy_Nexus_API_23",
  "appium:automationName": "uiautomator2"
}
I press the button "Start Session".

## Link to Appium logs

[debug] [35m[W3C (36bbd3b1)][39m Responding to client with driver.createSession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","deviceName":"Galaxy_Nexus_API_23","automationName":"uiautomator2","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true},"platformName":"Android","deviceName":"emulator-5554","automationName":"uiautomator2","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true,"deviceUDID":"emulator-5554","deviceApiLevel":23,"platformVersion":"6.0","deviceScreenSize":"720x1280","deviceScreenDensity":320,"deviceModel":"Android SDK built for x86","deviceManufacturer":"unknown","pixelRatio":2,"statBarHeight":48,"viewportRect":{"left":0,"top":48,"width":720,"height":1136}}}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m3514 ms - 988[39m
[info] [35m[HTTP][39m [90m[39m
[debug] [35m[Instrumentation][39m INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [35m[Instrumentation][39m INSTRUMENTATION_CODE: 0

[full log](https://github.com/soloweyDev/Appium/commit/884fe04386e2ec1de7b410f0739807001e3a0409)

**Comment by soloweyDev** [comment]
Tried Appium Server GUI 1.22.3-4 and Appium-Inspector-windows-2022.7.1 - problem reproduced.

**Comment by KazuCocoa** [comment]
Could you share the logcat as well?

**Comment by jlipps** [comment]
the appium server gui has a very old version of the uiauto2 driver embedded. you'll want to try to repro with appium 2 and the latest version of the driver for us to investigate further. and also make sure all appium related packages have been cleared off the device.

**Comment by soloweyDev** [comment]
Where can i download appium 2?
What needs to be cleaned before installing appium 2 and uiauto2?

**Comment by soloweyDev** [comment]
Found a solution to the problem. Components to be removed:
adb uninstall io.appium.uiautomator2.server
adb uninstall io.appium.uiautomator2.server.test
After launch Appium.

**Comment by jyotimanghnani-eaton** [comment]
I am getting this issue. Someone please help me.

The server is running
[Appium] Welcome to Appium v1.22.3
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:automationName":"UIAutomator2","appium:deviceName":"Android Emulator","appium:appPackage":"io.selendroid.testapp","appium:ignoreHiddenApiPolicyError":"true","appium:appActivity":"io.selendroid.testapp.HomeScreenActivity","appium:app":"C:\\Users\\e0677806\\Downloads\\selendroid-test-app.apk","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:automationName":"UIAutomator2","appium:deviceName":"Android Emulator","appium:appPackage":"io.selendroid.testapp","appium:ignoreHiddenApiPolicyError":"true","appium:appActivity":"io.selendroid.testapp.HomeScreenActivity","appium:app":"C:\\Users\\e0677806\\Downloads\\selendroid-test-app.apk","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","appium:automationName":"UIAutomator2","appium:deviceName":"Android Emulator","appium:appPackage":"io.selendroid.testapp","appium:ignoreHiddenApiPolicyError":"true","appium:appActivity":"io.selendroid.testapp.HomeScreenActivity","appium:app":"C:\\Users\\e0677806\\Downloads\\selendroid-test-app.apk","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"Android","appium:automationName":"UIAutomator2","appium:deviceName":"Android Emulator","appium:appPackage":"io.selendroid.testapp","appium:ignoreHiddenApiPolicyError":"true","appium:appActivity":"io.selendroid.testapp.HomeScreenActivity","appium:app":"C:\\Users\\e0677806\\Downloads\\selendroid-test-app.apk","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[BaseDriver] Event 'newSessionRequested' logged at 1678700728816 (15:15:28 GMT+0530 (India Standard Time))
[Appium] Appium v1.22.3 creating new AndroidUiautomator2Driver (v1.70.1) session
[Appium] Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "Android",
[BaseDriver]     "appium:automationName": "UIAutomator2",
[BaseDriver]     "appium:deviceName": "Android Emulator",
[BaseDriver]     "appium:appPackage": "io.selendroid.testapp",
[BaseDriver]     "appium:ignoreHiddenApiPolicyError": "true",
[BaseDriver]     "appium:appActivity": "io.selendroid.testapp.HomeScreenActivity",
[BaseDriver]     "appium:app": "C:\\Users\\e0677806\\Downloads\\selendroid-test-app.apk",
[BaseDriver]     "appium:ensureWebviewsHavePages": true,
[BaseDriver]     "appium:nativeWebScreenshot": true,
[BaseDriver]     "appium:newCommandTimeout": 3600,
[BaseDriver]     "appium:connectHardwareKeyboard": true
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] Capability 'ignoreHiddenApiPolicyError' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   connectHardwareKeyboard
[BaseDriver] Session created with session id: bd3cbec5-6632-4561-8c99-3c1ac4e80637
[BaseDriver] Using local app 'C:\Users\e0677806\Downloads\selendroid-test-app.apk'
[UiAutomator2] Checking whether app is actually present
[ADB] Found 2 'build-tools' folders under 'C:\Users\e0677806\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/e0677806/AppData/Local/Android/Sdk/build-tools/32.1.0-rc1
[ADB]     C:/Users/e0677806/AppData/Local/Android/Sdk/build-tools/32.0.0
[ADB] Using 'adb.exe' from 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices
[ADB] Connected devices: [{"udid":"emulator-5554","state":"device"}]
[AndroidDriver] Using device: emulator-5554
[ADB] Using 'adb.exe' from 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[ADB] Setting device id to emulator-5554
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 30
[ADB] Getting device platform version
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 11
[ADB] Device API level: 30
[UiAutomator2] Relaxing hidden api policy
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 wait-for-device'
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell echo ping'
[AndroidDriver] Pushing settings apk to device...
[ADB] Getting install status for io.appium.settings
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] 'io.appium.settings' is installed
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.settings'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.4.0' >= '3.4.0')
[ADB] There is no need to install/upgrade 'C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Getting IDs of all 'io.appium.settings' processes
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'pgrep --help; echo $?''
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'
[AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[Logcat] Starting logs capture with command: C:\\Users\\e0677806\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 logcat -v threadtime
[UiAutomator2] Forwarding UiAutomator2 Server port 6790 to local port 8200
[ADB] Forwarding system: 8200 to device: 6790
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward tcp:8200 tcp:6790'
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[ADB] 'io.appium.uiautomator2.server' is installed
[ADB] Getting package info for 'io.appium.uiautomator2.server'
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
[ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('4.27.0' >= '4.27.0')
[UiAutomator2] io.appium.uiautomator2.server installation state: sameVersionInstalled
[ADB] Checking app cert for C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk
[ADB] Using 'apksigner.jar' from 'C:\Users\e0677806\AppData\Local\Android\Sdk\build-tools\32.1.0-rc1\lib\apksigner.jar'
[ADB] Starting apksigner: 'C:\\Program Files (x86)\\Java\\jdk1.8.0_231\\bin\\java.exe' -Xmx1024M -Xss1m -jar C:\\Users\\e0677806\\AppData\\Local\\Android\\Sdk\\build-tools\\32.1.0-rc1\\lib\\apksigner.jar verify --print-certs C:\\Users\\e0677806\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.27.0.apk
[ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB] 
[ADB] sha256 hash did match for 'appium-uiautomator2-server-v4.27.0.apk'
[ADB] 'C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk' is signed with the default certificate
[ADB] Getting install status for io.appium.uiautomator2.server.test
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server.test'
[ADB] 'io.appium.uiautomator2.server.test' is installed
[ADB] Checking app cert for C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[ADB] Starting apksigner: 'C:\\Program Files (x86)\\Java\\jdk1.8.0_231\\bin\\java.exe' -Xmx1024M -Xss1m -jar C:\\Users\\e0677806\\AppData\\Local\\Android\\Sdk\\build-tools\\32.1.0-rc1\\lib\\apksigner.jar verify --print-certs C:\\Users\\e0677806\\AppData\\Local\\Programs\\Appium\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk
[ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB] 
[ADB] sha256 hash did match for 'appium-uiautomator2-server-debug-androidTest.apk'
[ADB] 'C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is signed with the default certificate
[UiAutomator2] Server packages are not going to be (re)installed
[UiAutomator2] Waiting up to 30000ms for services to be available
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm list instrumentation'
[UiAutomator2] Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[ADB] Adding packages ["io.appium.settings","io.appium.uiautomator2.server","io.appium.uiautomator2.server.test"] to Doze whitelist
[ADB] Got the following command chunks to execute: [["dumpsys","deviceidle","whitelist","+io.appium.settings",";","dumpsys","deviceidle","whitelist","+io.appium.uiautomator2.server",";","dumpsys","deviceidle","whitelist","+io.appium.uiautomator2.server.test",";"]]
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys deviceidle whitelist +io.appium.settings ; dumpsys deviceidle whitelist +io.appium.uiautomator2.server ; dumpsys deviceidle whitelist +io.appium.uiautomator2.server.test ;'
[ADB] Checking app cert for C:\Users\e0677806\Downloads\selendroid-test-app.apk
[ADB] Starting apksigner: 'C:\\Program Files (x86)\\Java\\jdk1.8.0_231\\bin\\java.exe' -Xmx1024M -Xss1m -jar C:\\Users\\e0677806\\AppData\\Local\\Android\\Sdk\\build-tools\\32.1.0-rc1\\lib\\apksigner.jar verify --print-certs C:\\Users\\e0677806\\Downloads\\selendroid-test-app.apk
[ADB] apksigner stdout: Signer #1 certificate DN: CN=Android Debug, O=Android, C=US
[ADB] Signer #1 certificate SHA-256 digest: f68117581679cdfaf3532a1c374547745a1889d266b3de8d3dc9014632599f33
[ADB] Signer #1 certificate SHA-1 digest: 4fdac9c8157aa966b9a79f11d31cda5be49fd44b
[ADB] Signer #1 certificate MD5 digest: 671d07ab3338c01c67994b9edb18362c
[ADB] 
[ADB] 'C:\Users\e0677806\Downloads\selendroid-test-app.apk' is signed with a non-default certificate
[ADB] Getting install status for io.selendroid.testapp
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.selendroid.testapp'
[ADB] 'io.selendroid.testapp' is installed
[ADB] Getting package info for 'io.selendroid.testapp'
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.selendroid.testapp'
[ADB] The version name of the installed 'io.selendroid.testapp' is greater or equal to the application version name ('0.12.0' >= '0.12.0')
[ADB] There is no need to install/upgrade 'C:\Users\e0677806\Downloads\selendroid-test-app.apk'
[AndroidDriver] Performing fast reset on 'io.selendroid.testapp'
[ADB] Getting install status for io.selendroid.testapp
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys package io.selendroid.testapp'
[ADB] 'io.selendroid.testapp' is installed
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.selendroid.testapp'
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell pm clear io.selendroid.testapp'
[AndroidDriver] Performed fast reset on the installed 'io.selendroid.testapp' application (stop and clear)
[UiAutomator2] Performing shallow cleanup of automation leftovers
[UiAutomator2] No obsolete sessions have been detected
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.appium.uiautomator2.server.test'
[UiAutomator2] Starting UIAutomator2 server 4.27.0
[UiAutomator2] Using UIAutomator2 server from 'C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.27.0.apk' and test from 'C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body
[WD Proxy] Got response with status 200: {"sessionId":"None","value":{"message":"UiAutomator2 Server is ready to accept commands","ready":true}}
[UiAutomator2] The initialization of the instrumentation process took 70ms
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8200/wd/hub/session] with body: {"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","automationName":"UIAutomator2","deviceName":"Android Emulator","appPackage":"io.selendroid.testapp","ignoreHiddenApiPolicyError":true,"appActivity":"io.selendroid.testapp.HomeScreenActivity","app":"C:\\Users\\e0677806\\Downloads\\selendroid-test-app.apk","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true},"platformName":"Android","automationName":"UIAutomator2","deviceName":"emulator-5554","appPackage":"io.selendroid.testapp","ignoreHiddenApiPolicyError":true,"appActivity":"io.selendroid.testapp.HomeScreenActivity","app":"C:\\Users\\e0677806\\Downloads\\selendroid-test-app.apk","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":t...
[WD Proxy] Got response with status 200: {"sessionId":"c13a673b-74a8-4cb3-b183-5a426edba102","value":{"capabilities":{"firstMatch":[{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","automationName":"UIAutomator2","deviceName":"Android Emulator","appPackage":"io.selendroid.testapp","ignoreHiddenApiPolicyError":true,"appActivity":"io.selendroid.testapp.HomeScreenActivity","app":"C:\\Users\\e0677806\\Downloads\\selendroid-test-app.apk","ensureWebviewsHavePages":true,"nativeWebScreenshot":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true},"platformName":"Android","automationName":"UIAutomator2","deviceName":"emulator-5554","appPackage":"io.selendroid.testapp","ignoreHiddenApiPolicyError":true,"appActivity":"io.selendroid.testapp.HomeScreenActivity","app":"C:\\Users\\e0677806\\Downloads\\selendroid-test-app.apk","ensureWebviewsHavePages":true,"nativeWebScreensho...
[WD Proxy] Determined the downstream protocol as 'W3C'
[WD Proxy] Proxying [GET /appium/device/info] to [GET http://127.0.0.1:8200/wd/hub/session/c13a673b-74a8-4cb3-b183-5a426edba102/appium/device/info] with no body
[WD Proxy] Got response with status 200: {"sessionId":"c13a673b-74a8-4cb3-b183-5a426edba102","value":{"androidId":"15b76eb8d38a23e3","apiVersion":"30","bluetooth":{"state":"ON"},"brand":"Android","carrierName":"Android","displayDensity":440,"locale":"en_US","manufacturer":"unknown","model":"Android SDK built for x86","networks":[{"capabilities":{"SSID":null,"linkDownBandwidthKbps":141000,"linkUpstreamBandwidthKbps":141000,"networkCapabilities":"NET_CAPABILITY_NOT_METERED,NET_CAPABILITY_INTERNET,NET_CAPABILITY_NOT_RESTRICTED,NET_CAPABILITY_TRUSTED,NET_CAPABILITY_NOT_VPN,NET_CAPABILITY_VALIDATED,NET_CAPABILITY_NOT_ROAMING,NET_CAPABILITY_FOREGROUND,NET_CAPABILITY_NOT_CONGESTED,NET_CAPABILITY_NOT_SUSPENDED","signalStrength":-30,"transportTypes":"TRANSPORT_WIFI"},"detailedState":"CONNECTED","extraInfo":"","isAvailable":true,"isConnected":true,"isFailover":false,"isRoaming":false,"state":"CONNECTED","subtype":0,"subtypeName":"","type":1,"typeName":"WIFI"},{"capabilities":{"SSID":null,"linkDownBandwidthKbps":30000,"linkUpstreamBandwidthKbps":15000,"netw...
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[UiAutomator2] Starting 'io.selendroid.testapp/io.selendroid.testapp.HomeScreenActivity and waiting for 'io.selendroid.testapp/io.selendroid.testapp.HomeScreenActivity'
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am start -W -n io.selendroid.testapp/io.selendroid.testapp.HomeScreenActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[Instrumentation] INSTRUMENTATION_CODE: 0
[Instrumentation] The process has exited with code 0
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'DELETE /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop io.selendroid.testapp'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[ADB] Running 'C:\Users\e0677806\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[BaseDriver] Event 'newSessionStarted' logged at 1678700746722 (15:15:46 GMT+0530 (India Standard Time))
[W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /appium/device/pixel_ratio' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[W3C]     at UIA2Proxy.command (C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:274:13)
[W3C]     at AndroidUiautomator2Driver.commands.getDevicePixelRatio (C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\commands\viewport.js:14:10)
[W3C]     at AndroidUiautomator2Driver.fillDeviceDetails (C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:244:28)
[W3C]     at AndroidUiautomator2Driver.createSession (C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:230:7)
[W3C]     at AppiumDriver.createSession (C:\Users\e0677806\AppData\Local\Programs\Appium\resources\app\node_modules\appium\lib\appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 18026 ms - 1652
[HTTP]

**Comment by idiachenko** [comment]
> Found a solution to the problem. Components to be removed: adb uninstall io.appium.uiautomator2.server adb uninstall io.appium.uiautomator2.server.test After launch Appium.


GOD BLESS YOU!
