### ISSUE TITLE
Unable to click on media control buttons iPhone Safari browser

### ISSUE THREAD

**Issue by gourabsahacognizant** [appium/appium#17265]
## The problem

We are automation responsive scenarios where we are required to click on media control buttons like play button, mute button, CC button, etc on a video page. We are using appium with iOSDriver of webelement type and using click method it is not able to click on those buttons. We tried on real devices and also on saucelab provided real devices. We also tried javascript click and other javascript methods but none worked. We also tried nativeWebTap capabilities.

[AppiumLog.txt](https://github.com/appium/appium/files/9180537/AppiumLog.txt)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.19/1.22
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: macOS Big Sur 11.6.2
* Node.js version (unless using Appium.app|exe): NA
* Npm or Yarn package manager: NA
* Mobile platform/version under test: any ios version above 12
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: NA

**Comment by mykola-mokhnach** [comment]
I don't observe any issues in the attached logs.

- Make sure you use the most recent Appium server version.
- Try to perform native click by coordinates 
- Make sure the device is idling. An active video stream might block xctest from interacting with the UI.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by gourabsahacognizant** [comment]
Even with latest appium driver and server same issue is faced. Also click by coordinates is working but we can't run the script on multiple devices as for different device the coordinates will vary.

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help much there. It could be that the vanilla web context click does not for your web app since it just a simple javascript snippet (selenium atom). And then it is either necessary to customize it manually or perform a click from native context. And the latter would require manual coordinates recalculation as the coordinates net in webview mode does not match the one in native mode. Read https://appiumpro.com/editions/36-using-the-nativewebtap-capability for more details.
