### ISSUE TITLE
Get Logs for appium-xcuitest-driver returns an empty array

### ISSUE THREAD

**Issue by tai2** [appium/appium#17346]
## The problem

[The Get Logs API](http://appium.io/docs/en/commands/session/logs/get-log/) returns an empty array even after an AUT crashes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): Not sure
* Desktop OS/version used to run Appium: macOS 12.4
* Node.js version (unless using Appium.app|exe): 16.14.2
* Npm or Yarn package manager: Yarn
* Mobile platform/version under test: iOS 14.4
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

https://github.com/appium/appium-xcuitest-driver/blob/fe46c0778eaf46a0421420086dede125292a19c2/lib/device-log/ios-crash-log.js#L54-L56

The XCUITest driver seems to glob crash log files with the `*.crash` pattern but there are only files that have the `.ips` extension under the `~/Library/Logs/DiagnosticReports/` directory in my environment. I can see crash logs in these `.ips` files.

I guess this is related to this issue.

## Link to Appium logs

https://gist.github.com/tai2/ef54b3ddeb271628fcff8323a4b89a8f

## Code To Reproduce Issue [ Good To Have ]

I cannot provide.

**Comment by mykola-mokhnach** [comment]
Please try the most recent driver version, which is only available as part of Appium2. Also, make sure the https://github.com/YueChen-C/py-ios-device tool is installed

**Comment by rerorero** [comment]
@mykola-mokhnach  This problem seems to happen only in simulator. I checked with the latest Appium2 and appium-xcuitest-driver and I can get the crash log without any problem on the real device, but not on the emulator. As @tai2 mentioned, I think the reason is that the driver doesn't read ips files. According to [this post](https://github.com/appium/appium-xcuitest-driver/pull/1431) Monterey changed the crash log format from .crash to .ips.

I have confirmed that[ this change](https://github.com/appium/appium-xcuitest-driver/pull/1431) fixes the emulator to get crash logs as well as the real device. Can you take a look at [this PR](https://github.com/appium/appium-xcuitest-driver/pull/1431) ?
