### ISSUE TITLE
Appium Docker container on hub.docker.com contains Log4J vulernability

### ISSUE THREAD

**Issue by lordfolken** [appium/appium#17378]
According to Aqua Security's image Scanner, the latest image on hub.docker.com/r/appium/appium:latest
contains the log4j vulnerability. 

Also the container is 4 months old, and there are a total of 417 vulnerabilities of which 189 are patchable. 

Please establish a procedure to update the container more frequently.

**Comment by mykola-mokhnach** [comment]
I did not even know there is a docker image somewhere that is maintained by Appium team 😕

**Comment by saikrishna321** [comment]
https://github.com/appium/appium-docker-android

**Comment by lordfolken** [comment]
https://hub.docker.com/u/appium so isn't this organization, but an imposter?

**Comment by lordfolken** [comment]
@budtmo is this your user? https://hub.docker.com/u/budtmorobot

**Comment by budtmo** [comment]
Hi @lordfolken , 

thank you for raising the issue. yes, it is my robot user to automate the build and the push because I dont want to use my personal account for that.
the docker images from hub.docker.com/r/appium/appium:latest is built by this project https://github.com/appium/appium-docker-android. 
I do not aware about that log4j vulnerability inside our docker image. Could you point out which part of the component has that vulnerability or maybe you can share the report with us here?

**Comment by budtmo** [comment]
I just release the new version -> [v1.22.3-p1](https://github.com/appium/appium-docker-android/releases/tag/v1.22.3-p1)

I just checked that version as well, that docker image has in total:
- 54 low vulnerabilities where 17 from official ubuntu base image (the rest come from openjdk, unzip, nodejs etc)
- 31 medium vulnerabilities where 4 from official ubuntu base image (the rest come from openjdk, unzip, nodejs etc)
- 0 high vulnerability
- 0 critical vulnerability

![appium-docker-android-vulnerabilities01](https://user-images.githubusercontent.com/22218312/185618915-e750318a-8ac9-4958-b050-d79fa98fd0a1.png)
![appium-docker-android-vulnerabilities02](https://user-images.githubusercontent.com/22218312/185618917-2b127e4b-b6db-48f5-9323-1fc955fba68d.png)

the log4J vulnerability should be gone.

Could you check @lordfolken ?

I will close the ticket, but feel free to reopen it again.
