### ISSUE TITLE
replace rimraf in @appium/support with fs.rm

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17494]
**Caveat**: If we're using `rimraf` (_not_ `npx rimraf`) somewhere in scripts, we should keep the dependency; otherwise, we can drop it.

In `@appium/support`'s `fs` module, we have `rimraf()` and `rimrafSync()` which use the `rimraf` module.  This can be replaced by Node.js' built-in `fs.rm()`/`fs.rmSync()` now that we have dropped support for Node.js v12.

**Comment by mykola-mokhnach** [comment]
I don't think this is going to work as https://nodejs.org/api/fs.html#fspromisesrmpath-options was only added in Node 14.14.0 and we support 14+

**Comment by boneskull** [comment]
I'm not sure we've been clear about whether or not supporting a major means supporting only the latest minor?  This is what we test on, fwiw--we have no checks against Node.js v14.0.0

**Comment by mykola-mokhnach** [comment]
I remember we had similar issues already in older node.js versions and It was super hard to track down. Users don't update their node.js minor versions frequently and they don't have to as we only require v >=14 in the manifest

**Comment by boneskull** [comment]
@jlipps what's yr opinion on this? given we don't test every single minor version of supported Node majors, I'm unsure we can really claim compatibility with anything but the latest of each. 

supporting only the latest release of a particular set of LTS lines is fairly common in the ecosystem; nobody runs CI  across minors. that said, given what @mykola-mokhnach wrote, this would technically be a breaking change.

**Comment by jlipps** [comment]
yeah i don't know. maybe it's too nuanced but we could support only latest minor of the LTS once it goes into maintenance mode?

**Comment by boneskull** [comment]
That sounds fine to me, as it would exclude < v14.14.0.  I'll post on the discussion forum about it and see if it would be trouble.

**Comment by mykola-mokhnach** [comment]
> yeah i don't know. maybe it's too nuanced but we could support only latest minor of the LTS once it goes into maintenance mode?

There should be some way to verify the minimum node minor version in the executable or at least on npm level. Currently there is no such possibility. Just mentioning that fact in the documentation is not very helpful as only a small part of users read it.
I would rather wait until node14 gets obsolete/unsupported and only then add the feature.

**Comment by Chaitya62** [comment]
found an interesting [read]( https://boneskull.com/recursive-directory-removal-in-node-js/) on `rimraf` vs `fs.rm` while trying to figure out the patch for this issue, adding here for reference. I figured just need to change [1](https://github.com/appium/appium/blob/4f564ef7ad350831b90994ffd4e8b00de227577d/packages/support/lib/fs.js#L90) and [2](https://github.com/appium/appium/blob/4f564ef7ad350831b90994ffd4e8b00de227577d/packages/support/lib/fs.js#L97), though testing out if we need to default the `recursive` option to true inside `fs.rm` since `rimraf` deletes the directory irrespective of any options passed on the other hand `fs.rm` doesn't if recursive is set to false.

**Comment by Chaitya62** [comment]
@jlipps @boneskull safe to close this issue?

**Comment by jlipps** [comment]
yep, thanks!
