### ISSUE TITLE
bug: Appium fails to install WDA on apple tv 4k.

### ISSUE THREAD

**Issue by rushi04** [appium/appium#17896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium session fails on apple tv 4k due to WDA installation failure. 

Error - [`debug] [AppiumDriver@4d47] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70`

Failed due to `[debug] [AppiumDriver@4d47] xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[debug] [AppiumDriver@4d47] 		{ id:630248c017358eb7f998a44157cf91d9be116eeb }`

But in available devices we can see that the device is available. 
`[debug] [AppiumDriver@4d47] 	Available destinations for the "WebDriverAgentRunner_tvOS" scheme:
[debug] [AppiumDriver@4d47] 		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Any tvOS Device }
[debug] [AppiumDriver@4d47] 		{ platform:tvOS, id:630248c017358eb7f998a44157cf91d9be116eeb, name:Living Room }
[debug] [AppiumDriver@4d47] 		{ platform:tvOS Simulator, id:82049AD9-58D6-4FA0-ABD1-18BD32C93A6A, OS:16.0, name:Apple TV 4K (2nd generation) }`

### Expected Behavior

Appium should be able to install wda on apple tv 4k.

### Minimal Reproducible Example

Start appium session with the following caps  - 
desired_cap = {
    "automationName": "XCUITest",
    "platformName": "tvOS",
    "platformVersion": "16.0",
    "deviceName": "[device name]",
    "appium:bundleId": "[bundle id]",
    "udid":"[udid]",
    "appium:useNewWDA": True,
    "showXcodeLog": True
}

### Environment

- Appium Version: v2.0.0-beta.35
- xcuitest driver: xcuitest@4.12.2
- Device: Apple Tv 4k 2nd gen 16.0
- Real device or emulator/simulator: Real device

### Link to Appium Logs

https://gist.github.com/rushi04/1701e8d0ae3ca0f9637a1bc0aa19cd0a

**Comment by mykola-mokhnach** [comment]
Could you please try to run the above command `xcodebuild build-for-testing test-without-building -project /Users/admin/bs/appium-njb/packages/appium/xcuitest/4.12.2/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -derivedDataPath /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-bgsfvygvpivglxfrhxpoatbulkqe -destination id=630248c017358eb7f998a44157cf91d9be116eeb IPHONEOS_DEPLOYMENT_TARGET=16.0 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Users/admin/bs/appium-njb/packages/appium/xcuitest/4.12.2/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent`

in terminal, but replace `IPHONEOS_DEPLOYMENT_TARGET` with `TVOS_DEPLOYMENT_TARGET `?

**Comment by KazuCocoa** [comment]
Perhaps the xcodebuild could not find the device?
```
[debug] [iProxy@630248c0:8100] Unexpected data: {"header":{"length":294,"version":1,"type":8,"tag":1},"payload":{"MessageType":"Result","Number":2}}
[XCUITestDriver@4090 (56576834)] socket hang up
[Xcode] xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[Xcode] 		{ id:630248c017358eb7f998a44157cf91d9be116eeb }
[Xcode]
[Xcode] 	The requested device could not be found because no available devices matched the request.
[Xcode]
[Xcode] 	Available destinations for the "WebDriverAgentRunner_tvOS" scheme:
[Xcode] 		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Any tvOS Device }
[Xcode] 		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Any tvOS Simulator Device }
[Xcode] 		{ platform:tvOS, id:630248c017358eb7f998a44157cf91d9be116eeb, name:Living Room }
[Xcode] 		{ platform:tvOS Simulator, id:71460EEB-9BFE-4D62-9C74-8FBE507D7F0F, OS:16.0, name:Apple TV }
[Xcode] 		{ platform:tvOS Simulator, id:82049AD9-58D6-4FA0-ABD1-18BD32C93A6A, OS:16.0, name:Apple TV 4K (2nd generation) }
[Xcode] 		{ platform:tvOS Simulator, id:FD811341-6929-49AF-B29C-D2D5728DA887, OS:16.0, name:Apple TV 4K (at 1080p) (2nd generation) }
[Xcode]
[Xcode] xcodebuild exited with code '70' and signal 'null'
```

I guess https://github.com/appium/appium/issues/17750 is the same or similar one

**Comment by rushi04** [comment]
> Perhaps the xcodebuild could not find the device?
yes, but its shown in available devices list.

> I guess https://github.com/appium/appium/issues/17750 is the same or similar one
Yes. Is building manually from xcode app the only solution here ? Any way we can make xcodebuild work for apple tv 4k ?

**Comment by rushi04** [comment]
@mykola-mokhnach replacing IPHONEOS_DEPLOYMENT_TARGET with TVOS_DEPLOYMENT_TARGET  worked. 🚀🔥 Thanks a ton. 

Can we make appium do the same while building wda for tvos ?

**Comment by KazuCocoa** [comment]
oh, interesting. Maybe newer xcodebuild restricted some behaviors. Previously it was no matter, if the target was IPHONEOS_DEPLOYMENT_TARGET or TVOS_DEPLOYMENT_TARGET for tvos, but iphone needed to be IPHONEOS_DEPLOYMENT_TARGET

**Comment by mykola-mokhnach** [comment]
xcuitest driver patch v4.13.3 has been published

**Comment by rushi04** [comment]
Hey folks ! It seems that the issue is unrelated to TVOS_DEPLOYMENT_TARGET arg. On apple tv 4k when the device is on `Remote Apps and Devices` screen in Settings app appium is able to build wda else its failing with `xcodebuild failure: xcodebuild failed with code 70.`

This issue might be due to unavailability of usb port on Apple tv 4k, hence for pairing we need to go to a different screen in Settings app. 

@KazuCocoa @mykola-mokhnach any alternative/hack for getting xcodebuild command to work without getting to this screen ?

**Comment by pmsviacom** [comment]
Hello Team,
For the issue i faced here - https://discuss.appium.io/t/unable-to-launch-webdriveragent-because-of-xcodebuild-failure-xcodebuild-failed-with-code-70/37366

I have upgraded my TVOS version & now it is 16.2. As per the release notes, i installed 14.2 version of Xcode as well.
But now i see that while building the project, the Xcode 14.2 has no option of TVOS 16.2 Sdk to choose. 16.1 is the max value seen. Is it possible to get 16.2 device support.
Thanks

**Comment by KazuCocoa** [comment]
Maybe no, we should wait for Apple

**Comment by pmsviacom** [comment]
is there any permanent fix/solution for the 70 code failure?

This issue is again throwing when my TVOS got updated to 16.4, having latest version of Xcode 14.3 and Appium 2.0.0 beta 62. The app launches fine when invoked via appium inspector and fails only through scripts.
With the same capabilities used for inspector, unable to see a permanent way to fix for this for automation run.

Adding the error details:-
*Driver info: driver.version: AppiumDriver*
*remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70*
*xcodebuild error message:*
*. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.*
*    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1067:9)*
*    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)*
*    at runNextTicks (node:internal/process/task_queues:60:5)*
*    at processImmediate (node:internal/timers:446:9)*
