### ISSUE TITLE
bug: "appium driver  uninstall" shows false success most of the times

### ISSUE THREAD

**Issue by pr4bh4sh** [appium/appium#18277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the command `appium driver uninstall espresso` the resulting output says the espresso driver is uninstalled successfully. However, if checked with the command `appium driver list --installed` the output says it is still installed. Rerunning uninstall command one more time finally uninstalls it.

### Expected Behavior

The driver should be uninstalled with just one uninstall command.

### Minimal Reproducible Example

```bash
❯ appium driver install espresso
✔ Installing 'espresso' using NPM install spec 'appium-espresso-driver'
ℹ Driver espresso@2.15.4 successfully installed
- automationName: Espresso
- platformNames: ["Android"]
❯ appium driver list --installed
✔ Listing installed drivers
- espresso@2.15.4 [installed (NPM)]
❯ appium driver uninstall espresso
✔ Successfully uninstalled driver 'espresso'
❯ appium driver list --installed
info Appium Discovered installed driver "espresso"
✔ Listing installed drivers
- espresso@2.15.4 [installed (NPM)]
❯ appium driver uninstall espresso
✔ Successfully uninstalled driver 'espresso'
❯ appium driver list --installed
✔ Listing installed drivers
❯ appium driver uninstall espresso
Error: ✖ Can't uninstall driver 'espresso'; it is not installed
```

### Environment

- Operating system: MacOS 13.2.1
- Appium CLI version (output of `appium --version`): 2.0.0-beta.56
- Node.js version (output of `node --version`): v18.12.1
- `npm` version (output of `npm --version`):  8.19.2

### Futher Information

Although this happens most of the time for me. It does however uninstalls the driver with just one command sometimes.

**Comment by jlipps** [comment]
> info Appium Discovered installed driver "espresso"

What directory are you running this command in?

**Comment by pr4bh4sh** [comment]
The directory is `/Users/prabhash/github/appium-espresso-driver`
Appium server is installed with `npm install -g appium@next`

**Comment by boneskull** [comment]
@pr4bh4sh If you're actually _in_ a driver directory (is this a working copy?) Appium automatically detects the driver.  Can you confirm this is the case?

The intent is to make it easier for extension developers, so if so, this is intended behavior.

However, I think there are some improvements we could make:

- `appium driver list` should show the Espresso driver as being "in dev mode" or something
- `appium driver uninstall espresso` should note that it cannot remove espresso because it's in dev mode. 
- Maybe an `appium driver list --long` which shows detailed information from the extension cache (such as "where is this driver actually installed?).  If not so helpful for users, it'd be helpful for us to debug issues, anyway!

**Comment by jlipps** [comment]
@boneskull i like that idea. i think it would help prevent confusion for users. we don't want to allow uninstall (or install or update) of locally-detected "dev" extensions. maybe a flag like `(auto-detected)` should show up in list

**Comment by pr4bh4sh** [comment]
@boneskull Yes, the directory is a working copy/git clone of the android-espresso-driver.

The improvement you have suggested will definitely remove the confusion and I especially like the last option.
