### ISSUE TITLE
[Feat]: ability to run XCUITestDriver without OSX

### ISSUE THREAD

**Issue by eyJhb** [appium/appium#18276]
**Is your feature request related to a problem? Please describe.**
I am currently running the XCUITestDriver, by starting the WDA and forwarding the port using go-ios.
This requires that the WDA is installed on the iPhone, and is ready to be run (trusted, etc.).
This gives me the ability to run Appium + XCUITestDriver on Linux, which is ideal for the project I am working  on.

**Describe the solution you'd like**
I  would like a capability, which allows to specify the bundleId, and then start a test using https://github.com/appium/appium-ios-device, which does not require any xcode.* to be installed on the system, and would allow to run Appium + XCUITestDriver on other hosts than  OS X.

**Describe alternatives you've considered**
Starting it manually myself, or make a  wrapper besides Appium which gives me this ability.
However, it doesn't seem far fetched that it could be integrated into Appium.

**Comment by eyJhb** [comment]
Further looking into go-ios, it looks like it tries to act as XCode when starting the test, which might not be functionality in the `appium-ios-device`, and might be out of scope for it. But it might be possible to integrate go-ios w/ XCUITestDriver?

I am unsure what the stance on this is, features vs. potential extra bloat.

**Comment by mykola-mokhnach** [comment]
We do not plan to do such integration. Not because we do to want, but rather because there is a big question about who is going to maintain it. There is a reason why xcuitest is based on tools provided by Xcode/Apple. They are properly maintained and updates for each new iOS build. Any third party tools though need to be updated by people who maintain them. In reality there are not so many developers on this globe who reverse engineer Apple's private protocols. 

As a conclusion - this feature could be done, but with the following requirements/limitations:
- It must be optional, e. g. the main flow using Xcode must work as before
- There should be a person who is proficient in the topic and has enough expertise to triage and fix possible issues as well as maintain the solution on a regular basis (both xcuitest-driver and low-level side)
