### ISSUE TITLE
mobile: type - hide and show keyboard on each symbol

### ISSUE THREAD

**Issue by atimofeev86** [appium/appium#18299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using ExecuteScript("mobile: type"), appium hide keyboard and show againg on each new symbol
https://youtu.be/RJTx00x9NVo

### Expected Behavior

Keyboard should be shown and not hide

### Minimal Reproducible Example

see video

### Environment

- Operating system: win10
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 1.22.3
  - Node.js version (output of `node --version`):  v14.16.0
  - `npm` version (output of `npm --version`): 6.14.11
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test: android 11, 12, 13
- Real device or emulator/simulator: real device

### Futher Information

https://youtu.be/RJTx00x9NVo

**Comment by KazuCocoa** [comment]
Could you share the full log as well?

It seems like the behavior is expected since the `type` command is to type unicode string. Then, Appium achieves it via Appium's IME.
https://github.com/appium/appium-uiautomator2-driver/blob/7013ba401252a7de59c2fe15516440db4e606a4c/lib/commands/general.js#L302
https://github.com/appium/appium-adb/blob/bed32382999437c542c04bb0a685dfd28f29f39b/lib/tools/settings-client-commands.js#L593-L607

If you'd like to keep the default IME open, and type only ascii, you could use W3C action's send keys:
e.g. ```driver.key_action.send_keys('hi').perform``` (The command vary from language)
