### ISSUE TITLE
bug: Crashed when I use findElement(MobileBy.IMAGE)

### ISSUE THREAD

**Issue by nanatlantica** [appium/appium#18360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[ImageElementPlugin] Finding image element with match threshold 0.4
[debug] [XCUITestDriver@efef (908745d6)] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/3B727833-3E77-43B5-9864-601A3005D321/window/size] with no body
[debug] [XCUITestDriver@efef (908745d6)] Got response with status 200: {"value":{"width":414,"height":896},"sessionId":"3B727833-3E77-43B5-9864-601A3005D321"}
[debug] [XCUITestDriver@efef (908745d6)] Waiting up to 0 ms for condition
[debug] [XCUITestDriver@efef (908745d6)] Taking screenshot with WDA
[debug] [XCUITestDriver@efef (908745d6)] Matched '/screenshot' to command name 'getScreenshot'
[debug] [XCUITestDriver@efef (908745d6)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/3B727833-3E77-43B5-9864-601A3005D321/screenshot] with no body
[debug] [XCUITestDriver@efef (908745d6)] Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAAAzwAAAcACAYAAAAVAUYrAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAADPKADAAQAAAABAAAHAAAAAAAYjVEBAAAAHGlET1QAAAACAAAAAAAAA4AAAAAoAAADgAAAA4AAB6+Lh6005AAAQABJREFUeAHsfQeAF9XV/e7CLtXee0yMiQUVUbHl0/glX4pJNPbeW2LKP7ErStnC0hQElmWXrlhRQUVUeu+9SFEB6X1p23fv/5w7c2dnFxBjFrKBO3p5M2/e3PfmzG/f3DP3vfsSxDdHwBFwBBwBR8ARcAQcAUfAEXAEDlAEEg7Q+/LbcgQcAUfAEXAEHAFHwBFwBBwBR0Cc8PiPwBFwBBwBR8ARcAQcAUfAEXAEDlgEnPAcsI/Wb8wRcAQcAUfAEXAEHAFHwBFwBJzw+G/AEXAEHAFHwBFwBBwBR8ARcAQOWASc8Bywj9ZvzBFwBBwBR8ARcAQcAUfAEXAEnPD4b8ARcAQcAUfAEXAEHAFHwBFwBA5YBJzwHLCP1m/MEXAEHAFHwBFwBBwBR8ARcASc8PhvwBFwBBwBR8ARcAQcAUfAEXAEDlgEnPAcsI/Wb8wRcAQcAUfAEXAEHAFHwBFwBJzw+G/AEXAEHAFHwBFwBBwBR8ARcAQOWASc8Bywj9ZvzBFwBBwBR8ARcAQcAUfAEXAEnPD4b8ARcAQcAUfAEXAEHAFHwBFwBA5YBJzwHLCP1m/MEXAEHAFHwBFwBBwBR8ARcASc8PhvwBFwBBwBR8ARcAQcAUfAEXAEDlgEnPAcsI/Wb8wRcAQcAUfAEXAEHAFHwBFwBJzw+G/AEXAEHIH/EALlqJciZfmBlJcgo0SKkBWXUhxTKrYy7EIiBRVngj07H+ijzkBwFtfs8bKqavZyvKuesF5BfTEpR1splluIsxS7L8u31PKjhoYVWX1...
[ImageElementPlugin] Verifying screenshot size and aspect ratio
[ImageElementPlugin] Screenshot aspect ratio '0.46205357142857145' (828x1792) matched screen aspect ratio '0.46205357142857145' (414x896)
[ImageElementPlugin] Scaling screenshot from 828x1792 to match screen at 414x896
[AppiumDriver@ae8c] Command 'findElement' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["images"].
[debug] [XCUITestDriver@efef (908745d6)] Encountered internal error running command: undefined
Fatal TypeError: Cannot use 'in' operator to search for 'w3cStatus' in 6681088
    at isProtocolError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1050:21)
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1063:8)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:476:57)

### Expected Behavior

Work fine

### Minimal Reproducible Example

png_file = open(name, 'rb')
b64_data = base64.b64encode(png_file.read()).decode('UTF-8')
time.sleep(1)
element = pDriver.find_element(MobileBy.IMAGE, b64_data)
element.click()

### Environment

Appium 2.0.0beta57
Images-Plugin 2.0.8

**Comment by mykola-mokhnach** [comment]
@boneskull Could you please take a look?

**Comment by mykola-mokhnach** [comment]
I assume the error happens because we have something like `throw 'somestring'` somewhere, so https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/in_operator_no_object happens.
Perhaps it would make sense to add additional debug log to https://github.com/appium/appium/blob/8805792089ed8a8bb2b7923bcb5d19c20e0dc89e/packages/base-driver/lib/protocol/protocol.js#L457

**Comment by mykola-mokhnach** [comment]
The patch above should help to address the issue. @nanatlantica please apply it locally and provide the resulting log or wait unit the next server version is released to try it.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by didental** [comment]
I had the same experience. 
Please check it again.


Is there an existing issue for this?
 I have searched the existing issues
Current Behavior
[HTTP] --> POST /session/e753a01f-f232-4a99-b577-e25129fbdc7c/elements
[HTTP] {"using":"-image","value":"iVBORw0KGgoAAAANSUhEUgAAAYgAAAAvCAYAAAD5LV3EAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAAEZ0FNQQAAsY8L/GEFAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAIXRFWHRDcmVhdGlvbiBUaW1lADIwMjE6MDk6MTUgMjI6MzI6MjBhYGP1AACFxElEQVR4XrW9Z6xlWXbft26O776cql7Vq5y7uqu7p9METiQnUAwSKdOEaBOiDIjSB1v64C+G4ZENAU6AYUOWIcGWAAmCYFmGJTMPLQ5nSPZMz3TOuSunl8PNyf/f2ufce9+rVzNDWV5V+51z9tlh7bXXXmHvffZNHDu12M9mMpZKpWx1q2q79bb1++YByCbMcumklYpZpUl6XF//Op2etVpta7d0bXetqftut2PW7YXMCWX0xKGg86eX7dd+6WfssUcP2bFjJcW09E5pLavQU4lNS1he9wWFollG94Wc/f7vv2p/8K2X7JVXXrH79+8rjV5l05bNpK2nsrsd1alyxitlO3xozn7zN75qn//MeUuq/F6/KXSals9nLZfNWTpVEDoZ4al25Katkxy3WrVnv/etP7H/9r/7+7aytWadflu4qxLQjoOes1NJSxcSyt8THfqWAu34vaC9aVZfDfcOUfNjOLw4af/Ff/qX7DPPng0RfeFtqotbYSuEFNRuK1uiWLR6N21377Xsd377j+1/+1//mSWSCUsmkiqWq/4qjI2P29TsrJ06f94qk5PWaYfyms2mffjee3bv1i3b3dry+L5o1RPuUFo39oUvPGe/+qu/YCcWezY3CQ3rykl/ABmFdHRbsn5+Uu2Zsrt3G/Z3/s5/Y9/5zvPhXdzG+Kqi87MpqxxNW7vRtk6jI/5QqTRPRaYIOSUuJS0lnsopY2E3Y/nNtNVXupZLdG1mxmxqSl1f7NvrH3Ts7gr8ZNYRzp2O+rsbWCyhuF/7lc/Y3/3Pf0X9qkhFtN...
[debug] [AndroidUiautomator2Driver@7c45 (e753a01f)] Calling AppiumDriver.findElements() with args: ["-image","iVBORw0KGgoAAAANSUhEUgAAAYgAAAAvCAYAAAD5LV3EAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAAAAEZ0FNQQAAsY8L/GEFAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAIXRFWHRDcmVhdGlvbiBUaW1lADIwMjE6MDk6MTUgMjI6MzI6MjBhYGP1AACFxElEQVR4XrW9Z6xlWXbft26O776cql7Vq5y7uqu7p9METiQnUAwSKdOEaBOiDIjSB1v64C+G4ZENAU6AYUOWIcGWAAmCYFmGJTMPLQ5nSPZMz3TOuSunl8PNyf/f2ufce9+rVzNDWV5V+51z9tlh7bXXXmHvffZNHDu12M9mMpZKpWx1q2q79bb1++YByCbMcumklYpZpUl6XF//Op2etVpta7d0bXetqftut2PW7YXMCWX0xKGg86eX7dd+6WfssUcP2bFjJcW09E5pLavQU4lNS1he9wWFollG94Wc/f7vv2p/8K2X7JVXXrH79+8rjV5l05bNpK2nsrsd1alyxitlO3xozn7zN75qn//MeUuq/F6/KXSals9nLZfNWTpVEDoZ4al25Katkxy3WrVnv/etP7H/9r/7+7aytWadflu4qxLQjoOes1NJSxcSyt8THfqWAu34vaC9aVZfDfcOUfNjOLw4af/Ff/qX7DPPng0RfeFtqotbYSuEFNRuK1uiWLR6N21377Xsd377j+1/+1//mSWSCUsmkiqWq/4qjI2P29TsrJ06f94qk5PWaYfyms2mffjee3bv1i3b3dry+L5o1RPuUFo39oUvPGe/+qu/YCcWezY3CQ3rykl/ABmFdHRbsn5+Uu2Zsrt3G/Z3/s5/Y9/5zvPhXdzG+Kqi87MpqxxNW7vRtk6jI/5QqTRPRaYIOSUuJS0lnsopY2E3Y/nNtNVXupZLdG1mxmxqSl1f7NvrH3Ts7gr8ZNYRzp2O+rsbWCyhuF/7lc/Y3/3Pf0X9qkhFtNpJsULXMhnakbFeLy...
[AppiumDriver@f860] Plugins which can handle cmd 'findElements': images
[AppiumDriver@f860] Plugin images is now handling cmd 'findElements'
[ImageElementPlugin] Finding image element with match threshold 0.7
[debug] [AndroidUiautomator2Driver@7c45 (e753a01f)] Matched '/window/current/size' to command name 'getWindowSize'
[debug] [AndroidUiautomator2Driver@7c45 (e753a01f)] Proxying [GET /window/current/size] to [GET http://127.0.0.1:8202/session/1acdaf63-bb88-45bf-a8fa-74c9cbd3deb1/window/current/size] with no body
[debug] [AndroidUiautomator2Driver@7c45 (e753a01f)] Got response with status 200: {"sessionId":"1acdaf63-bb88-45bf-a8fa-74c9cbd3deb1","value":{"height":2402,"width":1080}}
[debug] [AndroidUiautomator2Driver@7c45 (e753a01f)] Waiting up to 0 ms for condition
[debug] [AndroidUiautomator2Driver@7c45 (e753a01f)] Matched '/screenshot' to command name 'getScreenshot'
[debug] [AndroidUiautomator2Driver@7c45 (e753a01f)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8202/session/1acdaf63-bb88-45bf-a8fa-74c9cbd3deb1/screenshot] with no body
[debug] [AndroidUiautomator2Driver@7c45 (e753a01f)] Got response with status 200: {"sessionId":"1acdaf63-bb88-45bf-a8fa-74c9cbd3deb1","value":"iVBORw0KGgoAAAANSUhEUgAABDgAAApQCAYAAABYiJrlAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7J13fBXF+v8/GxIwCeQECMUACSDdhCIgaLhSRdoNiOUSBZQvKkFApeanFL00DYigwhVUUIgCvqwgElGqGkSkJyBdCE1ASoKUJCT7++Nk52yZbefsSYHnfa9kz+7sM7NTn3mmCQBEEARBEARBEARBEARBlGICijsABEEQBEEQBEEQBEEQvkIGDoIgCIIgCIIgCIIgSj1k4CAIgiAIgiAIgiAIotRDBg6CIAiCIAiCIAiCIEo9ZOAgCIIgCIIgCIIgCKLUQwYOgiAIgiAIgiAIgiBKPWTgIAiCIAiCIAiCIAii1EMGDoIgCIIgCIIgCIIgSj1k4CAIgiAIgiAIgiAIotRDBg6CIAiCIAiCIAiCIEo9ZOAgCIIgCIIgCIIgCKLUQwYOgiAIgiAIgiAIgiBKPWTgIAiCIAiCIAiCIAii1EMGDoIgCIIgCIIgCIIgSj1k4CAIgiAIgiAIgiAIotRDBg6CIAiCIAiCIAiCIEo9ZOAgCIIgCIIgCIIgCKLUQwYOgiAIgiAIgiAIgiBKPWTgIAiCIAiCIAiCIAii1EMGDoIgCIIgCIIgCIIgSj1k4CAIgiAIgiAIgiAIotRDBg6CIAiCIAiCIAiCIEo9ZOAgCIIgCIIgCIIgCKLUQwYOgiAIgiAIgiAIgiBKPWTgIAiCIAiCIAiCIAii1EMGDoIgCIIgCIIgCIIgSj1k4CAIgiAIgiAIgiAIotRDBg6CIAiCIAiCIAiCIEo9ZOAgCIIgCIIgCIIgCKLUQwYOgiAIgiAIgiAIgiBKPWTgIAiCIAiCIAiCIAii1EMGDoIgCIIgCIIgCIIgSj1k4CAIgiAIgiAIgiAIotRDBg6CIAiCIAiCIAiCIEo9ZOAg...
[ImageElementPlugin] Verifying screenshot size and aspect ratio
[ImageElementPlugin] When trying to find an element, determined that the screen aspect ratio and screenshot aspect ratio are different. Screen is 1080x2402 whereas screenshot is 1080x2640.
[ImageElementPlugin] Resizing screenshot to 1080x2640 to match screen aspect ratio so that image element coordinates have a greater chance of being correct.
[AppiumDriver@f860] Command 'findElements' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["images"].
[AndroidUiautomator2Driver@7c45 (e753a01f)] The thrown error object does not seem to be a valid instance of the Error class. This might be a genuine bug of a driver or a plugin.
[debug] [AndroidUiautomator2Driver@7c45 (e753a01f)] Encountered internal error running command: undefined
[HTTP] <-- POST /session/e753a01f-f232-4a99-b577-e25129fbdc7c/elements 500 1948 ms - 576

Expected Behavior
Work fine

Minimal Reproducible Example
```
with open(p, 'rb') as png_file:
    img = base64.b64encode(png_file.read()).decode('UTF-8')
obj = driver.find_elements(MobileBy.IMAGE, img)

```
Environment
Appium v2.0.0-beta.71
images@2.1.1
Appium-Python-Client Version: 2.10.1
Python 3.11.0

Link to Appium Logs
No response

Futher Information
No response
