### ISSUE TITLE
[feat] Set waitForIdleTimeout and/or waitForSelectorTimeout small time such as 100 in UIA2 driver by default

### ISSUE THREAD

**Issue by fleytman** [appium/appium#18451]
Can you improve uiautomator2-driver driver like https://github.com/KasperskyLab/Kaspresso/blob/master/wiki/02_Wrapper_over_UiAutomator.md ?

I looked at the source code of uiautomator2-driver, which uses waitForSelectorTimeout to wait for elements to appear on the screen. This can lead to unnecessary waiting or skipping elements if they appear later.

Perhaps you want to improve the uiautomator2-driver by adding the ability to use a mechanism similar to FlakySafeInterceptor to repeat actions without a timeout.

**Comment by KazuCocoa** [comment]
`waitForIdleTimeout` and `waitForSelectorTimeout` via settings api did not help?
https://github.com/appium/appium-uiautomator2-driver#settings-api (e.g. set the value as zero or much smaller than the default value)

**Comment by fleytman** [comment]
I read this. What I meant was that you have a default parameter with a wait of 1 second for each action. So most users won't change this parameter and they will have slow tests. It would make sense to make a mechanism similar to what kautomator did. And it would be more logical if it would not be implemented by everyone in their own project, but would be a mechanism at framework/driver level.

**Comment by KazuCocoa** [comment]
I see. So, your suggestion is to set lower values by default when Appium/UIA2 server starts instead of Android framework's value.
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/cmds/uiautomator/library/core-src/com/android/uiautomator/core/Configurator.java;l=33-34?q=setWaitForIdleTimeout

Appium/UIA2 does not set any values to follow the vanilla UIA framework at the beginning. Potentially less value could cause an unexpected UI crash (don't remember well, but uia framework's issue tracker or somewhere addressed lower value could cause such UI handling issue, so Android had the 1sec timeout by default), so Appium does not set its own value to respect the original framework. (as my understanding), instead just gives the ability to customize the value

**Comment by fleytman** [comment]
I found that you are familiar with this behavior[ from as far back as 2021](https://kazucocoa.wordpress.com/2021/02/12/appium-waitforidletimeout-and-waitforselectortimeout/). Did the appium team have any discussions and tests about it? It seems like if you try to do flak handling on the appium side and remove large waits, it would greatly improve the framework.

**Comment by KazuCocoa** [comment]
Probably at the initial implementation time for the settings api was to provide an ability to configure the timeout from the Android's default implementation to optimize the interaction speed. As for backward compatibility, Appium just provided the ability.

In my past work experience with UIA framework (not via Appium), I tried the zero value then. (It was over 5 years ago, so I don't remember clearly though). Then, I met weird test failures with UI animation in a manufacture's device, so perhaps I gave up using the zero value to avoid weird flakiness by UI something. I moved to vanilla Espresso at that time eventually though. (I remembered a bit when I was writing this comment that improving main thread usage in the product code's implementation helped to avoid the worst wait time without setting such zero timeout value. Bad animation implementation in the main thread easy to consume the idle timeout as the worst case)

I previously thought setting zero for such idle timeout and no window animation by default was better in automation, but it depended on automation purposes, I have learned. It was just my personal opinion. Currently, I don't have strong opinions about making zero value/animation by default in Appium since it has various use cases, already. (Some persons use Appium Espresso driver to optimize the running speed rather than Appium UIA2, for example, to make automation stable via Espresso framework)

(btw, I think your opinion is also correct opnion)

**Comment by fleytman** [comment]
> Then, I met weird test failures with UI animation in a manufacture's device, so perhaps I gave up using the zero value to avoid weird flakiness by UI something. 

These are quite probable errors. In this case it is just about the fact that the framework can handle such errors, by the example of how they did it in kaspresso. It's about the appium approach in general, and who should decide what waiting strategy. I'm sure most appium users know about explicit and implicit waits mechanisms and use them. And it seems odd if someone set a wait of 100ms for an item and in fact it can't be less than 1000ms. That's why I'm starting this discussion, I think we need to look at the problem with fresh eyes. There are points of growth in the performance of the appium tests.

P.S. I know that there is a stereotype that appium is slow. In fact, it can be accelerated, but it requires a change. For example, [there is a task from 2017](https://github.com/google/EarlGrey/issues/395) about adding to erlgray appium support, but as of 2023 there is no news. Maybe if the appium team and google cooperated, you could increase the test speed for ios as well.

**Comment by amedvedjev** [comment]
`P.S. I know that there is a stereotype that appium is slow. In fact, it can be accelerated, but it requires a change.`  - with iOS but not with Android. I am disabling all animation on devices and adding 200ms delay after each tap to make Appium a bit slow. Otherwise it tries to tap element while it appearing during animation (tap does not work in this case).

With iOS it is another story... every iOS version giving new speed. I remember some where really slow, some where quite fast (close to Android speed). Current 16 version about 20-30% slower then android speed we have with our tests. Many depends with iOS on number of elements on screen as we know and can slow elements find as hell (e.g. country list with 200 items).

**Comment by jlipps** [comment]
> Maybe if the appium team and google cooperated, you could increase the test speed for ios as well

I've tried many times, and had various meetings, but they never follow through.

**Comment by KazuCocoa** [comment]
It is appreciated to try something like below value as part of capabilities to see how like this small value helps. Our testing app is vary simple, so it would be appreciated to measure performance differences in real world apps.

```
"settings[waitForIdleTimeout]": 100
"settings[waitForSelectorTimeout]": 100
```

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-uiautomator2-driver#poor-elements-interaction-performance as a reference.
