### ISSUE TITLE
[Feat]: SendKeys() found by image search

### ISSUE THREAD

**Issue by Liqun-Ma** [appium/appium#18465]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cannot send keys after I find an element by an Image

**Describe the solution you'd like**
send keys after I find an element by an Image.

**Additional context**
I am using 2.0.0-beta.57 and WinAppDriver
I want to use in below way
var email = session.FindElement(by: MobileBy.Image(base64String));
email.SendKeys(MyEmail);

**Comment by KazuCocoa** [comment]
find image does not select actual native element, so the send_key itself may not work as same. One possible way is click the element once to make the element active, then send keys via w3c actions like `driver.action.send_keys('xxx').perform` (in Ruby).

It would be appreciate if you already have an idea to achieve it.

**Comment by mykola-mokhnach** [comment]
As @KazuCocoa in order to send keys to an element it must be an actual system object, like accessibility object in UIA2 driver. In case with image recognition all we have is just some matched region on the screen. All we know about it are coordinates. 

As a possible workaround you might perform a click and then type a text assuming the necessary element got the input focus.

I don't think there's much more we could do there unless you have some more ideas on how such functionality could reliably be implemented in windows driver

**Comment by Liqun-Ma** [comment]
I tried to use WinAppDriver only, below works,
`session.Keyboard.PressKey("L");`
but I can not find `Keyboard ` in my project. I am using this nugut package:`.nuget\packages\appium.webdriver\5.0.0-beta03\`

**Comment by Liqun-Ma** [comment]
I use `System.Windows.Forms`, and `SendKeys.SendWait("user@gmail.com");`. It works:)
