### ISSUE TITLE
bug: Elements on 'Notifications' page not found on iOS 16 with app open

### ISSUE THREAD

**Issue by IvanPasta0** [appium/appium#18512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On iPhone 14 Pro Max (iOS 16.3.1) the search of elements on 'Notifications' page works only if no apps are open.
On another iPhone (iPhone Xr with iOS 15) everything works as expected.

### Expected Behavior

The search of elements on 'Notifications' page should work even if an app is open.

### Minimal Reproducible Example

[This video](https://youtu.be/nXkME3yGHCs) shows the error using Appium Inspector.
As you can see the XPath expression `//XCUIElementTypeOther[@name="lockscreen-date-view"]` works only if 'Notes' app is closed or on background.

### Environment

- Appium running on macOS 11.3.1
- Appium CLI
  - Appium@2.0.0-beta.61
  - Xcuitest@4.21.12
  - Node.js 18.13.0
  - `npm` 8.19.3
- iOS 16.3.1
- iPhone14 Pro Max

**Comment by mykola-mokhnach** [comment]
You could try to play with defaultActiveApplication and activeAppDetectionPoint [settings](https://appium.github.io/appium-xcuitest-driver/4.19/settings/). Otherwise I don't have any good ideas on how this behaviour could be constomized from WDA see. The article https://appiumpro.com/editions/109-working-with-ipados-multitasking-split-view would also be useful to read
