### ISSUE TITLE
xcuitest: semantic release does not update package-lock.json

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18553]
I noticed this when pulling just after a tagged release just now: upon `npm install`, `package-lock.json` gets modified with an updated version:

```diff
diff --git a/package-lock.json b/package-lock.json
index 9a1eacd4..c6f18125 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,12 +1,12 @@
 {
   "name": "appium-xcuitest-driver",
-  "version": "4.23.1",
+  "version": "4.24.1",
   "lockfileVersion": 3,
   "requires": true,
   "packages": {
     "": {
       "name": "appium-xcuitest-driver",
-      "version": "4.23.1",
+      "version": "4.24.1",
       "license": "Apache-2.0",
       "dependencies": {
         "@xmldom/xmldom": "0.8.7",
```

This means--AFAICT--that `semantic-release` should have committed a change to `package-lock.json`, but did not.

**Comment by KazuCocoa** [comment]
This caused https://github.com/appium/appium-xcuitest-driver/pull/1638, so reverted the change at this time.

Let me dig into this later

**Comment by mykola-mokhnach** [comment]
@KazuCocoa can we close this issue?

**Comment by KazuCocoa** [comment]
Not yet. So far, maybe we need a task? to bump `package-lock.json` after a release job separately. Then can close this.
(or completely moves to package-lock.json instead of shrinkwrap. Then, maybe we should consider package-lock's version as well)

Anyway, I'll try to create a job to bump package-lock.json to do it. Then I think this ticket can be closed at least.
