### ISSUE TITLE
IOS app - the element is Displayed, the status is True, but I couldn't click on element

### ISSUE THREAD

**Issue by GarinaKristina** [appium/appium#18758]
Hi, I am testing the iOS application using Appium "2.0.0-beta.71" and "appium-xcuitest-driver": "4.30.2". with webdriverIO. I met with the issue regarding clicking action.
 Element is displayed
![Screenshot 2023-06-13 at 13 22 46](https://github.com/appium/appium/assets/87827778/78ed5ad3-6e18-44e3-9fcc-ece812f3f7a8)
When I start running the test on this page, the element is clicked and I see this on the UI. But if I run the test from other pages I saw two variants. 
First- in the terminal, I saw how this clicked in logs, but in UI I didn't see these actions.
Second-in terminal doesn`t click and UI doesn't click, too.

I tried to use other locators, and different methods for clicking but the result is the same

**Comment by jlipps** [comment]
If, in the Appium log, you see that the click has been reported as successful, then there's not much we can do about it. Sometimes the element you have selected is not the element with the click handler attached to it. I've noticed this periodically. It could be the element with the accessibility ID is not the correct element; maybe there is another one which is a child or a parent element which could be selected instead? 

The way I usually solve this is by using the Appium Inspector and finding the element, and making sure that the tap action actually works. Then it's often pretty clear if the selector is correct since the Inspector will often recommend a selector.

If you don't think this helps, you can always attach your full Appium log (not the WDIO log) ,and highlight the section where the click is happening so we can review. But if the click is completing "successfully" from the Appium side, then there won't really be much we can do probably, since we are just calling Apple's click methods from XCUITest.
