### ISSUE TITLE
bug: Appium Inspector doesn't display entering camera or giving permissions to use storage activity on Android emulator

### ISSUE THREAD

**Issue by R4Ajeti** [appium/appium#18807]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
I'm experiencing a bug I have been googling for more than 2 days but didn't find any solution.

The bug pertains to Appium 2.0, where it fails to open the camera or permission activity on the target device, I tried using Appium Inspector (don't show up), and also I tried using Python client (it doesn't find the element) it's the same.

![image](https://github.com/appium/appium/assets/19622120/a5313fdd-a55d-4428-9565-739cdf96be84)
![image](https://github.com/appium/appium/assets/19622120/41319d05-d565-433d-85ce-feb1efa98da6)

### Expected Behavior

Open permission activity, -> camera activity.

### Minimal Reproducible Example

Open an app using Inspector that has upload image on it.

### Environment

- Operating system: Windows 10
- Appium server version (output of `appium --version`): 2.0.0-rc.3
- Appium driver(s) and their version(s): espresso
- Appium plugin(s) and their version(s): images
- Node.js version (output of `node --version`): v18.14.0
- `npm` version (output of `npm --version`): 9.6.7
- Last component(s) version which did _not_ exhibit the problem: 1.22.3
- Platform and version under test:
- Real device or emulator/simulator: android emulator pixel 5, android version 13

### Link to Appium Logs

https://gist.github.com/R4Ajeti/f939110cccfd993248289b268d92ad80

**Comment by mykola-mokhnach** [comment]
I assume this might be a limitation of the Espresso framework itself as we use standard APIs that the framework provides to take screenshots: https://github.com/appium/appium-espresso-driver/blob/6f52e6250fa055465f564bf33e1d5bef2c74e9b2/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ScreenshotHelpers.kt#L42

**Comment by R4Ajeti** [comment]
Hi @mykola-mokhnach,

How I am supposed to pass that "Upload image step", can I send a static image using Appium python client or any suggestion, please?

**Comment by mykola-mokhnach** [comment]
> Is there any way I can do using the "UIAutomator2" driver because on Appium 2.0 also with automator is exactly the same issue

If UIA2 exposes the same issue then this means it uses the same system APIs to take screenshots. Perhaps, Google does not want security alerts to be present on automation screenshots and we cannot do much about it.

> Or should I move back to appium version 1

I cannot advice that because this version is not maintained and is basically a dead end if you use it as a foundation for your automation framework. 

As a possible workaround you could upgrade Espresso driver to the most recent version and use the [mobile: screenshots](https://github.com/appium/appium-espresso-driver#mobile-screenshots) extension to make a screenshot. It runs screencap utility under the hood instead of using system APIs directly. Maybe it works differently. If that still does not work then consider creating an issue report to Google.

**Comment by mykola-mokhnach** [comment]
The images plugin does not affect the way page source or screenshots are represented. 

Closed as third party issue
