### ISSUE TITLE
need to update remote debugger selenium atoms to latest

### ISSUE THREAD

**Issue by jlipps** [appium/appium#18951]
We haven't updated since 3.14159!

**Comment by jlipps** [comment]
Atoms currently in use in the xcuitest driver:

```
execute_script
is_displayed
is_enabled
is_selected
get_attribute_value
get_text
get_top_left_coordinates
get_size
click
type
clear
getElementScreenshot
get_frame_window
frame_by_index
frame_by_id_or_name
get_value_of_css_property
submit
refresh
title
find_element
find_elements
move_mouse
active_element
```

**Comment by jlipps** [comment]
Atoms seemingly available in the latest version of selenium:

```
clear
click
execute-async-script
execute-script
execute-sql
find-element
find-elements
get-effective-style
get-location
get-size
get-text
is-displayed
is-editable
is-enabled
is-focusable
is-interactable
submit
```

**Comment by jlipps** [comment]
We should be able to migrate to the new atoms as follows:

```
execute_script -> execute-script
is_displayed -> is-displayed
is_enabled -> is-enabled
get_attribute_value -> get-attribute
get_text -> get-text
get_top_left_coordinates -> get-location
get_size -> get-size
click -> click
clear -> clear
get_value_of_css_property -> get-effective-style
submit -> submit
find_element -> find-element
find_elements -> find-elements
```

This leaves the following existing atoms/behaviours without a clear migration path:

```
is_selected
type
get_frame_window
frame_by_index
frame_by_id_or_name
refresh  # maybe just window.location.reload()?
title # maybe just document.title?
move_mouse # this is from the deprecated moveTo command so we can just get rid of it?
active_element
```

Of these the most important is obviously `type`. What should we do instead? The frame stuff is probably also important.

**Comment by jlipps** [comment]
Requesting some assistance from e.g. @titusfortner @automatedtester. Would be great to have a bit of guidance on the questions in the comment directly above!

**Comment by titusfortner** [comment]
I don't have any insight into how the atoms have changed, I'm assuming from the new build process. @shs96c or @jimevans might also have the answers.

**Comment by shs96c** [comment]
Looking at these, the first thing we need to do is figure out which atom the functions map to. A quick pass through, and without much context, suggests:

`active_element` -> `bot.dom.getActiveElement`
`is_selected` -> `bot.dom.isSelected`
`move_mouse` -> `bot.action.moveMouse` (though it's preferable to use the Actions right now, as you suggest)
`type` -> `bot.action.type`

Once we know that, we just need to compile the atom to a fragment. If you need a hand exposing these in the Selenium code base, LMK, and we can prep a PR to make these easy to find. Building them should be trivial. Something like `bazel build //javascript/atoms/fragments:get-text` should do the trick, but we'll need to expose those atoms as fragments if they're the right ones.

There are some functions which look suspect to me. These are:

* `get_element_from_cache` (because it exposes an implementation detail of the atoms, which people shouldn't need to care about)
* `get_frame_window` (surely this is the `window` constant for a particular frame?)
* `frame_by_index` (no obvious candidate in the atoms, but it should be something like `window.frames[n]`)
* `frame_by_id_or_name` (again, no obvious candidate, but I think it's a JS function supplied by HTML)
* `refresh` (just call `reload`, as you suggest)
* `title` (maybe just document.title? Yes)

I'm happy to dig deeper if needed.

**Comment by jlipps** [comment]
Linking in https://github.com/appium/appium-android-driver/pull/819

**Comment by jlipps** [comment]
Ran into https://github.com/SeleniumHQ/selenium/issues/12549 which is causing a problem as well
