### ISSUE TITLE
[Feat] Support for HID calls similar to apple for XCUITest driver

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium#19022]
is their anyway we can achieve ioHID calls similar to below calls:

Home usagePage:0xc usage:0x40 downEvent:1 pressCount:2 down
Home usagePage:0xc usage:0x40 downEvent:1 phase:0x4 pressCount:2 end 

I am observing some syslogs from device and found the above hid calls for launching app-switcher(iphone 8)

**Comment by mykola-mokhnach** [comment]
There is no known way to make it work. The interface that testmanagerd exposes is limited and cannot make emulate down/up events. Only single click.
Trying to call this API from elsewhere won't work because it requires higher privileges, which you'd never get on non-rooted iOS platform.

Thus closing.

**Comment by nanoscopic** [comment]
The app switcher can be launched via the assistive touch overlay icon. That can be enabled by using control center.
