### ISSUE TITLE
[Question] Is `addUIInterruptionMonitor` method could be available to WebDriverAgent? 

### ISSUE THREAD

**Issue by Ernst-D** [appium/appium#19083]
Hi, Appium team! This question is more about wonder whether [addUIInterruptionMonitor](https://developer.apple.com/documentation/xctest/xctestcase/1496273-adduiinterruptionmonitor) method could be added to WebDriverAgent as a command and then invoked like Settings API command during test runs. 

I'm pretty sure that implentation of this method will find its application.

**Comment by mykola-mokhnach** [comment]
Currently the default interruptions monitor is disabled completely in WDA because it was slowing down the execution and even started creating unexpected issues after some xctest updates.
In general we do not plan to work on such feature in the future. The source code is open though, so you could always change it and add a custom monitor implementation if you need it for app testing.
