### ISSUE TITLE
Issue with Environment Variables in Appium

### ISSUE THREAD

**Issue by ketai4eg** [appium/appium#19463]
Dear sirs,

I hope this email finds you well. I am writing to seek assistance with an issue I have encountered while working with Appium 2 and the Windows driver.

The problem revolves around environment variables not being recognized or applied when running our Windows App through Appium. Specifically, the app is designed to connect to different staging servers based on the environment variables set in the system.

When I manually run the app, it seamlessly takes the environment variables from the system, and everything works as expected. However, when I attempt to do the same through Appium with the Windows driver, the environment variables do not seem to change, and the app does not adapt to the system variables.

I have considered several approaches to address this matter, including setting environment variables explicitly in the Appium and checking the Appium session configuration for desired capabilities related to environment variables. Despite these efforts, the issue persists.

I am using Appium 2 and the Windows driver. Any insights or suggestions you can provide would be greatly appreciated.

Thank you for your time and assistance.

**Comment by mykola-mokhnach** [comment]
I am afraid we won't be able to help you much on this as the server part is owned by Microsoft there, is pretty much abandoned by them, and is not open sourced. As a possible workaround you may run the app separately (for example using prerun capability or powerShell extension) and provide the necessary environment to it.

Otherwise consider reporting your issue to https://github.com/microsoft/WinAppDriver and hope somebody from the community might have an answer

**Comment by ketai4eg** [comment]
Certainly! Here's an improved version of your text:

Indeed, it appears you are correct. I've previously attempted the standard PowerShell approach and executed it in the pre-run phase. It works successfully in the base system environment—I can verify this on the machine. However, within the context of Appium, it somehow retains a different configuration.

Nonetheless, I appreciate your assistance!
