### ISSUE TITLE
[Feat]: if devicectl command can modify defaults

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#19933]
This includes investigation work.

If `devicectl` command can issue `defaults` command to modify Safari config (for example) to real devices like we do for simulators.

e.g. https://github.com/appium/appium-xcuitest-driver/blob/ba54e3837473d39e166e4a106f344a4f770198ac/lib/simulator-management.js#L292

If possible, we may be able to configure device via the `devicectl` command in real device as well, which helps further automation

**Comment by KazuCocoa** [comment]
Explored helps in commands. I don't see any helpful commands so far in a quick check. I'll take a look further

**Comment by mykola-mokhnach** [comment]
I also did some local experimentation and got https://github.com/appium/appium-xcuitest-driver/pull/2373
It seems like devicectl is slightly limited in what it could do and only supports execution of apps (e.g. requires a bundle identifier to be provided). At least I get the following error
```
ERROR: The operation couldn’t be completed. (OSStatus error -9499.) (NSOSStatusErrorDomain error -9499 (0xFFFFDAE5))
       _LSFunction = _LSFindBundleWithInfo_NoIOFiltered
       _LSLine = 173
```

when I try to provide a valid system binary path to it instead of a bundle identifier

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Can we close this issue?
