### ISSUE TITLE
Support prefs URL scheme for iOS devices

### ISSUE THREAD

**Issue by ilendemli** [appium/appium#19959]
Hey!

It would be nice to use prefs url to jump into specific settings page on iOS 
Here is a collection of existing urls: https://github.com/FifiTheBulldog/ios-settings-urls/blob/master/settings-urls.md

**Comment by mykola-mokhnach** [comment]
I think it is already possible with the support of deep links that Apple added to XCTest since iOS 17
Check the [mobile: deepLink](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/reference/execute-methods.md#mobile-deeplink) extension and the [appium:initialDeeplinkUrl](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/reference/capabilities.md#app) capability

**Comment by mykola-mokhnach** [comment]
Perhaps it would be a good idea to just document that somewhere/link the above list

**Comment by ilendemli** [comment]
I tried the deepLink extension but have had the same behaviour as @KazuCocoa. Settings app opens, but no specific page is opened.

**Comment by KazuCocoa** [comment]
I'm not sure if the `App-Prefs`/`prefs` works via https://developer.apple.com/documentation/xctest/xcuiapplication/4108226-openurl , but the deeplink basically calls open url like that API internally. @ilendemli how did you confirm the behavior without Appium?

If only via `UIApplication` works as the apple's forum, potentially via XCUIApplication for XCTest might not work.
- https://developer.apple.com/documentation/uikit/uiapplication?language=objc
- https://developer.apple.com/documentation/xctest/xcuiapplication?language=objc

**Comment by ilendemli** [comment]
Yea never mind, I remember this working back then a few years ago but it seems like this does not work anymore. But opening the URL from the Shortcuts app seems to work.
