### ISSUE TITLE
[Feat]: Support for custom usbmuxd socket path or url 

### ISSUE THREAD

**Issue by Himanshu-Gurjar** [appium/appium#20073]
As we can provide remote address and port for adb with the help of capabilities (remoteAdbHost and adbPort)

it is feasible that we can also provide usbmuxd socket path or usbmuxd socket remote address for iOS devices automation?

It will be helpful in case of remotely connected iOS devices.

**Comment by mykola-mokhnach** [comment]
I don't think we want to invest into that because Apple is moving away from usbmuxd support.
Eventually we'd like to get rid of appium-ios-device lib as it is not maintained and rely on a third party tool, like go-ios

Feel free to commit a PR though if you want to implement this functionality yourself.
