### ISSUE TITLE
[Appium] spawn EINVAL

### ISSUE THREAD

**Issue by 13817458995** [appium/appium#20487]
An error happens when starting appium:

[Appium] spawn EINVAL

Appium version is 2.0.0-rc.2

**Comment by eglitise** [comment]
Please try again with the latest version of Appium. If your issue is still reproducible, [please use the provided bug report template and provide all the required information](https://github.com/appium/appium/issues/new?assignees=&labels=Bug%2CNeeds+Triage&projects=&template=bug_report.yml&title=bug%3A+%3Ctitle%3E).
Closing as incomplete
