### ISSUE TITLE
driver.shake not available for android. ?

### ISSUE THREAD

**Issue by Priya-1893** [appium/appium#20660]
I am trying to automate the shake functionality in Android device , but i dont find any support or documents which can help me.
driver.shake is not working for android.

The only thing i noticed is adb command which be used form terminal . need support

**Comment by KazuCocoa** [comment]
It is not available since no provided API by Android. We're happy to review if you find a good way to achieve shake.

> The only thing i noticed is adb command which be used form termina

Could you share what command achieve shake via `adb`? Does it work for both real/emulator devices?

If you know of the shell command, you can use the shake via `mobile:shell` https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-shell command

**Comment by mykola-mokhnach** [comment]
Closed because of no response
