### ISSUE TITLE
Failure to find "launch" activity and launch certain Android apps

### ISSUE THREAD

**Issue by gone-skiing** [appium/appium#20679]
It appears that this [change](https://github.com/appium/appium-adb/pull/757) in appium-adb changed (caused regression in) launch behavior for certain apps. 

One example would be https://f-droid.org/packages/com.simplemobiletools.calendar.pro/
`packageAndLaunchActivityFromManifest` only returns the package, but not the activity for this apk. Subsequent adb call to start the app fails with intent matches multiple activities error. The error that gets thrown is below, but I think the root cause is the change in manifest parsing output.

```
An unknown server-side error occurred while processing the command. Original error: Cannot start the '[com.flickr.android](http://com.flickr.android/)' application. Consider checking the driver's troubleshooting documentation. Original error: Error executing adbExec. Original error: 'Command '/opt/android/platform-tools/adb -P 5037 -s emulator-5554 shell am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Command output: Error: Intent matches multiple activities; can't stop: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 }
```

Unit test code (just need to add apk file to fixtures directory):
```
  it.('packageAndLaunchActivityFromManifest should parse package and Activity for simplecal', async function () {
    let {apkPackage, apkActivity} = await adb.packageAndLaunchActivityFromManifest(path.resolve(__dirname, '..', 'fixtures', 'com.simplemobiletools.calendar.pro_240.apk'));
    apkPackage.should.equal('com.simplemobiletools.calendar.pro');
   // This will fail because apkActivity is empty.
    apkActivity.should.equal('.activities.SplashActivity.Orange');
  });
```

**Comment by gone-skiing** [comment]
Hopefully, I got this into the right repo/form. Please let me know if you need any additional details. We ended up pinning appium-adb to `12.4.8` for now.

**Comment by mykola-mokhnach** [comment]
Activity autodetection was never super reliable. The recommended approach would be still to provide the desired name manually.

The reason apkreader module was dropped is because the package itself is not maintained anymore, whereas aapt2 tool, which is used to retrieve package manifest details, is provided natively by Google.

Consider creating an issue to Google regarding the above behaviour (e.g. that aapt2 tool is unable to detect a launchable activity name from given packages while dumping their manifests).

**Comment by gone-skiing** [comment]
@mykola-mokhnach thank you for the quick response. Considering that apkreader is recently deprecated (I think I see releases in 2023) and if there are no critical vulnerabilities in it, is it an option to reinstate that as manfest parsing tool until we can get get `aapt2` support to be on par with it? I am not sure how many out there rely on the behavior that no longer works, but in our small sample size we have at least 2 apps where auto detection used to work with apkreader and does not with aapt2.
I have had limited success creating issues against google tools even in case of obvious defects. Something like this I am not holding my breath...

**Comment by mykola-mokhnach** [comment]
My experience says that Google is usually pretty fast with their bug replies if the issue description is compiled accurately and contains all the necessary details needed for its investigation.

We may consider adding support of alternative apk parsers, that are properly maintained, if you have any concrete proposals. Adding new third-party dependencies is always a complicated process because eventually all the dependency hell and compatibility maintenance burden lies on the Appium team.
