### ISSUE TITLE
bug: `[GET] /session/<sessionId>/window` is not implemented

### ISSUE THREAD

**Issue by christian-bromann** [appium/appium#20710]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I run a native iOS session e.g. with the following capabilities:
```ts
    {
        "appium:app": "com.apple.MobileAddressBook",
        "appium:automationName": "XCUITest",
        "platformName": "iOS"
    }
```

calling `[GET] /session/<sessionId>/window` fails with `Method is not implemented`.

### Expected Behavior

As a framework maintainer of WebdriverIO I would expect Appium to implement all WebDriver commands even in contexts where it doesn't make sense. IMHO Appium should polyfill the responses with a valid response so that framework that rely on the existence of it, can continue to work. I suggest Appium just returns a random window handle, e.g. with the same id as the session id.

### Minimal Reproducible Example

n/a

### Environment

all latest

**Comment by jlipps** [comment]
A few thoughts:

1. This would be something that would need to be brought up per driver, not globally since Appium itself does not implement any of these things. Though of course it would be nice to have a similar policy for all 1st-party drivers.
2. I don't really like the idea of returning garbage data instead of letting the consumer know it's a meaningless request they have made.

@christian-bromann what is the pain point of returning NYI in this case? Shouldn't the fact that the user has made a meaningless request to the server be met with an appropriate response?

If you have strong feelings about this for the WDIO framework, I would probably rather see the opinion implemented there (i.e., catch 501 NYI errors and return `""`, `null`, or `random-string` from within WDIO). It's not the sort of opinion I think would make the most sense for drivers themselves to implement. What if another framework in another language actually _wants_ to know that the method is meaningless/not supported?

**Comment by christian-bromann** [comment]
I believe that if Appium claims to support the WebDriver protocol, it should respond to all commands—even with a placeholder response—so that the command structure remains consistent, even if some commands are irrelevant in the native mobile context. Alternatively, Appium could clarify that it only supports a subset of WebDriver commands, with clear documentation on which ones are not implemented. This way, WebdriverIO could handle the integration more seamlessly, ensuring it 'just works.'

Currently, we're caught in a gray area: framework authors like myself often assume all WebDriver commands are universally available in any Appium session, which isn’t the case. This assumption led us to release a version that inadvertently broke all mobile tests. The issue arose as WebdriverIO began observing the window context to improve support for frame-switching in both WebDriver Classic and Bidi, exposing gaps in command compatibility for mobile tests.

**Comment by mykola-mokhnach** [comment]
As @jlipps mentioned above this functionality should be implemented at the driver level.  There are some maintained by us and much more maintained by third parties where it's up to driver authors to decide how they would like to handle different endpoints. 

P.S. Theoretically we may always return window handle `1` for the native context and make window switching a NOOP, like we did for the `/release` W3C action in UIA2 and XCUITest drivers, I don't foresee any negative impact from doing that.

**Comment by jlipps** [comment]
I guess I wouldn't be opposed to our drivers just sending back a constant `1` for any request to get the window handle, and make switching a noop as @mykola-mokhnach suggests!

**Comment by mykola-mokhnach** [comment]
The change has been published in xcuitest and uia2 drivers

**Comment by christian-bromann** [comment]
Awesome, thanks folks 🙏
