### ISSUE TITLE
Expose path and other attributes that are in page source as attributes on the element

### ISSUE THREAD

**Issue by penguinho** [appium/appium#2457]
Currently elements returned from appium have no attributes. There are several useful properties that we have (especially for Android) that it would be good to fetch from the attributes. (e.g. label, checked, scrollable, especially path)

I came across this when I implemented an locator tester as part of the latest Appium.app and I was able to test to make sure it worked, but unable to tie elements in page source to elements from locators because I did not have access to that path attribute we use when we map xpath to elements in the dom.

**Comment by dpgraham** [comment]
I think we should resurrect this issue. This is a big limitation in Appium Desktop that when we search for elements we can't link them to the page source and get attributes on them.

If we just had the `path` attribute, that would be good enough because then we can locate the element within the source.

**Comment by mykola-mokhnach** [comment]
@dpgraham Is this still relevant? I assume it would be more logical to create a new issue if something is still needed for proper Appium Desktop functionality. The original problem described here has been resolved a long time ago.

**Comment by dpgraham** [comment]
No, we can close it. If I decide to bring it up again I'll make a new issue.
