### ISSUE TITLE
opt-in mode to ignore exceptions with implicit wait

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#2586]
Compare:

``` ruby
driver.manage.timeouts.implicit_wait = 30
first_button.click
```

to

``` ruby
wait(30) { first_button.click }
```

If first_button.click encounters an error, such as null cannot be tapped, then in the first example the test code fails. In the second example, the test code succeeds because it ignores the error and keeps trying to click the button.

Wrapping every line of code in waits is a mess. It'd be nice if there was an opt-in way to tell the server to keep trying to find elements even if there's a problem. Then only if the element isn't found after the implicit wait has expired, return an error.

**Comment by Simon-Kaz** [comment]
:+1:

**Comment by jlipps** [comment]
going to close this since i don't think we are going to extend the semantics of implicit wait to include retrying arbitrary actions. just because an action generates an exception doesn't mean the action didn't happen or that there were no other side effects. silently continuing to try things for a certain amount of time seems dangerous.

better to try and make appium's internal systems stable enough that exceptions aren't encountered. or if we discover a particular exception cropping up all over the place, we could have a retry internally that is not visible to the user.
