### ISSUE TITLE
installApp command does not upgrade application on device

### ISSUE THREAD

**Issue by vicusbass** [appium/appium#3377]
Hi,

I am trying to test an application upgrade (install a new version while the old one still exists on the device). The scenario has the following steps:
- install app v1
- do some action in app
- install app v2 without uninstall v1
- validate that the actions effect is still present in the new version

I tried this with both noReset values. When set to false, the old app is uninstalled, so no real upgrade. When set to true, the new app is not installed. I also tried using driver.installApp("/app/test.apk"), but this does not work either.

Any ideas?

**Comment by lvconley** [comment]
I'm using Appium 1.4.8 (Draco) to build an upgrade test for our Android app. The test case calls for the automation to install the old app, then upgrade it, and then to verify that the upgraded app sends an analytics report specifying that it has been upgraded. 

The flow for this test case essentially goes like this:

1) Use Appium to install and then launch the old app on an emulator
2) Use Appium to close (background) the app (oddly, backgrounding the app ONLY works when the --full-reset flag is set, which, of course, makes no sense...)
3) Use the Appium androidDriver.installApp(appPath) method to install the newer app version and then launch the app so it can make its analytics report.

Trouble is, installApp() will ONLY work when the --full-reset flag is used on the Appium server, but this wipes-out the previous install, so the newer app never knows that it's been installed as an upgrade, thus negating the goal of the test case.

So, I've tried to get around this by splitting the test case into two separate runs. The first test case (part 1) has a shell script start a tcpdump capture so I can get my analytics, and then has Appium install and launch the old app on an AVD. Then I kill the Appium driver and server and close the emulator and pass the test--while keeping my tcpdump capture going. Then on the second test case (part 2), complete with new capabilities pointing to the newer app version, I try to launch the newer app on the same emulator, but this only works when the --full-reset flag is used on the Appium server, which again, prevents the newer app from ever knowing that the old app had been installed on the emulator and thus it sends no upgrade analytic.

When the --full-reset flag is used, any version of the app currently on the AVD at launch time gets uninstalled before the new build can be installed. So, *no upgrade* takes place.

And if I use the --no-reset flag on the Appium server (node), then the new app installation CANNOT be completed. When the --no-reset flag is set, the newer app will NOT be installed over the currently installed, older version of the app. Instead, Appium just essentially aborts the test run...

So, Appium is brilliantly effective at forcing me into not using it for my upgrade test because it completely blocks me from upgrading any app on an AVD.

Has anyone found a way around this blockage by Appium? This obstacle is actually forcing us to explore other, more capable, automation solutions for what we need to do on Android.

Any feedback on workarounds would be most appreciated!

Thanks,

Larry

**Comment by imsardine** [comment]
IMHO, the approach of "separate sessions/runs" may not work well with cloud-based solutions. To make sure all test cases are running on the same device, multiple test cases should be run in a session.

For the decision of "always including -r", I think users can explicitly remove the app (`removeApp()`) prior to calling `installApp()` if they do want to have a FRESH installation.

**Comment by priyankshah217** [comment]
@jlipps @bootstraponline , any workarounds on this issue. let me elaborate my case here.

The scenario which i want to perform is related to up gradation of apk file. The steps which i performed are below.

1. Install and Launch application using Appium (e.g : sample-1.apk)
2. Perform certain actions
3. Upgrade application (e.g: sample-2.apk, using driver.installApp() )

But issue i am facing is, while upgrading application appium server logs says application is unzip and installed successfully. Which actually did not upgrade (I checked it manually by verifying application version).

Also as per my findings, the app which were installed using appium, is not able to upgrade manually (was getting error. so now question arise whether appium re-sign application while installing (I m running automation in appium mode?) 
 
pkg: /data/local/tmp/en-android-1.apk
Failure [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]

Thanks,
Priyank Shah

**Comment by alangithubtrader** [comment]
@jlipps @bootstraponline 

Is this change only for Android? What about iOS?

And if we always include '-r' as a param, will installation still be successful if there's no existing app to begin with?

Thanks.

Best Regards,
Alan

**Comment by bootstraponline** [comment]
It's only for Android. Yes -r will still be successful if there's no existing app.

For iOS, not sure. That's a different issue (this one is only for Android).

**Comment by alangithubtrader** [comment]
@bootstraponline 
Thanks.

For reference, this is what works for me for both iOS and Android. 

Appium version 1.4.13
.Net Client 1.4.0.3
Xcode 7.0.1
iOS 9.0

For Android, in order for upgrade to work I had to remove app before installing, but for iOS i didn't have to.

            driver.CloseApp();

            switch (testPlatform)
            {
                case Android:
                    driver.RemoveApp(<appId>);
                    break;
            }

            driver.InstallApp(AppPath);

            driver.LaunchApp();

**Comment by shay777** [comment]
sorry for the late comment but any solution for that issue?
is that possible to simulate an upgrade using appium?
thanks

**Comment by shubhansha21** [comment]
@bootstraponline please let me know any updates or an eta of when this will be fixed.
Thanks

**Comment by bootstraponline** [comment]
I don't really work on appium anymore so this probably won't get fixed unless someone submits a pull request.

**Comment by Fanch-** [comment]
Is it still impossible to do an adb install -r using appium clients? 

I mean there isn't a capability to specify it, like AndroidMobileCapabilityType.UPGRADE to set to true to install with the -r flag.

Because using NO_RESET to true, it will just launch the previous apk with the data -because both package names are identic-, though the apk are differents.

**Comment by shubhansha21** [comment]
@jlipps is there a solution for this issue? is it added to backlog?

**Comment by jlipps** [comment]
@shubhansha21 @Fanch- does it work to use the `driver.installApp` command mid-test, in conjunction with noReset?

**Comment by Fanch-** [comment]
- Apk previously installed : lbc-delivery-V3.0.1.apk
- No_Reset = true
- driver.installApp("lbc-delivery-V3.0.0.apk") during test

```shell```
[HTTP] --> POST /wd/hub/session/63041c59-86de-4d94-857c-97b621c9cfeb/appium/device/install_app {"appPath":"/path/Documents/apk/lbc-delivery-V3.0.0.apk"}
[MJSONWP] Calling AppiumDriver.installApp() with args: ["/path/Docum...
[ADB] Checking whether aapt is present
[ADB] Using aapt from /path/Documents/outils/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/aapt
[ADB] Extracting package and launch activity from manifest
[debug] [ADB] badging package: fr.leboncoin.delivery
[debug] [ADB] badging act: fr.leboncoin.ui.activities.SwitcherActivity
[AndroidDriver] Remote apk path is /data/local/tmp/c3bb15467a9401181caebc8e436919d3.apk
[debug] [ADB] Getting connected devices...
[debug] [ADB] 12 device(s) connected
[debug] [ADB] Running /path/Documents/outils/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb with args: ["-P",5037,"-s","010961bce4e34587","shell","ls","/data/local/tmp/c3bb15467a9401181caebc8e436919d3.apk"]
[debug] [AndroidDriver] Checking if app is installed
[debug] [ADB] Getting install status for fr.leboncoin.delivery
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[debug] [ADB] 12 device(s) connected
[debug] [ADB] Running /path/Documents/outils/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb with args: ["-P",5037,"-s","010961bce4e34587","shell","pm","list","packages","-3","fr.leboncoin.delivery"]
[debug] [ADB] App is  installed
[MJSONWP] Responding to client with driver.installApp() result: null
[HTTP] <-- POST /wd/hub/session/63041c59-86de-4d94-857c-97b621c9cfeb/appium/device/install_app 200 1255 ms - 76 
```

I guess "Extracting package and launch activity from manifest" isn't sufficient to detect apk version differences (package/activity) : they are the same for each version, the app installation detection might be limited.

What about add another check between old apk and new apk ? : 

> adb shell dumpsys package my.package | grep versionName or timeStamp

**Comment by jlipps** [comment]
ok, sounds like we still need to do some work to support this case.

**Comment by vm31** [comment]
Any further updated on this solution

**Comment by shaynl** [comment]
Is there any solution yet for testing app upgrade on IOS and Android?

**Comment by mykola-mokhnach** [comment]
@shaynl Yes, there is. But you need to call adb/xcrun (works with iOS simulator only) commands manually.
For example, in order to test Android upgrade you need to:

1. Start the driver with _noReset_ capability set to true. You need to add _skipUninstall_ option as well, if you use Selendroid as main driver. Point _app_ capability to the old application build.
2. Quit the driver
3. Upgrade installed apk by executing 

```
adb install -r "<new_build_path>"
```

4. Start the driver with the same capabilities as for the last time.

Also, for iOS our solution works on Simulator only:

1. Start the driver with _noReset_ capability set to true. Point _app_ capability to the old application build.
2. Quit the driver
3. Upgrade installed app by executing 

```
xcrun simctl install booted <new_app_path>
```

4. Start the driver with the same capabilities as for the last time.

**Comment by dustinaltermann** [comment]
I don't really know what happened here to be honest: Multiple people report a problem that prevents the driver from being properly used in CI, which is sort of a big deal considering we are dealing with automation here, so you also want to automatically run the tests on the latest app version without losing all the apps data and system permissions (latter of which you can't set using the driver). -> An appium member comes in, recognized the problem and indicated that it should be fixed. -> Then nothing for 2 years somehow and in the end we wind up with an awkward workaround that doesn't even work in all cases (iOS real device).

Why on earth is this simple flag so difficult to implement into appium?

**Comment by jlipps** [comment]
probably to have a general solution we should add an `upgradeApp` command that stops, installs, and starts the app. the question is whether we can do this outside of our shutdown/startup flow. it looks like unfortunately this might just be a special case of the reset command, with all its difficulties.

**Comment by monsam** [comment]
I second with dustinaltermann, why adding a simple flag is taking so long, I am trying to run automation in CI environment I can't seem to reinstall my app keeping app data intact.

I have tried driver.install_app("release.apk") but it doesn't seem to do anything if the old app is already installed.

[MJSONWP] Calling AppiumDriver.installApp() with args: ["/release.apk","79c85d6f-6e53-417c-b229-70017f198739"]
[BaseDriver] Using local app 'release.apk'
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/xxx/android-sdks/build-tools/19.1.0/aapt
[ADB] Extracting package and launch activity from manifest
[ADB] badging package: com.xxxx.app
[ADB] badging act: com.xxx.MainActivity
[AndroidDriver] Remote apk path is /data/local/tmp/7e26d01fa0e205987c7693242e191a90.apk
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/xxxx/android-sdks/platform-tools/adb' with args: ["-P",5037,"-s","192.168.1.120:5555","shell","ls","/data/local/tmp/7e26d01fa0e205987c7693242e191a90.apk"]
[ADB] Running '/Users/xxx/android-sdks/platform-tools/adb' with args: ["-P",5037,"-s","192.168.1.120:5555","shell","ls","/data/local/tmp/7e26d01fa0e205987c7693242e191a90.apk"]
[AndroidDriver] Checking if app is installed
[ADB] Getting install status for com.xxxx.app
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[ADB] Running '/Users/xxxx/android-sdks/platform-tools/adb' with args: ["-P",5037,"-s","192.168.1.120:5555","shell","pm","list","packages","com.xxx.app"]
[ADB] App is installed
[MJSONWP] Responding to client with driver.installApp() result: null
[HTTP] <-- POST /wd/hub/session/79c85d6f-6e53-417c-b229-70017f198739/appium/device/install_app 200 3226 ms - 76

**Comment by darkmanno6** [comment]
please support this feature quckly, thanks

**Comment by sumanthmattapalli** [comment]
Did anyone found a solution for this issues? If so please can you share here.

Thanks,
Sumanth.

**Comment by mykola-mokhnach** [comment]
This command now accepts additional options, so the upgrade is now possible
