### ISSUE TITLE
add option for sending keys via adb, it might be faster

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#3789]
See comments in https://github.com/appium/appium/issues/3543#issuecomment-58362104

**Comment by jlipps** [comment]
i think we already have sendKeyStrategy as a cap for iOS, this could be extended

**Comment by jediboy** [comment]
Any updates on this? Using Appium 1.5.3 and it's still super slow. Still seeing the following in the log for every sendKeys() too:
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Could not check for hint text because the element is not focused!
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Clearing text not successful. Attempting to clear by selecting all and deleting.

**Comment by imurchie** [comment]
You can set the value through adb.

The endpoint is `/wd/hub/session/:sessionId/appium/element/:elementId/value`. In the Python client it is hit by the `driver. set_value` method. Other clients will have something similar.

**Comment by jediboy** [comment]
Thanks @imurchie .. I did try to hit the endpoint directly but the server still attempts to clear the text multiple ways and does something with the hint text which is what's causing the slowness. Is there any way to force it to not do this extra clearing?

**Comment by imurchie** [comment]
Can you provide more of your log? That does not look right.

**Comment by jediboy** [comment]
This is the log with a findElement(), followed by a click(), and then a sendKeys()

[appium.txt](https://github.com/appium/appium/files/488388/appium.txt)

**Comment by imurchie** [comment]
That is not the endpoint.

```
/wd/hub/session/:sessionId/element/:elementId/value
```

vs 

```
/wd/hub/session/:sessionId/appium/element/:elementId/value
```
