### ISSUE TITLE
Using built-in ideviceinstaller fails

### ISSUE THREAD

**Issue by danail-branekov** [appium/appium#3877]
Hi,

As far as I can see, Appium bundles ideviceinstaller for installing application IPAs on IOS devices. When I run Appium I get the following error when the application is about to be installed:
```
info: [debug] Installing ipa found at /Users/danail/EclipseLuna/Workspace/iostest-ipa/src/test/resources/real-device/expense-tracker-ios.ipa
info: [debug] Creating iDevice object with udid 47f06b93c007a24a015bc8dbf05e8dcaf0f44d03
info: [debug] Couldn't find ideviceinstaller, trying built-in at /Users/danail/git/appium/build/libimobiledevice-macosx/ideviceinstaller
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Command failed: dyld: Library not loaded: @executable_path/../lib/libimobiledevice.3.dylib
  Referenced from: /Users/danail/git/appium/build/libimobiledevice-macosx/ideviceinstaller
  Reason: image not found

info: [debug] Error: Command failed: dyld: Library not loaded: @executable_path/../lib/libimobiledevice.3.dylib
  Referenced from: /Users/danail/git/appium/build/libimobiledevice-macosx/ideviceinstaller
  Reason: image not found

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

When I run the built-in ideviceinstaller from the command line I get the same error:
```
~/git/appium/build/libimobiledevice-macosx$ ./ideviceinstaller 
dyld: Library not loaded: @executable_path/../lib/libimobiledevice.3.dylib
  Referenced from: /Users/danail/git/appium/build/libimobiledevice-macosx/./ideviceinstaller
  Reason: image not found
Trace/BPT trap: 5
```
If I installed ideviceinstaller as described at http://technotesonthego.blogspot.ru/2013/10/install-libimobiledevice-on-mac-os-x.html things are working great.

I guess that something is not configured on my end and this is the reason the built-in ideviceinstaller cannot be loaded. Are there any specific settings (e.g. setting some environment variables) I need to do prior running the test?

Thanks!

**Comment by curtissiemens** [comment]
Appium uses fruitstrap in version 1.3.3 to install *.ipa apps.
In 1.3.4 Appium changed and started using ideviceinstaller to install *.api apps & this breaks because ideviceinstaller has incorrect link to libimobiledevice.3.dylib
Note: 1.3.4 still uses fruitstrap to install *.app apps (and therefore works).

The libimobiledevice.3.dylib exists right besides ideviceinstaller so when it loads and tries to find it under @executable_path/../lib/libimobiledevice.3.dylib - that looks quite wrong:
./parts/npm/.npm/appium/1.3.4/package/build/libimobiledevice-macosx/ideviceinstaller
./parts/npm/.npm/appium/1.3.4/package/build/libimobiledevice-macosx/libimobiledevice.3.dylib

**Comment by paymand** [comment]
We don't use ``fruitstrap`` anymore and are using ``ideviceinstaller`` everywhere. See https://github.com/appium/appium/pull/4790.
Please make sure that you have the latest version of ``ideviceinstaller`` installed.
