### ISSUE TITLE
Multiple session support

### ISSUE THREAD

**Issue by sebv** [appium/appium#3950]
There is going to be some serious hardware requirement, but we should be able to handle it in the software.

In Android that should be possible. In ios, we will need to use some predefined users for the Instruments stuff.

Putting it in 3.0 Milestone.

**Comment by luonglne** [comment]
Hi Guys, does this mean that we cannot run the Selenium Grid with multiple Appium nodes for iOS?  Here is our current setup (everything on one server):

Server A - Running the Selenium Grid
     java -jar selenium-server-standalone-2.44.0.jar -role hub

Server A - Running Appium Node 1 
    appium --nodeconfig /Users/luonghuynh/workspace/iphone5.json --port 7676 --udid <udid of iphone5> --app /Users/luonghuynh/workspace/TEST.app --full-reset

Server B - Running Appium Node 2
   appium --nodeconfig /Users/luonghuynh/workspace/iphone4.json --port 7678 --udid <udid of iphone4> --app /Users/luonghuynh/workspace/TEST.app --full-reset

JSON file - the only difference between the two files are the browserName and deviceName
{
 "capabilities":
     [
       {
         "browserName": "iphone4",
         "deviceName": "TM Lucero",
         "version":"8.1.3",
         "maxInstances": 1,
         "platform":"MAC"
       }
     ],
 "configuration":
 {
   "cleanUpCycle":2000,
   "timeout":30000,
   "maxSession": 1,
   "register": true,
   "registerCycle": 5000,
   "hubPort": 4444,
   "hubHost": "localhost"
 }
}

Kicking off the test for Node 1:
./gradlew testFeatures -Ptags="@SignOutTests" -Dtarget.type=grid -Dappium.host=localhost -Dappium.port=7676 -Dgrid.capability.browserName=iphone5 -Dgrid.capability.deviceName='TM Sinestro' -Dgrid.capability.platformName=ios

Kicking off the test for Node 2:
./gradlew testFeatures -Ptags="@SignInTests" -Dtarget.type=grid -Dappium.host=localhost -Dappium.port=7678 -Dgrid.capability.browserName=iphone4 -Dgrid.capability.deviceName='TM Lucero' -Dgrid.capability.platformName=ios

So we kicked off the test for Node 1 first, it was running fine until we kicked off the test for Node 2.  Then as soon as the new instance of IOSDriver was created for Node 2, Node 1's Appium session got stopped and restarted.  Since I had --full-reset, so Node 1 uninstalled the TEST.app while Node 2 did the installation.  Then Node 1 did the installation, and at this point the Appium session ids for both Node 1 and Node 2 got lost or tangled up.  Then none of the tests could be run from that point onward.  Eventually Node 2 bailed out and Node 1 was hanging.  

Please let me know what you think.  Is this the same issue as mentioned above?

**Comment by SrinivasanTarget** [comment]
@jlipps @imurchie Does this exists in current Appium architecture [1.5] ? I think i heard this in "10 thing that we don't know about Appium" from @penguinho or its i interpreted this wrongly. Please clarify is it possible to create multiple session of server from single node instance.

**Comment by saikrishna321** [comment]
+1

**Comment by imurchie** [comment]
It is theoretically possible. I don't think we've tested it and made sure it works fully.

**Comment by SrinivasanTarget** [comment]
Is there a way to test this @imurchie? So far we are able to execute tests parallely on both android and iOS seamlessly without any instruments issues on Appium 1.5 but with many server instances on diff ports.

FYI - https://github.com/saikrishna321/AppiumTestDistribution

Looking forward to experiment this on single server instance.

**Comment by imurchie** [comment]
You can test by trying to open multiple sessions on the same server. The server technically keeps track of sessions, and handles drivers for each. But I'm not sure the separation is complete, and there is nothing that will end up being shared.

**Comment by jlipps** [comment]
I'm not sure the code is quite ready for this. What remains to be done is for each specific driver to know how to allot resources to new sessions while other sessions are running (for instance making sure two android tests don't try to use the same device). The logic for this shouldn't be too hard but it's probably delicate.

**Comment by SrinivasanTarget** [comment]
Didn't know how to create multiple sessions on same server now. Looking forward to get this completely in our near future releases. And ready to support for any testing activities related to this.

**Comment by jlipps** [comment]
this is now working, there will need to be minor adjustments for usability in the future of course.

**Comment by strong-code** [comment]
@jlipps is there any existing documentation available for people willing to test out beta channel releases? I (as well as many others) are very keen to get our hands on this feature. Thanks in advance!

**Comment by mykola-mokhnach** [comment]
@strong-code We have a special channel in Appium Slack for people willing to test beta features and share their feedback there. Would you like to join?

**Comment by strong-code** [comment]
@mykola-mokhnach Yes, please. If I need an email to be invited, please use the one listed in my profile. Thank you!

**Comment by saikrishna321** [comment]
@strong-code Invite sent ...

**Comment by welnanick** [comment]
@mykola-mokhnach @saikrishna321 I would also love to beta test this feature. Being able to run multiple devices in parallel would be great for what I am trying to do.
