### ISSUE TITLE
[1.3.2-beta2] spawning instruments failed, Instruments Usage Error : Specified target process is invalid: 

### ISSUE THREAD

**Issue by liqing380** [appium/appium#4101]
xcode:6.0.1 ( or Xcode6.1 ,  get the same error)
ipad device‘s ios :7.1
appium:1.3.2-beta2

##### i upgrade appium from  1.3.0-beta1 to 1.3.2-beta2, then, appium can not start ,it  spawning instruments failed,the log is: #####
```java
info: [debug] App is not installed. Will try to install the app.
info: [debug] Installing ipa found at /Users/coremail/Downloads/TestCoremailPushApp9.57.ipa
info: [debug] Creating iDevice object with udid 7cb45aefaaa0252295c98ebb59a66dee8d6103b9
info: [debug] Nothing found on device, going ahead and installing.
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 7cb45aefaaa0252295c98ebb59a66dee8d6103b9
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 7cb45aefaaa0252295c98ebb59a66dee8d6103b9 cn.coremail.CoremailPush -e UIASCRIPT "/Users/coremail/Library/Application Support/appium/bootstrap/bootstrap-c2aa93adc98b03d6.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2014-11-19 16:05:49.824 instruments[33139:5503] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: cn.coremail.CoremailPush
instruments, version 6.0 (56156)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]
info: [debug] [INSTSERVER] Instruments exited with code 255
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 7cb45aefaaa0252295c98ebb59a66dee8d6103b9
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 7cb45aefaaa0252295c98ebb59a66dee8d6103b9 cn.coremail.CoremailPush -e UIASCRIPT "/Users/coremail/Library/Application Support/appium/bootstrap/bootstrap-c2aa93adc98b03d6.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2014-11-19 16:05:55.769 instruments[33142:1307] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: cn.coremail.CoremailPush
instruments, version 6.0 (56156)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]
info: [debug] [INSTSERVER] Instruments exited with code 255
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #2
```
##### and i try the instrument command on it’s own,it failed: #####
```
coremailMacMini:~ coremail$ /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 7cb45aefaaa0252295c98ebb59a66dee8d6103b9 cn.coremail.CoremailPush -e UIASCRIPT "/Users/coremail/Library/Application Support/appium/bootstrap/bootstrap-c2aa93adc98b03d6.js" -e UIARESULTSPATH /tmp/appium-instruments
2014-11-19 16:06:15.160 instruments[33147:2207] WebKit Threading Violation - initial use of WebKit from a secondary thread.
Instruments Usage Error : Specified target process is invalid: cn.coremail.CoremailPush
instruments, version 6.0 (56156)
```

**Comment by ankitbhatnagar4u** [comment]
Similar error ... Using IPad 2 with IOS 7.1.1 And Appium 1.3.1. Trying to install my app but it fails since fruitstrap is being crashed. The desired capabilities and logs are shared below .Please help to resolve:
 File appDir = new File(classpathRoot.getAbsolutePath());
        File app = new File(appDir, Config.appName);      
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName","iPad 2");
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "7.1.1");  
      capabilities.setCapability("app", app.getAbsolutePath());
       capabilities.setCapability("appPackage", "com.adobe.livecycle.Capture");
        capabilities.setCapability("UDID", "ac5f348e57c8db28c5c0f4763ee32182bf9d0089");
        capabilities.setCapability("device", "Stl-iPad");
        capabilities.setCapability("ipa", "MWSForIPad.ipa");
        capabilities.setCapability(CapabilityType.PLATFORM, "MAC");
        driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	settings = new SettingsScreen(driver);
	login = new LoginScreen(driver);
	login.Login(Config.username, Config.password, Config.serverURL);


and Appium logs shows : 

info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/ankit/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/ankit/Library/Application Support/appium/bootstrap/bootstrap-60f23230385b0cfa.js

info: [debug] Reusing dynamic bootstrap: /Users/ankit/Library/Application Support/appium/bootstrap/bootstrap-60f23230385b0cfa.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.3.2","iOSSDKVersion":"8.3","deviceName":"iPad 2","platformVersion":"7.1.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad 2 (7.1.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons

info: [debug] On a real device; cannot clean device state

info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"56e9768c-01ab-4866-98bb-dabb866188d7"}

info: <-- GET /wd/hub/status 200 1.169 ms - 178 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"56e9768c-01ab-4866-98bb-dabb866188d7"}

info: [debug] Not pre-launching simulator

info: [debug] Creating iDevice object with udid ac5f348e57c8db28c5c0f4763ee32182bf9d0089

info: [debug] Checking app install status using: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id ac5f348e57c8db28c5c0f4763ee32182bf9d0089 --bundle com.adobe.livecycle.Capture

info: [debug] App is not installed. Will try to install the app.

info: [debug] Installing ipa found at /Users/ankit/Downloads/MWS Dev Automation/MWS - Latest/MWS-master/MWSForIPad.ipa
info: [debug] Creating iDevice object with udid ac5f348e57c8db28c5c0f4763ee32182bf9d0089

info: [debug] Nothing found on device, going ahead and installing.

info: [debug] Starting command proxy.

info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID ac5f348e57c8db28c5c0f4763ee32182bf9d0089
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w ac5f348e57c8db28c5c0f4763ee32182bf9d0089 com.adobe.livecycle.Capture -e UIASCRIPT "/Users/ankit/Library/Application Support/appium/bootstrap/bootstrap-60f23230385b0cfa.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-07-07 14:21:45.675 instruments[35553:5200137] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:45 Stl-iPad syncdefaultsd[225] <Notice>: (Note ) SYDAlwaysOnAccount: no account (null)

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:45 Stl-iPad syncdefaultsd[225] <Notice>: (Note ) SYDAccount: no account

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:45 Stl-iPad syncdefaultsd[225] <Notice>: (Note ) SYDPIMAccount: no account (null)

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:46 Stl-iPad DTMobileIS[226] <Warning>: Could not create service named com.apple.instruments.server.services.launchdaemon

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:46 Stl-iPad DTMobileIS[226] <Warning>: Could not create service named com.apple.instruments.server.services.device.xpccontrol

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:46 Stl-iPad DTMobileIS[226] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
info: [IOS_SYSLOG_ROW ] Jul  7 14:21:46 Stl-iPad DTMobileIS[226] <Warning>: Could not create service named com.apple.dt.Xcode.WatchProcessControl
info: [IOS_SYSLOG_ROW ] Jul  7 14:21:46 Stl-iPad DTMobileIS[226] <Warning>: Could not create service named com.apple.instruments.server.services.device.applictionListing

info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: com.adobe.livecycle.Capture
instruments, version 6.3.2 (57082)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]

info: [debug] [INSTSERVER] Instruments exited with code 255

info: [debug] Killall instruments

info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator

info: Launching instruments

info: [debug] Attempting to run app on real device with UDID ac5f348e57c8db28c5c0f4763ee32182bf9d0089

info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w ac5f348e57c8db28c5c0f4763ee32182bf9d0089 com.adobe.livecycle.Capture -e UIASCRIPT "/Users/ankit/Library/Application Support/appium/bootstrap/bootstrap-60f23230385b0cfa.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-07-07 14:21:53.479 instruments[35558:5201539] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:53 Stl-iPad DTMobileIS[228] <Warning>: Could not create service named com.apple.instruments.server.services.launchdaemon

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:53 Stl-iPad DTMobileIS[228] <Warning>: Could not create service named com.apple.instruments.server.services.device.xpccontrol

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:53 Stl-iPad DTMobileIS[228] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
info: [IOS_SYSLOG_ROW ] Jul  7 14:21:53 Stl-iPad DTMobileIS[228] <Warning>: Could not create service named com.apple.instruments.server.services.device.applictionListing

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:53 Stl-iPad DTMobileIS[228] <Warning>: Could not create service named com.apple.dt.Xcode.WatchProcessControl

info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: com.adobe.livecycle.Capture
instruments, version 6.3.2 (57082)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]

info: [debug] [INSTSERVER] Instruments exited with code 255

info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #2
info: [debug] Killall iOS Simulator

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:55 Stl-iPad mstreamd[223] <Notice>: (Note ) mstreamd: Not monitoring for external power.

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:55 Stl-iPad mstreamd[223] <Notice>: (Note ) PS: Media stream daemon stopping.

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:55 Stl-iPad mstreamd[223] <Notice>: (Note ) AS: <MSIOSAlbumSharingDaemon: 0x146754a0>: Shared Streams daemon has shut down.
info: [IOS_SYSLOG_ROW ] Jul  7 14:21:55 Stl-iPad mstreamd[223] <Notice>: (Warn ) mstreamd: mstreamd shutting down.

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:55 Stl-iPad mstreamd[229] <Notice>: (Note ) mstreamd: mstreamd starting up.

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:55 Stl-iPad mstreamd[229] <Notice>: (Note ) PS: Media stream daemon starting...

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:57 Stl-iPad lockdownd[52] <Notice>: 002c1000 _select_socket: receive secure message timeout!

info: Launching instruments

info: [debug] Attempting to run app on real device with UDID ac5f348e57c8db28c5c0f4763ee32182bf9d0089
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w ac5f348e57c8db28c5c0f4763ee32182bf9d0089 com.adobe.livecycle.Capture -e UIASCRIPT "/Users/ankit/Library/Application Support/appium/bootstrap/bootstrap-60f23230385b0cfa.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:59 Stl-iPad DTMobileIS[231] <Warning>: Could not create service named com.apple.instruments.server.services.launchdaemon

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:59 Stl-iPad DTMobileIS[231] <Warning>: Could not create service named com.apple.instruments.server.services.device.xpccontrol

info: [IOS_SYSLOG_ROW ] Jul  7 14:21:59 Stl-iPad DTMobileIS[231] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
info: [IOS_SYSLOG_ROW ] Jul  7 14:21:59 Stl-iPad DTMobileIS[231] <Warning>: Could not create service named com.apple.instruments.server.services.device.applictionListing

info: [debug] [INST STDERR] 2015-07-07 14:21:59.142 instruments[35562:5202581] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [IOS_SYSLOG_ROW ] Jul  7 14:21:59 Stl-iPad DTMobileIS[231] <Warning>: Could not create service named com.apple.dt.Xcode.WatchProcessControl

info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: com.adobe.livecycle.Capture
instruments, version 6.3.2 (57082)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]

info: [debug] [INSTSERVER] Instruments exited with code 255
info: [debug] Killall instruments

info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #3
info: [debug] Killall iOS Simulator

info: Launching instruments

info: [debug] Attempting to run app on real device with UDID ac5f348e57c8db28c5c0f4763ee32182bf9d0089
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w ac5f348e57c8db28c5c0f4763ee32182bf9d0089 com.adobe.livecycle.Capture -e UIASCRIPT "/Users/ankit/Library/Application Support/appium/bootstrap/bootstrap-60f23230385b0cfa.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-07-07 14:22:04.695 instruments[35567:5203454] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad DTMobileIS[233] <Warning>: Could not create service named com.apple.instruments.server.services.launchdaemon

info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad DTMobileIS[233] <Warning>: Could not create service named com.apple.instruments.server.services.device.xpccontrol

info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad DTMobileIS[233] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad DTMobileIS[233] <Warning>: Could not create service named com.apple.instruments.server.services.device.applictionListing
info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad DTMobileIS[233] <Warning>: Could not create service named com.apple.dt.Xcode.WatchProcessControl

info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad wifid[15] <Notice>: WiFi:[457951925.124449]: Low Accuracy Location Monitoring Timer Expired

info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad wifid[15] <Notice>: WiFi:[457951925.124918]: Failed to get location information; setting locale to default locale
info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad wifid[15] <Notice>: WiFi:[457951925.125321]: new locale:  , locale:
info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad wifid[15] <Notice>: WiFi:[457951925.125987]: Stopping Low Accuracy Location Monitoring
info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad wifid[15] <Notice>: WiFi:[457951925.126488]: Location Monitoring stopped

info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad wifid[15] <Notice>: WiFi:[457951925.126837]: WiFiManagerCoreLocationStopLocationUpdates: stopping location updates...
info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad wifid[15] <Notice>: WiFi:[457951925.127312]: Stopping Low Accuracy Location Monitoring
info: [IOS_SYSLOG_ROW ] Jul  7 14:22:05 Stl-iPad wifid[15] <Notice>: WiFi:[457951925.127697]: CLMonitoring is already stopped

info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: com.adobe.livecycle.Capture
instruments, version 6.3.2 (57082)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]
info: [debug] [INSTSERVER] Instruments exited with code 255
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons

info: [debug] On a real device; cannot clean device state
info: [debug] Cleaning up appium session
info: [debug] Error: Instruments crashed on startup
    at Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:387:31)
    at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:308:12)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)

error: Failed to start an Appium session, err was: Error: Instruments crashed on startup

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}
info: <-- POST /wd/hub/session 500 28194.543 ms - 182

**Comment by hnallani** [comment]
I am at appium 1.4.13; Xcode: 7.0.1; iOS 8.3 with iPhone 5 real device and same issue as +liqing380 when I provide the "app" as .ipa.....it doesn't install and getting same error. When "app" is provided as .app then application installs and launches........However, this is not an issue in simulator if .ipa is provided.

**Comment by nieschumi** [comment]
I'm at appium 1.4.13, Xcode 7.3, IOS9.3 with iPhone6 plus physical device, I'm getting the same error as above.

**Comment by nieschumi** [comment]
We resolved the issue by reset the iPhone device. 
We notice we can choose target from Automation instrument for some of our test devices, so we reset the phone that's not working, after reset we are able to run automation on it.

**Comment by SrinivasanTarget** [comment]
We are glad that it worked out for you.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by uzmasyed00** [comment]
How do we reset the device?

**Comment by nieschumi** [comment]
@uzmasyed00  Reset from the phone settings

**Comment by SrinivasanTarget** [comment]
@triager please close
