### ISSUE TITLE
Restart UIAutomator to find missing elements

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#4200]
Read the end of [this issue](https://github.com/appium/java-client/issues/74#issuecomment-61511540).

According to @ranbena restarting UIAutomator works %100 of the time to fix an issue where sometimes elements aren't returned by getPAgeSource(). It's definitely a bug in Android UIAutomator, but it seems like we can work around it by restarting the UIAutomator process.

Right now, restarting the process causes the Appium session to fail. What should we consider for fixing these missing elements?

Options I've thought of so far:
1) Make a "restart UIAutomator" function available to clients.
2) Restart UIAutomator whenever an element isn't found (or add it to some retry logic)
3) Create a "Setting" (from our settings api) which when enabled restarts UIAutomator when elements aren't found, and doesn't restart UIAutomator when disabled.

Any more ideas?
@jlipps @bootstraponline @sebv @imurchie @0x1mason @JessicaSachs

**Comment by 0x1mason** [comment]
@ranbena @mseneby @GeorgiMitkovHristov 
I believe I've overcome the issue.  Can you try installing AppiumBootstrap.jar in appium/build/android_bootstrap? You can download it from here: http://goo.gl/8CbQBr.  You'll probably want to backup the original first.

**Comment by 0x1mason** [comment]
Please let me know if this fixes the behavior you're seeing.

**Comment by GeorgiMitkovHristov** [comment]
Great job !

I can confirm that things are running just fine now with this version of AppiumBootstrap.jar.

Do you happen to have commit this change already ?

**Comment by 0x1mason** [comment]
@GeorgiMitkovHristov Woohoo!  PR is up [#4365](https://github.com/appium/appium/pull/4365).

**Comment by 0x1mason** [comment]
@GeorgiMitkovHristov Changes merged.

**Comment by mseneby** [comment]
@ranbena @0x1mason @GeorgiMitkovHristov 
Hi,
Thank you everybody for working on this critical issue. I applied the  AppiumBootstrap.jar in node_modules/appium/build/android_bootstrap/ and did not see the issue for a while. However, in last couple days we launched a new test flow that the issue got very visible again despite it is intermittent. 
I uploaded the scenario in youtube here:
http://youtu.be/f5IrG2WTm-g
 I can provide appium logs if needed , which has appium find commands for the particular id, "com.paypal.android.p2pmobile:id/web", where its content visible by eye on the screen, but test run could not find the id and failed. The test case was polling for id with no luck for about 20 sec, starting from second 40 to 60 in the video that is for verifying license agreement page in the Paypal app, which is publicly available . The issue is happening randomly, and we did not notice until we automate the flow.
I assume I don't have to change any setting after patching(overwriting) the jar file.

A snapshot from the logs is as the following
2015-01-23 22:06:18:536 - info: [debug] Waiting up to 0ms for condition
2015-01-23 22:06:18:536 - info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"com.paypal.android.p2pmobile:id/web","context":"","multiple":true}]
2015-01-23 22:06:18:539 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.paypal.android.p2pmobile:id/web","context":"","multiple":true}}
2015-01-23 22:06:18:539 - info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
2015-01-23 22:06:18:539 - info: [debug] [BOOTSTRAP] [debug] Got command action: find
2015-01-23 22:06:18:539 - info: [debug] [BOOTSTRAP] [debug] Finding com.paypal.android.p2pmobile:id/web using ID with the contextId:  multiple: true
2015-01-23 22:06:18:539 - info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[RESOURCE_ID=com.paypal.android.p2pmobile:id/web]
2015-01-23 22:06:18:540 - info: [debug] [BOOTSTRAP] [debug] getElements selector:UiSelector[RESOURCE_ID=com.paypal.android.p2pmobile:id/web]
2015-01-23 22:06:18:540 - info: [debug] [BOOTSTRAP] [debug] Element[] is null: (0)
2015-01-23 22:06:18:540 - info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=com.paypal.android.p2pmobile:id/web]
2015-01-23 22:06:18:573 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":[]}
2015-01-23 22:06:18:573 - info: [debug] Condition unmet after 37ms. Timing out.
2015-01-23 22:06:18:573 - info: [debug] Responding to client with success: {"status":0,"value":[],"sessionId":"8ec9cad8-8d23-4b36-b38e-8fd0a38f2ccd"}
2015-01-23 22:06:18:574 - info: <-- POST /wd/hub/session/8ec9cad8-8d23-4b36-b38e-8fd0a38f2ccd/elements 200 38.297 ms - 74 {"status":0,"value":[],"sessionId":"8ec9cad8-8d23-4b36-b38e-8fd0a38f2ccd"}
2015-01-23 22:06:18:628 - info: --> POST /wd/hub/session/8ec9cad8-8d23-4b36-b38e-8fd0a38f2ccd/elements {"using":"id","value":"com.paypal.android.p2pmobile:id/web"}
2015-01-23 22:06:18:629 - info: [debug] Waiting up to 0ms for condition

**Comment by bootstraponline** [comment]
@mseneby I recommend opening a new issue. Also it's unlikely that the problem can be fixed unless the developers have an app & testcase that reproduces the issue. If you're willing to provide one to Sauce Labs, that'd help immensely.

**Comment by 0x1mason** [comment]
@mseneby I don't see in the log that the Accessibility cache gets cleared.
Maybe there's a case I missed.

**Comment by mseneby** [comment]
@0x1mason Unfortunately, this flow requires real accounts that I couldn't provide java code directly. 
Is there any flag or some setting to enforce cache clearing. I encountered one statement in the logs as the following:
2015-01-23 22:06:37:308 - info: [debug] [BOOTSTRAP] [debug] Clearing cache and retrying.
In your commit, the debug statement is different, I am not sure you were looking for the above, which happen after failure point is over.
Here are the full logs for it
https://docs.google.com/file/d/0Bxurb7d6cwBuamNuSHVfVTVkU3c/edit

**Comment by 0x1mason** [comment]
@mseneby Thanks for the log.  I see the problem.  Working on a fix now.

**Comment by 0x1mason** [comment]
@mseneby Can you verify this fix?  http://goo.gl/n4CTQe

**Comment by mseneby** [comment]
@0x1mason 
Hi Eric,
I tried the fix this morning. Unfortunately, it caused a consistent side effect that I was unable to reach to the failure point for verifying the fix. Basically, whenever I launch the app and fill-out login credentials after couple welcome screens in the paypal app, the app has got closed immediately after submitting the form. I shortly see the animation that is happening normally during authentication time. The login window is a popup window different than the regular screens.
I can provide you a video if needed later, but here are the new appium logs:
https://docs.google.com/file/d/0Bxurb7d6cwBuM0hXU0hfVEh1S0k/edit
 The app closing happen just after clicking on ""com.paypal.android.p2pmobile:id/bttnLogin". The next steps in the app is animation for authentication and getting android:id/home id visible followed by animation, which never happen.

As soon as I switch back to older fix of AppiumBootstrap.jar, this side effect go away immediately. Please let me know if I may provide any more info.

Thanks,

**Comment by 0x1mason** [comment]
@mseneby Can you try installing the 1.3.5-beta and confirming that the regression is gone?  I want to make sure the that what you're seeing was caused by today's change.

`npm install appium@v1.3.5-beta`

**Comment by mseneby** [comment]
@0x1mason 
Great; I tried it with appium@1.3.5-beta. The side effect didn't happen and the test went through successfully. Note that the main problem (not finding ids) was intermittent. I will put this version into automation today to see whether it may happen again. I believe you fixed it permanently this time that my manual runs are passing. If anything may fail, I will try to inform you soon.
Thanks for working on this patiently.

**Comment by 0x1mason** [comment]
@mseneby  That's great news, I'm glad it worked for you.

**Comment by mseneby** [comment]
@0x1mason 
Sorry to inform that installing appium@1.3.5-beta wiped out AppiumBootStrap.jar that I copied manually earlier. This mislead me to conclude that the latest jar file is working fine. The app is still get closed as side-effect with Appium 1.3.5-beta. (Meanwhile, I will try earlier fix with  Appium 1.3.5-beta in automation.)

**Comment by bootstraponline** [comment]
could you capture and post the adb logcat logs?

**Comment by mseneby** [comment]
@0x1mason  
These are from the same morning run: (with appium 1.3.4 and your latest bootstrap)
https://docs.google.com/file/d/0Bxurb7d6cwBuTndMU01XR0NaMjg/edit

**Comment by bootstraponline** [comment]
adb logcat is not the same as appium server logs.

**Comment by mseneby** [comment]
sorry I put the wrong file in the rush; here are the adb logs
https://drive.google.com/file/d/0Bxurb7d6cwBuSXBWOWxJT1oxZ0k/view?usp=sharing

**Comment by bootstraponline** [comment]
It looks like you're using genymotion. Does the problem reproduce on a real physical API 21 device? I noticed two places in the log where the app appears to have crashed:

```
[2015-01-26T11:56:33-0800] [ALL] E/com.paypal.android.foundation.core( 2325): exception: /data/data/com.paypal.android.p2pmobile/files/AccountContents: open failed: ENOENT (No such file or directory) (java.io.FileNotFoundException: /data/data/com.paypal.android.p2pmobile/files/AccountContents: open failed: ENOENT (No such file or directory))


[2015-01-26T11:56:33-0800] [ALL] E/com.paypal.android.foundation.core( 2325): exception: /data/data/com.paypal.android.p2pmobile/files/CoreStateData: open failed: ENOENT (No such file or directory) (java.io.FileNotFoundException: /data/data/com.paypal.android.p2pmobile/files/CoreStateData: open failed: ENOENT (No such file or directory))
```

There's also some issue with maps however maybe that's unrelated.

```
[2015-01-26T11:56:52-0800] [ALL] E/Google Maps Android API( 2325): Failed to load map. Error contacting Google servers. This is probably an authentication issue (but could be due to network errors).
```

**Comment by 0x1mason** [comment]
@mseneby If I understand you correctly, the problem exists in the Beta, even if you use the .jar that is installed along with it.  Is that correct?

Does it make any difference if you call findElement for android:id/home instead of findElements?

**Comment by mseneby** [comment]
@0x1mason 
Yes, with beta or with 1.3.4 the new jar file causes app close(or crash), I am not sure whether exceptions above directly part of it. I did not try with real devices yet, but it should be uniform behavior. (I will try to see it on the real device later.)
Regarding findElement, you may be expert on this but they may make the same call in the appium framework behind the scenes that the api for the single one may return the first element from the results.It may not do any difference as a result.

**Comment by 0x1mason** [comment]
Can you check beta without new jar?  I'm trying to determine when "close app" behavior was introduced--today or previously.  Thanks!

**Comment by mseneby** [comment]
without the new jar, i observed both success and intermittent failures with the beta. None caused any close-app issue.

**Comment by 0x1mason** [comment]
findElement and findElements have different cache clearing behavior.  That's what I was trying to fix in the latest jar.

**Comment by 0x1mason** [comment]
@mseneby It's going to be very difficult for me to debug without the ability repro.  Here's what I recommend:

1. Investigate the exceptions that @bootstraponline mentions.  Let's make sure the problems are with Appium and not with your application or environment.
2. Try using findElement instead of findElements so we can establish if the cache clearing behavior is part of the problem.
3. See if you can identify the exact point of failure by systematically commenting out parts of your test.
4. It'd be helpful to me if you can use the Beta, but I understand if you cannot.
5. If you're unable to make any progress via the above, please provide video.  We might also consider setting up a skype/hangout.

Feel free to email me directly eric@saucelabs.com

**Comment by mseneby** [comment]
@0x1mason 
Thanks for troubleshooting this remotely. I agree it is difficult to understand without actually witnessing the problem. I'll try to investigate more and contact you with more concrete findings. I recheck the code that this failure was on findElements instead of findElement that was surprising me to have different behavior for both. I didn't test with findElement yet that both API is used intermittently in different places; I will let you know if this was the main pain point after make some internal changes and giving a try.
(Yes I tried with beta; I'll try more combinations)
Thanks

**Comment by 0x1mason** [comment]
@mseneby :+1:  Thanks!  Yeah the different behavior on findElement/s is surprising. I hadn't noticed the difference until yesterday (thank you).  Here's the basic problem in pseudo code:
```java
Object r = null;
if (isFindMultiple) {
  r = findElement(selector); // r remains null on fail
} else {
  r = findElements(selector); // on fail, r is an empty list, most definitely != null
}
// handle fail case
if (r == null) {
  return clearTheCacheAndRetryThenReturnFailIfStillCantFind(); // findElement behaves as expected
}
// handle success case
return doSuccessStuff();  // findElements always returns success
```
This problem is unrelated to my changes and afaik has been there for months.  You can see findElements returning success even when it fails in the logs you provided.  I'm concerned my fix blew up your tests, since it indicates logic upstream is predicated on the bad formulation.  All that is to say, we may be seeing 2 bugs here (your issue and the findElements asymmetry), not one, although I need to double check the findElements code isn't by design.

**Comment by 0x1mason** [comment]
@mseneby Looks like it's by design, though not sure what the rationale is. Will find out.

**Comment by 0x1mason** [comment]
@mseneby Can you try this jar?  https://drive.google.com/file/d/0B44l57OD4uwPNGdaWjVUdHRfbms/view?usp=sharing

**Comment by bootstraponline** [comment]
Also one thing to try is --full-reset. `pm clear` may cause problems with certain apps and potentially explains the missing files.

**Comment by mseneby** [comment]
@0x1mason I switched to single item find (findItem); the logs clearly shows retry as  "Failed to locate element. Clearing Accessibility cache and retrying." However, result is same.
Here are the new logs (same flow as in the earlier video)
https://drive.google.com/?tab=mo&authuser=0#my-drive
I also tried to find another element that is successful interestingly. In this simple screen, out of two ids; one is reachable (probably because it is same as previous screen) and the other is not. I also added UI automator viewer details.

I tried to see some clues in the adb logs but not sure about the cause. Can you please take a look?
Not sure whether log statements such as below matter; their occurrences much less than cache clear statements
D/Volley  (11341): [836] DiskBasedCache.put: Could not clean up file /dev/null/1830314641002827663
(I also see those in successful sessions.)

**Comment by 0x1mason** [comment]
Thanks for the info.  Will take a look early next week.  Did you try the
new jar I linked above?  I'm not optimistic given your last results, but
it's worth trying.  You shouldn't have to worry about
findElement/findElements with the new jar.


Again, I appreciate your help and will get back to you with a more
substantive analysis.

**Comment by mseneby** [comment]
yes, forgot to mention that this should be appium-1.3.5-beta + the last jar. I also tried some other combinations older versions, just beta, etc., (https://drive.google.com/file/d/0B44l57OD4uwPNGdaWjVUdHRfbms/view?usp=sharing)

**Comment by mseneby** [comment]
@ 0x1mason Hi, I uploaded here multiple runs on real devices, namely Samsung Galaxy S5 and S4. While it is almost always passing with S4, it consistently fail with S5. I hope these may help to analyze better:
https://drive.google.com/file/d/0Bxurb7d6cwBudzFhZl9uc0ZFLVk/view?usp=sharing

**Comment by 0x1mason** [comment]
@mseneby Awesome data.  Thanks!  Will dig in.

**Comment by 0x1mason** [comment]
@mseneby I've been debugging this and related issues.  Unfortunately, I don't have a fix for you.  As you've discovered, there's a great amount of variability between devices.  I've also found variability between OSes; eg, Android 5+ works great in my tests, but 4.4.x does not.  I don't think this is an Appium bug.  The cache hack helps, but Appium's current tooling on UiAutomator limits how much access it has to the system, so other workarounds and hacks are out of reach ftm.  We've got some things in the works that might help down the road, but nothing in the short term.  I wish I had better news for you.

**Comment by mseneby** [comment]
Thank you for all the efforts on this complex issue.

**Comment by 0x1mason** [comment]
You're welcome.  Thanks for all the debugging help.  Hopefully 1.3.5 is an
improvement, if not a 100% fix.

**Comment by RohailQayyum** [comment]
My uiaotomator.bat isn't open, whenever I clicked on my bat file it open for millisecond & then disappeared. How do i open this file. 
Thanks
