### ISSUE TITLE
PopupWindow issue

### ISSUE THREAD

**Issue by Benlooking** [appium/appium#4317]
I tried with inspector , but it is not showing the PopupWindow.I can not get any element with inspector.
  this issue is same as  https://github.com/selendroid/selendroid/issues/140 

 Thanks for your help

**Comment by jpkrause** [comment]
This issue is also occurring for me. The PopupWindow view is not present in the view hierarchy, thus I am unable to perform any actions against it or query its contents/views. This class is used in Android for the autocomplete suggestions when typing text into a url or search field. It is not present in a view hierarchy dump from monitor either.
![screen shot 2015-01-02 at 4 54 04 pm](https://cloud.githubusercontent.com/assets/10201255/5601059/64642756-92a0-11e4-8fcb-a6958f1746d5.png)
I saw in [a forum post](https://groups.google.com/d/msg/appium-discuss/XlcHl-0gKsM/Rv1TbZSlGbcJ) that the focus settings affect its visibility. By default, [PopupWindows are not focusable when created](http://developer.android.com/reference/android/widget/PopupWindow.html#PopupWindow%28android.content.Context%29).

**Comment by bootstraponline** [comment]
If it's a custom view component then it may not be supported by default in
uiautomator. The android developer docs explain in more detail.
http://developer.android.com/tools/testing/testing_ui.html

**Comment by jpkrause** [comment]
It's part of the Android API library since level 1. [android.widget.PopupWindow](http://developer.android.com/reference/android/widget/PopupWindow.html)
Perhaps it is not supported by default anyway.

**Comment by bootstraponline** [comment]
Unfortunately, my guess is that this is one of the components that
uiautomator doesn't support. You could try on API 21 to see if it's any
different there.

**Comment by jpkrause** [comment]
Just checked 21. Same problem. Sounds like it might be an Android feature request.

**Comment by bootstraponline** [comment]
My advice is to file this bug on the uiautomator issue tracker.
https://code.google.com/p/android/issues/list

Here's an example bug report that they fixed.
https://code.google.com/p/android/issues/detail?id=58733

**Comment by jpkrause** [comment]
Logged: https://code.google.com/p/android/issues/detail?id=93268
