### ISSUE TITLE
Appium is unable to switch context from Native app to Web view. 

### ISSUE THREAD

**Issue by unlimited91** [appium/appium#4321]
Hi, I am having a problem in switching the context of the driver from NATIVE_APP to WEBVIEW_<application packageName> using the driver.context(context). I am using appium java client 2.1.0 and chromedriver for linux 64 bit 2.13. I am testing an App for javascript injection in it's webView but whenever I try to switch the context it fails with an error as 

Chromedriver create session did not work. Status was 200 and body was {"sessionId":"b2c0aa00fd16686da5d89ec3d2e70f64","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.13.307649 (bf55b442bb6b5c923249dd7870d6a107678bfbb6),platform=Linux 3.13.0-43-generic x86_64)"}}

Kindly Suggest some solutions or work around regarding this issue.

**Comment by jlipps** [comment]
Please send in a full set of appium server logs

**Comment by bchaudhari** [comment]
Hi jlipps,

Providing the logs for context switching. Steps I'm trying to automate are

1. Open Hybrid App and click on a link which redirects to web view.
2. Switch to WEBVIEW 
3. Switch back to NATIVE_VIEW

Logs:

Debug: Running system command #9: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef"}
info: <-- POST /wd/hub/session/b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef/element/0/click 200 1194.732 ms - 74 {"status":0,"value":"","sessionId":"b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef"}

info: --> GET /wd/hub/session/b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef/contexts {}

info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray

info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_5"],"sessionId":"b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef"}
info: <-- GET /wd/hub/session/b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef/contexts 200 1.931 ms - 98 {"status":0,"value":["NATIVE_APP","WEBVIEW_5"],"sessionId":"b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef"}
info: --> POST /wd/hub/session/b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef/context {"name":"WEBVIEW_5"}
info: [debug] Attempting to set context to 'WEBVIEW_5'
info: [debug] [REMOTE] Debugger web socket connected to url [ws://localhost:27753/devtools/page/5]
info: [debug] Responding to client with success: {"status":0,"value":"WEBVIEW_5","sessionId":"b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef"}
info: <-- POST /wd/hub/session/b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef/context 200 2.546 ms - 83 {"status":0,"value":"WEBVIEW_5","sessionId":"b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef"}

info: --> POST /wd/hub/session/b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef/context {"name":"NATIVE_APP"}

info: [debug] Attempting to set context to 'NATIVE_APP'
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef"}
info: <-- POST /wd/hub/session/b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef/context 200 1.116 ms - 74 {"status":0,"value":"","sessionId":"b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef"}
info: [debug] [REMOTE] Disconnecting from remote debugger

info: --> DELETE /wd/hub/session/b7b4c2bb-fe3a-43c9-8bb1-e677ab2415ef {}

info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments

**Comment by changusmc** [comment]
I also see this issue, but only on Saucelabs. It works fine locally against emulator or device.

1. Switch to WebView
2. Perform some action
3. Switch to Native

SessionNotFoundException is thrown.

Logs below:

3862015-02-19 01:41:55:877 - info: [debug] returning process name: com.furiex
3872015-02-19 01:41:55:877 - info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.furiex
3882015-02-19 01:41:55:878 - info: [debug] ["WEBVIEW_com.furiex"]
3892015-02-19 01:41:55:878 - info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.furiex
3902015-02-19 01:41:55:878 - info: [debug] Connecting to chrome-backed webview
3912015-02-19 01:41:55:879 - info: [debug] Creating Chrome session
3922015-02-19 01:41:55:881 - info: [debug] Determining linux architecture
3932015-02-19 01:41:55:885 - info: [debug] Set chromedriver binary as: /home/chef/appium/build/chromedriver/linux/chromedriver32
3942015-02-19 01:41:55:885 - info: [debug] Ensuring Chromedriver exists
3952015-02-19 01:41:55:885 - info: [debug] Killing any old chromedrivers, running: ps -ef | grep /home/chef/appium/build/chromedriver/linux/chromedriver32 | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
3962015-02-19 01:41:55:896 - info: [debug] Successfully cleaned up old chromedrivers
3972015-02-19 01:41:55:897 - info: [debug] Spawning chromedriver with: /home/chef/appium/build/chromedriver/linux/chromedriver32
3982015-02-19 01:41:55:903 - info: [debug] [CHROMEDRIVER] Starting ChromeDriver 2.12.301324 (de8ab311bc9374d0ade71f7c167bad61848c7c48) on port 9515
399Only local connections are allowed.
4002015-02-19 01:41:55:905 - info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.furiex","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}}
4012015-02-19 01:41:56:277 - info: [debug] [CHROMEDRIVER STDERR] [0.373][WARNING]: PAC support disabled because there is no system implementation
4022015-02-19 01:41:56:415 - info: [debug] Successfully started chrome session 0b8f007775ad8cb8cb33dfd6e18781f9
4032015-02-19 01:41:56:415 - info: [debug] Setting proxy session id to 0b8f007775ad8cb8cb33dfd6e18781f9
4042015-02-19 01:41:56:416 - info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"c53de1b8-a61b-4dcd-bc48-abc058ea8f4b"}
4052015-02-19 01:41:56:419 - info: <-- POST /wd/hub/session/c53de1b8-a61b-4dcd-bc48-abc058ea8f4b/context 200 674.478 ms - 76 {"status":0,"value":null,"sessionId":"c53de1b8-a61b-4dcd-bc48-abc058ea8f4b"}
4062015-02-19 01:41:56:447 - info: --> POST /wd/hub/session/c53de1b8-a61b-4dcd-bc48-abc058ea8f4b/elements {"using":"id","value":"Login"}
4072015-02-19 01:41:56:448 - info: [debug] Proxying command to 127.0.0.1:9515
4082015-02-19 01:41:56:449 - info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/0b8f007775ad8cb8cb33dfd6e18781f9/elements","method":"POST","json":{"using":"id","value":"Login"}}
4092015-02-19 01:41:56:838 - info: [debug] Proxied response received with status 200: {"sessionId":"0b8f007775ad8cb8cb33dfd6e18781f9","status":0,"value":[{"ELEMENT":"0.45291872206144035-1"}]}
4102015-02-19 01:41:56:839 - info: <-- POST /wd/hub/session/c53de1b8-a61b-4dcd-bc48-abc058ea8f4b/elements 200 392.423 ms - 105
4112015-02-19 01:41:56:867 - info: --> POST /wd/hub/session/0b8f007775ad8cb8cb33dfd6e18781f9/elements {"using":"id","value":"Login"}
4122015-02-19 01:41:56:868 - info: [debug] Proxying command to 127.0.0.1:9515
4132015-02-19 01:41:56:868 - info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/0b8f007775ad8cb8cb33dfd6e18781f9/elements","method":"POST","json":{"using":"id","value":"Login"}}
4142015-02-19 01:41:56:936 - info: [debug] Proxied response received with status 200: {"sessionId":"0b8f007775ad8cb8cb33dfd6e18781f9","status":0,"value":[{"ELEMENT":"0.45291872206144035-1"}]}
4152015-02-19 01:41:56:937 - info: <-- POST /wd/hub/session/0b8f007775ad8cb8cb33dfd6e18781f9/elements 200 69.580 ms - 105
4162015-02-19 01:41:56:965 - info: --> POST /wd/hub/session/0b8f007775ad8cb8cb33dfd6e18781f9/context {"name":"NATIVE_APP"}
4172015-02-19 01:41:56:966 - info: <-- POST /wd/hub/session/0b8f007775ad8cb8cb33dfd6e18781f9/context 404 1.051 ms - 40

**Comment by moizjv** [comment]
Hi @changusmc can you email your issue to `help@saucelabs.com` we can look into it

**Comment by wsobasik** [comment]
It has something to do with invalidate (refreshing window).
In my scenario: 
I can find my back arrow on the top toolbar.
Switch to webview (validate www url).
Switch back to NATIVEapp
Can not find element exception is thrown but....!!!

Using presskeycode(4) - android back arrow
on the next screen (native app) everything works fine.!

**Comment by jlipps** [comment]
Closing since chromedriver updates should have fixed this in recent versions.

**Comment by mySportstg** [comment]
Hi @changusmc

May I know if you have found out why it is not working in Sauce Labs? I've encountered issue to locate element after switching back to Webview, but was working fine in my local machine too. Please advice. Thanks!
