### ISSUE TITLE
Appium v1.3.4 swipe not working

### ISSUE THREAD

**Issue by achung01** [appium/appium#4461]
Hi,

I'm currently having issue with swipe using Appium v1.3.4, swipe is not working. We tried using v1.2.4 and it is working as expected.

Here's the code:

public void swipe(String direction, double operationTime) {
		js = (JavascriptExecutor) driverDevice;
		HashMap<String, Double> swipeObject = new HashMap<String, Double>();

		if (StringUtils.equalsIgnoreCase(direction, "Up")) {
			swipeObject.put("startX", 0.5);
			swipeObject.put("startY", 0.25);
			swipeObject.put("endX", 0.5);
			swipeObject.put("endY", 0.99);
		} else if (StringUtils.equalsIgnoreCase(direction, "Down")) {
			swipeObject.put("startX", 0.5);
			swipeObject.put("startY", 0.80);
			swipeObject.put("endX", 0.5);
			swipeObject.put("endY", 0.01);
		} else if (StringUtils.equalsIgnoreCase(direction, "Left")) {
			swipeObject.put("startX", 0.01);
			swipeObject.put("startY", 0.5);
			swipeObject.put("endX", 0.99);
			swipeObject.put("endY", 0.5);
		} else if (StringUtils.equalsIgnoreCase(direction, "Right")) {
			swipeObject.put("startX", 0.99);
			swipeObject.put("startY", 0.5);
			swipeObject.put("endX", 0.01);
			swipeObject.put("endY", 0.5);
		} else {
			System.out
					.println("Invalid supplied direction. Please specify [Right, Left, Up or Down]");
		}

		swipeObject.put("duration", operationTime);
		js.executeScript("mobile: swipe", swipeObject);
	}

After using that code, we got this error.

INFO: slideToLeft|Failed|org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)

Any help is greatly appreciated. Thanks!

**Comment by achung01** [comment]
Looks like the JavascriptExecutor is the one not working. I also tried using the 'tap' commad and it is not working as well.

public void tapScreen(int xCoordinate, int yCoordinate) {
		js = (JavascriptExecutor) driverDevice;
		HashMap<String, Integer> tapObject = new HashMap<String, Integer>();
		tapObject.put("x", xCoordinate);
		tapObject.put("y", yCoordinate);

		js.executeScript("mobile: tap", tapObject);
	}

Appreciate any help. Thanks!

**Comment by hironmoypaul** [comment]
When I try to use this for swiping

    action = Appium::TouchAction.new
    action.swipe :start_x => 10, :start_y => 100, :end_x => 200, :end_y => 100, :duration => 1000
    action.perform


I see the following in my logs

--> POST /wd/hub/session/ef000acc-fce1-49d5-ab4d-6aaf55e2fe2b/touch/perform [{"action":"press","options":{"x":10,"y":100}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":200,"y":100}},{"action":"release"}]
info: [debug] Pushing command to appium work queue: "au.dragApp(10,100,200,100,1)"
info: [debug] Sending command to instruments: au.dragApp(10,100,200,100,1)
info: [debug] [INST] 2015-02-06 22:13:53 +0000 Debug: Got new command 53 from instruments: au.dragApp(10,100,200,100,1)
info: [debug] [INST] 2015-02-06 22:13:53 +0000 Debug: evaluating au.dragApp(10,100,200,100,1)
info: [debug] [INST] 2015-02-06 22:13:53 +0000 Debug: target.dragFromToForDuration({x:"10", y:"100"}, {x:"200", y:"100"}, "1")
info: [debug] [INST] 2015-02-06 22:13:54 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-02-06 22:13:54 +0000 Debug: responding with:
info: [debug] [INST] 2015-02-06 22:13:54 +0000 Debug: Running system command #54: /usr/local/Cellar/node/0.10.36/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"ef000acc-fce1-49d5-ab4d-6aaf55e2fe2b"}
info: <-- POST /wd/hub/session/ef000acc-fce1-49d5-ab4d-6aaf55e2fe2b/touch/perform 200 2167.813 ms - 74 {"status":0,"value":"","sessionId":"ef000acc-fce1-49d5-ab4d-6aaf55e2fe2b"}
info: --> DELETE /wd/hub/session/ef000acc-fce1-49d5-ab4d-6aaf55e2fe2b {}
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2015-02-06 22:14:00 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] 2015-02-06 22:14:00 +0000 Error: Script threw an uncaught JavaScript error: JSON Parse error: Unexpected EOF on line 2567 of bootstrap-1fb90a0f7e596c1d.js
info: [debug] [INST] Instruments Trace Complete (Duration : 46.014023s; Output : /tmp/appium-instruments/instrumentscli0.trace)


Not sure if this was due to the swipe action. Also I did not see the swipe happen on the simulator that was launched

**Comment by moizjv** [comment]
@achung01  can you try using `mobile: scroll` [documentation](https://github.com/moizjv/appium/blob/scroll-doc/docs/en/writing-running-appium/touch-actions.md)

**Comment by sukh48** [comment]
getting the same problem

**Comment by sebv** [comment]
Moving it to bugs, seems to be a few issue like this.

**Comment by SConrad-Whoop** [comment]
Has this been fixed in 1.4.0?

**Comment by jlipps** [comment]
The swipe bug is an Apple bug, not an Appium bug, and so it won't be fixed in an Appium release.

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/issues/350

**Comment by SrinivasanTarget** [comment]
@triager please close
