### ISSUE TITLE
Can't find an element on a webview page of an iOS native app

### ISSUE THREAD

**Issue by xuel270** [appium/appium#4649]
I have a native app which opens few web-view pages. I'm running appium on the app to do some automation test on a web-view page that I need to scroll down to find the username and password fields. I tried all the suggestion I can find online, and it doesn't work. Can anyone help? 
I'm running:
Appium v1.3.5
iOS 8.1

Here is my code:

// switch to webview

Thread.sleep(6000);
final Set<String> contextNames = driver.getContextHandles();
for (final String contextName : contextNames) {
  System.out.println(contextName);
  if (contextName.contains("WEBVIEW")) {
    driver.context(contextName);
  }
}

Thread.sleep(6000);
WebElement x = driver.findElement(By.cssSelector("Username *"));
assertTrue(x.isDisplayed());
Here is the element I try to scroll to and enter username

```
 <AppiumAUT>
   <UIAApplication name="Demo A" label="Demo A" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0" x="0" y="24.125" width="375" height="642.1875">    
    <UIAWindow name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2" x="0" y="0.6875" width="375" height="665.625">
    <UIAScrollView name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/1" x="29.296875" y="40.53125" width="316.40625" height="548.4375">
        <UIAWebView name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/2/1/0" x="29.296875" y="40.53125" width="684.375" height="1170.703125">
            <UIAStaticText name="Username *" label="Username *" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/2/1/0/15" x="94.921875" y="783.5" width="92.578125" height="22.265625">
            </UIAStaticText>
            <UIATextField name="" label="" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/2/1/0/16" x="94.921875" y="811.625" width="604.6875" height="46.875">
            </UIATextField>
```

Here is the error message:

org.openqa.selenium.InvalidElementStateException: SyntaxError: DOM Exception   12 (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 22 milliseconds

I have tried the following and didn't work:
1. switch to the window first using driver.switchTo().window("WEBVIEW_1");
2. use driver.findElement(By.id("Username *"))
3. use driver.findElement(By
   .xpath("//input[@name='Username *']"));
4. use driver.findElement(By .xpath("//UIAApplication[1]/UIAWindow[3]/UIAScrollView[1]/UIAWebView[1]/UIAStaticText[14]"));

I also tried to scroll to it first:
1. use just scollto: driver.scrollTo("Username *");
2. use script ((JavascriptExecutor) driver).executeScript(
   "arguments[0].scrollIntoView(true);", driver.findElement(By.name("Username *")));

Error message are either NoSuchElement or the one above.

Please help! Thanks!

**Comment by jeffscaturro-wf** [comment]
It may be related to the fact that they stopped recursively looking for elements in web views. See [this line](https://github.com/appium/appium-uiauto/blob/master/uiauto/lib/element-patch/lookup-patch.js#L174). We manually remove that check that ignores WebViews so that we can get the elements in a child that is a web view.

**Comment by Jonahss** [comment]
Aha, so really, that line should be changed to ignore webviews when searching through native view hierarchies, but disabled when searching through webview contexts.

**Comment by jlipps** [comment]
@Jonahss when searching through webview contexts we use the selenium atoms, so this code isn't touched at all. The issue here is that @jeffscaturro-wf is trying to run a native command on a webview element, but these are in separate worlds. The frustrating thing from his perspective is that the element _is_ actually accessible in Native mode (UIAutomation does give native access to some webview elements), so he should be able to do this. But because UIAutomation gives access to these elements, sometimes there are so many (say in the case of a big webpage), that we rule them out from search to make searches take a reasonable amount of time.

I think that the only solution here is to provide a capability that turns searching through webviews natively back on. It will make people's tests slower but it will allow them to have native access to certain webview elements.

In general this isn't something we want to support, however; theoretically there should be a way to use the atoms to do pretty much anything you'd want to do with an element while in the webview context.

**Comment by jlipps** [comment]
All that to say, this isn't a bug but a feature request. Marking accordingly.

**Comment by thanhxnguyen** [comment]
Hi @jlipps 
Was this enhancement included in Appium Release 1.4?
I cannot still inspect all elements in WebView

**Comment by jlipps** [comment]
no, this was added back to the general Features bucket, it was not handled in 1.4. 1.4 used to mean "things we _might_ include in 1.4", which was confusing, so we put it in Features. It will be addressed when we move it into a specific release milestone.

**Comment by alexlazarciuc** [comment]
Hey guys!

Not sure if the best place where to post this, but suddenly I started facing an issue when executing the tests on iOS app and cannot find the WEBVIEW context. When I call the method Driver.Context/Contexts; I can see only NATIVE_APP. The same is happening on the MAC machine I'm using on the standalone Appium server, when I inspect the elements, on contexts section, no contexts are detected. I'm using Appium 1.5.3. Does anyone facing or faced this issue and have a solution or a tip on how to handle this?

Thanks in advance,
Alex

**Comment by philatpremise** [comment]
Hi @alexlazarciuc , 
the same issue which you described is happening on the latest appium 1.7.2. Did you manage to deal with the issue after all?
Thanks,
Phil

**Comment by mykola-mokhnach** [comment]
Closed as obsolete

**Comment by dev-0x1** [comment]
> Hey guys!
> 
> Not sure if the best place where to post this, but suddenly I started facing an issue when executing the tests on iOS app and cannot find the WEBVIEW context. When I call the method Driver.Context/Contexts; I can see only NATIVE_APP. The same is happening on the MAC machine I'm using on the standalone Appium server, when I inspect the elements, on contexts section, no contexts are detected. I'm using Appium 1.5.3. Does anyone facing or faced this issue and have a solution or a tip on how to handle this?
> 
> Thanks in advance,
> Alex

Did you find any solution for this. It will be helpfull for many of the developers who are facing with the above issue.
