### ISSUE TITLE
PlistBuddy fails to get Xcode version in some cases [v1.3.7] 

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#4809]
From: https://discuss.appium.io/t/appium-1-3-7-release/3547

error: Could not determine Xcode version:Command failed: /bin/sh -c /usr/libexec/PlistBuddy -c 'Print CFBundleShortVersionString' /Applications/ Xcode 6.1.1.app/Contents/Info.plist

error: Could not get the iOS SDK version because the Xcode version could not be determined.

error: Could not get the iOS SDK version because the Xcode version could not be determined.

error: Could not get the iOS SDK version because the Xcode version could not be determined.

error: Could not determine iOS SDK version

info: [debug] Cleaning up appium session

error: Could not pre-launch appium: Error: Could not get the iOS SDK version because the Xcode version could not be determined.

I'vent changed anything in my configurations , and they are equal to the previous configurations I've used with 1.3.6 Appium version

**Comment by jlipps** [comment]
wondering if spaces need to be escaped

**Comment by 0x1mason** [comment]
@jlipps My thought exactly

**Comment by 0x1mason** [comment]
```js
var ESCAPE_SPACE_RE = /\s+/;
var SPACE_ESCAPE = '\ ';

function escapeSpace(str) {
  return str.split(ESCAPE_SPACE_RE).join(SPACE_ESCAPE);
}
```

**Comment by 0x1mason** [comment]
Add escapeSpace to lib/helpers.js. 
Will need a unit test for escapeSpace in test/unit/helper-specs.js.
Change needs to be made in lib/devices/ios/xcode.js. Call escapeSpace on plistPath on line 85.

**Comment by jlipps** [comment]
resolving https://github.com/appium/appium/issues/2041 would also fix this issue (the wrapper would just always do the right thing, so we don't have to remember to escape every time we use exec

**Comment by wensj** [comment]
I have the same problem:
error: Could not get the iOS SDK version because the Xcode version could not be determined.
error: Could not get the iOS SDK version because the Xcode version could not be determined.

info: [debug] Cleaning up appium session
info: [debug] Error: Could not get the iOS SDK version because the Xcode version could not be determined.
    at /Applications/Appium.app/Contents/Resourcesde_modules/appiumb/devices/ios/xcode.js:111:10
    at /Applications/Appium.app/Contents/Resourcesde_modules/appiumb/devices/ios/xcode.js:80:14
    at /Applications/Appium.app/Contents/Resourcesde_modules/appiumb/devices/ios/xcode.js:57:9
    at ChildProcess.exithandler (child_process.js:735:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not get the iOS SDK version because the Xcode version could not be determined.)","origValue":"Could not get the iOS SDK version because the Xcode version could not be determined."},"sessionId":null}
info: <-- POST /wd/hubssion 500 56.865 ms - 290 

error: Could not get the iOS SDK version because the Xcode version could not be determined.
error: Could not determine iOS SDK version
error: Failed to start an Appium session, err was: E

**Comment by wensj** [comment]
Is this bug been fixed?When can I get a new version of appium to solve this problem?

**Comment by jlipps** [comment]
@wensj you can run from source or wait for appium 1.4

**Comment by amedvedjev** [comment]
does not work with 1.4.0-beta
