### ISSUE TITLE
Concurrent screen captures?

### ISSUE THREAD

**Issue by GindiKhangura** [appium/appium#4854]
I attempted to grab screen captures concurrently in order to create a video-like display of the device. However, when a thread is running and has made the call to the driver to capture the screen image, the next thread that runs while it is in the middle of the previous operation effectively "cancels" the 1st thread's screen capture operation (does not cancel the thread on the client-side itself), which then returns back an empty array of bytes (since I'm using OutputType.BYTES). Basically, any thread in the middle of its operation for grabbing the screen image returns back no data if another screen capture operation is ran.

Is this expected behavior? If so, is it possible to allow concurrent screen captures on a single driver? I have not tried running multiple Appium servers and have each take screen captures of the same device, as I'd like to avoid having to do that.

I used a Samsung Galaxy Tab Pro on Android 4.4.2 using Appium 1.3.7.

**Comment by jlipps** [comment]
Right now the server expects session commands to be serial, not parallel. In particular the way we do screenshots uses temp files so that's probably why you're getting an empty array of bytes (second command clears out contents of screenshot file before first command has a chance to return it).

Multiple appium servers talking to the same device also won't work (they'll clobber each others' UiAutomator processes)

If your goal is to create a video-like display of the device, other tools are probably better suited for that purpose than appium.
