### ISSUE TITLE
Kill instruments stuck on a wait condition

### ISSUE THREAD

**Issue by apolatynski** [appium/appium#4933]
I'm running UI tests on iOS 8.1 simulator and using appium java client + cucumber. When I run all tests, it  executes the first scenario and closes the simulator as expected. While restarting simulator for the second test case, appium just prints the following 2 messages repeatedly:

```
info: [debug] Checking condition to see if we should kill instruments

info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
```

I'm using OS X 10.10.3 and simulator from Xcode 6.2 (same problem was when using Xcode 6.3). Appium version 1.3.7

**Comment by jlipps** [comment]
Please provide the full logs (no need for many repetitions of the text you pointed out though)

**Comment by apolatynski** [comment]
http://pastebin.com/iZXfENYN

**Comment by Jonahss** [comment]
Hm. It looks we actually detect this, but don't do anything about it.
https://github.com/appium/appium-instruments/blob/a11c46926f8bccedf385b151a2cca0cbdfae9165/lib/instruments.js#L298

We should have it quit and return an error, or kill the session.

**Comment by SrinivasanTarget** [comment]
This has been re-fractored and moved out in current architecture.Shall i close this? @imurchie

**Comment by imurchie** [comment]
Sure.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by bverkron** [comment]
I am experiencing this same issue Appium 1.4.13, Xcode 7.3 (7D175) and it's specifically related to the safariignorefraudwarning capability for testing mobile Safari.  Works fine without that capability. As soon as I add it I get the "required dirs don't yet exist" loop and Safari closes right after it's launched in the Simulator.

I noticed that the capability in question causes a POST line to show up at the beginning of the log.  Maybe that's a clue?

`info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"safari","platformName":"iOS","safariIgnoreFraudWarning":true,"deviceName":"iPhone 6","platformVersion":"9.3"}}

info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_91)

info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: [debug] Configuring Safari session
info: [debug] We're on iOS8+ so not copying mobile safari app
info: [debug] Creating new appium session 7198433d-5a6f-42cb-ba5a-a2723f41b8a0

info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version

info: [debug] Xcode version set to 7.3

info: [debug] Setting iOS SDK Version

info: [debug] iOS SDK Version set to 9.3

info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.3","iOSSDKVersion":"9.3","deviceName":"iPhone 6","platformVersion":"9.3"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (9.3)'
info: [debug] iOS sim UDID is 097D1DF0-B409-4E87-BC5D-814D53D4872F
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Localizable.strings is not currently supported when using real devices.
info: [debug] Creating instruments

info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/ben/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/ben/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js

info: [debug] Reusing dynamic bootstrap: /Users/ben/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.3","iOSSDKVersion":"9.3","deviceName":"iPhone 6","platformVersion":"9.3"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (9.3)'
info: [debug] Not setting device type since we're using bundle ID and assuming app is already installed
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process

info: [debug] Killing any other simulator daemons

info: [debug] Cleaning sim data files

info: node-simctl: Executing: xcrun with args: simctl erase 097D1DF0-B409-4E87-BC5D-814D53D4872F and timeout: 2000

info: [debug] Killall iOS Simulator

info: [debug] Cleaning mobile safari data files

warn: Applications directory /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Containers/Data/Application doesn't exist. Have you run this simulator before?

info: [debug] Deleting /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Library/Caches/Snapshots/com.apple.mobilesafari
info: [debug] Deleting /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Library/Caches/com.apple.mobilesafari/Cache.db*
info: [debug] Deleting /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Library/Caches/com.apple.WebAppCache/*.db
info: [debug] Deleting /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Library/Safari
info: [debug] Deleting /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Library/WebKit/LocalStorage/*.*
info: [debug] Deleting /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Library/WebKit/GeolocationSites.plist
info: [debug] Deleting /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Library/Cookies/*.binarycookies

info: [debug] Not setting locale
info: [debug] Setting iOS and app preferences
warn: Applications directory /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
info: [debug] Sim files for the 9.3 SDK do not yet exist, launching the sim to populate the applications and preference dirs
info: [debug] Not pre-launching simulator
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/ben/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/ben/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js
info: [debug] Reusing dynamic bootstrap: /Users/ben/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.3","iOSSDKVersion":"9.3","deviceName":"iPhone 6","platformVersion":"9.3"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (9.3)'
info: Launching instruments briefly then killing it

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Attempting to run app on iPhone 6 (9.3)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.3)" com.apple.mobilesafari -e UIASCRIPT "/Users/ben/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7"}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] Checking condition to see if we should kill instruments
warn: Applications directory /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...

info: [debug] Checking condition to see if we should kill instruments

warn: Applications directory /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...

info: [debug] Checking condition to see if we should kill instruments

warn: Applications directory /Users/ben/Library/Developer/CoreSimulator/Devices/097D1DF0-B409-4E87-BC5D-814D53D4872F/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...

info: [debug] Checking condition to see if we should kill instruments

info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...

info: [debug] Checking condition to see if we should kill instruments

info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...

info: [debug] Checking condition to see if we should kill instruments

info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...

info: [debug] Checking condition to see if we should kill instruments`
