### ISSUE TITLE
Switching context to default 'WEBVIEW' (without id) doesn't work on iOS real devices

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#5087]
Because we switch to webview '1', but ios_webkit_debug_proxy could have any number of webview...

@imurchie 

@jlipps my suggestion is just to remove this feature.

**Comment by imurchie** [comment]
Getting rid of it sounds fine with me. I don't think it's in the spec. But we might want to deprecate it in case anyone is using it. Then just bracket the test so real devices don't use it.

Alternatively, it could be changed to take whatever is the first webview, which is essentially what is being done on a simulator. Rather than adding `1`, we could find the lowest index and use that.

**Comment by jlipps** [comment]
webview names are just that---names. i don't think we can even assume there will be a number in it. i think the best practice is to always get the contexts and then choose based on some feature of the context (maybe its title, etc...). in most cases just getting the first non-native context is the right thing to do

**Comment by Jonahss** [comment]
Ok then, this ticket should be to fix that bit, to get the first non-native webview and return it when you try to switch to the 'WEBVIEW" context.
