### ISSUE TITLE
Instruments error: Attempting to set event horizon when core is not engaged, request ignored

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#5107]
OS X 10.10.3
appium 1.4.0
XCode6.3

My tests start to run normally and after 2/3 tests it stops being able to launch them with the error below.

```
info: [debug] Using local .ipa from desired caps: /Users/wcs_mac/Desktop/appium/cucumber/MessagePlusAppium.ipa
info: [debug] Copying local zip to tmp dir
info: [debug] /Users/wcs_mac/Desktop/appium/cucumber/MessagePlusAppium.ipa copied to /var/folders/jg/z88q__lx7hzfsszf57gpkyxw0000gn/T/115412-37814-vby61/appium-app.zip
info: [debug] Unzipping /var/folders/jg/z88q__lx7hzfsszf57gpkyxw0000gn/T/115412-37814-vby61/appium-app.zip
info: [debug] Testing zip archive: /var/folders/jg/z88q__lx7hzfsszf57gpkyxw0000gn/T/115412-37814-vby61/appium-app.zip
info: [debug] Zip archive tested clean
info: [debug] Unzip successful
info: [debug] Using locally extracted app: /var/folders/jg/z88q__lx7hzfsszf57gpkyxw0000gn/T/115412-37814-vby61/Payload/MessagePlus.app
info: [debug] Creating new appium session 208ddf9b-9b2b-4b29-9574-569678f4178b
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/wcs_mac/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.10.31/bin/node","commandProxyClientPath":"/usr/local/avm/versions/1.4.0/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. D...ot manually modify!
info: [debug] Dynamic bootstrap path: /Users/wcs_mac/Library/Application Support/appium/bootstrap/bootstrap-c6d46f54209209b9.js
info: [debug] Reusing dynamic bootstrap: /Users/wcs_mac/Library/Application Support/appium/bootstrap/bootstrap-c6d46f54209209b9.js
info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
warn: Could not capture logs from device. Continuing without capturing logs.
info: [debug] Creating iDevice object with udid 39bcf05aabb1bddf783b79d452cca052b32e2f2f
warn: Could not capture device log
info: [debug] App is installed.
info: [debug] fullReset not requested. No need to install.
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 39bcf05aabb1bddf783b79d452cca052b32e2f2f
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 39bcf05aabb1bddf783b79d452cca052b32e2f2f com.witsoftware.messageplus -e UIASCRIPT "/Users/wcs_mac/Library/Application Support/appium/bootstrap/bootstrap-c6d46f54209209b9.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-05-12 13:14:20.910 instruments[39052:217421] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST] 2015-05-12 12:14:21 +0000 Fail: The target application appears to have died
info: [debug] [INST STDERR] 2015-05-12 13:14:21.976 instruments[38945:216790] Attempting to set event horizon when core is not engaged, request ignored
2015-05-12 13:14:21.977 instruments[38945:216790] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST] Instruments Trace Complete (Duration : 39.856518s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [debug] On a real device; cannot clean device state
info: [debug] Cleaning up appium session
info: [debug] [INST] 2015-05-12 12:14:24 +0000 Error: Script threw an uncaught JavaScript error: JSON Parse error: Invalid number on line 2606 of bootstrap-c6d46f54209209b9.js
info: [debug] [INST] 2015-05-12 12:14:24 +0000 Stopped: Script was stopped by the user
info: [debug] [INST STDERR] 2015-05-12 13:14:24.825 instruments[39052:217473] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST STDERR] 2015-05-12 13:14:24.827 instruments[39052:217377] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST] Instruments Trace Complete (Duration : 4.037177s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 39bcf05aabb1bddf783b79d452cca052b32e2f2f
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 39bcf05aabb1bddf783b79d452cca052b32e2f2f com.witsoftware.messageplus -e UIASCRIPT "/Users/wcs_mac/Library/Application Support/appium/bootstrap/bootstrap-c6d46f54209209b9.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-05-12 13:14:33.124 instruments[39069:217500] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST] 2015-05-12 12:14:36 +0000 Error: Script threw an uncaught JavaScript error: JSON Parse error: Invalid number on line 2606 of bootstrap-c6d46f54209209b9.js
info: [debug] [INST] 2015-05-12 12:14:36 +0000 Stopped: Script was stopped by the user
info: [debug] [INST STDERR] 2015-05-12 13:14:37.016 instruments[39069:217494] Attempting to set event horizon when core is not engaged, request ignored
2015-05-12 13:14:37.017 instruments[39069:217500] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST] Instruments Trace Complete (Duration : 4.434457s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #2
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 39bcf05aabb1bddf783b79d452cca052b32e2f2f
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 39bcf05aabb1bddf783b79d452cca052b32e2f2f com.witsoftware.messageplus -e UIASCRIPT "/Users/wcs_mac/Library/Application Support/appium/bootstrap/bootstrap-c6d46f54209209b9.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
```

**Comment by tfcardoso** [comment]
I discover if I kill the app between each test (ios) it will never fail :|

**Comment by Jonahss** [comment]
The first log line I'm seeing that reports a failure is
`info: [debug] [INST] 2015-05-12 12:14:21 +0000 Fail: The target application appears to have died`

Is it possible that your app is crashing?

**Comment by sebv** [comment]
Closing, likely app issue, may be reopened if needed.

**Comment by BartVanRaemdonck** [comment]
I have the same issue, since Appium 1.4.8, my tests stop for no reason.

<addr>
info: [debug] Socket data received (39 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"30"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"30"},"sessionId":"3f846225-cd99-467a-b180-50d7fa6849e5"}
info: <-- POST /wd/hub/session/3f846225-cd99-467a-b180-50d7fa6849e5/element 200 24250.499 ms - 88 {"status":0,"value":{"ELEMENT":"30"},"sessionId":"3f846225-cd99-467a-b180-50d7fa6849e5"}
info: --> GET /wd/hub/session/3f846225-cd99-467a-b180-50d7fa6849e5/element/30/attribute/label {}
info: [debug] Pushing command to appium work queue: "au.getElement('30').label()"
info: [debug] Sending command to instruments: au.getElement('30').label()
info: [debug] [INST] 2015-08-04 13:29:09 +0000 Debug: evaluating au.getElementByIndexPath('/0/0/3/3')

info: [debug] [INST] 2015-08-04 13:29:09 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-08-04 13:29:09 +0000 Debug: Lookup returned [object UIAStaticText] with the name "Premier League" (id: 30).

info: [debug] [INST] 2015-08-04 13:29:09 +0000 Debug: responding with:

info: [debug] [INST] 2015-08-04 13:29:09 +0000 Debug: Running system command #232: /Volumes/Appium/Appium.app/Contents/Resources/node/bin/node /Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"30"}}...

info: [debug] [INST] 2015-08-04 13:29:10 +0000 Debug: Got new command 232 from instruments: au.getElement('30').label()

info: [debug] Socket data received (39 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"Premier League"}
info: [debug] Responding to client with success: {"status":0,"value":"Premier League","sessionId":"3f846225-cd99-467a-b180-50d7fa6849e5"}
info: <-- GET /wd/hub/session/3f846225-cd99-467a-b180-50d7fa6849e5/element/30/attribute/label 200 1093.531 ms - 88 {"status":0,"value":"Premier League","sessionId":"3f846225-cd99-467a-b180-50d7fa6849e5"}
info: --> DELETE /wd/hub/session/3f846225-cd99-467a-b180-50d7fa6849e5 {}
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments

info: [debug] [INST] 2015-08-04 13:29:10 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] 2015-08-04 13:29:10 +0000 Debug: evaluating au.getElement('30').label()
info: [debug] [INST] 2015-08-04 13:29:10 +0000 Debug: evaluation finished
       2015-08-04 13:29:10 +0000 Debug: responding with:
2015-08-04 13:29:10 +0000 Debug: Running system command #233: /Volumes/Appium/Appium.app/Contents/Resources/node/bin/node /Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"Premier League"}...

info: [debug] [INST STDERR] 2015-08-04 15:29:10.375 instruments[22702:1163169] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST STDERR] 2015-08-04 15:29:10.376 instruments[22702:1163169] Attempting to set event horizon when core is not engaged, request ignored

info: [debug] [INST] Instruments Trace Complete (Duration : 596.592346s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0

</addr>

**Comment by popei69** [comment]
Hi guys,

As @BartVanRaemdonck, I have the same kind of issue, it was working fine on 1.4.0 and since the update, it crash saying ` The target application appears to have died`.

But I checked with UIAutomation, and all objects are available, I can do same script on it and it works fine. It's only via Appium Server.

I tried to downgrade it, but it doesn't seems to be done properly.

If you have any clue guys, that could be great,

Thanks,
Ben

**Comment by ivan-baranovski-intellectsoft** [comment]
I have the same problem! Appium: Version 1.4.8, IPhone 5, IOS 8.3, 8.4. IPhone 6 with version 8.3 works correctly.

**Comment by utkarsha1** [comment]
I see the issue above when attempting to sendKeys in a text field. Appium: 1.4.8, IOS 8.4, IPhone 6 plus & IPhone 5. Appium logs have this:

Error: invalid json
    at parse (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/body-parser/lib/types/json.js:79:15)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/body-parser/lib/read.js:102:18
    at done (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/body-parser/node_modules/raw-body/index.js:248:14)
    at IncomingMessage.onEnd (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/body-parser/node_modules/raw-body/index.js:294:7)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)

info: [debug] Responding to client with error: {"status":1,"value":{"message":"undefined status object"},"sessionId":"14711924-1e02-4f27-969e-b2df53e39afb"}

**Comment by emoleumassi** [comment]
Something new about this topic?

**Comment by Omurden** [comment]
any updates?

**Comment by juhlila** [comment]
i was getting this error and what i changed that made it work was that i was running appium  `--native-instruments-lib` and changed to only `appium`, then it worked
