### ISSUE TITLE
Android: Background app actually restarts the application

### ISSUE THREAD

**Issue by lukcioj** [appium/appium#5176]
Hi,

I was testing: ( java ) driver.runAppInBackground(5); for both platforms: Android/iOS and it seems that it works differently.

For Android an app is actually restarted (killed & started) where for iOS it's backgrounded for given time. 

I think that it should work the same way for Android as it works for iOS. 

Appium: 1.4.1
iOS 8.1.2 & 8.3
Xcode: 6.2
ios-webkit-debug-proxy: 1.4
Android KitKat & Lollipop
Chromedriver 2.15

**Comment by imurchie** [comment]
I'm not able to reproduce this behaviour. Android processes remain active on my device, unless I use the debugging settings to specify that I want activities destroyed when they are not actively being used.

**Comment by SeikoTheWiz** [comment]
I was looking through internet because I happened to have the same issue and wanted to check if this was the normal behaviour.

I'm on Appium 1.3.7

**Comment by dianamenezes** [comment]
i am using 1.3.7 
appium_lib 7.0.0
I tried $appiumDriver.background_app(5)
It kills and restarts the apps. Does not maintain the app session.

**Comment by sebv** [comment]
Is there a way we can reproduce this using an opensource app? Just wondering if it could be the app itself (or a bug in the app) killing itself when backgrounded.

**Comment by lukcioj** [comment]
I'm not sure if this is relevant but I was using a hybrid-app. Unfortunately it's not open source...

**Comment by sebv** [comment]
Ok so next thing is to try to repro with a hybrid app, forinsance the Selendroid test app.

**Comment by SeikoTheWiz** [comment]
On my part it was on a 100% native ad (and a very small at that). Thank you for looking into it!

**Comment by epiccoleman** [comment]
I'm experiencing this too. Unfortunately our app is closed source so I can't help with the reproduction effort, but I have some additional information.

We're using Appium to do some session managment testing, and one of our tests requires backgrounding the app for _n_ seconds. When we background, things seem to be fine, but when the application comes back to the foreground, it acts as though it has restarted, taking us back to the initial login screen. 

This doesn't happen when we background the app and bring it back up manually (when we do this, the app comes back to where it is supposed to). We've also noted that, if we let Appium background the app, then bring it back to the foreground manually, the app comes back to the correct state. It seems like the problem lies in whatever Appium does to bring the app back to the foreground. 

I'm attaching the relevant portion of the logs. If we've missed something important here, let me know.

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"b04467d4-af14-413b-be3c-0ab61bfc348f"}
info: <-- GET /wd/hub/status 200 0.540 ms - 155 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"b04467d4-af14-413b-be3c-0ab61bfc348f"}

info: --> POST /wd/hub/session/b04467d4-af14-413b-be3c-0ab61bfc348f/appium/app/background {"seconds":30}

info: [debug] Getting focused package and activity
info: [debug] executing cmd: /opt/android-sdk/platform-tools/adb -s 192.168.56.101:5555 shell "dumpsys window windows"

info: [debug] executing cmd: /opt/android-sdk/platform-tools/adb -s 192.168.56.101:5555 shell "input keyevent 3"

info: [debug] Getting device API level

info: [debug] executing cmd: /opt/android-sdk/platform-tools/adb -s 192.168.56.101:5555 shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 21
info: [debug] executing cmd: /opt/android-sdk/platform-tools/adb -s 192.168.56.101:5555 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.foo.androidapp.b2.b3/com.foo.androidapp.MainActivity"

info: [debug] Waiting for pkg "com.foo.androidapp.b2.b3" and activity "com.foo.androidapp.MainActivity" to be focused

info: [debug] Getting focused package and activity
info: [debug] executing cmd: /opt/android-sdk/platform-tools/adb -s 192.168.56.101:5555 shell "dumpsys window windows"

info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"b04467d4-af14-413b-be3c-0ab61bfc348f"}
info: <-- POST /wd/hub/session/b04467d4-af14-413b-be3c-0ab61bfc348f/appium/app/background 200 31272.195 ms - 76 {"status":0,"value":null,"sessionId":"b04467d4-af14-413b-be3c-0ab61bfc348f"}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"b04467d4-af14-413b-be3c-0ab61bfc348f"}
info: <-- GET /wd/hub/status 200 5.092 ms - 155 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}},"sessionId":"b04467d4-af14-413b-be3c-0ab61bfc348f"}

Thanks for any help!

**Comment by holphi** [comment]
I have the same issue on Appium 1.4.13.1, my app under test is a native app which has splash screen, when I invoked runBackground(), I saw the activity went to background, then the app went to foreground with splash screen, any workarounds?

**Comment by sanjayahuja** [comment]
Same issue... was working in Appium 1.4.8 with ios 8.4 :(

**Comment by shubham2508** [comment]
Any possible workaround for it?

**Comment by holphi** [comment]
@shubham2508 Well, on Android platform, you may set the app to background by pressing home key, then resume the app to foreground by executing am command. Please check bellowing code implemented by C#:

        /// <summary>
        /// Set app from background to foreground
        /// </summary>
        public static void SetAppToForeground()
        {
            string shell_cmd = String.Format("shell am start -a android.intent.action.MAIN -n {0}/{1}",
                                             APP_PACKAGE, APP_ACTIVITY);
            Util.ExecuteADBCommand(shell_cmd);
        }
        
        protected static int KEYCODE_HOME = 3;

        public static void PressHomeKey()
        {
           driver.KeyEvent(KEYCODE_HOME);
        }

**Comment by igalep** [comment]
try to add "--dont-stop-app-on-reset" as an appium server flag

**Comment by shubham2508** [comment]
@holphi what is  Util in  that line? I am working on Appium for android, so what should be used for it??

**Comment by shermanericSF** [comment]
Definitely still reproduces with our app in 1.4.16.  I can ask my cohorts if I can send the apk over if it's still useful @sebv 
I'm not sure about 1.5 yet if this happens or not.

**Comment by SrinivasanTarget** [comment]
Background app implementation is quite different in Appium 1.5. Please try
in Appium 1.5 and update us back with appium logs as gist in case if you
face any issues.

**Comment by abhilashcae** [comment]
This still fails in Appium 1.5.2 for Android.

**Comment by vm31** [comment]
Any solution for this issue.

**Comment by sandp89** [comment]
So I was having the same issue on Android. I checked the following option on Appium "No Reset" and it foregrounds to the same activity rather than resetting the app.

**Comment by abdul-rehman** [comment]
I am also facing same issue on Appium 1.5.3 . Any Solution regarding this issue ?

**Comment by dtopuzov** [comment]
runAppInBackground still does not work properly with Appium 1.5.3 and Java client 4.1.0.
It can be easily reproduced when you try run in background is called when app is not on its default activity.

Test app:
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android-rottentomatoes-demo-debug.apk

Scenario:
1. Launch the app
2. Tap on some list view item to pen details (another activity)
3. Run in background

Result:
It minimize the app and open default activity (home screen of the app) and appium fails because it try to verify that current activity is same as when app was minimized (detail page).

Logs:
```
[MJSONWP] Calling AppiumDriver.background() with args: [10,"925922c7-4c14-450d-ad0...
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Tools\android-sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Tools\android-sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","emulator-5554","shell","input","keyevent",3]
[debug] [ADB] Device API level: 19
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Tools\android-sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","emulator-5554","shell","am","start","-n","com.codepath.example.rottentomatoes/com.codepath.example.rottentomatoes.BoxOfficeActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Waiting for pkg: 'com.codepath.example.rottentomatoes' and activity: '.BoxOfficeDetailActivity' to be focused
[debug] [ADB] Possible activities, to be checked: .BoxOfficeDetailActivity
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Tools\android-sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'com.codepath.example.rottentomatoes' and activity: '.BoxOfficeActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Tools\android-sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'com.codepath.example.rottentomatoes' and activity: '.BoxOfficeActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Tools\android-sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'com.codepath.example.rottentomatoes' and activity: '.BoxOfficeActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
```
What happens is appium minimize the app (open home screen) with 
```
[debug] [ADB] Running C:\Tools\android-sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","emulator-5554","shell","input","keyevent",3]
```
and then start the app with:
```
[debug] [ADB] Running C:\Tools\android-sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","emulator-5554","shell","am","start","-n","com.codepath.example.rottentomatoes/com.codepath.example.rottentomatoes.BoxOfficeActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
```

Current workaround in your team:
We use "adb shell input keyevent 3" to minimize the app, click apps button on the phone/emulator, navigate to app and tap launch icon.

It will be best if somehow we can simulate launching the app from its icon with adb commands.

Tested with "adb shell monkey -p your.app.package.name -c android.intent.category.LAUNCHER 1" and it also does not work -> it launch default activity (while manual launch via app icon open last activity before minimize).

We can get last activity and use "adb shell am start -n com.package.name/.ActivityName" to launch it, but I don't believe this is good runInBackground simulation.

**Comment by Kignuf** [comment]
Using ruby, I successfully made it work on appium 1.5.3 by using the default capability "dontStopAppOnReset".
http://appium.io/slate/en/master/?ruby#the-default-capabilities-flag

Hope this can help.

**Comment by VasilijSviridov** [comment]
@Kignuf thanks, works for me as well on 1.4.3 and 1.5.3 java.

Cheers

**Comment by saikrishna321** [comment]
Works on latest appium version.
