### ISSUE TITLE
SessionNotCreatedException with chrome driver

### ISSUE THREAD

**Issue by udayanem** [appium/appium#5239]
I have been facing SessionNotCreatedException exception when i work on Chrome Driver in Emulator or Physical Device.

Enviornment details:
ChromeDriver: 2.14 or 2.15
OS: Windows 7
Phone: Physical Device(Nexus 5) and Emulator
Appium: 1.3.4.1

Please find below link for the discussion in Appium, 
https://discuss.appium.io/t/chrome-driver-fails-again/4682/4

**Comment by sebv** [comment]
ping @imurchie

**Comment by imurchie** [comment]
Not sure I have any input on this. Is there a way to figure out what `adb` command timed out, and see if it can be run successfully manually? It might be an interaction between API level/SDK version/ChromeDriver version.

**Comment by udayanem** [comment]
Hi Isaac,

Following are my observations:
When i run the basic below script, i observed "chromedriver.exe" process in
Process tab of Task Manager.
I hope during this time, my physical device/emulator(i tested in both)
flashes and appium waits for sometime(i think it is 30 sec) and getting
"SessionNotCreatedException". If chromedriver.exe process already exists(if
you dont delete manually if it exists), soon you run you will get this
message.

Please find attached video and attached appium log.

In physical devices, it happens 70% of time we get the same above error,
but 30% of time the above script is running.(I am not sure why this
intermittent behavior.

Thanks,
Uday

**Comment by juanpicado** [comment]
I have the same feeling than @imurchie after the upgrade of the last Chrome I've been having the same issue, I think something is wrong with the communication adb <--> chromedriver.exe <--> browser, since I upgrade to adb 1.0.32 and the new chrome mobile all started to goes bad.
````
info: server=>[14632] info: [debug] Error: An operation did not complete before its timeout expired. (Original error: timeout: Adb command timed out after 30 seconds
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 6.1 SP1 x86_64))
    at JWProxy.command$ (lib/proxy.js:148:15)
    at tryCatch (C:\Users\userWindows\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:67:40)
````` 
I downgraded to ``adb`` 1.0.31 and the problem persist sometimes ... in the first try everything works fine, but then, timeout all the time. I tried to kill all processes and sometimes works, sometimes  not.
I'm wondering if someone has the same issue in other platforms, Mac or Linux.
