### ISSUE TITLE
"error: Got some configuration version mismatches. Appium is at 1.4.5." happened

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#5274]
Hi,

When I started Appium 1.4.5 installed via `npm` , then I encountered the following errors and couldn't start Appium server.

```
 $(npm bin)/appium
error: Got some configuration version mismatches. Appium is at 1.4.5.
error: ios configured at 1.4.5-beta
error: android configured at 1.4.5-beta
error: selendroid configured at 1.4.5-beta
error: firefoxos configured at 1.4.5-beta
error: Please re-run reset.sh or config
```

Is this just mistake of 1.4.5 release ?

**Comment by nikhil969** [comment]
I am also facing the same issue

**Comment by PavelGorbanj** [comment]
We also face the same problem

**Comment by nikhil969** [comment]
When I checked out the latest code from github and started appium from bin

spartans@ubuntu:~/appium/bin$ ./appium.js
info: Welcome to Appium v1.4.5 (REV 9d1af07681e73c01d59eca608b9ca57c97e9b4dc)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4","deviceName":"Unicorn4.4","platformName":"Android","browserName":"Browser"}}
info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: Set mode: Proxying straight through to Chromedriver
info: [debug] Looks like we want chrome on android
info: [debug] Creating new appium session 72e690aa-67be-4210-a43e-4a9ec0503278
info: [debug] Checking whether adb is present
info: [debug] Using adb from /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's already on the device
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb devices
info: [debug] 1 device(s) connected
info: Found device emulator-5554
info: [debug] Setting device id to emulator-5554
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 wait-for-device
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 install "/home/spartans/appium/build/unlock_apk/unlock_apk-debug.apk"
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 shell "dumpsys window"
info: [debug] Screen already unlocked, continuing.
info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 forward tcp:4724 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 push "/home/spartans/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.browser -e disableAndroidWatchers false
info: [debug] [UIAUTOMATOR STDOUT] WARNING: linker:
info: [debug] [UIAUTOMATOR STDOUT] libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
info: [debug] [UIAUTOMATOR STDOUT] WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] dataDir set to: /data
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data","status":0}
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: TypeError: Cannot read property 'stop' of null
info: [debug] TypeError: Cannot read property 'stop' of null
    at Chromedriver.start$ (lib/chromedriver.js:93:24)
    at tryCatch (/home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Cannot read property 'stop' of null)","origValue":"Cannot read property 'stop' of null"},"sessionId":null}
info: <-- POST /wd/hub/session 500 2988.243 ms - 192 
^[^C
spartans@ubuntu:~/appium/bin$ cls
No command 'cls' found, but there are 18 similar ones
cls: command not found
spartans@ubuntu:~/appium/bin$ clear

spartans@ubuntu:~/appium/bin$ ./appium.js
info: Welcome to Appium v1.4.5 (REV 9d1af07681e73c01d59eca608b9ca57c97e9b4dc)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4","deviceName":"Unicorn4.4","platformName":"Android","browserName":"Browser"}}
info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: Set mode: Proxying straight through to Chromedriver
info: [debug] Looks like we want chrome on android
info: [debug] Creating new appium session d0a13d2a-d55c-4960-8118-301ab5920217
info: [debug] Checking whether adb is present
info: [debug] Using adb from /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's already on the device
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb devices
info: [debug] 1 device(s) connected
info: Found device emulator-5554
info: [debug] Setting device id to emulator-5554
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 wait-for-device
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 install "/home/spartans/appium/build/unlock_apk/unlock_apk-debug.apk"
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 shell "dumpsys window"
info: [debug] Screen already unlocked, continuing.
info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 forward tcp:4724 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 push "/home/spartans/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /home/spartans/.linuxbrew/Cellar/android-sdk/24.2/platform-tools/adb -s emulator-5554 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.browser -e disableAndroidWatchers false
info: [debug] [UIAUTOMATOR STDOUT] WARNING: linker:
info: [debug] [UIAUTOMATOR STDOUT] libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] dataDir set to: /data
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data","status":0}
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: TypeError: Cannot read property 'stop' of null
info: [debug] TypeError: Cannot read property 'stop' of null
    at Chromedriver.start$ (lib/chromedriver.js:93:24)
    at tryCatch (/home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /home/spartans/appium/node_modules/appium-chromedriver/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Cannot read property 'stop' of null)","origValue":"Cannot read property 'stop' of null"},"sessionId":null}
info: <-- POST /wd/hub/session 500 2989.683 ms - 192

**Comment by vikramvi** [comment]
Questions:
1. where is reset.sh located ?
2. what is meaning of re-run config ?

**Comment by SportySeb** [comment]
Facing the same problem today. Yesterday it worked without any issues. 

I think it's similar to https://github.com/appium/appium/issues/2090 => someone did a mistake on the "nightly" commit and we now can only wait for the next commit.

**Comment by nikhil969** [comment]
Don't clone the code and try to execute. I had the same issue delete the folder/ uninstall appium
Install it using "npm install -g appium"  open terminal and then type  "appium" the server will start

**Comment by moizjv** [comment]
Yes we had some issues with past patch releases due to upstream dependencies. Now we have release 1.4.6 which should be stable. Please use that. Let us know if you still face issues. Thanks

**Comment by KazuCocoa** [comment]
Thanks for your re-publishing !

Appium 1.4.6 works well :grinning: 

```
$appium
info: Welcome to Appium v1.4.6 (REV 1efd33330243765bae4e6216b62df3c9ec3cede5)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
```

I close this issue.

**Comment by SportySeb** [comment]
if you installed with npm, when simply delete the folder ~/.npm/appium and execute "npm install -g appium" again.

**Comment by vikramvi** [comment]
verified fixed from my side as well. 

Thanks for the quick fix.

**Comment by yupilab** [comment]
I have installed appium 1.4.6 via brew. In my case I still have this issue. Logs below:
error: Got some configuration version mismatches. Appium is at 1.4.6.
error: ios configured at 1.3.4
error: android configured at 1.3.4
error: Please re-run reset.sh or config

What can I do?

**Comment by moizjv** [comment]
@yupilab can you try `rm .appiumconfig.json` and then install?
