### ISSUE TITLE
How to collect and generate report from performance logs for Hybrid app for webview in Android

### ISSUE THREAD

**Issue by csharsha** [appium/appium#5346]
Hi,

How to collect and generate report from performance logs for Hybrid app for webview in Android and iOS. I have seen something like 'enablePerformanceLogs' capability feature for Android alone, how to implement the same in iOS apps. And also where will be the results collected? I need to generate the performance analysis report based on the data collected. As of now if I try to get the logs, I am getting only Logcat and Client in the collection of logs.

Thanks

**Comment by Jonahss** [comment]
Hmmmmm. I think the way to get that isn't currently a feature of appium, but I have heard of others implementing it. What you should do is use a different xcode trace template file. Appium has a server flag by which you can pass it the path to a specific trace template to use. I think instruments will then collect the performance data you are looking for and record it.

@bootstraponline do you know about this?

Closing, because this isn't a bug in appium, and it's not a feature we expect to implement soon.

**Comment by bootstraponline** [comment]
Appium doesn't support this on ios and has limited support on android (no native app support). Instruments offers performance profiling and apple has documented it on their official website. Android is easier since uiautomator has some performance monitoring APIs and adb makes collecting hardware stats such as processor and memory usage easy. appium doesn't currently support that though.

**Comment by csharsha** [comment]
@bootstraponline @Jonahss: How to collect the data in adb in appium test. Can you elaborate this?

**Comment by csharsha** [comment]
@bootstraponline How to do it android, can you please elaborate?

**Comment by bootstraponline** [comment]
search google for the adb commands. ex: `adb shell dumpsys cpuinfo`
