### ISSUE TITLE
IOSDriver JavascriptExecutor throws "An error occurred while executing user supplied JavaScript" when return statements are used

### ISSUE THREAD

**Issue by phystem** [appium/appium#5390]
When I try to return values from JavaScriptExecutor it is throwing

       JavascriptExecutor js = (JavascriptExecutor) wd;
       System.out.println(js.executeScript("return true"));

```
Exception in thread "main" org.openqa.selenium.WebDriverException: An error occurred while executing user supplied JavaScript. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.95 seconds
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'APPLEs-Mac-mini.local', ip: '192.168.1.112', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.4', java.version: '1.7.0_79'
Session ID: dfd47c18-aebd-4df0-8598-029c24bae21d
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{platformVersion=8.2, app=/Users/Apple/Library/Developer/Xcode/DerivedData/UICatalog-awyrhprjhfypbofjkcjkujlkngty/Build/Products/Debug-iphonesimulator/UICatalog.app, platform=MAC, databaseEnabled=false, javascriptEnabled=true, platformName=iOS, deviceName=iPhone 5s, browserName=iOS, appium-version=1.0, webStorageEnabled=false, networkConnectionEnabled=false, desired={app=/Users/Apple/Library/Developer/Xcode/DerivedData/UICatalog-awyrhprjhfypbofjkcjkujlkngty/Build/Products/Debug-iphonesimulator/UICatalog.app, platformVersion=8.2, deviceName=iPhone 5s, platformName=iOS, appium-version=1.0}, locationContextEnabled=false, warnings={}, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:27)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:514)
	at testapp.TestApp.main(TestApp.java:42)
```

Full code

```
DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability("appium-version", "1.0");
            capabilities.setCapability("platformName", "iOS");
            capabilities.setCapability("platformVersion", "8.2");
            capabilities.setCapability("deviceName", "iPhone 5s");
            capabilities.setCapability("app", "/Users/Apple/Library/Developer/Xcode/DerivedData/UICatalog-awyrhprjhfypbofjkcjkujlkngty/Build/Products/Debug-iphonesimulator/UICatalog.app");
            IOSDriver wd = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
            JavascriptExecutor js = (JavascriptExecutor) wd;
            System.out.println(js.executeScript("return true"));
```

**Comment by vinceis1337** [comment]
Why do you need to return true at the end?

**Comment by phystem** [comment]
That's an example .Whatever i'm returning it's throwing that exception.I mean whenever there is a return statement it is not executing

**Comment by vinceis1337** [comment]
I guess my question is you usually have a function or method that you need a return value for. Is there more code that you can provide? I would expect something like: 
```
js.executeScript(" function tmp(){var attrb = jQuery(jQuery("[name='q']")[0]).attr('type');if(typeof attrb !== 'undefined' && attrb !== false){return attrb;}else{return '';}}tmp();");
```

**Comment by sebv** [comment]
Please provide full log.

**Comment by nick5454** [comment]
I get the same issue when issuing any command in Javascript. get() is a java syntax to get the actual Element from an Optional type. I verified it's valid and use sendKeys to write successfully.

Command:
`        JavascriptExecutor js = (JavascriptExecutor)wd; // wd is the WebDriver
        js.executeScript("arguments[0].click();", lastNameTextField.get());`
Log:
`info: --> POST /wd/hub/session/af29fa26-f1be-47bd-be00-1785146a8d5d/execute {"script":"arguments[0].click();","args":[{"ELEMENT":"3","element-6066-11e4-a52e-4f735466cecf":"3"}]}


info: [debug] Pushing command to appium work queue: "arguments[0].click();"


info: [debug] Sending command to instruments: arguments[0].click();


info: [debug] [INST] 2016-04-12 19:29:48 +0000 Debug: Got new command 15 from instruments: arguments[0].click();


info: [debug] [INST] 2016-04-12 19:29:48 +0000 Debug: evaluating arguments[0].click();


info: [debug] Socket data received (86 bytes)


info: [debug] Socket data being routed.


info: [debug] Got result from instruments: {"status":17,"value":"undefined is not an object (evaluating 'arguments[0].click')"}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"undefined is not an object (evaluating 'arguments[0].click')"},"sessionId":"af29fa26-f1be-47bd-be00-1785146a8d5d"}


info: <-- POST /wd/hub/session/af29fa26-f1be-47bd-be00-1785146a8d5d/execute 500 841.442 ms - 221 


info: [debug] [INST] 2016-04-12 19:29:48 +0000 Error: TypeError: undefined is not an object (evaluating 'arguments[0].click')


info: [debug] [INST] 2016-04-12 19:29:48 +0000 Error: Error during eval: eval code
       eval@[native code]
startProcessing@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/BEBA01CC-1ADE-4CBF-B094-D12B0075CED8/bootstrap-9a1136664d01e391.js:2710:30
bootstrap@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/BEBA01CC-1ADE-4CBF-B094-D12B0075CED8/bootstrap-9a1136664d01e391.js:2778:31
global code@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/BEBA01CC-1ADE-4CBF-B094-D12B0075CED8/bootstrap-9a1136664d01e391.js:2787:10


info: [debug] [INST] 2016-04-12 19:29:48 +0000 Debug: responding with:


info: [debug] [INST] 2016-04-12 19:29:48 +0000 Debug: Running system command #16: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":17,"value":"undefined is not an object (evaluating 'arguments[0].click')"}...


info: --> DELETE /wd/hub/session/af29fa26-f1be-47bd-be00-1785146a8d5d {}


info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2016-04-12 19:29:52 +0000 Stopped: Script was stopped by the user
info: [IOS_SYSLOG_ROW ] Apr 12 14:29:52 mylaptop.local SpringBoard[6153]: Unable to get short BSD proc info for 6191: No such process


info: [IOS_SYSLOG_ROW ] Apr 12 14:29:52 mylaptop com.apple.CoreSimulator.SimDevice.E51C2408-AECB-448A-8364-26E99B309B06.launchd_sim[6139] (UIKitApplication:com.***.****[0x89fd][6191]): Service exited due to signal: Killed: 9


info: [IOS_SYSLOG_ROW ] Apr 12 14:29:52 mylaptop.local SpringBoard[6153]: Application 'UIKitApplication:com.***.****[0x89fd]' exited abnormally via signal.


info: [IOS_SYSLOG_ROW ] Apr 12 14:29:52 mylaptop assertiond[6157]: assertion failed: 15E65 12H141: assertiond + 12334 [EDAF3958-87C7-3C61-A8E6-24689FBBE168]: 0x1
info: [IOS_SYSLOG_ROW ] Apr 12 14:29:52 mylaptop.local assertiond[6157]: notify_suspend_pid() failed with error 7
info: [IOS_SYSLOG_ROW ] Apr 12 14:29:52 mylaptop assertiond[6157]: assertion failed: 15E65 12H141: assertiond + 12334 [EDAF3958-87C7-3C61-A8E6-24689FBBE168]: 0x1


info: [debug] [INST STDERR] 2016-04-12 14:29:52.738 instruments[6132:260168] Attempting to change event horizon while disengage


info: [debug] [INST] Instruments Trace Complete (Duration : 51.832207s; Output : /tmp/appium-instruments/instrumentscli0.trace)


info: [debug] [INSTSERVER] Instruments exited with code 0


info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons


info: [debug] Killall iOS Simulator
info: [IOS_SYSLOG_ROW ] Apr 12 14:29:52 mylaptop.local DTMobileIS[6162]: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn


info: [debug] Cleaning sim data files


info: node-simctl: Executing: xcrun with args: simctl erase E51C2408-AECB-448A-8364-26E99B309B06 and timeout: 2000

`

**Comment by imurchie** [comment]
This is not the same issue. The original issue is because the user is attempting to use `return` outside of a function. This does not work.

Your problem is that the arguments are not used in the native context. You need to construct a string that is a valid UIAutomation script. This is simply exec-ed within the context of the device.

So you need to construct a string like `the_element_i_want.click();`. It is your responsibility to figure out what the element is within UIAutomation syntax.

**Comment by nick5454** [comment]
The real issue is that the execute script does not process arguments[0] after moving the return into a function. That is broken and also the parent property returns blank.

**Comment by imurchie** [comment]
There are no arguments. Appium does not use them in the native context. So `arguments[0]` will **always** be `undefined`.

**Comment by nick5454** [comment]
Ok, thanks for the info!

**Comment by SrinivasanTarget** [comment]
Closing this because of no logs been tagged here related to issue.

**Comment by SrinivasanTarget** [comment]
@triager please close
