### ISSUE TITLE
Start uiautomator session without launching anything

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5401]
It'd be nice to simply launch a uiautomator session and not have to initialize the driver with an app. This would be useful for automating against the default state of particular devices.

**Comment by Fanch-** [comment]
:+1: 
Need it !

**Comment by artkoshelev** [comment]
:+1:

**Comment by jlipps** [comment]
Seems like if we want to do this, we should have a magic app capability string, like "Home" or something like that. In UiAutomator 1 this feature is trivial; we just bypass our app launching logic. In UiAutomator 2 it is probably less trivial, since it is instrumentation-based and we have to launch _some_ app. However we could probably have an empty app which we automate and then simply go to the home screen after that. Either way, this is not a high-priority feature since users can do the same thing as I just described as a workaround.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
