### ISSUE TITLE
send_keys is wrong

### ISSUE THREAD

**Issue by kingangelTOT** [appium/appium#5449]
appium version 1.4.8
system: os x
platform: android
version:5.0.2

login 
content-desc: 
type: android.widget.EditText
text: 111111111aaaaaaaaa
index: 0
enabled: true
location: {1, 283}
size: {1078, 144}
checkable: false
checked: false
focusable: true
clickable: true
long-clickable: true
package: me.ele
password: false
resource-id: me.ele:id/easy_edit_text
scrollable: false
selected: false
xpath: //android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.FrameLayout[2]/android.widget.LinearLayout[1]/android.widget.RelativeLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.EditText[1]

password 
content-desc: 
type: android.widget.EditText
text: 
index: 0
enabled: true
location: {1, 426}
size: {915, 144}
checkable: false
checked: false
focusable: true
clickable: true
long-clickable: true
package: me.ele
password: true
resource-id: me.ele:id/easy_edit_text
scrollable: false
selected: false
xpath: //android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.FrameLayout[2]/android.widget.LinearLayout[1]/android.widget.RelativeLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[2]/android.widget.LinearLayout[1]/android.widget.EditText[1]

password is sent to login, not sent to password

Expect 
login :111111111
password:aaaaaaaaa

actual
login:111111111aaaaaaaaa
password:

**Comment by cjtcwyk** [comment]
post your code, need to see what happen

**Comment by kingangelTOT** [comment]
{
          "flowStepId":"3",
          "stepType":"element",
          "keyWord":"sendKeys",
          "content":"111111111111",
          "element":{
            "amount": "single",
            "by":"findElementByAndroidUIAutomator",
            "value":"new UiSelector().className(\"android.widget.EditText\").instance(0)",
            "isSenior":"false"
          },
          "trans":[
          ]
        },
        {
          "flowStepId":"4",
          "stepType":"element",
          "keyWord":"sendKeys",
          "content":"aaaaaaaaaaaa",
          "element":{
            "amount": "single",
            "by":"findElementByAndroidUIAutomator",
            "value":"new UiSelector().className(\"android.widget.EditText\").instance(1)",
            "isSenior":"false"
          },
          "trans":[
            {
              "transId":"10",
              "transType":"element",
              "transValue":"",
              "keyWord":"getText",
              "element":{
                "amount": "single",
                "by":"findElementByAndroidUIAutomator",
                "value":"new UiSelector().className(\"android.widget.EditText\").instance(0)",
                "isSenior":"false"
              }

            },

testdata
this use java 

use ruby

element = driver.find_element('id', 'me.ele:id/home_bottom_tab_4')

element.click
element = driver.find_element('uiautomator', 'new UiSelector().className("android.widget.RelativeLayout").instance(1)')
element.click

element = driver.find_element('xpath', '//android.widget.EditText[1]')
element.send_keys('1111111111')

element = driver.find_element('xpath', '//android.widget.EditText[2]')
element.send_keys('aaaaaaaaaaa')

element = driver.find_element('name', '登陆')
element.click
driver.quit

**Comment by kingangelTOT** [comment]
element = driver.find_element('id', 'me.ele:id/home_bottom_tab_4')
element.click
element = driver.find_element('uiautomator', 'new UiSelector().className("android.widget.RelativeLayout").instance(1)')
element.click
element = driver.find_element('xpath', '//android.widget.EditText[1]')
element.send_keys('11111111111')
element = driver.find_element('xpath', '//android.widget.EditText[2]')

element.click

element.send_keys('aaaaaaaaaaa')
element = driver.find_element('name', '登陆')
element.click
driver.quit

add click is ok

**Comment by chenhengjie123** [comment]
I checked appium source codes, found that although [Fix Android keys by finding focused element](https://github.com/appium/appium/commit/f8c803423717e8ba1402efb2c1248fca51779b0c) is added in [appium/lib/devices/android/bootstrap/src/io/appium/android/bootstrap/handler/SetText.java](https://github.com/appium/appium/blob/v1.4.8/lib/devices/android/bootstrap/src/io/appium/android/bootstrap/handler/SetText.java) in Appium 1.4.8 and may just send key to current focus element like mentioned above, but the logs show that it didn't run into send key to focus element( otherwise log like "Using currently-focused element." would occur) .

I have use send key on Appium 1.3.7 with Android 4.3 for almost half year and never meet this issue, also from source code the send key logic in this issue is the same as I use, so I think this may be caused by app or uiautomator in android system. So I check `setText` function in uiautomator on android 5.0.2:

<http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.0.2_r1/com/android/uiautomator/core/UiObject.java?av=f>
```
public boolean More ...setText(String text) throws UiObjectNotFoundException {
         Tracer.trace(text);
         clearTextField();
         return getInteractionController().sendText(text);
     }

```

<http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.0.2_r1/com/android/uiautomator/core/UiObject.java#UiObject.clearTextField%28%29>
```
public void More ...clearTextField() throws UiObjectNotFoundException {
         Tracer.trace();
         // long click left + center
         AccessibilityNodeInfo node = findAccessibilityNodeInfo(mConfig.getWaitForSelectorTimeout());
         if(node == null) {
             throw new UiObjectNotFoundException(getSelector().toString());
         }
         Rect rect = getVisibleBounds(node);
         getInteractionController().longTapNoSync(rect.left + 20, rect.centerY());
         // check if the edit menu is open
         UiObject selectAll = new UiObject(new UiSelector().descriptionContains("Select all"));
         if(selectAll.waitForExists(50))
             selectAll.click();
         // wait for the selection
         SystemClock.sleep(250);
         // delete it
         getInteractionController().sendKey(KeyEvent.KEYCODE_DEL, 0);
     }
```

<http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.0.2_r1/com/android/uiautomator/core/InteractionController.java#InteractionController.sendText%28java.lang.String%29>
```
public boolean More ...sendText(String text) {
        if (DEBUG) {
            Log.d(LOG_TAG, "sendText (" + text + ")");
        }

        KeyEvent[] events = mKeyCharacterMap.getEvents(text.toCharArray());

        if (events != null) {
            long keyDelay = Configurator.getInstance().getKeyInjectionDelay();
            for (KeyEvent event2 : events) {
                // We have to change the time of an event before injecting it because
                // all KeyEvents returned by KeyCharacterMap.getEvents() have the same
                // time stamp and the system rejects too old events. Hence, it is
                // possible for an event to become stale before it is injected if it
                // takes too long to inject the preceding ones.
                KeyEvent event = KeyEvent.changeTimeRepeat(event2,
                        SystemClock.uptimeMillis(), 0);
                if (!injectEventSync(event)) {
                    return false;
                }
                SystemClock.sleep(keyDelay);
            }
        }
        return true;
    }
```

Firstly, `clearTextField()` function would tap the text field that need to send key later, then select all, click delete button. Aftert that `sendKey` would send keys to current focus text field. So the text field would always get focus before send keys. 

Could you tell us the details when executing the send_keys function in your script on your android device? Does the "tap->select all->delete" happens on your password text field? Without these information I can't found the root course of this issue and give you the possible solution.

**Comment by kingangelTOT** [comment]
If do not have the click password in the password box, password will send to user name box

**Comment by chenhengjie123** [comment]
Did it tap->select all->delete in username box while "11111111111" is already in it?

**Comment by JayeshVaghela** [comment]
Hello,

You can try the below, it would give you the result.

AndroidElement email1 = new AndroidElement();
email1 =  driver.findElementByXPath("//android.widget.EditText[@text='Email']");
pass1.click();
email1.send_keys("11111111111");
**driver.hideKeyboard();**
AndroidElement pass1 = new AndroidElement();
pass1 = driver.findElementByXPath("//android.widget.EditText[@text='Password']");
pass1.click();
pass1.sendKeys("aaaaaaaaaa");	    
**driver.hideKeyboard();**
