### ISSUE TITLE
TypeError: Failed to execute 'createNSResolver' on 'Document': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by bayandin** [appium/appium#5454]
Error which occurs while closing/switching windows and trying to find some element:
```
invalid selector: Unable to locate an element with the xpath expression //h1[contains(@class, "page-title") and (contains(text(), "Photos"))] because of the following error:
TypeError: Failed to execute 'createNSResolver' on 'Document': parameter 1 is not of type 'Node'.
  (Session info: chrome=44.0.2403.128)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.11.0 x86_64) (Selenium::WebDriver::Error::InvalidSelectorError)
```

Fixed in https://github.com/appium/appium-atoms/pull/2

**Comment by sholland2882** [comment]
I'm having the same issue 
org.openqa.selenium.InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression //div[@id='main']/div[2]/div[6]/form[1]/div[1]/a because of the following error:
TypeError: Failed to execute 'createNSResolver' on 'Document': parameter 1 is not of type 'Node'.
  (Session info: chrome=45.0.2454.93)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.20 seconds

**Comment by AppiumUserForMobile** [comment]
I am having same issue  and it started happening all of a sudden from last couple of days. Tried with latest appium version and its still happening. Can someone confirm if this is the current bug in appium? If so, when would this be solved and what is the work around in the mean while? This is blocking us currently and appreciate any response. Thanks!
com.amazon.phoenix.driver.exception.BrowserDriverException: invalid selector: Unable to locate an element with the xpath expression //input[@id='addNewAddressButton'] because of the following error:
TypeError: Failed to execute 'createNSResolver' on 'Document': parameter 1 is not of type 'Node'.
  (Session info: chrome=45.0.2454.84)
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 3.13.0-58-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.23 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:30'
System info: host: 'tod-wrkr-shared-prod-2c-m3x-i-c600a31d.us-west-2.amazon.com', ip: '172.23.140.154', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.45-0.6.acc.624.45.283.amzn1acc.x86_64', java.version: '1.8.0_60'
Driver info: com.amazon.phoenix.driver.device.appium.SwipeableAppiumDriver

**Comment by bayandin** [comment]
Hey @sholland2882 and @AppiumUserForMobile 
The fix for this error in https://github.com/appium/appium-atoms/pull/2.
But even after it is merged you will will still get an 'exception'. But instead of TypeError you'll staring to get NoSuchElement for find_element or empty array for find_element**s** method.
Now you can just catch one more exception and handle it like in situation when element not found.

**Comment by AppiumUserForMobile** [comment]
Are you saying even after the patch, the issue still exists but will just now throw a different exception? If the original issue of not able to find the element even if it is present on the page fixed or not?

**Comment by AppiumUserForMobile** [comment]
And why does it happen all of a sudden? My tests were running fine on both Android and iphone but all of a sudden started failing from last couple of days. Appreciate your help!

**Comment by bayandin** [comment]
Yep, I believe it is and it is not a bug when element couldn't be found.
If you check original selenium [issue](https://code.google.com/p/selenium/issues/detail?id=8600) you'll see that before selenium returned `InvalidSelectorError ` and after some changes began to return `TypeError `.
