### ISSUE TITLE
xcode 7 GM , iphone 5s (9.0) sim with Appium 1.4.0 - Instrument Crashed and cant create a new sessoin

### ISSUE THREAD

**Issue by ashishraj14** [appium/appium#5617]
Hi folks,
just downloaded Xcode 7 GM and changed platform version to 9.0  and tried to run the existing iOS automation tests (which work fine on iOS8.4/8.2 with Appium 1.4.0)
Few of things which I have observed:
1. Simulator name was being truncated - fixed that issue
2. iphone 5s starts with the iOS9 black screen and it takes a very long time for the actual app to get loaded when launched via Appium GUI.
3. when running the scripts , the simulator never starts up and error message is "Error: A new session could not be created. (Original error: Instruments crashed on startup) (33)"

Has anyone come across this behaviour and can they provide any pointers on how to fix it ?

Thanks,
Ash

**Comment by amedvedjev** [comment]
try latest! 1.4.11

**Comment by ashishraj14** [comment]
Thanx! I tried to search for the installer but the latest that I could find
was 1.4.8
Where to find the 1.4.11 dmg file to install on my Mac?

**Comment by moizjv** [comment]
@ashishraj14 you can use our appium server :) ... we dont have 1.4.11 yet in dmg

**Comment by manishmittal79** [comment]
@moizjv : I am running into a problem. I have upgraded from xcode6 to xcode7. My app is still same, but iOS instrument is keep on crashing. I am using 1.4.11 but the problem persists.
![screen shot 2015-09-21 at 4 58 51 pm](https://cloud.githubusercontent.com/assets/2325064/10005248/26910ab8-6084-11e5-9a19-afeb7c11dae7.png)

Here is the screenshot of the logs.
![screen shot 2015-09-21 at 4 58 51 pm](https://cloud.githubusercontent.com/assets/2325064/10005272/4f06fdfe-6084-11e5-8328-94852dd8ab30.png)

Any kind of help and suggestion is appreciated.

**Comment by cougil** [comment]
We've the same problem (_Failed to start an Appium session, err was: Error: Instruments crashed on startup_) running Appium 1.4.8 trying to launch an iOS App with a Simulator.

We've found that it doesn't work even without an App (trying to run the SafariTest from the sample-code examples).

The interesting thing is that if the Simulator is opened Appium will close it correctly.

Here you can see the stacktrace of the problem in the Appium console:
```
info: [debug] [INST STDERR] dyld: could not load inserted library '/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib' because no suitable image found.  Did find:
	/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/third
info: [debug] [INST STDERR] party/iwd7/InstrumentsShim.dylib: mmap() error 1 at address=0x10FBBD000, size=0x00001000 segment=__TEXT in Segment::map() mapping /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib

info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator

info: [debug] Cleaning sim data files
info: Executing: xcrun simctl erase 16F5313C-53BD-4A6A-860F-40153B04323A with timeout 2000

info: [debug] Cleaning app data files

warn: Applications directory /Users/xxx/Library/Developer/CoreSimulator/Devices/16F5313C-53BD-4A6A-860F-40153B04323A/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/xxx/Library/Developer/CoreSimulator/Devices/16F5313C-53BD-4A6A-860F-40153B04323A/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Cleaning up appium session

error: Failed to start an Appium session, err was: Error: Instruments crashed on startup

info: [debug] Error: Instruments crashed on startup
    at [object Object].Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:440:31)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}
info: <-- POST /wd/hub/session 500 17201.565 ms - 182 
```

Best,

**Comment by manishmittal79** [comment]
Is there any work around??
I am kind of blocked.

Sent from my iPhone

On Sep 23, 2015, at 10:15, Nacho Cougil <notifications@github.com> wrote:

We've the same problem (*Failed to start an Appium session, err was: Error:
Instruments crashed on startup*) running Appium 1.4.8 trying to launch an
iOS App with a Simulator.

We've found that it doesn't work even without an App (trying to run the
SafariTest from the sample-code examples).

The interesting thing is that if the Simulator is opened Appium will close
it correctly.

Here you can see the stacktrace of the problem in the Appium console:

info: [debug] [INST STDERR] dyld: could not load inserted library
'/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib'
because no suitable image found.  Did find:
    /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/third
info: [debug] [INST STDERR] party/iwd7/InstrumentsShim.dylib: mmap()
error 1 at address=0x10FBBD000, size=0x00001000 segment=__TEXT in
Segment::map() mapping
/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib

info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for
instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator

info: [debug] Cleaning sim data files
info: Executing: xcrun simctl erase
16F5313C-53BD-4A6A-860F-40153B04323A with timeout 2000

info: [debug] Cleaning app data files

warn: Applications directory
/Users/xxx/Library/Developer/CoreSimulator/Devices/16F5313C-53BD-4A6A-860F-40153B04323A/data/Containers/Data/Application
doesn't exist. Have you run this simulator before?
warn: Applications directory
/Users/xxx/Library/Developer/CoreSimulator/Devices/16F5313C-53BD-4A6A-860F-40153B04323A/data/Containers/Bundle/Application
doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Cleaning up appium session

error: Failed to start an Appium session, err was: Error: Instruments
crashed on startup

info: [debug] Error: Instruments crashed on startup
    at [object Object].Instruments.onInstrumentsExit
(/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:440:31)
    at [object Object].<anonymous>
(/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
info: [debug] Responding to client with error:
{"status":33,"value":{"message":"A new session could not be created.
(Original error: Instruments crashed on
startup)","origValue":"Instruments crashed on
startup"},"sessionId":null}
info: <-- POST /wd/hub/session 500 17201.565 ms - 182

Best,

—
Reply to this email directly or view it on GitHub
<https://github.com/appium/appium/issues/5617#issuecomment-142614638>.

**Comment by moizjv** [comment]
It is fixed in later version of appium, though gui is not updated for it. You can try using appium server

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium.

**Comment by SrinivasanTarget** [comment]
@triager please close
