### ISSUE TITLE
scrollTo and scrollToExact issue Appium Driver

### ISSUE THREAD

**Issue by balajig18** [appium/appium#5660]
Im trying to use ScrollTo and scrollToExact to Find Element which is not present in visible part of screen.Both method is working fine. But if there is any touchable element like SpinnerButton present in path of scrolling means, then scrollTo and scrollToExact tapping that touchable element( Spinner Button) instead of scrolling

App Name = Selendroid-test-app
Page = Register a new User Page
Java_client=3.2.0
Appium Version = 1.4.0

**Comment by jlipps** [comment]
The Java client simply calls UIAutomation's [scrollToElementWithName](https://developer.apple.com/library/ios/documentation/ToolsLanguages/Reference/UIAScrollViewClassReference/#//apple_ref/javascript/instm/UIAScrollView/scrollToElementWithName) under the hood for `scrollToExact`. Since we don't have control over this Apple method we're unable to fix its behavior. Sorry--I recommend you submit a bug to Apple!
