### ISSUE TITLE
Tested Hybrid apps on Android real device - only get NATIVE_APP

### ISSUE THREAD

**Issue by greedypinky** [appium/appium#5691]
Tested with Appium version 1.4.13 (lastest as of today)
[steps]
I tried to load a Hybrid apps on Android real device for testing (Android OS 4.4.2).
The apps starts the splashscreen first and when the webview is loaded, it is switched to the
webview activity. I tried put some sleep to wait for the webview content to get loaded but 
the appium server can only give me back the "NATIVE_APP" context.
anyone knows how to fix this?

[test by wd client using Mocha]
it("should login successfully", function () {
  
 return driver
    .sleep(30000)
    .contexts()
      .then(function (ctxs) {
        console.log("What is the context after waiting for webview to load?" + ctxs);
        return driver.context(ctxs[ctxs.length - 1]);
      })
      .sleep(20000)
      .elementById("login-username").sendKeys("test@testcom");
     
  });

[log]
info: [debug] Waiting for pkg "xxx" and activity "com.xxx.activity
.WebviewActivity" to be focused
....
info: [debug] Device is at release version 4.4.2
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to 120 secs
info: [debug] Appium session started with sessionId 9afe0355-2f84-4ad5-ac09-6b74770678fa
info: <-- POST /wd/hub/session 303 10858.429 ms - 74
info: --> POST /wd/hub/session/9afe0355-2f84-4ad5-ac09-6b74770678fa/timeouts/implicit_wait {"ms":100
00}
info: [debug] Set Android implicit wait to 10000ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"9afe0355-2f84
-4ad5-ac09-6b74770678fa"}
info: <-- POST /wd/hub/session/9afe0355-2f84-4ad5-ac09-6b74770678fa/timeouts/implicit_wait 200 7.190
 ms - 76 {"status":0,"value":null,"sessionId":"9afe0355-2f84-4ad5-ac09-6b74770678fa"}
info: --> GET /wd/hub/session/9afe0355-2f84-4ad5-ac09-6b74770678fa/contexts {}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: C:\andriod\adt-bundle-windows-x86_64-20140702\sdk\platfor
m-tools\adb.exe -s 551bb0db shell "cat /proc/net/unix"
info: [debug] Available contexts:
info: [debug] []
info: [debug] Available contexts: NATIVE_APP
info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP"],"sessionId":"9af
e0355-2f84-4ad5-ac09-6b74770678fa"}
info: <-- GET /wd/hub/session/9afe0355-2f84-4ad5-ac09-6b74770678fa/contexts 200 54.745 ms - 86 {"sta
tus":0,"value":["NATIVE_APP"],"sessionId":"9afe0355-2f84-4ad5-ac09-6b74770678fa"}
info: --> GET /wd/hub/session/9afe0355-2f84-4ad5-ac09-6b74770678fa/context {}
info: [debug] Responding to client with success: {"status":0,"value":"NATIVE_APP","sessionId":"9afe0
355-2f84-4ad5-ac09-6b74770678fa"}
info: <-- GET /wd/hub/session/9afe0355-2f84-4ad5-ac09-6b74770678fa/context 200 3.171 ms - 84 {"statu
s":0,"value":"NATIVE_APP","sessionId":"9afe0355-2f84-4ad5-ac09-6b74770678fa"}
info: --> GET /wd/hub/session/9afe0355-2f84-4ad5-ac09-6b74770678fa/contexts {}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: C:\andriod\adt-bundle-windows-x86_64-20140702\sdk\platfor
m-tools\adb.exe -s 551bb0db shell "cat /proc/net/unix"
info: [debug] Available contexts: NATIVE_APP
info: [debug] []
info: [debug] Available contexts: NATIVE_APP
info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP"],"sessionId":"9af
e0355-2f84-4ad5-ac09-6b74770678fa"}
info: <-- GET /wd/hub/session/9afe0355-2f84-4ad5-ac09-6b74770678fa/contexts 200 104.179 ms - 86 {"st
atus":0,"value":["NATIVE_APP"],"sessionId":"9afe0355-2f84-4ad5-ac09-6b74770678fa"}
info: --> POST /wd/hub/session/9afe0355-2f84-4ad5-ac09-6b74770678fa/context {"name":"NATIVE_APP"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: C:\andriod\adt-bundle-windows-x86_64-20140702\sdk\platfor
m-tools\adb.exe -s 551bb0db shell "cat /proc/net/unix"
info: [debug] Available contexts: NATIVE_APP
info: [debug] []
info: [debug] Available contexts: NATIVE_APP
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"9afe0355-2f84
-4ad5-ac09-6b74770678fa"}

**Comment by GindiKhangura** [comment]
I'm seeing the same thing with another team's app that I'm testing.

If I log out the page source when on the webview, I see that the web elements are included in the XML UI layout and I am able to interact with them as if they were native objects. I did some searching and found in Appium's documentation (http://appium.io/slate/en/master/?ruby#automating-hybrid-apps) it is stated that you need to call <i><b>setWebContentsDebuggingEnabled</b></i> on the webview in the app's code in order to actually spy the web elements in their webview form (it is not clear if it is relative to the paragraph above about Selendroid or if it is indeed for any app).

We adapted our code to handle this and it works fine. There may be things that you have access to with the web element that you don't with the "wrapped" element, but I have not experimented enough to figure out what those could be.

On a side note, the documentation states "Appium also uses Selendroid under the hood for webview support on devices older than 4.4", when from my understanding, and correct me if I'm wrong, it is OS <4.2 that Appium uses Selendroid.
