### ISSUE TITLE
Change to WEBVIEW contexts on a browser opened by an app

### ISSUE THREAD

**Issue by vrunoa** [appium/appium#5728]
I have a test that opens an Android app, clicks on a button and launches the browser via an Intent. Is it possible to change to the **WEBVIEW** contexts on the browser opened by the app ? I'm only getting **NATIVE_APP** context after clicking on the button. 

Here's my test, 
[https://github.com/Urucas/AppiumTests/blob/master/open-browser/test.py](https://github.com/Urucas/AppiumTests/blob/master/open-browser/test.py) and a related [Appium discuss link](https://discuss.appium.io/t/can-we-handle-browser-opened-by-clicking-on-link-present-in-native-application/6479/8)

Thanks

**Comment by scottdixon** [comment]
Have you tried setting the `autoWebview` capability?

There's a great explanation here: https://discuss.appium.io/t/what-does-the-autowebview-desired-capability-really-do/69/2

**Comment by vrunoa** [comment]
@scottdixon i'm not getting the **WEBVIEW** contexts while i'm on Chrome. My test opens an app, clicks on a button, opens a browser via intent but after this, event with a sleep timeout the **WEBVIEW** context is never listed. 
On the [sauce.io doc link](http://sauceio.com/index.php/2014/06/live-panel-mobile-testing-with-appium-recap/) says:
```For Android, you could switch between the app and the Chrome browser without issue.``` but for this flow it's not working. 

Here are the test lines where I check for the **WEBVIEW** contexts
[https://github.com/Urucas/AppiumTests/blob/master/open-browser/test.py#L45-L50](https://github.com/Urucas/AppiumTests/blob/master/open-browser/test.py#L45-L50)
```
contexts = self.driver.contexts
has_webview = False
for i in range(0, len(contexts)):
  search = re.search('WEBVIEW', contexts[i])
  if search is not None:
    has_webview = True
```
printing the contexts var shows **[NATIVE_APP]**. 

I'm testing on a Nexus 7, Android 5.1.1, Chrome Version 46.0.2490.75

**Comment by scottdixon** [comment]
After you click the button that triggers Chrome app, `you can trigger a keyevent which will take you to the home screen. Then you can find the chrome icon and click on it.`

From there you should be able to automate the webview.

If you get stuck, send me your apk and I'll provide an example.

**Comment by vrunoa** [comment]
oh, now I understand @scottdixon . I'll change my test and let you know. Thanks!

**Comment by jane-misfit** [comment]
@vrunoa  Hi, Did you succeed?  I met the same problem.

**Comment by vrunoa** [comment]
hey @jane-misfit I still didn't found the best solution, i'm testing on a Samsung Galaxy S5 and on a Nexus 5, and they both have Chrome button on different places and different menu slide to search for the button. Today i'll try an implementation by searching for Chrome in the opened apps and let you know.

**Comment by vrunoa** [comment]
@jane-misfit @scottdixon clicking on the android chrome app list is not a solution: I continue to have just NATIVE_APP in the ```contexts``` list. I also try clicking on the Chrome button on the Nexus 7 launcher, and the Chrome icon inside the app menus list but still not having the WEBVIEW ```contexts```.  

Here's my test; [https://github.com/Urucas/AppiumTests/blob/master/open-browser/test.py#L59-L85](https://github.com/Urucas/AppiumTests/blob/master/open-browser/test.py#L59-L85)

**Comment by paulaladdin** [comment]
Why was this closed?  I am having this issue as well.

**Comment by kskrishnan** [comment]
I am seeing the same issue as well. Unable to get the WEBVIEW contexts.

**Comment by kskrishnan** [comment]
After some more research, I asked by Dev to set WebViewDebuggingEnabled = True and then I got the WEBVIEW Contexts shown. However, now, I am getting the error 
[debug] [Chromedriver] Changed state to 'stopped'
   [testng] [Chromedriver] Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: unable to discover open pages

Any pointers?

**Comment by imurchie** [comment]
Can you provide more of the server logs, @kskrishnan ?

**Comment by kskrishnan** [comment]
@imurchie - Upon further investigation, I found that Appium recognised webviews that are embedded within the App, but does not recognise the new page opened in a browser window (e.g. by clicking on a link / twitter sign-in, etc.). I am getting the errors below -

[testng] [debug] [AndroidDriver] Found webviews: ["WEBVIEW_xx.com.xxxxxx","WEBVIEW_com.android.browser"]
   [testng] [debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_xx.com.xxxxxx","WEBVIEW_com.android.browser"]
   [testng] [debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com.android.browser'
   [testng] [AndroidDriver] Cannot pass option true because Appium needs it to make chromeDriver work
   [testng] [AndroidDriver] Cannot pass option xx.com.xxxxxx because Appium needs it to make chromeDriver work
   [testng] [debug] [Chromedriver] Changed state to 'starting'
   [testng] [Chromedriver] Set chromedriver binary as: /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
   [testng] [Chromedriver] Killing any old chromedrivers, running: ps -ef | grep /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
   [testng] [Chromedriver] Successfully cleaned up old chromedrivers
   [testng] [Chromedriver] Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037
   [testng] [Chromedriver] [STDOUT] Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 9515
   [testng] Only local connections are allowed.
   [testng] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
   [testng] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.11.5\"}}}"
   [testng] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"xx.com.xxxxxx","androidUseRunningApp":true,"args":[],"extensions":[],"binary":"/Users/k.s.krishnan/Downloads/chromedriver","androidDevice...
   [testng] [JSONWP Proxy] Got response with status 200: {"sessionId":"378994f49a434c8cf086319c6510588f","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cda...
   [testng] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"xx.com.xxxxxx","androidUseRunningApp":true,"args":[],"extensions":[],"binary":"/Users/k.s.krishnan/Downloads/chromedriver","androidDevice...
   [testng] [JSONWP Proxy] Got response with status 200: {"sessionId":"3d80b6df7d0507b63725db0ff8cb85c8","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cda...
   [testng] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"xx.com.xxxxxx","androidUseRunningApp":true,"args":[],"extensions":[],"binary":"/Users/k.s.krishnan/Downloads/chromedriver","androidDevice...
   [testng] [JSONWP Proxy] Got response with status 200: {"sessionId":"0aca1dcdc9bea31756bdf28002a396df","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cda...
   [testng] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"xx.com.xxxxxx","androidUseRunningApp":true,"args":[],"extensions":[],"binary":"/Users/k.s.krishnan/Downloads/chromedriver","androidDevice...
   [testng] [JSONWP Proxy] Got response with status 200: {"sessionId":"8cb8660c926bcf1dd9747c52c786a6c4","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cda...
   [testng] [Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
   [testng] [debug] [Chromedriver] Changed state to 'stopped'
   [testng] [Chromedriver] Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: unable to discover open pages
   [testng]   (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.5 x86_64))
   [testng]     at JWProxy.command$ (lib/proxy.js:139:15)
   [testng]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
   [testng]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
   [testng]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
   [testng]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
   [testng]     at run (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
   [testng]     at /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
   [testng]     at flush (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
   [testng]     at nextTickCallbackWith0Args (node.js:420:9)
   [testng]     at process._tickCallback (node.js:349:13)
   [testng]  { [Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: unable to discover open pages
   [testng]   (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.5 x86_64))]
   [testng]   status: 13,
   [testng]   value: { message: 'unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.5 x86_64)' },
   [testng]   httpCode: 200 }
   [testng] [MJSONWP] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: unable to discover open pages
   [testng]   (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.5 x86_64))
   [testng]     at JWProxy.command$ (lib/proxy.js:139:15)
   [testng]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
   [testng]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
   [testng]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
   [testng]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
   [testng]     at run (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
   [testng]     at /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
   [testng]     at flush (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
   [testng]     at nextTickCallbackWith0Args (node.js:420:9)
   [testng]     at process._tickCallback (node.js:349:13)
