### ISSUE TITLE
Error: Unable to authorize simulated daemon

### ISSUE THREAD

**Issue by cliff76** [appium/appium#5735]
OS: OS X 10.10.5
Xcode 7
iOS 9.0
Appium Version 1.4.8 (Draco)

I am having trouble getting Appium to run on my iOS simulator. When I run it I constantly get: "Unable to authorize simulated daemon" errors. I've trinstalling Appium from npm when I 1st saw the error. I later tried running the Appium app which gave a different error. I finally tried running Appium from source following instructions here: https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/appium-from-source.md

I'm still getting the "Unable to authorize simulated daemon" errors in the console
followed by:
Permission to debug com.example.apple-samplecode.UICatalog was denied.

Appium is constantly launching and then killing my simulator and throwing these errors. I thought this would be related to my not running the authorization step but it still occurs even after I run authorize_ios. Thank you in advance for any help/guidance.

This is what I see in the Appium output:
I get this in the logs:
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST] Waiting for device to boot...
info: [debug] [INST STDERR] 2015-10-16 11:33:49.352 instruments[72332:30370864] -[XRSimulatorDevice prepareConnection:]: Unable to authorize simulated daemon (72364): 5
info: [debug] [INST STDERR] 2015-10-16 11:34:00.344 instruments[72332:30370858] Failed to connect to local pid watcher service: (os/kern) failure
info: [debug] [INST STDERR] 2015-10-16 11:34:06.443 instruments[72332:30370923] Attempting to change event horizon while disengage
info: [debug] [INST STDERR] 2015-10-16 11:34:06.448 instruments[72332:30370923] Attempting to change event horizon while disengage
info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Permission to debug com.example.apple-samplecode.UICatalog was denied.
info: [debug] [INSTSERVER] Instruments exited with code 253
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall Simulator

When I try to Launch Appium from the Appium app I get this:
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "8.1" --platform-name "iOS" --app "/Users/212474815/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/UICatalog.app" --show-ios-log --default-device

module.js:338
    throw err;
          ^
Error: Cannot find module 'argparse'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/parser.js:2:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by ccardoso** [comment]
Hello, I have the same problem... any ideas ?

**Comment by aghoshal** [comment]
I'm also getting similar issues ...

I tried using Custom server flags as --native-instruments-lib

... still getting this issue:

info: [debug] [INST STDERR] 2015-12-02 14:01:57.778 instruments[12059:358144] Failed to connect to local pid watcher service: (os/kern) failure

info: [IOS_SYSLOG_ROW ] Dec  2 14:01:57 --- last message repeated 1 time ---

info: [IOS_SYSLOG_ROW ] Dec  2 14:01:57 C02ML05UFD57 DTMobileIS[11989]: DTMobileIS(11989) [error]: 'mach_msg_send' failed: (ipc/send) invalid destination port (268435459)
info: [IOS_SYSLOG_ROW ] Dec  2 14:01:57 C02ML05UFD57 DTMobileIS[11989]: Unable to acquire task port after launch of pid 12065 (com.ge.ent.PredixGoReferenceApp)
info: [IOS_SYSLOG_ROW ] Dec  2 14:01:57 C02ML05UFD57 com.apple.CoreSimulator.SimDevice.7CF73FA4-AFB4-46CC-AC41-B1F125B8D014.launchd_sim[11966] (UIKitApplication:com.ge.ent.PredixGoReferenceApp[0x2734][12065]): Service exited due to signal: Killed: 9
info: [IOS_SYSLOG_ROW ] Dec  2 14:01:57 C02ML05UFD57 SpringBoard[11980]: [com.ge.ent.PredixGoReferenceApp (12065)] Kill failed. Error: No such process (3)
info: [debug] [INST STDERR] 2015-12-02 14:01:57.855 instruments[12059:358146] Attempting to change event horizon while disengage
info: [debug] [INST STDERR] 2015-12-02 14:01:57.855 instruments[12059:358214] Attempting to change event horizon while disengage
info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Permission to debug com.ge.ent.PredixGoReferenceApp was denied.
info: [debug] [INSTSERVER] Instruments exited with code 253
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [IOS_SYSLOG_ROW ] Dec  2 14:01:57 C02ML05UFD57 DTMobileIS[11989]: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn

info: [debug] Cleaning sim data files
info: node-simctl: Executing: xcrun with args: simctl erase 7CF73FA4-AFB4-46CC-AC41-B1F125B8D014 and timeout: 2000

info: node-simctl: Executing: xcrun with args: simctl erase 7CF73FA4-AFB4-46CC-AC41-B1F125B8D014 and timeout: 2000

info: [debug] Cleaning app data files

warn: Applications directory /Users/anindyaghoshal/Library/Developer/CoreSimulator/Devices/7CF73FA4-AFB4-46CC-AC41-B1F125B8D014/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/anindyaghoshal/Library/Developer/CoreSimulator/Devices/7CF73FA4-AFB4-46CC-AC41-B1F125B8D014/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Resetting Content and Settings for Simulator

info: node-simctl: Executing: xcrun with args: simctl erase 7CF73FA4-AFB4-46CC-AC41-B1F125B8D014 and timeout: 2000

info: [debug] Cleaning up appium session

info: [debug] Error: Instruments crashed on startup
    at [object Object].Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/lib/instruments.js:440:31)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

error: Failed to start an Appium session, err was: Error: Instruments crashed on startup
