### ISSUE TITLE
Implement `file` endpoint

### ISSUE THREAD

**Issue by EECOLOR** [appium/appium#5746]
The default selenium server supports uploading a file that can then be used in a file upload.

An example of such a call can be seen here: https://github.com/SeleniumHQ/selenium/blob/ab1e647d0fc8fc39e6b00ae94321ab228b6728f2/java/client/src/org/openqa/selenium/remote/RemoteWebElement.java#L124

The endpoint is `post("/session/:sessionId/file")`: https://github.com/SeleniumHQ/selenium/blob/ab1e647d0fc8fc39e6b00ae94321ab228b6728f2/java/client/src/org/openqa/selenium/remote/http/JsonHttpCommandCodec.java#L112

From a naive perspective it seems the endpoint could be added to `routes.js` and, with just a few modifications, send it using `push_file`.

The `js` version seems to be located here: https://github.com/SeleniumHQ/selenium/blob/f4a8391eb464d3762eab098fb7cf6aa90347e377/javascript/node/selenium-webdriver/remote/index.js#L324

An example of usage: https://gist.github.com/ashwingonsalves/8634de2a2e34a83f7942

**Comment by scottdixon** [comment]
cc @imurchie

**Comment by gitnickgit** [comment]
cc @mreicha

**Comment by gitnickgit** [comment]
Is there any way we can get this set to a higher prioritization?

**Comment by jlipps** [comment]
Pretty sure this is a non-starter. Mobile Safari doesn't work the same way desktop browsers work. When you click on a file input element, what happens in Mobile Safari is basically that the photo browser pops up and you can choose a photo.

So what you really want is a way to pre-populate the photo library so that you can then automate the UI to select the photo you want to "upload".

The Selenium file upload features are irrelevant in this scenario. All Selenium normally does is set the path of the uploaded file to something you choose (either something on the local machine or something which has been pre-uploaded and indexed to a remote host). But in Mobile Safari, there is no way to set anything like a "path" to a file to upload. All you can do is choose from the photo library.
