### ISSUE TITLE
What is the difference between noReset and fullReset?

### ISSUE THREAD

**Issue by chris1248** [appium/appium#5747]
What do both of these do, what are their differences and are they mutually exclusive?

**Comment by scottdixon** [comment]
No reset: don’t reset app state between sessions (IOS: don’t delete app plist files; Android: don’t uninstall app before new session)

Full reset: (iOS) Delete the entire simulator folder. (Android) Reset app state by uninstalling app instead of clearing app data. On Android, this will also remove the app after the session is complete.

**Comment by scottdixon** [comment]
Closing issue. Let me know if you have any further queries.
