### ISSUE TITLE
Unable to Launch Appium with xcode 7.0.1 and iphoneSimulator 8.4

### ISSUE THREAD

**Issue by ashishkumar1000** [appium/appium#5778]
Hey, 

I am on xcode 7.0.1 and appium 1.4.13, and when I try to launch appium with iOS 8.4, I am getting below error -

error : could not pre-launch appium: Error: Instruments crashed on startup

Further I found this in the appium log : 
[INST STDERR] dyld: could not load inserted library '/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib' because no suitable image found.  Did find:
	/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib: mmap() error 1 at address=0x10BB07000, size=0x00001000 segment=__T
info: [debug] [INST STDERR] EXT in Segment::map() mapping /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib

I am unable to figure out what is the problem here !

**Comment by moizjv** [comment]
try using appium server

**Comment by KashishAggarwal** [comment]
Facing this issue currently after perform RESET PREFERENCE in Appium, please help in resolving

Appium Server is not getting started after, performing Appium RESET PREFERENCES option and filling desired capabilities for IOS simulator. #517

**Comment by ashishkumar1000** [comment]
@moizjv - Nopes it also didn't work. This time thought excpetion is different. 

info: [debug] [INST STDERR] dyld: could not load inserted library '/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib' because no suitable image found.  Did find:
	/Applications/Appium.app/Contents/Resou
info: [debug] [INST STDERR] rces/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib: mmap() error 1 at address=0x1059FE000, size=0x00001000 segment=__TEXT in Segment::map() mapping /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib

error: Failed to start an Appium session, err was: Error: Instruments crashed on startup

info: [debug] Error: Instruments crashed on startup
    at [object Object].Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/lib/instruments.js:440:31)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

**Comment by uscengineer** [comment]
This issue also happens with iphone simulator 9.0 and 9.1

**Comment by divyanshugarg** [comment]
I also facing the same problem. Using Xcode 7.1,Appium 1.4.13, and tried with iOS 8.4, iOS 8.2 and iOS 9.0.
nfo: [debug] Attempting to run app on iPhone 6 (8.2)

info: [debug] Spawning instruments with command: /Volumes/Xcode/Xcode-beta.app/Contents/Developer/usr/bin/instruments -t /Volumes/Xcode/Xcode-beta.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (8.2)" com.apple.mobilesafari -e UIASCRIPT "/Users/z001nhb/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7"}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] dyld: could not load inserted library '/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib' because no suitable image found.  Did find:
	/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib: mmap() error 1 at address=0x10E6C6000, size=0x00001000 segment=__TEXT in Segment::map() mapping /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib
.
.
.

error: Could not pre-launch appium: Error: Instruments crashed on startup
warn: Applications directory /Users/z001nhb/Library/Developer/CoreSimulator/Devices/3F1E1F28-0F4A-4C89-91C8-00A864E1617A/data/Containers/Data/Application doesn't exist. Have you run this simulator before?

**Comment by hongqatest** [comment]
Please the following steps. It solved my issue.

My environment:
* Xcode (latest): Version 7.2 (7C68)
* Appium (latest): Version 1.4.13 (Draco)
* OS: OS X Yosemite Version 10.10.5

Steps to fix it:
* under iOS setting: select "Advanced" and check "Use Native Instruments Library"
* save
* relaunch he server

Hope it will help.

**Comment by ahmednasserswe** [comment]
thanks @hongqatest that worked for me :)

**Comment by scottdixon** [comment]
@ashishkumar1000 - reopen if @hongqatest's solution doesn't resolve your issue.
