### ISSUE TITLE
Error after upgrading to 1.4.13: [INST STDERR] dyld: could not load inserted library 

### ISSUE THREAD

**Issue by uscengineer** [appium/appium#5787]
Getting the following error after upgrading to 1.4.13 using OS X 10.11.1
```
[INST STDERR] dyld: could not load inserted library '/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib' because no suitable image found.  Did find:
	/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib: mmap() error 1 at address=0x108DAC000, size=0x00001000 segment=__TEXT in Segment::map() mapping /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib
```

This prevents the simulator from opening. Goes into a loop trying to open the simulator but never gets past this error.

**Comment by divyanshugarg** [comment]
I also facing the same problem. Using Xcode 7.1,Appium 1.4.13, and tried with iOS 8.4, iOS 8.2 and iOS 9.0.
nfo: [debug] Attempting to run app on iPhone 6 (8.2)

info: [debug] Spawning instruments with command: /Volumes/Xcode/Xcode-beta.app/Contents/Developer/usr/bin/instruments -t /Volumes/Xcode/Xcode-beta.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (8.2)" com.apple.mobilesafari -e UIASCRIPT "/Users/z001nhb/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7"}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] dyld: could not load inserted library '/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib' because no suitable image found.  Did find:
	/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib: mmap() error 1 at address=0x10E6C6000, size=0x00001000 segment=__TEXT in Segment::map() mapping /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib
.
.
.

error: Could not pre-launch appium: Error: Instruments crashed on startup
warn: Applications directory /Users/z001nhb/Library/Developer/CoreSimulator/Devices/3F1E1F28-0F4A-4C89-91C8-00A864E1617A/data/Containers/Data/Application doesn't exist. Have you run this simulator before?

**Comment by chemanth** [comment]
Could you try running authorize-ios.js inside appium bin folder ?

**Comment by scottdixon** [comment]
Try running with the `--native-instruments-lib` flag.

**Comment by uscengineer** [comment]
Thanks @chemanth and @scottdixon . It took both to make it work. Had previously tried --native-instruments-lib on its own but that did not work. After I ran the authorize-ios.js and added the flag I simulator now opens! Now I need to figure out why tests that were previously passing are now failing with no code changes.

**Comment by imurchie** [comment]
You can also try the fix for `iwd` in iOS 9+ here: https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/iwd_xcode7.md

**Comment by uscengineer** [comment]
@imurchie I am using the dmg file for appium. I would need to clone the repo to run the steps on that page right?

**Comment by imurchie** [comment]
Until the release of 1.4.14, the script is not there. At that time, you can go into the Appium.app (assuming that it is in the default location)

```shell
cd /Applications/Appium.app/Contents/Resources/node_modules/
```

Then follow the instructions in the document.

Instead of cloning the whole repo, though, you can just get the single file (https://github.com/appium/appium/blob/master/bin/xcode_iwd.sh) and execute it.

**Comment by divyanshugarg** [comment]
solved by running authorize-ios.js. Now, I am able to run simulator & App on below config:
xCode - 7.1
Appium 1.4.14
iOS - 9.1
App: mobileSafari
OS: 10.10.5

**Comment by iamsk** [comment]
Same error!
xCode - 7.1
Appium 1.4.13
iOS - 9.1
App: TestApp
OSX: 10.11.1

after download and execute the xcode_iwd.sh, still not ok

Into appium folder and run with this `--native-instruments-lib ` works ok.

**Comment by pavelzag** [comment]
Thanks @chemanth and @scottdixon. This one bugged me for some good weeks..
