### ISSUE TITLE
Appium failed to create session in case of Full Reset (A new session could not be created. (Original error: Could not navigate to webview! Err: Error: connect ECONNREFUSED)

### ISSUE THREAD

**Issue by divyanshugarg** [appium/appium#5881]
Appium failed to create session when running on 'Full Reset' mode. 

Problem Statement: Before start new execution, I need to download & install new version of my .ipa file (a Hybrid IOS App). So, I am using '--full-reset' flag when starting Appium server because previous version installed on device. 
Observation: If we check in the device, app perfectly un-install, install & lunch.  But in code, it failed with exception '(A new session could not be created. (Original error: Could not navigate to webview! Err: Error: connect ECONNREFUSED)'. 

Environment: Appium 1.4.13, xCode: 7.1 and platform: 9.1, OS: 10.10.5, iPod-touch 9.0.2

Sharing some capabilities, which might be help to give some idea.
capabilities.setCapability(MobileCapabilityType.APP,appPath);
capabilities.setCapability(MobileCapabilityType.LAUNCH_TIMEOUT,"360,000");
capabilities.setCapability("autoWebview",true);
new IOSDriver<WebElement>(remoteSeleniumUrl, capabilities);

Something need to notice notice in log: info: [debug] Waiting for 6000 ms before navigating to view.
Question: How to change this time?

Detail Appium LOGS:
info: [debug] Creating iDevice object with udid 1f16f41c4ded81a27826d0b6780a1a5b186d1f25

info: [debug] App is installed.

info: [debug] fullReset requested. Forcing app install.
info: [debug] Installing ipa found at /Users/z001nhb/ApplicationUnderTest/xxxx.ipa

info: [debug] Bundle found on device, removing before reinstalling.

info: [debug] [INST] 2015-11-27 08:27:48 +0000 Fail: The target application appears to have died

info: [debug] [INST STDERR] 2015-11-27 13:57:48.394 instruments[73816:1253915] Attempting to change event horizon while disengage

info: [debug] [INST] Instruments Trace Complete (Duration : 994.783325s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.

info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall Simulator

info: [debug] fullReset requested. Will try to uninstall the app.

info: [debug] Removed com.XXXXXXXXXXXXXXXX

info: [debug] Cleaning up appium session

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 1.396 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 0.827 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 1.153 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: [debug] Starting command proxy.

info: [debug] Instruments socket server started at /tmp/instruments_sock

info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 1f16f41c4ded81a27826d0b6780a1a5b186d1f25
info: On xcode 7.0, instruments-without-delay does not work, skippinginstruments-without-delay
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 1f16f41c4ded81a27826d0b6780a1a5b186d1f25 com.target.stores.mywork.daily -e UIASCRIPT "/Users/z001nhb/Library/Application Support/appium/bootstrap/bootstrap-5b08b331b944fae5.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And launch timeouts (in ms): {"global":2800000}

info: [debug] [INST STDERR] 2015-11-27 13:58:16.386 instruments[73861:1254811] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: Instruments is ready to receive commands

info: [debug] Instruments launched. Starting poll loop for new commands.
info: [debug] Setting bootstrap config keys/values
info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"

info: [debug] Socket data received (2 bytes)
info: [debug] Socket data being routed.
info: [debug] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;

info: [debug] [INST] 2015-11-27 08:28:20 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-11-27 08:28:20 +0000 Debug: responding with:

info: [debug] Socket data received (27 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":true}
info: [debug] Setting initial orientation to PORTRAIT
info: [debug] Pushing command to appium work queue: "au.setScreenOrientation('PORTRAIT')"
info: [debug] Sending command to instruments: au.setScreenOrientation('PORTRAIT')

info: [debug] [INST] 2015-11-27 08:28:20 +0000 Debug: Running system command #1: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":true}...

info: [debug] [INST] 2015-11-27 08:28:21 +0000 Debug: Got new command 1 from instruments: au.setScreenOrientation('PORTRAIT')

info: [debug] [INST] 2015-11-27 08:28:21 +0000 Debug: evaluating au.setScreenOrientation('PORTRAIT')

info: [debug] [INST] 2015-11-27 08:28:21 +0000 Debug: target.setDeviceOrientation("1")

info: [debug] [INST] 2015-11-27 08:28:22 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-11-27 08:28:22 +0000 Debug: responding with:

info: [debug] [INST] 2015-11-27 08:28:22 +0000 Debug: Running system command #2: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...

info: [debug] Socket data received (33 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Setting auto webview
info: [debug] Waiting for 6000 ms before navigating to view.

info: [debug] Navigating to most recently opened webview

info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray

error: [REMOTE] Could not connect to WebKitRemoteDebugger server

info: [debug] Cleaning up appium session
info: [debug] Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1688:12)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1582:21)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1569:21)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-hybrid.js:62:21)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/webkit-remote-debugger.js:77:14)
    at ClientRequest.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js:890:21)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not navigate to webview! Err: Error: connect ECONNREFUSED)","origValue":"Could not navigate to webview! Err: Error: connect ECONNREFUSED"},"sessionId":null}
info: <-- POST /wd/hub/session 500 47272.854 ms - 248 

error: Failed to start an Appium session, err was: Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED

**Comment by divyanshugarg** [comment]
"iosDriver.getContextHandles()" method returns below error on logs (working on the same environment as shared above). 
Just after lunch the Hybrid app on iPod-touch real device, try to execute "iosDriver.getContextHandles()". If we run the same app on i-Phone simulator (rest everything same) then methods works fine.

info: --> GET /wd/hub/session/ed83881c-79fd-4a61-8ae9-1b0fe3f58998/contexts {}
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
error: [REMOTE] Could not connect to WebKitRemoteDebugger server
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"ed83881c-79fd-4a61-8ae9-1b0fe3f58998"}
info: <-- GET /wd/hub/session/ed83881c-79fd-4a61-8ae9-1b0fe3f58998/contexts 500 7.920 ms - 293

**Comment by khallbec** [comment]
I think Im having the same problem. I just upgraded to Xcode 7 and this is my log:

 => appium
info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/kerrihallbeck/Production/trunk/Build/Products/Debug-iphonesimulator/Overstock.app","newCommandTimeout":"600","platformVersion":"9.0","waitForAppScript":"$.delay(2000); $.acceptAlert();","keepKeyChains":true,"locale":"en_US","platformName":"iOS","deviceName":"iPad Air"}}
info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: [debug] Using local app from desired caps: /Users/kerrihallbeck/Production/trunk/Build/Products/Debug-iphonesimulator/Overstock.app
info: [debug] Creating new appium session 92555b0c-2868-4503-88c9-035a553a5920
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version
info: [debug] Xcode version set to 7.0
info: [debug] Setting iOS SDK Version
info: [debug] iOS SDK Version set to 9.0
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.0","iOSSDKVersion":"9.0","deviceName":"iPad Air","platformVersion":"9.0"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (9.0)'
info: [debug] iOS sim UDID is 12F7582E-1842-4429-BF03-93B382D4E7BE
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/kerrihallbeck/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. D...ot manually modify!
info: [debug] Dynamic bootstrap path: /Users/kerrihallbeck/Library/Application Support/appium/bootstrap/bootstrap-f32e2b90692b09d4.js
info: [debug] Reusing dynamic bootstrap: /Users/kerrihallbeck/Library/Application Support/appium/bootstrap/bootstrap-f32e2b90692b09d4.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.0","iOSSDKVersion":"9.0","deviceName":"iPad Air","platformVersion":"9.0"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (9.0)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.0","iOSSDKVersion":"9.0","deviceName":"iPad Air","platformVersion":"9.0"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (9.0)'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall Simulator
info: [debug] Cleaning sim data files
info: [debug] Resetting simulator and saving Keychains
info: node-simctl: Executing: xcrun with args: simctl erase 12F7582E-1842-4429-BF03-93B382D4E7BE and timeout: 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/kerrihallbeck/Library/Developer/CoreSimulator/Devices/12F7582E-1842-4429-BF03-93B382D4E7BE/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/kerrihallbeck/Library/Developer/CoreSimulator/Devices/12F7582E-1842-4429-BF03-93B382D4E7BE/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Setting locale information
info: [debug] New locale: en_US
info: [debug] Writing new locale plist data
info: [debug] Locale was set
info: [debug] First time setting locale, or locale changed, killing existing Instruments and Sim procs.
info: [debug] Killall instruments
info: [debug] Killall Simulator
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 8.* simulator log capture
info: [debug] Not pre-launching simulator
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPad Air (9.0)
info: On xcode 7.0, instruments-without-delay does not work, skippinginstruments-without-delay
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPad Air (9.0)" /Users/kerrihallbeck/Production/trunk/Build/Products/Debug-iphonesimulator/Overstock.app -e UIASCRIPT "/Users/kerrihallbeck/Library/Application Support/appium/bootstrap/bootstrap-f32e2b90692b09d4.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-12-09 10:24:09.345 instruments[15291:1278204] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST] Waiting for device to boot...
info: [debug] [INST] 2015-12-09 17:24:44 +0000 Fail: The target application appears to have died
info: [debug] [INST STDERR] 2015-12-09 10:24:44.207 instruments[15291:1282313] Attempting to change event horizon while disengage
info: [debug] [INST] Instruments Trace Complete (Duration : 23.161316s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall Simulator
info: Launching instruments
info: [debug] Attempting to run app on iPad Air (9.0)
info: On xcode 7.0, instruments-without-delay does not work, skippinginstruments-without-delay
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPad Air (9.0)" /Users/kerrihallbeck/Production/trunk/Build/Products/Debug-iphonesimulator/Overstock.app -e UIASCRIPT "/Users/kerrihallbeck/Library/Application Support/appium/bootstrap/bootstrap-f32e2b90692b09d4.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST] Waiting for device to boot...
info: [debug] [INST STDERR] 2015-12-09 10:24:50.738 instruments[15388:1282929] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST STDERR] Instruments Usage Error : Timed out waiting for device to boot: "iPad Air (9.0)"
info: [debug] [INSTSERVER] Instruments exited with code 255
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #2
info: [debug] Killall Simulator
info: Launching instruments
info: [debug] Attempting to run app on iPad Air (9.0)
info: On xcode 7.0, instruments-without-delay does not work, skippinginstruments-without-delay
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPad Air (9.0)" /Users/kerrihallbeck/Production/trunk/Build/Products/Debug-iphonesimulator/Overstock.app -e UIASCRIPT "/Users/kerrihallbeck/Library/Application Support/appium/bootstrap/bootstrap-f32e2b90692b09d4.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST] Waiting for device to boot...
info: [debug] [INST STDERR] 2015-12-09 10:25:26.482 instruments[15463:1284458] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST] 2015-12-09 17:25:31 +0000 Fail: The target application appears to have died
info: [debug] [INST STDERR] 2015-12-09 10:25:31.598 instruments[15463:1284458] Attempting to change event horizon while disengage
info: [debug] [INST] Instruments Trace Complete (Duration : 4.850963s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #3
info: [debug] Killall Simulator
info: Launching instruments
info: [debug] Attempting to run app on iPad Air (9.0)
info: On xcode 7.0, instruments-without-delay does not work, skippinginstruments-without-delay
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPad Air (9.0)" /Users/kerrihallbeck/Production/trunk/Build/Products/Debug-iphonesimulator/Overstock.app -e UIASCRIPT "/Users/kerrihallbeck/Library/Application Support/appium/bootstrap/bootstrap-f32e2b90692b09d4.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST] Waiting for device to boot...
info: [debug] [INST STDERR] 2015-12-09 10:25:38.331 instruments[15538:1286386] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: Instruments is ready to receive commands
info: [debug] Instruments launched. Starting poll loop for new commands.
info: [debug] Setting bootstrap config keys/values
info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"
info: [debug] Socket data received (2 bytes)
info: [debug] Socket data being routed.
info: [debug] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;

info: [debug] [INST] 2015-12-09 17:25:43 +0000 Fail: The target application appears to have died
info: [debug] [INST STDERR] 2015-12-09 10:25:43.606 instruments[15538:1286378] Attempting to change event horizon while disengage
info: [debug] [INST] Instruments Trace Complete (Duration : 4.953175s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall Simulator
info: [debug] Cleaning sim data files
info: [debug] Resetting simulator and saving Keychains
info: node-simctl: Executing: xcrun with args: simctl erase 12F7582E-1842-4429-BF03-93B382D4E7BE and timeout: 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/kerrihallbeck/Library/Developer/CoreSimulator/Devices/12F7582E-1842-4429-BF03-93B382D4E7BE/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/kerrihallbeck/Library/Developer/CoreSimulator/Devices/12F7582E-1842-4429-BF03-93B382D4E7BE/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] We were in the middle of processing a command when instruments died; responding with a generic error
info: [debug] Cleaning up appium session
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: [object Object]
info: [debug] undefined
info: [debug] Responding to client with error: {"status":33,"value":{"message":"Instruments died while responding to command, please check appium logs","name":"UnknownError","origValue":"Instruments died while responding to command, please check appium logs"},"sessionId":null}
info: <-- POST /wd/hub/session 500 100377.954 ms - 230

**Comment by khallbec** [comment]
I upgraded the appium.app also and I see this in that log:
aunching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "500000" --pre-launch --debug-log-spacing --platform-version "8.4" --platform-name "iOS" --app "/Users/kerrihallbeck/Production/trunk/Build/Products/Debug-iphonesimulator/Overstock.app" --show-ios-log --show-ios-log --device-name "iPhone 6 Plus"

/Users/kerrihallbeck/.bash_profile: line 57: ll: command not found

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: [debug] Using local app from command line: /Users/kerrihallbeck/Production/trunk/Build/Products/Debug-iphonesimulator/Overstock.app
info: [debug] Creating new appium session 2fcc5de0-d40d-4014-9db8-422c5b62e0ee

info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version

info: [debug] Xcode version set to 7.0

info: [debug] Setting iOS SDK Version

info: [debug] iOS SDK Version set to 9.0
info: [debug] Checking whether instruments supports our device string

info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.0","iOSSDKVersion":"9.0","deviceName":"iPhone 6 Plus","platformVersion":"8.4"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 Plus (8.4)'
info: [debug] iOS sim UDID is 5B293066-49D1-43E0-ABF0-B84A0540F672
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/kerrihallbeck/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/kerrihallbeck/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js
info: [debug] Reusing dynamic bootstrap: /Users/kerrihallbeck/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.0","iOSSDKVersion":"9.0","deviceName":"iPhone 6 Plus","platformVersion":"8.4"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 Plus (8.4)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.0","iOSSDKVersion":"9.0","deviceName":"iPhone 6 Plus","platformVersion":"8.4"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 Plus (8.4)'
info: [debug] Parsed app Info.plist (as binary)

info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons

info: [debug] Killall iOS Simulator

info: [debug] Cleaning sim data files

info: node-simctl: Executing: xcrun with args: simctl erase 5B293066-49D1-43E0-ABF0-B84A0540F672 and timeout: 2000

info: [debug] Cleaning app data files

warn: Applications directory /Users/kerrihallbeck/Library/Developer/CoreSimulator/Devices/5B293066-49D1-43E0-ABF0-B84A0540F672/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/kerrihallbeck/Library/Developer/CoreSimulator/Devices/5B293066-49D1-43E0-ABF0-B84A0540F672/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed

info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 8.* simulator log capture

info: [debug] Not pre-launching simulator

info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPhone 6 Plus (8.4)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 Plus (8.4)" /Users/kerrihallbeck/Production/trunk/Build/Products/Debug-iphonesimulator/Overstock.app -e UIASCRIPT "/Users/kerrihallbeck/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7"}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] dyld: could not load inserted library '/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib' because no suitable image found.  Did find:
	/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib: mmap() error 1 at address=0x106890000, size=0x00001000 segment=__TEXT in Segment::map() mapping /A
info: [debug] [INST STDERR] pplications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib


info: [debug] [INSTSERVER] Instruments exited with code null

info: [debug] Killall instruments

info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator

**Comment by scottdixon** [comment]
These issues were opened some time ago. Please try with the latest version of Appium + open an issue if you get any problems.
