### ISSUE TITLE
nosign - default to true rather than false?

### ISSUE THREAD

**Issue by rompic** [appium/appium#5969]
There is an ongoing discussion concerning the nosign capability on the forum. would be great if a developer could join https://discuss.appium.io/t/why-does-appium-sign-the-apk-are-there-any-benefits/7434/3

**Comment by bootstraponline** [comment]
Selendroid requires the app apk and test apk to be signed with the same key. The expectation is that users configure a keystore via [desired capabilities](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md). For apps that don't care about how they're signed then the debug key works.

uiautomator (v1, what appium currently uses) doesn't care about if the app is signed or not. I agree it'd make sense to not bother resigning in the uiautomator driver situation if the app is already signed.

uiautomator v2 uses instrumentation and has the same requirements as selendroid for signing. 

The idea behind signing by default is that people can immediately begin testing with instrumentation. Otherwise the app won't even start which is a poor user experience.
