### ISSUE TITLE
Getting "Failed to start an Appium session, err was: Error: EPERM, rename <C:\Test_Branch_3.12\target\test-classes\apk\testApk.apk'

### ISSUE THREAD

**Issue by mayurdharmadhikari** [appium/appium#6043]
Hi,

I am trying to implement appium grid and connected 2 emulators(genymotion) to my windows PC.

Out of 2 devices, I could create driver for 1 device and for other device, I am getting Getting "Failed to start an Appium session, err was: Error: EPERM, rename <C:\Test_Branch_3.12\target\test-classes\apk\testApk.apk' while creating driver.

Below is the stacktrace:

[31merror[39m: Failed to start an Appium session, err was: Error: EPERM, rename 'C:\Test_Branch_3.12\target\test-classes\apk\testApk.apk'
[36minfo[39m: [debug] Error: EPERM, rename 'C:\Test_Branch_3.12\target\test-classes\apk\testApk.apk'
    at Error (native)
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: EPERM, rename 'C:\Test_Branch_3.12\target\test-classes\apk\testApk.apk')","errno":-4048,"code":"EPERM","path":"C:\Test_Branch_3.12\target\test-classes\apk\testApk.apk","origValue":"EPERM, rename 'C:\Test_Branch_3.12\target\test-classes\apk\testApk.apk'"},"sessionId":null}
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 19552.192 ms - 490[39m [90m[39m
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: EPERM, rename 'C:\Test_Branch_3.12\target\test-classes\apk\testApk.apk') (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 19.81 seconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'L-251947-P15', ip: '192.168.171.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'
Driver info: io.appium.java_client.android.AndroidDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
    at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:161)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:170)
    at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:82)
    at com.symantec.framework.driver.mobile.android.DriverAndroid.createDriver(DriverAndroid.java:89)
    at com.symantec.framework.driver.mobile.Mobile$Builder.build(Mobile.java:91)
    at com.symantec.nms.base.BaseTest.setUpMobileDriver(BaseTest.java:162)
    at com.symantec.nms.base.BaseTest.setupDevice(BaseTest.java:194)
    at com.symantec.nms.abat.tests.CallBlockingTest.setUp(CallBlockingTest.java:31)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
    at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)

I am using 1.4.13 appium version.

Any help would be really great for me!

**Comment by scottdixon** [comment]
Please try with appium 1.5 beta `npm install -g appium@beta`

**Comment by mayurdharmadhikari** [comment]
Thanks Scott, I will try it.

**Comment by ews-android** [comment]
scottixon. I am trying to run my testsuite from jenkins, and only one device is connected, but still getting same error on appium console.
I am on windows 7

Please help

**Comment by imurchie** [comment]
If you posted the server logs we could determine what directory is being written to. You will need to change the permissions to be able to write to that directory.

Alternatively, you can use the server flag `--tmp` to specify what directory Appium will use to store temporary files.

**Comment by Kashif-Ur-Rehman** [comment]
@imurchie.
here are my logs in appium console:-

info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\build-tools\23.0.3\zipalign.exe -f 4 "C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk" C:\Users\KASHIF~1.EWS\AppData\Local\Temp\11646-13740-1798ncj\appium.tmp
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> error: Failed to start an Appium session, err was: Error: EPERM, rename 'C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk'
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Error: EPERM, rename 'C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk'
>     at Error (native)


Not:- Jenkins is picking my testsuite code from jenkins.
and from jenkins I am executing this command in 
"Invoke top level maven commands":-
-X compile exec:java -Dexec.mainClass="edmx.StartApplication"

**Comment by imurchie** [comment]
Do you have access to `C:\Users\KASHIF~1.EWS\AppData\Local\Temp\11646-13740-1798ncj\`?

**Comment by Kashif-Ur-Rehman** [comment]
Yes, i ca see "appium.tmp" file in above folder.

and where in can set this flat --tmp ?

**Comment by ews-android** [comment]
Any idea guys ? how to fix it ?

I am having this issue from last 4 days..

**Comment by imurchie** [comment]
I still need the _full_ logs (in a gist) in order to make a full assessment.

**Comment by Kashif-Ur-Rehman** [comment]
@imurchie , here are complete logs from appium console:-


> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --full-reset --session-override --platform-name Android --platform-version 21 --automation-name Appium --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","sessionOverride":true,"fullReset":true,"logNoColors":true,"platformName":"Android","platformVersion":"21","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":0,"platformVersion":"5.1.1","app":"C:\\Program Files (x86)\\Jenkins\\jobs\\AndroidEDMXAutomation\\workspace\\Apps\\edmx\\android-edmx.apk","deviceName":"Nexus 5","platformName":"Android","browserName":"\"\"","appActivity":"com.edmx.supersonic.festivalguide.activity.TutorialActivity"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk
> info: [debug] Creating new appium session cdf387a1-7bf2-44e1-8317-ce8ad195e663
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.7.0_17
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\platform-tools\adb.exe
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\build-tools\23.0.3\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\build-tools\23.0.3\aapt.exe dump badging "C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk"
> info: [debug] badging package: com.edmx.supersonic.festivalguide
> info: [debug] badging act: com.edmx.supersonic.festivalguide.activity.TutorialActivity
> info: [debug] Parsed package and activity are: com.edmx.supersonic.festivalguide/com.edmx.supersonic.festivalguide.activity.TutorialActivity
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 060e8fae3443b73e
> info: [debug] Setting device id to 060e8fae3443b73e
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 060e8fae3443b73e wait-for-device
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 060e8fae3443b73e shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 060e8fae3443b73e shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: Device API level is: 22
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 060e8fae3443b73e shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk" "C:\Users\KASHIF~1.EWS\AppData\Local\Temp\com.edmx.supersonic.festivalguide" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk" "C:\Users\KASHIF~1.EWS\AppData\Local\Temp\com.edmx.supersonic.festivalguide"
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 060e8fae3443b73e push "C:\\Users\\KASHIF~1.EWS\\AppData\\Local\\Temp\\com.edmx.supersonic.festivalguide\\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\build-tools\23.0.3\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\build-tools\23.0.3\aapt.exe dump xmltree "C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk" AndroidManifest.xml
> info: [debug] Set app process to: com.edmx.supersonic.festivalguide
> info: [debug] Uninstalling com.edmx.supersonic.festivalguide
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 060e8fae3443b73e shell "am force-stop com.edmx.supersonic.festivalguide"
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\platform-tools\adb.exe -s 060e8fae3443b73e uninstall com.edmx.supersonic.festivalguide
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] Checking app cert for C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk.
> info: [debug] executing cmd: java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" "C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk"
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\build-tools\23.0.3\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\build-tools\23.0.3\zipalign.exe -f 4 "C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk" C:\Users\KASHIF~1.EWS\AppData\Local\Temp\11646-13740-1798ncj\appium.tmp
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> error: Failed to start an Appium session, err was: Error: EPERM, rename 'C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk'
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Error: EPERM, rename 'C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk'
>     at Error (native)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: EPERM, rename 'C:\\Program Files (x86)\\Jenkins\\jobs\\AndroidEDMXAutomation\\workspace\\Apps\\edmx\\android-edmx.apk')","errno":-4048,"code":"EPERM","path":"C:\\Program Files (x86)\\Jenkins\\jobs\\AndroidEDMXAutomation\\workspace\\Apps\\edmx\\android-edmx.apk","origValue":"EPERM, rename 'C:\\Program Files (x86)\\Jenkins\\jobs\\AndroidEDMXAutomation\\workspace\\Apps\\edmx\\android-edmx.apk'"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 14667.858 ms - 499 
> Killed Node Server.
> Appium server process ended

**Comment by ews-android** [comment]
@ Imurchie any idea ?

**Comment by imurchie** [comment]
Are you able to manually run the command `C:\Users\kashif-ur-rehman.EWS\AppData\Local\Android\sdk\build-tools\23.0.3\zipalign.exe -f 4 "C:\Program Files (x86)\Jenkins\jobs\AndroidEDMXAutomation\workspace\Apps\edmx\android-edmx.apk" C:\Users\KASHIF~1.EWS\AppData\Local\Temp\11646-13740-1798ncj\appium.tmp`?

**Comment by prateek-patel** [comment]
Hello guys,

Did we find any solution to this ??

I'm also facing the same error from the past 2 days, I'm also able to run the zipalign command from cmnd pormpt.

This is the full log on appium-
info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"noReset":true}
info: Console LogLevel: debug
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"
version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
info: <-- GET /wd/hub/status 200 12.322 ms - 105 {"status":0,"value":{"build":{"
version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":null,
"platformVersion":"6.0.1","app":"C:\\AutomationWorkspace\\Spitfire-IntegrationTe
sts-Telstra2\\telstra-android-telphdevtr01-3.0.171-aligned.apk","appWaitPackage"
:null,"deviceName":"android","platformName":"android","appActivity":"com.asurion
.android.digitalprotection.telstra.ui.ZeroActivity","autoLaunch":true,"appWaitAc
tivity":null,"udid":null,"appPackage":"com.telstra.asurion.android.digitalprotec
tion"}}
info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: [debug] Using local app from desired caps: C:\AutomationWorkspace\Spitfire
-IntegrationTests-Telstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk
info: [debug] Creating new appium session 0522d5eb-8fae-4b45-807a-b500fb816487
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.7.0_75
info: [debug] Checking whether adb is present
info: [debug] Using adb from C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe
info: [debug] Using fast reset? false
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe devices
info: [debug] 1 device(s) connected
info: Found device 03157df37a6de419
info: [debug] Setting device id to 03157df37a6de419
info: [debug] Waiting for device to be ready and to respond to shell commands (t
imeout = 5)
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe -s 03157df37a6de419 wait-for-device
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe -s 03157df37a6de419 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Getting device API level
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe -s 03157df37a6de419 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 23
info: Device API level is: 23
info: [debug] Extracting strings for language: default
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe -s 03157df37a6de419 shell "getprop persist.sys.language"
info: [debug] Current device persist.sys.language:
info: [debug] java -jar "C:\Appium\node_modules\appium\node_modules\appium-adb\j
ars\appium_apk_tools.jar" "stringsFromApk" "C:\AutomationWorkspace\Spitfire-Inte
grationTests-Telstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk" "C:\User
s\CWRPRA~1.PAT\AppData\Local\Temp\com.telstra.asurion.android.digitalprotection"

info: [debug] Reading strings from converted strings.json
info: [debug] Setting language to default
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe -s 03157df37a6de419 push "C:\\Users\\CWRPRA~1.PAT\\AppData\\Local\\Te
mp\\com.telstra.asurion.android.digitalprotection\\strings.json" /data/local/tmp

info: [debug] Checking whether aapt is present
info: [debug] Using aapt from C:\ide_android_sdk\android-sdk-windows\build-tools
\23.0.3\aapt.exe
info: [debug] Retrieving process from manifest.
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\build-tools\
23.0.3\aapt.exe dump xmltree C:\AutomationWorkspace\Spitfire-IntegrationTests-Te
lstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk AndroidManifest.xml
info: [debug] Set app process to: com.telstra.asurion.android.digitalprotection
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Checking app cert for C:\AutomationWorkspace\Spitfire-IntegrationT
ests-Telstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk.
info: [debug] executing cmd: java -jar C:\Appium\node_modules\appium\node_module
s\appium-adb\jars\verify.jar C:\AutomationWorkspace\Spitfire-IntegrationTests-Te
lstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk
info: [debug] App already signed.
info: [debug] Zip-aligning C:\AutomationWorkspace\Spitfire-IntegrationTests-Tels
tra2\telstra-android-telphdevtr01-3.0.171-aligned.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from C:\ide_android_sdk\android-sdk-windows\build-t
ools\23.0.3\zipalign.exe
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\build-tools\
23.0.3\zipalign.exe -f 4 C:\AutomationWorkspace\Spitfire-IntegrationTests-Telstr
a2\telstra-android-telphdevtr01-3.0.171-aligned.apk C:\Users\CWRPRA~1.PAT\AppDat
a\Local\Temp\116723-5720-1nr7gt5\appium.tmp
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
warn: UiAutomator did not shut down fast enough, calling it gone
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: EPERM, rename 'C:\Auto
mationWorkspace\Spitfire-IntegrationTests-Telstra2\telstra-android-telphdevtr01-
3.0.171-aligned.apk'
info: [debug] Error: EPERM, rename 'C:\AutomationWorkspace\Spitfire-IntegrationT
ests-Telstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk'
    at Error (native)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"
A new session could not be created. (Original error: EPERM, rename 'C:\\Automati
onWorkspace\\Spitfire-IntegrationTests-Telstra2\\telstra-android-telphdevtr01-3.
0.171-aligned.apk')","errno":-4048,"code":"EPERM","path":"C:\\AutomationWorkspac
e\\Spitfire-IntegrationTests-Telstra2\\telstra-android-telphdevtr01-3.0.171-alig
ned.apk","origValue":"EPERM, rename 'C:\\AutomationWorkspace\\Spitfire-Integrati
onTests-Telstra2\\telstra-android-telphdevtr01-3.0.171-aligned.apk'"},"sessionId
":null}
info: <-- POST /wd/hub/session 500 10994.106 ms - 520
info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":null,
"platformVersion":"6.0.1","app":"C:\\AutomationWorkspace\\Spitfire-IntegrationTe
sts-Telstra2\\telstra-android-telphdevtr01-3.0.171-aligned.apk","appWaitPackage"
:null,"deviceName":"android","platformName":"android","appActivity":"com.asurion
.android.digitalprotection.telstra.ui.ZeroActivity","autoLaunch":true,"appWaitAc
tivity":null,"udid":null,"appPackage":"com.telstra.asurion.android.digitalprotec
tion"}}
info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: [debug] Using local app from desired caps: C:\AutomationWorkspace\Spitfire
-IntegrationTests-Telstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk
info: [debug] Creating new appium session 97b4ccf2-a340-4c58-b658-ae93d3d73cb7
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.7.0_75
info: [debug] Checking whether adb is present
info: [debug] Using adb from C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe
info: [debug] Using fast reset? false
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe devices
info: [debug] 1 device(s) connected
info: Found device 03157df37a6de419
info: [debug] Setting device id to 03157df37a6de419
info: [debug] Waiting for device to be ready and to respond to shell commands (t
imeout = 5)
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe -s 03157df37a6de419 wait-for-device
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe -s 03157df37a6de419 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Getting device API level
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe -s 03157df37a6de419 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 23
info: Device API level is: 23
info: [debug] Extracting strings for language: default
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe -s 03157df37a6de419 shell "getprop persist.sys.language"
info: [debug] Current device persist.sys.language:
info: [debug] java -jar "C:\Appium\node_modules\appium\node_modules\appium-adb\j
ars\appium_apk_tools.jar" "stringsFromApk" "C:\AutomationWorkspace\Spitfire-Inte
grationTests-Telstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk" "C:\User
s\CWRPRA~1.PAT\AppData\Local\Temp\com.telstra.asurion.android.digitalprotection"

info: [debug] Reading strings from converted strings.json
info: [debug] Setting language to default
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\platform-too
ls\adb.exe -s 03157df37a6de419 push "C:\\Users\\CWRPRA~1.PAT\\AppData\\Local\\Te
mp\\com.telstra.asurion.android.digitalprotection\\strings.json" /data/local/tmp

info: [debug] Checking whether aapt is present
info: [debug] Using aapt from C:\ide_android_sdk\android-sdk-windows\build-tools
\23.0.3\aapt.exe
info: [debug] Retrieving process from manifest.
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\build-tools\
23.0.3\aapt.exe dump xmltree C:\AutomationWorkspace\Spitfire-IntegrationTests-Te
lstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk AndroidManifest.xml
info: [debug] Set app process to: com.telstra.asurion.android.digitalprotection
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Checking app cert for C:\AutomationWorkspace\Spitfire-IntegrationT
ests-Telstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk.
info: [debug] executing cmd: java -jar C:\Appium\node_modules\appium\node_module
s\appium-adb\jars\verify.jar C:\AutomationWorkspace\Spitfire-IntegrationTests-Te
lstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk
info: [debug] App already signed.
info: [debug] Zip-aligning C:\AutomationWorkspace\Spitfire-IntegrationTests-Tels
tra2\telstra-android-telphdevtr01-3.0.171-aligned.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from C:\ide_android_sdk\android-sdk-windows\build-t
ools\23.0.3\zipalign.exe
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: C:\ide_android_sdk\android-sdk-windows\build-tools\23.0.3\zipalign.exe -f 4 C:\AutomationWorkspace\Spitfire-IntegrationTests-Telstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk C:\Users\CWRPRA~1.PAT\AppData\Local\Temp\116723-5720-89n6w\appium.tmp
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
warn: UiAutomator did not shut down fast enough, calling it gone
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: EPERM, rename 'C:\Auto
mationWorkspace\Spitfire-IntegrationTests-Telstra2\telstra-android-telphdevtr01-
3.0.171-aligned.apk'
info: [debug] Error: EPERM, rename 'C:\AutomationWorkspace\Spitfire-IntegrationT
ests-Telstra2\telstra-android-telphdevtr01-3.0.171-aligned.apk'
    at Error (native)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"
A new session could not be created. (Original error: EPERM, rename 'C:\\Automati
onWorkspace\\Spitfire-IntegrationTests-Telstra2\\telstra-android-telphdevtr01-3.
0.171-aligned.apk')","errno":-4048,"code":"EPERM","path":"C:\\AutomationWorkspac
e\\Spitfire-IntegrationTests-Telstra2\\telstra-android-telphdevtr01-3.0.171-alig
ned.apk","origValue":"EPERM, rename 'C:\\AutomationWorkspace\\Spitfire-Integrati
onTests-Telstra2\\telstra-android-telphdevtr01-3.0.171-aligned.apk'"},"sessionId
":null}
info: <-- POST /wd/hub/session 500 22811.625 ms - 520

**Comment by hareeshnkp** [comment]
Hi ,
I am also getting the following error while running devices in parallel.
Any one gets the solution for this ? Please help..
warn: UiAutomator did not shut down fast enough, calling it gone
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: EPERM, rename

**Comment by saikrishna321** [comment]
@prateek-patel pls upgrade to 1.6.5v and give it a try .. make sure you set UIAutomator2 as AutomationName
