### ISSUE TITLE
Android M Grant permissions

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#6091]
It'd be nice if appium granted permissions by default in Android M like [calabash does](https://github.com/calabash/calabash-android/commit/54f7a29828af9f429444d08922e7b1caeed1e932)

**Comment by bootstraponline** [comment]
In addition to the `-g` flag on install, it'd be nice to support an interface to the pm grant/revoke commands.

**Comment by ednguyen7** [comment]
@bootstraponline 

Have you found a workaround for this? 

How do I add the -g flag on app install when running an appium test?

**Comment by bootstraponline** [comment]
There's no work around other than implementing the fixes I mentioned in an appium fork.

You can easily make the change [in this module](https://github.com/appium/appium-adb/blob/6a897e93c7f275b97f272e46bc72d737f4ae8119/lib/tools/apk-utils.js#L171).

**Comment by Domuska** [comment]
I am also hoping something like this could be added, I saw somewhere that something of a workaround could be done with this on Java:

`Runtime.getRuntime().exec("adb install -g path_to_apk")`

and launching the app manually afterwards, but it did not seem to help to work too well, if driver.launchApp() is done after that the app will still ask for permissions for some reason.

I don't think that would be a nice way to do it either. No clue how it would work in a situation where you are working in a cloud situation either.

This is problematic since my application asks for permissions even before the mainactivity starts up, so appium will think that the app never launched and hang there, leading to the session stopping.

**Comment by bootstraponline** [comment]
I think [linkedin/test-butler](https://github.com/linkedin/test-butler) is an even better fix to the Android permissions issue.

**Comment by amedvedjev** [comment]
Fix does not work. pls look at comment https://github.com/appium/appium-adb/pull/173

**Comment by mykola-mokhnach** [comment]
This is how we workaround it in our automated tests:

```java

    public static final String[] STANDARD_WIRE_PERMISSIONS = new String[]{
            "android.permission.WRITE_EXTERNAL_STORAGE",
            "android.permission.READ_CONTACTS",
            "android.permission.RECORD_AUDIO",
            "android.permission.CAMERA",
            "android.permission.READ_PHONE_STATE",
            "android.permission.ACCESS_FINE_LOCATION"
    };

......

       if (isAutoAcceptOfSecurityAlertsEnabled &&
                    ((WireAndroidDriver) drv).getOSVersion().compareTo(new DefaultArtifactVersion("6.0")) >= 0) {
                AndroidCommonUtils.grantPermissionsTo(CommonUtils.getAndroidPackageFromConfig(getClass()),
                        AndroidCommonUtils.STANDARD_WIRE_PERMISSIONS);
            }

......

    public static void grantPermissionsTo(String bundleId, String... perms) throws Exception {
        for (String permissionName : perms) {
            executeAdb(String.format("shell pm grant %s %s", bundleId, permissionName));
        }
    }

......
```

This method is executed as soon as the application under test is successfully installed.

**Comment by jlipps** [comment]
This feature request is being tracked in #5561. We'll pursue the strategy mentioned here though.
