### ISSUE TITLE
[Appium-1.5] - Android bootstrap socket crashed when tests run in parallel 

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#6202]
## The problem

Not able to trigger android tests in parallel using appium 1.5 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5 
* Last Appium version that did not exhibit the issue (if applicable):1.4.16
* Desktop OS/version used to run Appium: Mac 10.11.3
* Node.js version (unless using Appium.app|exe):v5.6.0
* Mobile platform/version under test:genymotion - nexus 5 
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe:CLI

## Details

When triggering android tests in parallel, android bootstrap socket crashes and this happens only when two appium server is triggered with different port and bootstrap port 

appium --session-override -p 62508 -U 192.168.56.101:5555 -bp 57364
appium --session-override -p 62350 -U 192.168.56.104:5555 -bp 56494

I have a sample example to reproduce the issue. As i'm using parallel GNU, please install through 
```brew install parallel```
https://github.com/saikrishna321/AppiumAndroidParallelExecution

## Link to Appium logs

https://gist.github.com/saikrishna321/07e5a648b825b6274555

**Comment by saikrishna321** [comment]
@SrinivasanTarget @imurchie @bootstraponline could some please help me on this

**Comment by SrinivasanTarget** [comment]
@imurchie Can you help on this?

**Comment by saikrishna321** [comment]
ping @imurchie any help on this ?

**Comment by crashbell** [comment]
I ran into the same problem either, my log is here https://gist.github.com/crashbell/19d6ce558b42aa424e64. Hope that it would help somehow.

**Comment by crashbell** [comment]
Take a look on [appium-android-bootstrap](https://github.com/appium/appium-android-bootstrap) and it turns out to some interesting points.
Seems like the port is hardcoded here: https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap%2Fsrc%2Fio%2Fappium%2Fandroid%2Fbootstrap%2FBootstrap.java#L36

And my opinion would be stronger when I saw this: https://github.com/appium/appium-android-driver/blob/master/lib%2Fdriver.js#L14

I tried with `---bootstrap-port` or `-bp` but it obviously ended up with `4724` (the port default) for Android Bootstrap. There's some reason makes Appium 1.5 get rid of this flexibility, I don't know. 

To clarify, I think the root cause is that 2 or more devices send `SHUTDOWN` command to the same running server. The code below will be triggered and that server will stop listening all its sockets:
https://github.com/appium/appium-android-bootstrap/blob/31464f03e23b41942bd2fa617011666267270770/bootstrap/src/io/appium/android/bootstrap/SocketServer.java#L163

**Comment by imurchie** [comment]
This is a bug. I'll get on fixing. Thanks!

**Comment by SrinivasanTarget** [comment]
Thanks for looking into this.

**Comment by crashbell** [comment]
Thanks a lot!

**Comment by imurchie** [comment]
The issue is not on the Bootstrap side (as @crashbell's ideas above). That server exists in a different instance on different devices. So each device has a bootstrap process connected to port `4724`. 

On problem is that we were not forwarding the ports correctly. There is a further issue that I'm trying to identify now. There seems to be a race condition, in that two tests can be run if they are staggered ever-so-slightly, but if they start at (pretty much) the same time one will fail when the other ends.

**Comment by imurchie** [comment]
I think that I have fixed this. At least my tests work.

Running from source, can you update `appium-android-driver` (to 1.6.14) and `appium-android-bootstrap` (to 2.5.2, which should happen on its own with the updated driver) and try?

Thanks!

**Comment by SrinivasanTarget** [comment]
Sure, we will try and update you @imurchie.

Thanks.

**Comment by crashbell** [comment]
I can't update both now, maybe NPM needs time to sync the build. I will give it a try asap. Thank you @imurchie!

**Comment by crashbell** [comment]
It's working on my side!

**Comment by saikrishna321** [comment]
@imurchie Thanks a lot for the fix, i retested with the latest source and it works fine :+1: 

Closing the issue

**Comment by imurchie** [comment]
Awesome! Thanks!

**Comment by asharm9** [comment]
@imurchie 

Is the fix for this bootstrap crash issue available in the latest stable version 1.5.3 ?
Coz i tried using 1.5.3 both on mac and windows machine..... but i am still facing this issue of bootstrap crash for Android parallel run

**Comment by saikrishna321** [comment]
@asharm9 yah this has been fixed. I'm running 1.5.3 and works fine on running tests in parallel..

**Comment by asharm9** [comment]
@saikrishna321  Are you using the same bootstrap port number for multiple appium servers for different devices or different port numbers for each of the server. And if same, are you using any specific bootstrap port ?

**Comment by saikrishna321** [comment]
I'm providing different bootstrap ports for different appium sessions

**Comment by asharm9** [comment]
@saikrishna321  Thanks

**Comment by PratapSingh09** [comment]
this framework [](https://github.com/saikrishna321/PageObjectPatternAppium) does not work on windows 7 right??
iOS and Android both are not running parallelly on Windows 7 with below configuration:
appium version: 1.7.1
java: 1.8

Please let me know,How to run this framework and  on which platform/OS

**Comment by PratapSingh09** [comment]
This framework  [(https://github.com/saikrishna321/PageObjectPatternAppium)]  does not work on windows 7 right??
iOS and Android both are not running parallelly on Windows 7 with below configuration:
appium version: 1.7.1
java: 1.8

Please let me know,How to run this framework and on which platform/OS

**Comment by asharm9** [comment]
First of all my question is.. how can iOS run on windows machine ??
is there a way to achieve that..... ??

**Comment by PratapSingh09** [comment]
Yes, right that is the reason I am asking
We can use VMWare to run the iOS device on Windows.
But what I am asking is there any way we can run both devices attached to one OS and run them parallel.
If not then this framework will run individually the test cases on Android and iOS, not parallel.

Note: we have mention here that we can run test cases paralley and have not mention how?

So my question is  HOW??

**Comment by asharm9** [comment]
I am running both iOS and Android on one mac machine. By running to
different servers for iOS and Android.
Not sure about Windows OS

**Comment by Anand093** [comment]
Hi @imurchie,

I am getting same socket crash when i run 2 tests in parallel.

I am using maven (pom.xml) as a dependencies, how will i update.
 appium-android-driver (to 1.6.14) and appium-android-bootstrap (to 2.5.2, which should happen on its own with the updated driver)  ?

Thanks,
Manish Anand
