### ISSUE TITLE
Appium 1.5 doesn't launch Android emulator

### ISSUE THREAD

**Issue by jonesdar** [appium/appium#6233]
## The problem

1.4.16 with the following capabilities would automatically launch the Android emulator:

    platformName: 'Android',
    deviceName: 'Android Emulator',
    app: path.resolve('../myapp.apk'),
    avd: 'Nexus_5_API_21'

1.5 doesn't do that - logs show it trying to find connected devices for a while and then it fails with 'Error: Could not find a connected Android device.'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16 
* Desktop OS/version used to run Appium: Mac OS X Yosemite 10.10.5
* Node.js version (unless using Appium.app|exe): 5.4.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

See https://discuss.appium.io/t/appium-1-5-doesnt-launch-android-emulator/8883

## Link to Appium logs

https://gist.github.com/jonesdar/2b1e1f4c3895c4b8889d

**Comment by scottdixon** [comment]
Can you please post your successful 1.4.16 logs?

Also, what's your output of `adb devices`?

**Comment by jonesdar** [comment]
1.4.16 logs here: https://gist.github.com/jonesdar/7ed2a20c60a58f5e001f

`adb devices` shows nothing (which is expected because I have no connected devices and no emulators running)

I tried several major releases of Appium (I went back as far as 1.0.0) and the launch worked in all of them.

**Comment by EfiMaZa** [comment]
Appium 1.7 doesn't launch Android emulator

[HTTP] <-- POST /wd/hub/session 500 22010 ms - 179
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/mattivisti/Work/Appium/sample-code/sample-code/apps/ContactManager/ContactManager.apk","deviceName":"Nexus_6_API_25","platformName":"Android","platformVersion":"7.1.1","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/mattivisti/Work/Appium/sample-code/sample-code/apps/ContactManager/ContactManager.apk","deviceName":"Nexus_6_API_25","platformName":"Android","platformVersion":"7.1.1","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1536826188590 (11:09:48 GMT+0300 (EEST))
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v3.7.0) session
[Appium] Capabilities:
[Appium]   app: /Users/mattivisti/Work/Appium/sample-code/sample-code/apps/ContactManager/ContactManager.apk
[Appium]   deviceName: Nexus_6_API_25
[Appium]   platformName: Android
[Appium]   platformVersion: 7.1.1
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"app":"/Users/mattivisti/W...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: decccafa-1ce3-4306-939b-79f112b0897d
[AndroidDriver] Java version is: 1.8.0_181
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Getting connected devices...
[ADB] 0 device(s) connected
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[ADB] Could not find devices, restarting adb server...
[ADB] Restarting adb
[ADB] Killing adb server on port 5037
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[BaseDriver] Event 'newSessionStarted' logged at 1536826210060 (11:10:10 GMT+0300 (EEST))
[MJSONWP] Encountered internal error running command: Error: Could not find a connected Android device.
[MJSONWP]     at ADB.getDevices$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:196:13)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at enqueueResult (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
[MJSONWP]     at new Promise ()
[MJSONWP]     at new F (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
[MJSONWP]     at AsyncIterator.enqueue (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
[MJSONWP]     at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at Object.runtime.async (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
[MJSONWP]     at getDevices (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/build/lib/tools/system-calls.js:409:38)
[MJSONWP]     at ADB.getDevices$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-adb/lib/tools/system-calls.js:213:20)
[MJSONWP]     at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP]     at 
[HTTP] <-- POST /wd/hub/session 500 21474 ms - 179
[HTTP] 

adb devices shows nothing (which is expected because I have no connected devices and no emulators running)
