### ISSUE TITLE
Wifi change crashes appium 1.5

### ISSUE THREAD

**Issue by adamf663** [appium/appium#6261]
## The problem

Killing an associated access point and/or reenabling it crashes appium 1.5.  This problem also exists in appium 1.4.16.

## Environment
It is a real device;  we are developing a lollipop distribution for our hardware.
Running under ubuntu 14.04

It doesn't matter what is running;  killing and/or enabling wifi will crash appium.

[logfile.zip](https://github.com/appium/appium/files/166058/logfile.zip)

**Comment by scottdixon** [comment]
I wonder if this is related to https://github.com/appium/appium-android-driver/issues/33 

Although it looks like you're using gestures to turn off wifi.

Any chance you can share your test script?

**Comment by adamf663** [comment]
I don't have to touch the phone.  All I need do is turn the AP on or off and appium will crash.  It seems to use a network connection and the phone's handoff/roaming logic interrupts appium's connection and appium makes no attempt to recover.

----- Original Message -----

**Comment by SrinivasanTarget** [comment]
@adamf663 Please try a latest version of appium-android-driver and we have done some improvements there.

**Comment by adamf663** [comment]
I've been forced to abandon appium as issuing adb commands crashes appium and nobody at appium gives a shit.


----- Original Message -----

**Comment by imurchie** [comment]
And therein lies the rub. "Nobody at appium gives a shit". This is an **open source project**, provided to you for **free**. The people developing it do give a shit. Deeply. But being entitled, and demanding something be done despite nebulous and irreproducible problems, does not engender people helping.

The code is there. If you cared, rather than just wanting folks to bend over backwards for you, you would do something about the problems. We would have been happy to give you support.

**Comment by adamf663** [comment]
Funny how other open source projects are able to put out releases that aren't so buggy as to be useless.  
Imagine if testNG crashed any time a java list was used.  Or if eclipse crashed anytime there was console output.

Version 1.5.x should never have been released.  It's garbage.  

----- Original Message -----

**Comment by SrinivasanTarget** [comment]
@triager please close
