### ISSUE TITLE
Can't find reset.sh under appium folder?

### ISSUE THREAD

**Issue by mandymatiantian** [appium/appium#6507]
## Can't find reset.sh file

I tried to follow tutorial in "Install Ruby", followings are the text 
"Run reset.sh. When running reset.sh, make sure to be on Xcode 5.0.2 for best results. You may have problems if you reset on Xcode 4.6.3 and then switch to a newer Xcode.
cd appium; ./reset.sh"

I couldn't find reset.sh file, even though I have installed appium successfully, attached the logs below:
Mandys-MacBook-Pro:appium mandyma$ npm install -g appium
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js
/usr/local/bin/authorize-ios -> /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios
/usr/local/lib
└── appium@1.5.2 

I tried to run command node . and got following error:
Mandys-MacBook-Pro:appium mandyma$ node .
module.js:440
    throw err;
    ^

Error: Cannot find module '/Users/mandyma/Documents/appium'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3

Thank you for your advice!
## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
The advice is wrong. Can you point me to the tutorial?

After installing Appium with `npm install -g appium` all you need to do is run `appium`.

**Comment by mandymatiantian** [comment]
http://appium.io/slate/en/tutorial/ios.html?ruby#install-ruby
Here is the tutorial link, thanks!

**Comment by SrinivasanTarget** [comment]
@triager please label : Documentation

**Comment by darthpelo** [comment]
I confirm: the iOS tutorial probably is out of date: 

> Clone appium
> git clone git://github.com/appium/appium.git
> 
> Run reset.sh. When running reset.sh, make sure to be on Xcode 5.0.2 for best results. You may have problems if you reset on Xcode 4.6.3 and then switch to a newer Xcode.
> cd appium; ./reset.sh
> 
> If you see config errors, try cleaning git. git clean -dfx; git reset --hard
> 
> You can also reset by platform. ./reset.sh --ios
> 
> Authorize for testing. Must run reset.sh as mentioned above before running the grunt task. If you’re only testing Android, this can be skipped.
> sudo `which grunt`; authorise
> 
> Start appium.
> $ node .

**Comment by gwpantazes** [comment]
Same with the Android tutorial at http://appium.io/slate/en/tutorial/android.html, it also references reset.sh. 
I just went through the android tutorial and at the Install Ruby section, there seem to be some out of date things which didn't work quite right. http://appium.io/slate/en/tutorial/android.html?java#install-ruby
Are the tutorials out of sync with the docs?

**Comment by imurchie** [comment]
Can you be more specific about the problems?

**Comment by gwpantazes** [comment]
Alright, specifically the install ruby section of http://appium.io/slate/en/tutorial/android.html?java#install-ruby

These brew commands seem out of order. Possibly split them up into install/already installed:
> Install nodejs using brew.
>
>     brew update
>     brew upgrade node
>     brew install node

Installing grunt according to the tutorial doesn't work as described
> Install grunt.
>
>     npm install -g grunt grunt-cli
>
> Run the version command from the appium folder. If you’re not in that folder, the grunt version will not display.
>
>     grunt --version
>     grunt-cli v0.1.13
>     grunt v0.4.2

Instead, only grunt-cli shows its version:

    somebody@somebodys-MacBook-Pro:~$ grunt --version
    grunt-cli v1.2.0

The one-liner `Install ant if it’s not already installed.` could be more descriptive. Links should be present pointing to:

- the downloads page: http://ant.apache.org/bindownload.cgi
- the install instructions: http://ant.apache.org/manual/install.html

The user should be informed that ant should be downloaded as binary and extracted to some recommended location on their system (on MacOSX, ~/Library/apache-ant-x.x.x?), and ANT_HOME should be put into their path similarly to the android tools.

Here would be a potential Apache Ant bash_profile section

    $ nano ~/.bash_profile
    export ANT_HOME="${HOME}/Library/apache-ant-1.9.7" # Add ANT_HOME
    PATH="${PATH}:$ANT_HOME/bin"                       # Add ant bin to PATH
    export PATH

And ant can be verified with `ant -version`.

Maven can now be installed with a brew command `brew install maven`, which would be more helpful and concise to the user. It can be checked with`mvn --version`.

It's already been said that this portion is out of date:
> Run reset.sh. When running reset.sh, make sure to be on Xcode 5.0.2 for best results. You may have problems if you reset on Xcode 4.6.3 and then switch to a newer Xcode.
>
>     cd appium; ./reset.sh
> If you see config errors, try cleaning git. `git clean -dfx; git reset --hard`
> You can also reset by platform. `./reset.sh --ios`

But the last portion is also out of date because it doesn't work 😦
> Authorize for testing. Must run reset.sh as mentioned above before running the grunt task. If you’re only testing Android, this can be skipped.
>
>     sudo `which grunt`; authorize
>

We installed grunt globally earlier via npm, but when I try to run the sudo command, it fails. See [this gist of shell output in which grunt is not found, then no gruntfile is found](https://gist.github.com/gwpantazes/c49d55f3b5299e156c55de212221a1f5). Figuring out why this happens and including a fix in the tutorial/docs would be helpful to the user.

> Start appium.
>
>     $ node .
> 

Finally, this node statement fails with the original error in this thread posted by @mandymatiantian 

    module.js:442
        throw err;
        ^

    Error: Cannot find module '/Users/tester/repo/appium'
        at Function.Module._resolveFilename (module.js:440:15)
        at Function.Module._load (module.js:388:25)
        at Module.runMain (module.js:575:10)
        at run (bootstrap_node.js:352:7)
        at startup (bootstrap_node.js:144:9)
        at bootstrap_node.js:467:3

I'd be happy to submit a pull request with some fixups to appium.io, but certain things I can't find the answer to easily, such as how to "run appium" and what's going on with the global install of grunt.

Environment
===

OS: Mac OSX 10.11.6 El Capitan
Appium CLI git revision = `32d5b7a132a61ab84fa5e182e89147c8d9242fbb`
Appium App (NOT HOOKED UP): v1.5.3
Node Version: v6.3.1

**Comment by imurchie** [comment]
A PR Would be awesome! And thanks for the detailed write-up.

The repository where this lives is https://github.com/appium/tutorial

As for grunt, it's not needed anymore. I've updated that in [this PR](https://github.com/appium/tutorial/pull/27).

**Comment by mbaroi** [comment]
What's the work-around since it seems that grunt isn't necessary and the rest of the other parts to getting appium to work? I've been trying to get this to work for a while now. Thanks!

**Comment by psswf1172** [comment]
Just wondering where to find the updated instructions?  I followed the tutorial directions and wound up here. I'd really like to run my server from the command line since the GUI version is not the latest.

**Comment by jlipps** [comment]
The [README](https://github.com/appium/appium/blob/master/README.md) is accurate, basically it's as simple as:

```
npm install -g appium
appium
```

But see the rest of the docs on github for other platform-related setup

**Comment by dpgraham** [comment]
Closing this. This will be part of our onboarding overhaul: (https://github.com/appium/appium/issues/7169)
