### ISSUE TITLE
Unable to select individual elements in UIATableView by Xpath

### ISSUE THREAD

**Issue by hoverduck** [appium/appium#6517]
## The problem

Originally documented here - https://github.com/appium/appium-dot-app/issues/521 - there are cases where Appium is unable to detect the individual elements of a UIATableView or UICollectionViewCells.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.0, 1.5.2 and 1.4.13 were tested
- Desktop OS/version used to run Appium: OSX 10.11.4 and 10.10.5
- Node.js version (unless using Appium.app|exe): 5.10.1
- Mobile platform/version under test: iOS 9.1
- Real device or emulator/simulator: All
- Appium CLI or Appium.app|exe: Both

An example application exhibiting this problem is https://github.com/wordpress-mobile/WordPress-iOS, on the Posts list.

**Comment by apankov1** [comment]
We have the same issue with our app. 


We have a UAITableView with UIATableCell within it.

When using Inspector I can see each cell but when I'm trying to click on the item I get:
```WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: elementId 5 could not be tapped```

Here is an example of XML of the app:
```
<UIATableView name="" label="" value="rows 1 to 3 of 221" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/2" x="0" y="64" width="414" height="623">
    <UIATableCell name="SCIENCE, From farm to lab to table, a tale of tomatoes and a top banana, 05.25.16" label="SCIENCE, From farm to lab to table, a tale of tomatoes and a top banana, 05.25.16" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/2/0" x="0" y="64" width="414" height="256">
        <UIAStaticText name="SCIENCE" label="SCIENCE" value="SCIENCE" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/2/0/0" x="25" y="219" width="60.66666666666667" height="16">
        </UIAStaticText>
        <UIAStaticText name="From farm to lab to table, a tale of tomatoes and a top banana" label="From farm to lab to table, a tale of tomatoes and a top banana" value="From farm to lab to table, a tale of tomatoes and a top banana" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/2/0/1" x="25" y="244" width="364" height="47.33333333333337">
        </UIAStaticText>
        <UIAStaticText name="05.25.16" label="05.25.16" value="05.25.16" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/2/0/2" x="329" y="219" width="60" height="16">
        </UIAStaticText>
    </UIATableCell>
</UIATableView>
```

Appium 1.5.2, Appium-Python-Client (0.22)

**Comment by SrinivasanTarget** [comment]
@imurchie Can you please give us some insights on this?

**Comment by SrinivasanTarget** [comment]
@triager please label: iOS

**Comment by SrinivasanTarget** [comment]
@imurchie Can you help on this? Let me know if you need any logs/info.

**Comment by achiber** [comment]
We have the same issue with our app.
This my detail.
![2016-09-05 4 20 48](https://cloud.githubusercontent.com/assets/6235156/18241749/6b91dbe6-7385-11e6-98c6-f743662fa74f.png)
![2016-09-05 4 23 53](https://cloud.githubusercontent.com/assets/6235156/18241750/6b92c0d8-7385-11e6-996f-f6c9c8e37bcc.png)

**Comment by achiber** [comment]
I could not  detect uitextfild in uitableview.

**Comment by BenjaminZaiser** [comment]
Dear Appium team,

we are also experiencing exactly the same issue.
Would be great if you could have a look at this problem, because this really blocks us from writing test cases.
Also if you have a look at the comments in https://github.com/appium/appium-dot-app/issues/521 some developers are already switching to other automation frameworks or even worse: they test it manually.

From my point of view, this issue should receive a higher priority!

Thanks.

**Comment by mykola-mokhnach** [comment]
Perhaps, the real problem is that elements inside cell are not defined properly as accessible. Please check this code snippet: https://github.com/wireapp/wire-ios/blob/develop/Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m#L222 for more details. Also, you can use Accessibility Inspector developer tool, which was introduced in Xcode 8 to make sure all necessary UI elements are accessible and have correct attributes.

**Comment by imurchie** [comment]
Does anyone have an app that I can use to reproduce this? The one in the original post doesn't run on my machine, for reasons unknown. I'll continue to try to make it work.

But our tests apps work fine with this scenario. Alas.

**Comment by mauriparra** [comment]
Dear mykola-mokhnach

Thanks for the redirection on this issue. I read your comment on October and I understand that the problem is in the accessibility configuration for the UIElements. But I researched more about the accessibility guidelines in iOS apps and I found this:

https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/iPhoneAccessibility/Making_Application_Accessible/Making_Application_Accessible.html

In the part of "Make the Contents of Custom Container Views Accessible": 

_If your application displays a custom view that contains other elements with which users interact, you need to make the contained elements separately accessible. At the same time, you need to make sure that_ **the container view itself is not accessible**. _The reason is that users interact with the contents of the container, not with the container itself._

If the developers use this rules correctly, we will not have problems with appium and the interaction of the UIElements inside of the containers or views. I hope that this information helps to this community.

Regards!

**Comment by mykola-mokhnach** [comment]
Thanks for the investigation @mauriparra
I hope this info will be useful for people as well.
