### ISSUE TITLE
Switching to WEBVIEW halts execution sometime on Android 6.0 and above

### ISSUE THREAD

**Issue by KrazySush** [appium/appium#6616]
Hi All,

I am automating hybrid app.

For Android 6.0 & above, while switching to Webview, execution halts the execution for 5 - 10 mins.

I tried adding following cap:
**capabilities.setCapability("recreateChromeDriverSessions", true);**

But still facing same issue.

Need help.

**Comment by KrazySush** [comment]
@jlipps Can you please help?

**Comment by KrazySush** [comment]
@Jonahss Can you please help?

**Comment by abhilashcae** [comment]
I'm also facing the same problem. Following.

**Comment by ssynix** [comment]
You're probably experiencing the issue I've also experienced in https://github.com/appium/appium/issues/6607.

Try to capture chromedriver logs and see if that's the case.

**Comment by ssynix** [comment]
https://github.com/appium/appium/issues/6634 fixed it for me.

**Comment by KrazySush** [comment]
@ssynix 
Still facing the same issue.
Following are the appium logs related to chromedriver:




[JSONWP Proxy] Proxying [GET /url] to [GET http://127.0.0.1:9515/wd/hub/session/e14a60547e5d47d1cd4cbecbef38841f/url] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"e14a60547e5d47d1cd4cbecbef38841f\",\"status\":100,\"value\":{\"message\":\"chrome not reachable\\n  (Session info: chrome=51.0.2704.81)\\n  (Driver info: chromedriver=2.21.371459 ...
[debug] [AndroidDriver] ChromeDriver is not associated with a window. Re-initializing the session.
[Chromedriver] Restarting chromedriver
[debug] [Chromedriver] Changed state to 'restarting'
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:9515/wd/hub/session/e14a60547e5d47d1cd4cbecbef38841f] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"e14a60547e5d47d1cd4cbecbef38841f\",\"status\":0,\"value\":null}"
[Chromedriver] Killing any old chromedrivers, running: ps -ef | grep /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
[Chromedriver] Successfully cleaned up old chromedrivers
[Chromedriver] Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 9515
Only local connections are allowed.
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.11.5\"}}}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.xxx.yyy","androidUseRunningApp":true,"androidDeviceSerial":"03uuhitredf"}}}



at this stage execution halts.

**Comment by ssynix** [comment]
The logs are exactly what I would see in my case when the bug was triggered, but I don't think you've actually applied the fix mentioned in #6634, nor have you captured the chromedriver logs:

> [Chromedriver] Spawning chromedriver with: /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037

 For the fix, you need to build chromedriver from source (after modifying the file mentioned in the issue) and pass the custom chromedriver to appium via the `--chromedriver-executable` flag. For example, this is what I see in my Appium logs:

> Spawning chromedriver with: ~/workspace/chromium/src/out/Release/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037 --log-path=~/workspace/chromedriver_bug/log/chromedriver.log --verbose

I personally pass the chromedriver `--log-path` parameter directly in Appium's source, but I was surprised to find that apparently there's no other way to do it through the capabilities or server flags—at least I wasn't able to.

**Comment by KrazySush** [comment]
Hi @ssynix
Can you please guide me, how to build chromedriver from source on MAC?

**Comment by ssynix** [comment]
There's detailed guide for it on [chromium](https://chromium.googlesource.com/chromium/src/+/master/docs/mac_build_instructions.md#Using-Xcode_Ninja-Hybrid), but these are the steps I followed:
```bash
cd ~/workspace/
mkdir chromium; cd $_
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
export PATH=$PATH:~/workspace/chromium/depot_tools
fetch  --no-history chromium # this will take a while if you don't have a super fast connection
cd src
gclient runhooks
# Now you should modify the file mentioned in the #6634
# adp_impl.cc also seen in the pull request submitted to chromedriver
ninja -C out/Release chromedriver # this also takes a while
```

**Comment by KrazySush** [comment]
Thank u so much @ssynix.
It is working fine now.

**Comment by SameekshaSahib** [comment]
Hello guys.
I made the changes and built the chromedriver build from source. Issue is still there :( 
Any help?

**Comment by SameekshaSahib** [comment]
This is my appium log
info: --> POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context {"name":"WEBVIEW_com.xxxxxxx"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_14789 mapped to pid 14789
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "ps"
info: [debug] Parsed pid: 14789 pkg: com.xxxxxxx
info: [debug] from: u0_a604,14789,228,1079956,164784,SyS_epoll_,0000000000,S,com.xxxxxxx
info: [debug] returning process name: com.xxxxxxx
info: [debug] Available contexts: 
info: [debug] ["WEBVIEW_com.xxxxxxx"]
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.xxxxxxx
info: [debug] Connecting to chrome-backed webview
info: Chromedriver: Changed state to 'starting'
info: Chromedriver: Set chromedriver binary as: /Users/automation/git/chromium/src/out/Release/chromedriver
info: Chromedriver: Killing any old chromedrivers, running: ps -ef | grep /Users/automation/git/chromium/src/out/Release/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
info: Chromedriver: Successfully cleaned up old chromedrivers
info: Chromedriver: Spawning chromedriver with: /Users/automation/git/chromium/src/out/Release/chromedriver --url-base=wd/hub --port=9515
info: Chromedriver: [STDOUT] Starting ChromeDriver 2.22.408616 (e823e5e60d848de11799d3741fade5a68ca8681e) on port 9515
Only local connections are allowed.
info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
info: JSONWP Proxy: Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Mac OS X","version":"10.10.5"}}}
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.xxxxxxx","androidUseRunningApp":true,"androidDeviceSerial":"HT4AEJT08500"}}}

info: JSONWP Proxy: Got response with status 200: {"sessionId":"ab3c9d60b2979c36ffb5a17f70e1a535","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedrive...

info: Chromedriver: Changed state to 'online'
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"b8056f73-3fba-4eec-9261-5dabf869501f"}
info: <-- POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context 200 1471.297 ms - 76 {"status":0,"value":null,"sessionId":"b8056f73-3fba-4eec-9261-5dabf869501f"}
info: --> GET /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/url {}
info: JSONWP Proxy: Proxying [GET /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/url] to [GET http://127.0.0.1:9515/wd/hub/session/ab3c9d60b2979c36ffb5a17f70e1a535/url] with body: {}

info: JSONWP Proxy: Got response with status 200: {"sessionId":"ab3c9d60b2979c36ffb5a17f70e1a535","status":0,"value":"file:///storage/emulated/0/Android/data/com.xxxxxxx/files/urn_uuid_mobileiqqa_automation_qxpenrichmentguide_production/360Im...
info: JSONWP Proxy: Replacing sessionId ab3c9d60b2979c36ffb5a17f70e1a535 with b8056f73-3fba-4eec-9261-5dabf869501f
info: <-- GET /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/url 200 53.052 ms - 210 
info: --> POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context {"name":"NATIVE_APP"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_14789 mapped to pid 14789
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "ps"
info: [debug] Parsed pid: 14789 pkg: com.xxxxxxx
info: [debug] from: u0_a604,14789,228,1099928,189648,SyS_epoll_,0000000000,S,com.xxxxxxx
info: [debug] returning process name: com.xxxxxxx
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.xxxxxxx
info: [debug] ["WEBVIEW_com.xxxxxxx"]
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.xxxxxxx
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"b8056f73-3fba-4eec-9261-5dabf869501f"}
info: <-- POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context 200 110.188 ms - 76 {"status":0,"value":null,"sessionId":"b8056f73-3fba-4eec-9261-5dabf869501f"}
info: --> POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context {"name":"WEBVIEW_com.xxxxxxx"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_14789 mapped to pid 14789
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/automation/Library/Android/sdk/platform-tools/adb -s HT4AEJT08500 shell "ps"

info: [debug] Parsed pid: 14789 pkg: undefined
info: [debug] from: u0_a604,14789,228,1099928,189652,0000000000,R,com.xxxxxxx
info: [debug] returning process name: undefined
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.xxxxxxx
info: [debug] ["WEBVIEW_undefined"]
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_undefined
info: [debug] Responding to client with error: {"status":35,"value":{"message":"No such context found.","origValue":"Context 'WEBVIEW_com.xxxxxxx' does not exist"},"sessionId":"b8056f73-3fba-4eec-9261-5dabf869501f"}
info: <-- POST /wd/hub/session/b8056f73-3fba-4eec-9261-5dabf869501f/context 500 149.587 ms - 176 


Appium is getting list of webviews multiple time (I don't know why). And then finally failing due to WEBVIEW_Undefined .

**Comment by Domuska** [comment]
Hi all, I am also experiencing problems with the webview on android 6.0. I downloaded the new version (2.23) of chromedriver from the [chromedriver](https://sites.google.com/a/chromium.org/chromedriver/), website. Issue I am experiencing is that either the context is not found, or that my chrome version is not high enough. This issue does not come up with android version 5.1. I am running the appium from the appium.exe provided. 

I put the new chromedriver in the node_modules/appium/node_modules/appium-chromedriver/chromedriver/win folder and also tried to supply it from a different path with capability when creating the driver but neither seemed to make any difference.

The server log provided is either as follows (at the case of chrome version being too low) or similar as SameekshaSahib above (in the case of context not being found).

I cut out from the log earlier parts that are not related to the webview.

> info: --> POST /wd/hub/session/d3ad0ab7-3a5c-4dbe-b101-bac34b0da150/element {"using":"class name","value":"android.webkit.WebView"}
> info: [debug] Waiting up to 0ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"class name","selector":"android.webkit.WebView","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"class name","selector":"android.webkit.WebView","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding android.webkit.WebView using CLASS_NAME with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.webkit.WebView, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"12"}}
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"12"},"sessionId":"d3ad0ab7-3a5c-4dbe-b101-bac34b0da150"}
> info: <-- POST /wd/hub/session/d3ad0ab7-3a5c-4dbe-b101-bac34b0da150/element 200 1532.405 ms - 88 {"status":0,"value":{"ELEMENT":"12"},"sessionId":"d3ad0ab7-3a5c-4dbe-b101-bac34b0da150"}
> info: --> GET /wd/hub/session/d3ad0ab7-3a5c-4dbe-b101-bac34b0da150/element/12/displayed {}
> info: [debug] Pushing command to appium work queue: ["element:getAttribute",{"elementId":"12","attribute":"displayed"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"elementId":"12","attribute":"displayed"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getAttribute
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"true"}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"d3ad0ab7-3a5c-4dbe-b101-bac34b0da150"}
> info: <-- GET /wd/hub/session/d3ad0ab7-3a5c-4dbe-b101-bac34b0da150/element/12/displayed 200 32.698 ms - 76 {"status":0,"value":true,"sessionId":"d3ad0ab7-3a5c-4dbe-b101-bac34b0da150"}
> info: --> GET /wd/hub/session/d3ad0ab7-3a5c-4dbe-b101-bac34b0da150/contexts {}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: C:\Users\username\Android_SDK\platform-tools\adb.exe -s 013d23706c6b9dcd shell "cat /proc/net/unix"
> info: [debug] WEBVIEW_14650 mapped to pid 14650
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: C:\Users\username\Android_SDK\platform-tools\adb.exe -s 013d23706c6b9dcd shell "ps"
> info: [debug] Parsed pid: 14650 pkg: org.package.app
> info: [debug] from: u0_a539,14650,502,2391580,238732,SyS_epoll_,0000000000,S,org.package.app
> info: [debug] returning process name: org.package.app
> info: [debug] Available contexts: 
> info: [debug] ["WEBVIEW_org.package.app"]
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_org.package.app
> info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_org.package.app"],"sessionId":"d3ad0ab7-3a5c-4dbe-b101-bac34b0da150"}
> info: <-- GET /wd/hub/session/d3ad0ab7-3a5c-4dbe-b101-bac34b0da150/contexts 200 297.059 ms - 116 {"status":0,"value":["NATIVE_APP","WEBVIEW_org.package.app"],"sessionId":"d3ad0ab7-3a5c-4dbe-b101-bac34b0da150"}
> info: --> POST /wd/hub/session/d3ad0ab7-3a5c-4dbe-b101-bac34b0da150/context {"name":"WEBVIEW_org.package.app"}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: C:\Users\username\Android_SDK\platform-tools\adb.exe -s 013d23706c6b9dcd shell "cat /proc/net/unix"
> info: [debug] WEBVIEW_14650 mapped to pid 14650
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: C:\Users\username\Android_SDK\platform-tools\adb.exe -s 013d23706c6b9dcd shell "ps"
> info: [debug] Parsed pid: 14650 pkg: org.package.app
> info: [debug] from: u0_a539,14650,502,2391580,238732,SyS_epoll_,0000000000,S,org.package.app
> info: [debug] returning process name: org.package.app
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_org.package.app
> info: [debug] ["WEBVIEW_org.package.app"]
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_org.package.app
> info: [debug] Connecting to chrome-backed webview
> info: Chromedriver: Changed state to 'starting'
> info: Chromedriver: Set chromedriver binary as: C:\Users\username\Downloads\chromedriver_win32\chromedriver.exe
> info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
> info: Chromedriver: No old chromedrivers seemed to exist
> info: Chromedriver: Spawning chromedriver with: C:\Users\username\Downloads\chromedriver_win32\chromedriver.exe --url-base=wd/hub --port=9515
> info: Chromedriver: [STDOUT] Starting ChromeDriver 2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129) on port 9515
> Only local connections are allowed.
> info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
> info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0.10240\"}}}"
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"org.package.app","androidUseRunningApp":true,"androidDeviceSerial":"013d23706c6b9dcd"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"b7b932d215ae3cd959698390d6a00e80","status":13,"value":{"message":"unknown error: Chrome version must be >= 51.0.2704.0\n  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae1...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"org.package.app","androidUseRunningApp":true,"androidDeviceSerial":"013d23706c6b9dcd"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"1f12efbff25e6bc07594da02fe6abc9f","status":13,"value":{"message":"unknown error: Chrome version must be >= 51.0.2704.0\n  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae1...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"org.package.app","androidUseRunningApp":true,"androidDeviceSerial":"013d23706c6b9dcd"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"0140c951b4c23f2eeea462b3f3688c1a","status":13,"value":{"message":"unknown error: Chrome version must be >= 51.0.2704.0\n  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae1...
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"org.package.app","androidUseRunningApp":true,"androidDeviceSerial":"013d23706c6b9dcd"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"d6dc6394a121c59d3f20543b6cb4389d","status":13,"value":{"message":"unknown error: Chrome version must be >= 51.0.2704.0\n  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae1...
> error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
> info: Chromedriver: Changed state to 'stopped'
> warn: Chromedriver for context WEBVIEW_org.package.app stopped unexpectedly
> warn: Chromedriver quit unexpectedly, but it wasn't the active context, ignoring
> error: Chromedriver: Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Chrome version must be >= 51.0.2704.0
>   (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 10.0.10240 x86_64))
>     at JWProxy.command$ (lib/proxy.js:133:15)
>     at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at bound (domain.js:284:14)
>     at GeneratorFunctionPrototype.runBound (domain.js:297:12)
>     at run (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:89:39)
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:100:28
>     at flush (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\appium-jsonwp-proxy\node_modules\babel-runtime\node_modules\core-js\library\modules\$.microtask.js:17:13)
>     at process._tickDomainCallback (node.js:381:11)
>  { [Error: An unknown server-side error occurred while processing the command. (Original error: unknown error: Chrome version must be >= 51.0.2704.0
>   (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 10.0.10240 x86_64))]
>   status: 13,
>   value: { message: 'unknown error: Chrome version must be >= 51.0.2704.0\n  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 10.0.10240 x86_64)' },
>   httpCode: 200 }

Any ideas on how to handle this?

**Comment by Domuska** [comment]
Actually, the problem was exactly what it says in the error message - my chrome version was too low for the driver. After updating System WebView on my phone it works now fine.

**Comment by KrazySush** [comment]
ryt. Both Chrome and System WebView of Android phone must be updated to latest version.
