### ISSUE TITLE
how can i switch ON/OFF gps using appium in device

### ISSUE THREAD

**Issue by diaojunxian** [appium/appium#6632]
## The problem

In our App,we should switch ON/OFF GPS to see what would happens?
so when I had in app,how to  enter the settings to switch GPS ON/OFF

## Environment

appium 1.4.16
xcode 7.1.3
mac 10.11.5

**Comment by mykola-mokhnach** [comment]
You can potentially call this dialog from  by executing the corresponding adb commend, like it's described here:
http://android.stackexchange.com/questions/40147/is-it-possible-to-enable-location-services-via-shell
Then it will be necessary to handle some confirmation alerts.

Appium does not contain any built-in features for it (it has only API to control network connection state).

**Comment by diaojunxian** [comment]
@mykola-mokhnach  It is to say I can't achieve my purpose in iPhone?

**Comment by mykola-mokhnach** [comment]
Probably not, using any "standard" approach. 
Although, you could try some hacks, for example to open quick access pane by swiping with three fingers  from the bottom and then clicking the GPS glyph to activate/deactivate the feature. Appium, will, most likely, fail to tap this element directly, using its id, since it is not a part of your application, so you'll have to calculate its coordinates and then execute generic tap by coordinates.

**Comment by diaojunxian** [comment]
thank you for very much

**Comment by SrinivasanTarget** [comment]
@triager please close
