### ISSUE TITLE
How to slide the slider Of iOS

### ISSUE THREAD

**Issue by smalldew** [appium/appium#6636]
help me .

i want to know how to slide the slider of iOS with nodejs.

**Comment by jmolliver** [comment]
You can do this by setting its value to 0 or 1, depending on if you want the slider on or off. You could just "click" on it, but that is unreliable because it will only set the slider to opposite of what it currently is.  
If you test expects the slider to be set a particular value use .setImmediateValue(1) and identify the slider by however you can (byName, byXPath, etc)

 .elementByName('kiosk_mode').setImmediateValue(1)

**Comment by SrinivasanTarget** [comment]
@smalldew Please raise your questions here: discuss.appium.io

**Comment by SrinivasanTarget** [comment]
@triager please close
