### ISSUE TITLE
|Ruby| How does one assert that certain element is not visible on the screen

### ISSUE THREAD

**Issue by StipeKolovrat** [appium/appium#6675]
Assert that element is not visible on the screen

Hi guys, 
I am having difficulties to assert that certain text is not visible on the screen. I have tried my luck with RSpec Expectations, and different approaches which would be working for web app. However with Appium it does not seem to work. 

**Here is the link of what I have tried:** 
http://stackoverflow.com/questions/38372530/appium-how-does-one-assert-that-certain-text-is-not-displayed-on-the-screen

There are many examples, how to assert that something IS visible, and that is working as expected. However when its vice versa then it is not going smoothly. 

## Environment
```
* Mobile app - iOS
* Appium 1.5.2 + Cucumber + WatirWebdriver + Ruby + RSpec Expectations
```

**Comment by jmolliver** [comment]
I verify the visible attribute with xpath. Here is an example with node js, but you can do the same thing in your xpath to locate the element you want to verify.

.elementByXPath("//*[@value='zoom_color_label']" + "[@visible='false']")

You could also use .elementByXPath(("//*[@value='zoom_color_label']").isVisible().should.become(false)

**Comment by StipeKolovrat** [comment]
Hi, 
thanks for the response. What you are saying are not covered options in Ruby. I will try something in Ruby based on this idea and see if it will work. 

Do you have suggestions for Ruby ?

**Comment by JaniJegoroff** [comment]
I'm using Appium Ruby bindings and here is an example what I do in such cases:
```
[1] pry(main)> wait_true { ignore { text('text that is not visible on screen') }.nil? }
true
```

**Comment by StipeKolovrat** [comment]
Thanks @JaniJegoroff it works beautifully. 

If you are willing, could elaborate more about line
`wait_true { ignore { text('text that is not visible on screen') }.nil? }
true`

I would like to understand it

**Comment by JaniJegoroff** [comment]
No problem - hope this brief explanation helps.

`wait_true { ignore { text('text that is not visible on screen') }.nil? }`

`wait_true`, `ignore` and `text` are Appium Ruby binding methods and can be found from project: https://github.com/appium/ruby_lib

`text` will return the first "textfield" element with given text. Since such element is not going to be found it will throw an exception. We will catch exception with `ignore` block. When text is not found `ignore` block will return `nil`. Finally we use `wait_true` block to poll that return value is `nil` meaning text is not visible on the screen.

**Comment by SrinivasanTarget** [comment]
@triager please close
