### ISSUE TITLE
Appium clear appium log bug

### ISSUE THREAD

**Issue by JordanGS** [appium/appium#6868]
## The problem

I am running appium from the terminal and piping the output to the appium.log. In between runs, i clear the contents of appium.log file and append the header. The first time i run a test, the file is 500kb. I clear the log and then run a second test, the appium.log file is now 1Mb, there is a cache somewhere or something because the server is appending useless information that i no longer want in there. Is there a way to programatically clear the server cache?

## Environment

* 1.4.16

## Details

Updating appium is not a choice, too much deprecated methods were removed and would require rework of multiple applications.

Thanks

**Comment by jlipps** [comment]
If you don't use `--log` and instead just pipe output to a file, you won't see this. I wasn't aware Appium had a log cache but maybe it's something internal to Winston (the logging package we use). If that doesn't work, and upgrading isn't an option, there won't be anything we can do (since we aren't going to patch 1.4.16 any further).

**Comment by JordanGS** [comment]
@jlipps I wasn't aware either until i discovered 300MB log files even though the log was being cleared between runs, it would still re append the full log, even from previous test.s
