### ISSUE TITLE
Appium 1.5.3 : TouchAction Swipe on iOS 9 not working

### ISSUE THREAD

**Issue by ericzered** [appium/appium#6918]
## The problem

Since I've install 1.5.3 (and same with the 6 beta version), when I use Appium:TouchAction.new.swipe I always have the exact same swipe on Safari, for every value I've tried for start_x, start_y, start_y and start_y.
With Appium 1.4.16, I don't have this issue
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3 (and 6 beta too)
- Last Appium version that did not exhibit the issue (if applicable): 1.4.16
- Desktop OS/version used to run Appium: Mac OSX
- Node.js version (unless using Appium.app|exe): 6.6.0
- Mobile platform/version under test: Safari on iOS 9.3
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe: Appium CL
## Details

With appium 1.4.16, I was using Appium:Touchaction.new.swipe with success.
To make a small scroll in one direction in Safari iOS 9.3, I was doing this : 
Appium::TouchAction.new.swipe(start_x: 50, start_y: 300, end_x: 50, end_y: 350, duration: 500).perform
And in the other direction : 
Appium::TouchAction.new.swipe(start_x: 50, start_y: 350, end_x: 50, end_y: 300, duration: 500).perform

But since I've installed Appium 1.5.3, with this 2 commands I have the exact same result : I see a swipe from top to bottom. Looks like coordonate I put are not taken into account.
## Link to Appium logs

Logs when I swipe in one way and in the other way just after (and I have the same result on the screen) : 

[HTTP] --> POST /wd/hub/session/0d78404a-c873-4971-964f-1985c854d41c/touch/perform {"actions":[{"action":"press","options":{"x":37.5,"y":300.15}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":37.5,"y":366.85}},{"action":"release"}]}

[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [iOS] Executing iOS command 'performTouch'

[debug] [UIAuto] Sending command to instruments: target.touch([{"touch":[{"x":37.5,"y":300.15}],"time":0.2},{"touch":[{"x":37.5,"y":300.15}],"time":0.7},{"touch":[{"x":75,"y":667}],"time":0.8999999999999999}])

[debug] [Instruments] [INST] 2016-09-30 13:27:54 +0000 Debug: Got new command 12 from instruments: target.touch([{"touch":[{"x":37.5,"y":300.15}],"time":0.2},{"touch":[{"x":37.5,"y":300.15}],"time":0.7},{"touch":[{"x":75,"y":667}],"time":0.8999999999999999}])

[debug] [Instruments] [INST] 2016-09-30 13:27:54 +0000 Debug: evaluating target.touch([{"touch":[{"x":37.5,"y":300.15}],"time":0.2},{"touch":[{"x":37.5,"y":300.15}],"time":0.7},{"touch":[{"x":75,"y":667}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-09-30 13:27:54 +0000 Debug: target.touch(__NSCFArray)

[debug] [Instruments] [INST] 2016-09-30 13:27:55 +0000 Debug: evaluation finished

[debug] [Instruments] [INST] 2016-09-30 13:27:55 +0000 Debug: responding with:

[debug] [Instruments] [INST] 2016-09-30 13:27:55 +0000 Debug: Running system command #13: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/s9/1ryws64x3qj4ftkymtfylqv00000gp/T/instruments_sock 2,{"status":0,"v...
[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/0d78404a-c873-4971-964f-1985c854d41c/touch/perform 200 2242 ms - 76 

[HTTP] --> POST /wd/hub/session/0d78404a-c873-4971-964f-1985c854d41c/touch/perform {"actions":[{"action":"press","options":{"x":37.5,"y":366.85}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":37.5,"y":300.15}},{"action":"release"}]}

[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [iOS] Executing iOS command 'performTouch'

[debug] [UIAuto] Sending command to instruments: target.touch([{"touch":[{"x":37.5,"y":366.85}],"time":0.2},{"touch":[{"x":37.5,"y":366.85}],"time":0.7},{"touch":[{"x":75,"y":667}],"time":0.8999999999999999}])

[iOSLog] [IOS_SYSLOG_ROW] Sep 30 15:28:12 --- last message repeated 2 times ---

[iOSLog] [IOS_SYSLOG_ROW] Sep 30 15:28:12 MBP-ELerouge assertiond[44891]: assertion failed: 15G31 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1

[debug] [Instruments] [INST] 2016-09-30 13:28:12 +0000 Debug: Got new command 13 from instruments: target.touch([{"touch":[{"x":37.5,"y":366.85}],"time":0.2},{"touch":[{"x":37.5,"y":366.85}],"time":0.7},{"touch":[{"x":75,"y":667}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-09-30 13:28:12 +0000 Debug: evaluating target.touch([{"touch":[{"x":37.5,"y":366.85}],"time":0.2},{"touch":[{"x":37.5,"y":366.85}],"time":0.7},{"touch":[{"x":75,"y":667}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-09-30 13:28:12 +0000 Debug: target.touch(__NSCFArray)

[debug] [Instruments] [INST] 2016-09-30 13:28:13 +0000 Debug: evaluation finished

[debug] [Instruments] [INST] 2016-09-30 13:28:13 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-09-30 13:28:13 +0000 Debug: Running system command #14: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/s9/1ryws64x3qj4ftkymtfylqv00000gp/T/instruments_sock 2,{"status":0,"v...
## Code To Reproduce Issue [ Good To Have ]

@browser.goto("https://en.wikipedia.org/wiki/Main_Page")
@driver.set_context("NATIVE_APP")
Appium::TouchAction.new.swipe(start_x: 37.5, start_y: 300.15, end_x: 37.5, end_y: 366.85, duration: 500).perform
Appium::TouchAction.new.swipe(start_x: 37.5, start_y: 366.85, end_x: 37.5, end_y: 300.15, duration: 500).perform

**Comment by ericzered** [comment]
I was reading to this https://github.com/appium/appium/issues/6257#issuecomment-196949576
and I totally understand what happens : since appium 1.5, Endy and EndX coordinate should be think like relative coordinate from the starts.
So to make a swipe in one way : 
Appium::TouchAction.new.swipe(start_x: 37, start_y: 300, end_x: 100, end_y: 100, duration: 500).perform
and in the other way : 
Appium::TouchAction.new.swipe(start_x: 37, start_y: 300, end_x: -100, end_y: -100, duration: 500).perform

I will update my code knowing this !
So I think it's still a bug, and because I have the exact same on Appium v1.6.0-beta2, it's not resolved.
Thanks !

**Comment by vikaspune** [comment]
@ericzered Yes I am also facing this issue since long https://github.com/appium/appium/issues/6639
but by mistake i closed it when i found it is working on Android. But after closing I realized it's till a bug with appium.

 I would like to mention few points from my experience

1. In Android all coordinates i.e. start(x,y) and end(x,y) are absolute. driver.swipe() perfectly works for Android with all directions.

2. For IOS:  I have used TouchAction directly instead of driver.swipe()
a. swipe LEFT and RIGHT working perfectly, below is the script example .
```
//LEFT swipe
new TouchAction(driver).press(centerX, centerY).waitAction(1000).moveTo(150, 0).release().perform()
```

But if i give 
`
new TouchAction(driver).press(centerX, centerY).waitAction(1000).moveTo(0,-200).release().perform()
`
is not scrolling in any direction. neither I can see any movements on my screen though my app is in a state where it can be swiped in all 4 direction.

**Comment by Yaromudr** [comment]
I have same problem. Appium version - 1.6.1, iOS version - 9.3, appium-xcuitest-driver - 2.4.2

I have 2 version code.
First:
`TouchAction action = new TouchAction(driver);
action.press(webElement).waitAction(200).moveTo(location.getX()-size.getWidth()/2, location.getY()).release().perform();`

Second:
`TouchAction action = new TouchAction(driver);
action.press(webElement).waitAction(200).moveTo(location.getX(), location.getY()-size.getWidth()/2).release().perform();`

But I see a swipe from top to bottom in both cases

**Comment by ToddGlover** [comment]
I'm having the same issue on 1.6.3.

**Comment by BertLeonaers** [comment]
I Have the same problem.
Appium: 1.6.3
XCUITEST-driver
I am using ruby.
I did some investigation, and I noticed the following.

I want to swipe up with the following command:
`swipe(start_x: 100, start_y: 500, delta_x: 0, delta_y: -200, duration: 200)`

This command gets translated to this:
`#<Appium::TouchAction:0x007f8889b5b760 @actions=[{:action=>:press, :options=>{:x=>100, :y=>500}}, {:action=>:wait, :options=>{:ms=>200}}, {:action=>:moveTo, :options=>{:x=>100, :y=>300}}, {:action=>:release}]>`
This is correct, because end y is 200 less then start y.

When I look in the logs of appium, I see the following:
`[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":100,"y":500}},{"action":"wait","options":{"ms":200}},{"action":"moveTo","options":{"x":100,"y":300}},{"action":"release"}],"7085a71b-e7dd-42de-bd69-c84617f2cd0e"]`
This is similar to previous line.

But there is a problem from moving from previous line to next line:
`[debug] [JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/17C13C43-54F0-431C-9991-19E540DDE696/uiaTarget/0/dragfromtoforduration] with body: {"fromX":100,"fromY":500,"toX":200,"toY":800,"duration":0.2}`
The toY value is miscalculated. It is the sum of start_y and the y of moveTo.

Here is the full logs of 1 Swipe action:
`[HTTP] --> POST /wd/hub/session/7085a71b-e7dd-42de-bd69-c84617f2cd0e/touch/perform {"actions":[{"action":"press","options":{"x":100,"y":500}},{"action":"wait","options":{"ms":200}},{"action":"moveTo","options":{"x":100,"y":300}},{"action":"release"}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":100,"y":500}},{"action":"wait","options":{"ms":200}},{"action":"moveTo","options":{"x":100,"y":300}},{"action":"release"}],"7085a71b-e7dd-42de-bd69-c84617f2cd0e"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-moveTo-release
[debug] [JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/17C13C43-54F0-431C-9991-19E540DDE696/uiaTarget/0/dragfromtoforduration] with body: {"fromX":100,"fromY":500,"toX":200,"toY":800,"duration":0.2}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"17C13C43-54F0-431C-9991-19E540DDE696","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/7085a71b-e7dd-42de-bd69-c84617f2cd0e/touch/perform 200 2370 ms - 74`

Currently, I use the following workaround:
`Appium::TouchAction.new.press(x: 100, y: 500).wait(100).move_to(x:100, y:-200).release.perform`

This gives me the right behaviour:
`[HTTP] --> POST /wd/hub/session/7085a71b-e7dd-42de-bd69-c84617f2cd0e/touch/perform {"actions":[{"action":"press","options":{"x":100,"y":500}},{"action":"wait","options":{"ms":100}},{"action":"moveTo","options":{"x":100,"y":-200}},{"action":"release"}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":100,"y":500}},{"action":"wait","options":{"ms":100}},{"action":"moveTo","options":{"x":100,"y":-200}},{"action":"release"}],"7085a71b-e7dd-42de-bd69-c84617f2cd0e"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-moveTo-release
[debug] [JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/17C13C43-54F0-431C-9991-19E540DDE696/uiaTarget/0/dragfromtoforduration] with body: {"fromX":100,"fromY":500,"toX":200,"toY":300,"duration":0.1}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"17C13C43-54F0-431C-9991-19E540DDE696","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/7085a71b-e7dd-42de-bd69-c84617f2cd0e/touch/perform 200 1732 ms - 74`

**Comment by BertLeonaers** [comment]
When I print the location of an element, I get the right values.
