### ISSUE TITLE
appium starts up twice for Safari ( iOS simulator)  

### ISSUE THREAD

**Issue by rafalf** [appium/appium#7025]
## The problem

appium starts up twice for Safari ( iOS) 
setting fullReset not helping out. 
this seems quiet inefficient 

## Environment

* Appium 1.6
* Macbook Air 

caps:
[Appium] Capabilities:
[Appium] nativeWebTap: true
[Appium] deviceName: 'iPhone Simulator'
[Appium] automationName: 'XCUITest'
[Appium] browserName: 'safari'
[Appium] safariIgnoreFraudWarning: true
[Appium] newCommandTimeout: '120'
[Appium] platformVersion: '10.0'
[Appium] fullReset: 'true'
[Appium] platformName: 'iOS'
[debug] [XCUITest] XCUITestDriver version: 2.0.26

## Link to Appium logs

[logs on gist:](https://gist.github.com/rafalf/082be45231538a43a553c8ea71c31c22)

**Comment by imurchie** [comment]
This is necessary because you specified `safariIgnoreFraudWarning` and are using a new simulator. The first launch creates the directories that are needed in order to set settings. The sim is then killed and the settings are set. The sim is then relaunched. Unfortunately simulators are not affected by file system changes when running, so this is necessary.

**Comment by rfusik** [comment]
@imurchie Many thanks. Commenting it out got me sorted!

**Comment by rafalf** [comment]
closing it thanks
