### ISSUE TITLE
Long working with XPATH or crash

### ISSUE THREAD

**Issue by baliand** [appium/appium#7085]
## The problem
Long time to get ui element from application if I use xPath.

## Environment

* Appium 1.6.0 - appium@1.6.0
* Desktop OS/version used to run Appium: OS X 10.11.6
* Node.js version (unless using Appium.app|exe): v 6.2.0
* Mobile platform/version under test: iOS 10.0.2
* Real device : iPhone 6S

## Details
Problem is if I try to get ui element by xPath, very long time to get element and in the end element was found or I get exception "**org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stack trace information
Command duration or timeout: 240.05 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html)**"

I found dependency. If **getPageSource()**  returns xml with over 1000 lines. Appium have problem to find element by xPath. if less 500 lines - it's working normally. 

Please check this problem.

Sorry I can't attach log and some info.

I'm trying to help you if you have some questions.

**Comment by mykola-mokhnach** [comment]
Known issue. Might be fixed by https://github.com/facebook/WebDriverAgent/pull/308

**Comment by baliand** [comment]
@mykola-mokhnach So as I understand your code is under review?

**Comment by mykola-mokhnach** [comment]
Yes it is. FB guys are usually very busy and have been keeping it in this state for almost 1 month. But I still hope it's going to be merged at some time.

**Comment by mykola-mokhnach** [comment]
You can always fork the project and apply the changes from my branch locally. Then just replace the "default" WebDriverAgent source inside _appium-xcuitest-driver_ folder where your Appium is installed and you should be ready to go.

**Comment by baliand** [comment]
Ok. Thanks.

**Comment by baliand** [comment]
@mykola-mokhnach I still have a problem with the user interface element that is in the bottom layout of xml markup. I will try to give you xml-markup ui page.
Could you see and help me?

**Comment by mykola-mokhnach** [comment]
yes, you can share the xml as a gist plus your xpath query. Btw, how much time it takes for you to detect an element with my implementation or it still times out?

**Comment by baliand** [comment]
for my element is still time out 240 seconds.
I make this query : driver.findElement(By.xpath(".//XCUIElementTypeTabBar/XCUIElementTypeButton[@name='Features']")); and on page where not much elements this query works fine.
But when page contains much ui elements  - org.openqa.selenium.NoSuchElementException time out 240 second

**Comment by mykola-mokhnach** [comment]
OK, I think we can optimize your request. It's easier when you know the way it works under the hood. 

So, the framework executes your xpath query on the tree and receives matching element snapshots as a result. These snapshots can be matched to UI elements, but in order to match snapshot to an UI element we have to resolve this element first (e.g read all the attributes from the UI). And this is supposed to be the longest operation. Also, the more matches you have the longer this operation is supposed to be. 
In order to cut off search duration we only try to resolve elements, which have the same type, as matching snapshots, but this can be also time-consuming in case there are multiple elements with the same type. 
In your case we got multiple matches for  **XCUIElementTypeButton** type (we need to resolve ALL the elements with this type, not only XCUIElementTypeTabBar descendants) and that is why search takes so much time (since it always starts from the root of the document and your button is closer to the end of the xml). 
Let's optimize it now. First, try to look for an element, which has much less type matches. In you case this will be **//XCUIElementTypeTabBar**. Then try to find the button inside this particular root: 

```java
driver.findElement(By.xpath("//XCUIElementTypeTabBar").findElement(MobileBy.AccessibilityId("Features")))
```

or even simpler (taking into account you have only one **XCUIElementTypeTabBar** in the tree):

```java
driver.findElement(By.className("XCUIElementTypeTabBar")).findElement(MobileBy.AccessibilityId("Features"))
```

**Comment by baliand** [comment]
I have tried second variant and it helped me.
xPath  - returned exception and 240 second

**Comment by baliand** [comment]
@mykola-mokhnach  for future, will xPath faster?I have to find an alternative variant, to find the element?

**Comment by mykola-mokhnach** [comment]
There is a nice Chinese proverb for such situation: "There is nothing more constant than temporary". Try to use the implementation, which is the fastest for now. And then we'll see - probably, Apple or someone else, or even yourself, will find out how to speed up this stuff.

**Comment by mykola-mokhnach** [comment]
@triager please close

**Comment by baliand** [comment]
@mykola-mokhnach Thanks.
