### ISSUE TITLE
ios 10 - appium 1.6.0 -Am facing issue while switching to webview 

### ISSUE THREAD

**Issue by acdurai** [appium/appium#7087]
@SrinivasanTarget 

Xcode 8.0
Appium 1.6.0
iOS 10
Latest ios-webkit-debug-proxy

Am able to run the test in native screens, but facing issue only while switching to hybrid pages.
please find the error log here
https://gist.github.com/acdurai/9406cfe6f40e48615cda7990727fe9e2

**Comment by rexors** [comment]
@acdurai I got the exact same error. After switching to webview appium returns `null` and the tests fail.

I already opened an issue on this: [Switching context to Webview (Cordova app) not working](https://github.com/appium/appium/issues/7041)

**Comment by dpgraham** [comment]
Indeed, this is the same issue that @rexors is experiencing. I'm going to close this as a duplicate and any future progress will be tracked on: https://github.com/appium/appium/issues/7041

**Comment by dpgraham** [comment]
@acdurai It looks like your call to 'setContext' is working correctly. The null value is expected based on the specification and doesn't mean that it failed.

Based on your logs, it looks like your problem is at line 34 the call to 'findElement' is not returning anything. Before you call 'find_element' can you try calling 'page_source' and then check the XML source to verify that the XPath you're using (```//section[@id='checkoutPaypalContainer']//button[@id='proceedtocheckout']```) matches an element.
