### ISSUE TITLE
Unable to perform a driver.getPageSource() with Android 7 for some screens

### ISSUE THREAD

**Issue by appiumnovice** [appium/appium#7235]
## The problem

Unable to perform a driver.getPageSource() for some screens under Android 7.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Desktop OS/version used to run Appium: MacOS El Capitan 10.11.6
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Nexus 5x device + Android Studio emulator
* Appium CLI or Appium.app|exe: CLI
* Use of Selenium Grid

## Details

Unable to perform a driver.getPageSource() for some screens under Android 7.
The method getPageSource() works well under Android 4 to 6.

The test waits for a server response but without success (I stopped the test after 1 hour).

Every around 15 minutes, it got the message:

[Forwarding getPageSource on session e99ef1de-45b1-4531-9813-f511d72f5bf1 to remote] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://dm-c07nn0slg1j1.local:5053: The target server failed to respond
[Forwarding getPageSource on session e99ef1de-45b1-4531-9813-f511d72f5bf1 to remote] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://dm-c07nn0slg1j1.local:5053

## Link to Appium logs

https://gist.github.com/appiumnovice/f58fe333e10f574ac999251a18f0c066

You can find gits for:
- Appium full log
- Visibles errors from the client side
- The page source of the screen under Android 6

## Code To Reproduce Issue [ Good To Have ]

driver.getPageSource()

**Comment by gwpantazes** [comment]
I am having the same issue on a different version of Appium! I'll add more information to this bug report instead of duping it.

## The problem

Intermittent error when calling driver.getPageSource(), driver.takeScreenshot(), driver.hideKeyboard(), and touchActions that causes org.apache.http.NoHttpResponseException which disconnects the driver and retries for an hour. Most commonly, it is getPageSource().

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2
* Desktop OS/version used to run Appium: MacOS 10.11.6
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: Nexus 9
* Appium CLI or Appium.app|exe: CLI

## Details

The setup is typical. A host machine connected to real device via USB. The only extra consideration is that the job is running from an automated Jenkins server and the device and host stay on for long periods of time.

It appears that commands driver.getPageSource(), driver.takeScreenshot(), and driver.hideKeyboard, and touchActions can cause the driver to take an hour to communicate to the Appium server / device. It also appears that this is a blocking command in the test suite thread, so the test suite takes hours more than it should.

I haven't been able to pin down what causes the disconnects. Other commands such as findBy seem to be working fine right before the problem occurs. When I had more calls to hideKeyboard() in my test suite, that command caused the most occurences of this issue. Now it most commonly is getPageSource, then takeScreenshot, then swipe().

My suspicion is that it is commands that rely on certain adb protocols underneath are the cause of this, but I haven't been able to verify the cause of this intermittent issue.

## Link to Appium logs
https://gist.github.com/gwpantazes/76377de37913492066df5e2ec7454aac gist has:

- the full Appium log of a session
- the test suite logs paired with it for context
- a simplified code snippet showing where the problem typically happens.

In the full Appium log, refer to the timestamp at 2016-11-07 16:13:12,662 to see the problem

```
2016-11-07 16:13:12,655 INFO  [jfptest-nexus9 Appium Instance] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["14686f3b-b098-4174-be36-cd306ff0c604"]
    2016-11-07 16:13:12,656 INFO  [jfptest-nexus9 Appium Instance] [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
    2016-11-07 16:13:12,658 INFO  [jfptest-nexus9 Appium Instance] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
    2016-11-07 16:13:12,660 INFO  [jfptest-nexus9 Appium Instance] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
    2016-11-07 16:13:12,662 INFO  [jfptest-nexus9 Appium Instance] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
    2016-11-07 16:23:12,693 INFO  [jfptest-nexus9 Appium Instance] [HTTP] <-- GET /wd/hub/session/14686f3b-b098-4174-be36-cd306ff0c604/source - - ms - -
    2016-11-07 16:23:12,695 INFO  [jfptest-nexus9 Appium Instance] [HTTP] --> GET /wd/hub/session/14686f3b-b098-4174-be36-cd306ff0c604/source {}
    2016-11-07 16:23:12,696 INFO  [jfptest-nexus9 Appium Instance] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["14686f3b-b098-4174-be36-cd306ff0c604"]
```
    
In the test suite log, refer to the timestamp at 17:41:28 to see the problem.

```
17:41:28 [main] INFO com.mycompany.interaction.objects.structure.WebTree - Getting page source with driver.getPageSource()
17:51:28 Nov 17, 2016 5:51:28 PM org.apache.http.impl.execchain.RetryExec execute
17:51:28 INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://mobiletest.mydomain.mycompany.com:4727: The target server failed to respond
```

The the timestamps don't match up because they are from different sessions, but it's the same exact problem.

## Code To Reproduce Issue [ Good To Have ]

See the code snippet provided in the gist for the most common point of failure.

- driver.getPageSource()
- driver.takeScreenshot()
- driver.hideKeyboard()
- touchActions (in my test suite, the driver.swipe() method triggered the problem)

Unfortunately, this bug is only reproducible during long test suite runs (but can happen early on) from the Jenkins server. I can't reproduce this issue on a local machine and Nexus 9.

**Comment by appiumnovice** [comment]
I think this is not the same problem.
I have this one only on Android 7, for 2 screens and it is reproducible.

**Comment by gwpantazes** [comment]
OK, should I take out my comment and make a different issue?

We both get the same RetryExec problem as you showed with yours:
```
[Forwarding getPageSource on session e99ef1de-45b1-4531-9813-f511d72f5bf1 to remote] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://dm-c07nn0slg1j1.local:5053: The target server failed to respond
[Forwarding getPageSource on session e99ef1de-45b1-4531-9813-f511d72f5bf1 to remote] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {}->http://dm-c07nn0slg1j1.local:5053
```
and this is what mine looks like:
```
17:51:28 Nov 17, 2016 5:51:28 PM org.apache.http.impl.execchain.RetryExec execute
17:51:28 INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://mobiletest.mydomain.mycompany.com:4727: The target server failed to respond
```

I think we might have the root of the problem in common.

**Comment by jlipps** [comment]
@gwpantazes I believe what is happening is your client script is timing out waiting for a response from the Appium server. It looks like the source command is just taking a really long time. So your client decides to time out, which is why you get an exception. I don't think Appium can do anything to fix that.

Can you think of any reason why the source would take a long time to generate? If you use `uiautomatorviewer`, does it work quickly

**Comment by gwpantazes** [comment]
@jlipps driver.getPageSource() works fine most of the time. It is an intermittent (but frequent enough) issue that causes my timeouts. I haven't been able to try Uiautomatorviewer because it is a remote device hooked up to a Jenkins server, but I can have someone check that.

If @appiumnovice can reproduce their timeout on certain screens, that's a clue for me to try to isolate all the screens that the timeout has occurred on. I'd like to point out that I've had my timeout not just on pagesource, but on hiding the keyboard, touchActions, and taking a screenshot.

My thoughts were maybe this problem could have to do with Appium Server and ADB causing a hang with the device, leaving the client script hanging waiting for a response. Appium might be able to help if it has to do with reestablishing connection with ADB. I'll try to isolate the problem to specific pages to see if I can reproduce it.

**Comment by jlipps** [comment]
@gwpantazes that sounds like a good plan. There may indeed be something appium can do if we can isolate this to adb hanging or something similar.

**Comment by qjf1111** [comment]
I am having the same issue ,with  some screens under Android 7;perform  driver.getPageSource() or drinver.FindElementByName()  will with no response untill timeout. but in those screens, uiautomatorviewer can get elements quickly.   Do any one have a Solution?

**Comment by vanangelov** [comment]
I am having exactly the same problem. Everything works even with Android 7 for a few of the simpler screens in our app (basically the login screen), but then at one of the busier screens getPageSource() timeouts. At least this thread made me realize this does not happen with Android 6.
Here is what the hierarchy of the problematic activity looks like, in case this can be helpful:

    <android.widget.FrameLayout>
        <android.widget.LinearLayout>
            <android.widget.FrameLayout>
                <android.widget.LinearLayout>
                    <android.widget.FrameLayout>
                        <android.support.v4.widget.DrawerLayout>
                            <android.view.ViewGroup>
                                <android.widget.LinearLayout>
                                    <android.widget.FrameLayout>
                                        <android.widget.ImageView>
                                    <android.view.ViewGroup>
                                        <android.widget.ImageButton>
                                        <android.view.View>
                                    <android.widget.LinearLayout>
                                        <android.widget.ImageView>
                                <android.widget.FrameLayout>
                                    <android.widget.FrameLayout>
                                        <android.view.ViewGroup>
                                            <android.support.v7.widget.RecyclerView>
                                                <android.widget.TextView>
                                                <android.widget.FrameLayout>
                                                    <android.widget.LinearLayout>
                                                        <android.widget.RelativeLayout>
                                                            <android.widget.ImageView>
                                                            <android.widget.TextView>
                                                            <android.widget.TextView>
                                                        <android.widget.LinearLayout>
                                                            <android.widget.TextView>
                                                            <android.widget.TextView>
                                                        <android.view.View>
                                                        <android.widget.LinearLayout>
                                                            <android.widget.TextView>
                                                            <android.widget.TextView>
        <android.view.View>

**Comment by ymin** [comment]
Having same issue on Android 7 for some screen, here is the logs getPageSource call and its response:
```
[2017-05-03 03:41:24][HTTP] --> GET /wd/hub/session/5c5f7108-00a7-49e4-a264-ead9e386a5c4/source {}
[2017-05-03 03:41:24][MJSONWP] Calling AppiumDriver.getPageSource() with args: ["5c5f7108-00a7-49e4-a264-ead9e386a5c4"]
[2017-05-03 03:41:24][AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[2017-05-03 03:41:24][AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
[2017-05-03 03:41:24][AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[2017-05-03 03:41:24][AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
[2017-05-03 03:43:14][AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"<\/hierarchy>"}
[2017-05-03 03:43:14][AndroidBootstrap] Received command result from bootstrap
[2017-05-03 03:43:14][MJSONWP] Responding to client with driver.getPageSource() result: ""
[2017-05-03 03:43:14][HTTP] <-- GET /wd/hub/session/5c5f7108-00a7-49e4-a264-ead9e386a5c4/source 200 110052 ms - 564 
```

**Comment by mykola-mokhnach** [comment]
@ymin Check the adb logcat output - are there any errors there?

**Comment by ymin** [comment]
[adblogs.txt](https://github.com/appium/appium/files/973540/adblogs.txt)

@mykola-mokhnach here is the adb logs
You can see that the previous action/command works, and screen switches to new page, but then the call getPageSource is getting "Retrying" for 110s, from 05-03 15:41:12.365 to 05-03 15:43:12.777

**Comment by ymin** [comment]
so it's the same issue than https://github.com/appium/appium/issues/7775, I will try with UIA2

**Comment by ymin** [comment]
Works with uiautomator2 for my case.

**Comment by VasilijSviridov** [comment]
same issue here, any update or suggestion ?

**Comment by VasilijSviridov** [comment]
[HTTP] --> GET /wd/hub/session/43b77131-5bc1-422b-8adc-5dedc1f34715/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["43b77131-5bc1-422b-8adc-5dedc1f34715"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
[HTTP] --> GET /wd/hub/session/43b77131-5bc1-422b-8adc-5dedc1f34715/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["43b77131-5bc1-422b-8adc-5dedc1f34715"]
[HTTP] <-- GET /wd/hub/session/43b77131-5bc1-422b-8adc-5dedc1f34715/source - - ms - - 
[HTTP] --> GET /wd/hub/session/43b77131-5bc1-422b-8adc-5dedc1f34715/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["43b77131-5bc1-422b-8adc-5dedc1f34715"]
[HTTP] <-- GET /wd/hub/session/43b77131-5bc1-422b-8adc-5dedc1f34715/source - - ms - - 
[HTTP] --> GET /wd/hub/session/43b77131-5bc1-422b-8adc-5dedc1f34715/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["43b77131-5bc1-422b-8adc-5dedc1f34715"]
[HTTP] <-- GET /wd/hub/session/43b77131-5bc1-422b-8adc-5dedc1f34715/source - - ms - - 
[HTTP] --> GET /wd/hub/session/43b77131-5bc1-422b-8adc-5dedc1f34715/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["43b77131-5bc1-422b-8adc-5dedc1f34715"]
[HTTP] <-- GET /wd/hub/session/43b77131-5bc1-422b-8adc-5dedc1f34715/source - - ms - - 
[HTTP] --> GET /wd/hub/session/43b77131-5bc1-422b-8adc-5dedc1f34715/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["43b77131-5bc1-422b-8adc-5dedc1f34715"]

**Comment by vanangelov** [comment]
@VasilijSviridov - at this point I am just not trying to run my tests on Android 7.  Uiautomator2 does seem to solve this particular issue, however I ran into other serious problems with it.

**Comment by VasilijSviridov** [comment]
sweet :D

Cheers @vanangelov

**Comment by VasilijSviridov** [comment]
it seems that at some point appium overloading uiautomator to get xml, and it seems that there is some major memory leaking and some problems with garbage collectors, if you can split your test in chunks and use smth like pipeline, you may get some extreme nice results .
As example I split test in 40 chunks, and running every of it as independent jenkins build, no more issues friends =)

**Comment by happyMeiyo** [comment]
same issue here, any update or suggestion ?
