### ISSUE TITLE
Error occured while starting App. Original error: com.company.android.app.qa/com.company.android.app.controller.SplashActivity or .com.company.android.app.controller.SplashActivity never started

### ISSUE THREAD

**Issue by xshuRoadie** [appium/appium#7267]
## The problem

With Appium 1.6.0-beta3 I keep getting this error when our android app is launched: 
Encountered internal error running command: Error: Error occured while starting App. Original error: com.company.android.app.qa/com.company.android.app.controller.SplashActivity or .com.company.android.app.controller.SplashActivity never started

The same tests are running completely fine with Appium 1.5.3 though. 

Here are my desired capabilities. Any change I should make to work with the latest appium?
'platformName': 'Android',
'platformVersion': '5.1.1',
'deviceName': 'Nexus 5',
'newCommandTimeout': 240,
'noSign': 'true',
'fullReset': 'true',
'automationName': 'appium'

## Link to Appium logs
https://gist.github.com/xshuRoadie/9d26a30286a5238cb423ac81143f8e60

**Comment by jlipps** [comment]
I'm not sure. It seems that your app is starting a different activity:

> [debug] [ADB] Found package: 'com.company.android.app.qa' and activity: 'com.company.android.app.controller.ftue.NewFtueActivity'

Not sure what Appium change could contribute to that. But FWIW you could use 1.6.1 beta instead of 1.6.0 beta

**Comment by xshuRoadie** [comment]
Updated to 1.6.1 beta. The issue is still there. I will just work with 1.5.3 for now. Hopefully later this issue can go away automatically :)

**Comment by xshuRoadie** [comment]
I just figured that out. The order of activities specified in desired capabilities matters. The following configuration fixed the issue:
'appActivity': 'com.company.android.app.controller.SplashActivity',
'appWaitActivity': 'com.company.android.app.controller.SplashActivity, com.company.android.app.controller.main.MainActivity'

**Comment by jlipps** [comment]
Glad to hear that fixed it!

**Comment by avrahamShutterFly** [comment]
@jlipps @imurchie I have this issue on appium 1.6.5.beta

**Comment by imurchie** [comment]
@avrahamShutterFly Ok. There is nothing we can do to help without the Appium server logs (full logs, posted as a link to a [gist](https://gist.github.com)).

**Comment by divyavairavel** [comment]
Am also facing the same issue. can anyone help me? 
![image](https://user-images.githubusercontent.com/29920754/27865305-bc1d8e7a-61af-11e7-9501-d232a09d0fdf.png)

**Comment by danigol** [comment]
I've also been seeing this issue. Providing no wait activity doesn't help, neither does adding the "missing" activities to the desired capabilities for app wait package. In fact, it seems the more I add, the more complex the requested activity strings get, eventually becoming long activities, each one failing after it's done waiting for the one before it. 

I have retry logic built into our tests, which reloads the app and restarts it, which seems to work, but this is adding significant time to our tests. 

App will launch, sit for a few seconds, and crash, then we reset, and it's not always fixed, so this sometimes happens a number of times before failing my tests, often wasting quite a few minutes. 

[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: com.company.organization.controller.activities.NavDrawerActivity or com.company.organization.controller.com.company.organization.controller.activities.NavDrawerActivity never started

Yes, the package, com.company.org is repeated twice in the second activity, which is why entering these in to the desired capabilities doesn't fix the problem, it just keeps repeating that as though it's attempting to recursively build out a package name and getting stuck at the base case for a few executions.

**Comment by imurchie** [comment]
@danigol Can you create a new issue with the full logs, etc.? Then we can try to fix this in the latest code.

**Comment by danigol** [comment]
@imurchie Sorry for the delay. Issue created: https://github.com/appium/appium/issues/8868
