### ISSUE TITLE
'RoutingHTTPServer/RoutingConnection.h' file not found FBWebServer.m

### ISSUE THREAD

**Issue by gopi09m** [appium/appium#7283]
## The problem

'RoutingHTTPServer/RoutingConnection.h' file not found FBWebServer.m error while building webDriverAgent project in Xcode

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4
* Desktop OS/version used to run Appium: mac OSx 10.12.1
* Node.js version (unless using Appium.app|exe): latest
* Mobile platform/version under test: iOS 10.1
* Real device or emulator/simulator:: Real Device
* Appium CLI or Appium.app|exe: 1.6 no UI

## Details

Our app is signed with a dev team (apple dev account)certificate. Test team has their own dev account which we use in webDriverAgent code singing settings and when i try to launch the app through appium selenium code it was giving some errors  related to codesigning. After few trial and errors i got everything fixed except the below error:

'RoutingHTTPServer/RoutingConnection.h' file not found FBWebServer.m

When i again look at the build errors its due to provision certificate error. It installs the app on device but fails at launch. 

So if WebDriverAgent project doesnt compile, then it will never launch the app ? 
Should we use Dev certificate for WebDriverAgent code signing settings or a different Dev account test team should also work?

**Comment by mykola-mokhnach** [comment]
Execute 

```
bash Scripts/bootstrap.sh -d
```

script to download carthage dependencies first.

**Comment by gopi09m** [comment]
Now i get the following message:

Failed to create provisioning profile. The app ID "com.facebook.IntegrationApp" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.
No profiles for 'com.facebook.IntegrationApp' were found:  Xcode couldn't find a provisioning profile matching 'com.facebook.IntegrationApp'.
Code signing is required for product type 'Application' in SDK 'iOS 10.1'

**Comment by mykola-mokhnach** [comment]
Please search the existing issues. This problem has been discussed many times before.

**Comment by gopi09m** [comment]
We were not able to run the command "sudo -s bash /Users/automation/node_modules/appium-xcuitest-driver/WebDriverAgent/Scripts/bootstrap.sh -d"

It says "Run this script from the root of repository"

We enabled root user and also tried the bash bootstrap.sh command from Scripts directory in terminal window

**Comment by mykola-mokhnach** [comment]
This does not mean you need to run the command as root, but rather that the current shell folder (pwd) should be the root folder of WDA project.

**Comment by gopi09m** [comment]
Ok . Thanks for that tip. It was able to download all the dependencies. Now it gives the below error 

Failed to create provisioning profile. The app ID "com.facebook.IntegrationApp" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.
No profiles for 'com.facebook.IntegrationApp' were found:  Xcode couldn't find a provisioning profile matching 'com.facebook.IntegrationApp'.
Code signing is required for product type 'Application' in SDK 'iOS 10.1'

**Comment by gopi09m** [comment]
When i selected the enterprise team account it was able to compile without a need for provisioning. Thanks for the help @mykola-mokhnach

**Comment by RashmiMurthy** [comment]
still same issue persists in Appium 1.6.2 version

'RoutingHTTPServer/RoutingHTTPServer.h' file not found hile building webDriverAgent project in Xcode

**Comment by sarozNep** [comment]
@mykola-mokhnach  i dont know how to execute ....i am new to these ,, can u please help me ,, i have the same problem while building ..

bash Scripts/bootstrap.sh -d

script to download carthage dependencies first.

**Comment by acahet** [comment]
@sarozNep 
go to: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent using your terminal and from there just paste it to your terminal:  ---> Scripts/bootstrap.sh -d  <----
and press enter
don't need to have 'bash'

**Comment by hliulka15** [comment]
This does not work for me. Same problem persists. I've tried the above bash command and I've tried changing signing profile on WebDriverAgentLib and WebDriverAgentRunner. Same error message occurs. I've also tried uninstalling and reinstalling appium.

Interestingly, Appium and WDA still run as expected on an iPhone simulator but they will not work on a real device.  I had it running before but I have no idea why it's so badly broken now. Is it possible Appium 1.3.2 (GUI) broke this file as well? I'm running Appium 1.3.1 (GUI) and 1.7.2 (command line).

Also, WDA in xcode looks alarming (image attached).

<img width="296" alt="screen shot 2018-02-14 at 10 30 53 am" src="https://user-images.githubusercontent.com/34134820/36215607-2d46478c-1172-11e8-822b-e57718b6b1ce.png">

**Comment by ctrevarthen** [comment]
@hliulka15 

First, I would not be very worried about the red files in the project. It mean the the locations of the files and directories expected by the Xcode project file are not in the location Xcode expects (which doesn't mean they're not there). In this case, the path to `WebDriverAgentLib` is `XCTWebDriverAgentLib` and `WebDriverAgentRunner` is `XCTUITestRunner` in the `.pbxproj` file. It looks like this was a refactoring that wasn't updated in the project, but it shouldn't cause any issues. 

If you are concerned enough to remove the red highlighting, you can click the offending folder and then choose the new location of the file using the "Identity and Type" inspector:

![screen shot 2018-05-07 at 3 54 27 pm](https://user-images.githubusercontent.com/2512443/39721971-234d0242-520f-11e8-9ad8-46f8af0dfa53.png)

So that it looks like this:

![screen shot 2018-05-07 at 3 56 54 pm](https://user-images.githubusercontent.com/2512443/39722014-4f9c0d3e-520f-11e8-9247-7a5bd6ee9933.png)

As for the issue of not finding `RoutingHTTPServer/RoutingConnection.h`, I ran into this when my Carthage frameworks weren't installed correctly. To confirm whether you've got everything set up right, first find out where appium is installed with:

```
which appium
```

 You should see something like `/usr/local/bin/appium`. However, that's just a link to a single appium js file, so you'll need to also run:

```
ls /usr/local/bin/appium
```

Which should give you a listing like:

```
/usr/local/bin/appium -> ../lib/node_modules/appium/build/lib/main.js
```

That means your root appium directory is `/usr/local/lib/node_modules/appium`. Within that directory, there will be a `node_modules/appium-xcuitest-driver/WebDriverAgent` directory, which has the Xcode project for the WebDriverAgent. Change to that directory: 

```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
```

From here, run the bootstrap script to pull down project dependencies, including the HTTPServer framework (note the `-d` which will only pull down dependencies, which is what you want):

```
./Scripts/bootstrap.sh -d
```

After this step, you should see a directory `Carthage/Build/iOS` which has the `RoutingHTTPServer.framework` and `YYCache.framework` files. 

The WebDriverAgentLib Xcode project will be looking in the `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS` directory for those frameworks, so if they're not there, then that would explain why you can't build. (Alternatively, a file named `Carthage` may be there, but it's not a directory, which is also not going to work).

In the event that those framework files are not there, you could try removing any instances of Appium from your machine, using `npm uninstall -g appium` and making sure the `/usr/local/lib/node_modules/appium` directory is cleaned up.

Then reinstall the appium node modules with `npm install -g appium`.

Hope this helps!

**Comment by KRUBERLICK** [comment]
```
⇣0%  sudo Scripts/bootstrap.sh -d
Password:
Fetching dependencies
*** Checking out RoutingHTTPServer at "v1.0.1"
*** Checking out YYCache at "1.0.5"
*** Cloning YYCache
Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=512 "The file “Carthage” couldn’t be saved in the folder “WebDriverAgent”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage, NSUnderlyingError=0x7fca06c26ab0 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}})
```

What's wrong with this one?

**Comment by followzms** [comment]
Maybe it will be helpful for someone.
I have had the same problem - 'RoutingHTTPServer/RoutingConnection.h' file not found FBWebServer.m
I tried to execute `bootstrap.sh` , but nothing happened.
I resolved this problem by following steps:
1. Check  Carthage version
`carthage version`
2. If you have 
`-bash: -bash:: command not found`
try to install Carthage via brew
`brew install carthage`
3. If after this you have 
`Warning: carthage already installed, it's just not linked`
try 
`brew link carthage`
4. In my case after `brew link carthage`, I have had the following error
```
Warning: Could not link carthage. Unlinking...
Error: The brew link step did not complete successfully
The formula built, but is not symlinked into /usr/local
You can try again using `brew link carthage'
Error: Permission denied - /usr/local/Frameworks
```
5. So, I created Frameworks directory
`sudo mkdir /usr/local/Frameworks`
and try to
`brew link carthage`
again, and it was successfully completed
`Linking /usr/local/Cellar/carthage/0.3… 4 symlinks created`
6. Than I try to execute bootstrap.sh again 
```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
./Scripts/bootstrap.sh -d
```
After this, the XCode build was completed.

**Comment by tiecongli** [comment]
> @hliulka15
> 
> First, I would not be very worried about the red files in the project. It means the the locations of the files and directories expected by the Xcode project file are not in the location Xcode expects (which doesn't mean they're not there). In this case, the path to `WebDriverAgentLib` is `XCTWebDriverAgentLib` and `WebDriverAgentRunner` is `XCTUITestRunner` in the `.pbxproj` file. It looks like this was a refactoring that wasn't updated in the project, but it shouldn't cause any issues.
> 
> If you are concerned enough to remove the red highlighting, you can click the offending folder and then choose the new location of the file using the "Identity and Type" inspector:
> 
> ![screen shot 2018-05-07 at 3 54 27 pm](https://user-images.githubusercontent.com/2512443/39721971-234d0242-520f-11e8-9ad8-46f8af0dfa53.png)
> 
> So that it looks like this:
> 
> ![screen shot 2018-05-07 at 3 56 54 pm](https://user-images.githubusercontent.com/2512443/39722014-4f9c0d3e-520f-11e8-9247-7a5bd6ee9933.png)
> 
> As for the issue of not finding `RoutingHTTPServer/RoutingConnection.h`, I ran into this when my Carthage frameworks weren't installed correctly. To confirm whether you've got everything set up right, first find out where appium is installed with:
> 
> ```
> which appium
> ```
> You should see something like `/usr/local/bin/appium`. However, that's just a link to a single appium js file, so you'll need to also run:
> 
> ```
> ls /usr/local/bin/appium
> ```
> Which should give you a listing like:
> 
> ```
> /usr/local/bin/appium -> ../lib/node_modules/appium/build/lib/main.js
> ```
> That means your root appium directory is `/usr/local/lib/node_modules/appium`. Within that directory, there will be a `node_modules/appium-xcuitest-driver/WebDriverAgent` directory, which has the Xcode project for the WebDriverAgent. Change to that directory:
> 
> ```
> cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
> ```
> From here, run the bootstrap script to pull down project dependencies, including the HTTPServer framework (note the `-d` which will only pull down dependencies, which is what you want):
> 
> ```
> ./Scripts/bootstrap.sh -d
> ```
> After this step, you should see a directory `Carthage/Build/iOS` which has the `RoutingHTTPServer.framework` and `YYCache.framework` files.
> 
> The WebDriverAgentLib Xcode project will be looking in the `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS` directory for those frameworks, so if they're not there, then that would explain why you can't build. (Alternatively, a file named `Carthage` may be there, but it's not a directory, which is also not going to work).
> 
> In the event that those framework files are not there, you could try removing any instances of Appium from your machine, using `npm uninstall -g appium` and making sure the `/usr/local/lib/node_modules/appium` directory is cleaned up.
> 
> Then reinstall the appium node modules with `npm install -g appium`.
> 
> Hope this helps!

I was getting this error because I was not in the right directory. The one I was on was /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent. Thanks a lot you saved my life.
