### ISSUE TITLE
missing npm-shrinkwrap.json file?

### ISSUE THREAD

**Issue by john7doe** [appium/appium#7359]
## The problem

I think that that last few releases (1.6.1 and 1.6.2) are missing their npm-shrinkwrap.json file.

At least the change log for 1.6.2 seems to hint to usage of an updated version of the WebDriverAgent: "This is a small, mostly-emergency release because we realized we omitted
XCUITest upgrades via WebDriverAgent that we had mistakenly presumed were part
of 1.6.1."

but there have not been any changes to the package.json entry for appium-xcuitest-driver (its been ^2.0.25 since the 1.6.0) release.

Since the npm-shrinkwrap.json file have been absent in 1.6.1 and 1.6.2 i'm having a hard time figuring out what version of  appium-xcuitest-driver that is intended to be used.

**Comment by jlipps** [comment]
@john7doe how are you getting appium? I just reinstalled it using `npm install -g appium`, and when I looked into its directory where it was installed, I found a `npm-shrinkwrap.json`.

You're right that `package.json`s all over the place have not changed, because their semver ranges include all the updates that have been released, so `package.json` updates are not required. This should be reflected in the `npm-shrinkwrap.json`, though.

**Comment by john7doe** [comment]
Im working directly off the source, and did a `git checkout v1.6.2` in the main repo. 
previous releases do contain a npm-shrinkwrap.json:
e.g:
https://github.com/appium/appium/blob/v1.6.0/npm-shrinkwrap.json
https://github.com/appium/appium/blob/1.5.3/npm-shrinkwrap.json

I would expect the file to be present per. https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/developers-overview.md#releasing: "Since the configuration file, npm-shrinkwrap.json, only exists on release branches, it is necessary to manually manage it during the release process. It needs to be checked in to GitHub along with changes to package.json."

**Comment by jlipps** [comment]
`npm-shrinkwrap.json` has once again been committed at the appropriate tags. Thanks for the heads up.
