### ISSUE TITLE
WDA Fails to Start Properly on iOS 10.2 - XCode 8.2.1 - Real Device

### ISSUE THREAD

**Issue by baclark774** [appium/appium#7586]
WebDriverAgent is never started properly on iOS 10.2 with XCode 8.2

## Environment

* Appium Version: 1.6.3
* Desktop OS/version used to run Appium: OS Sierra
* Node.js version (unless using Appium.app|exe): Latest
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details
Launching WebDriverAgent on 10.2 hangs on the "Setup" line without the proxy listener indicating it's ready:

xcodebuild -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<id>' test

Will hang forever at:

Test Suite 'All tests' started at 2016-12-21 16:13:08.512
Test Suite 'WebDriverAgentRunner.xctest' started at 2016-12-21 16:13:08.515
Test Suite 'UITestingUITests' started at 2016-12-21 16:13:08.516
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2016-12-21 16:13:08.520
    t =     0.01s     Set Up

I've tried updating WebDriverAgent from both the master and 8.2 branches but the problem persists.

**Comment by dpgraham** [comment]
This sounds like a problem with https://github.com/facebook/WebDriverAgent

**Comment by imurchie** [comment]
Appium 1.6.4-beta has been released (to upgrade, run `npm uninstall -g appium && npm install -g appium@beta`). How we connect to devices has been significantly changed, and should be more reliable. Please try it out.

There is some documentation here: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

I am closing this issue since the details will have changed completely. If you still have problems, please see if there is a similar issue, or else create a new issue with as much information as possible. We are committed to tracking down these elusive problems!
