### ISSUE TITLE
Webview context not found on Android 7.0

### ISSUE THREAD

**Issue by jesusMT** [appium/appium#7639]
## The problem
Webdriver context not found when I login for a second time.
  
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Book Pro
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android 7.0 API Level 24
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: npm appium
* Chrome: 55.0.2883.95
* ChromeDriver: 2.20.353124

## Details
I have an Android app and I'm trying to testing the login access.
In the first step, when I login, the context switch correctly to webview. Later, I logout and I want to relogin into the app (accessLogin.feature line:9) but the webview context is not found (global-position-page.js, line 20) and the test fails because the function timed out after 90000 milliseconds. 
I try to reproduce other scenario with differents steps but with the same cases, and I have the same problem when I logout and relogin.

## Link to Appium logs
https://gist.github.com/jesusMT/deef9b343e7d8ce96cac4ca7406bcdef
(The error starts at line 1208).

## Code To Reproduce Issue [ Good To Have ]
https://gist.github.com/jesusMT/2cbd96102fcbd52fcd840b14855d53cb

**Comment by jlipps** [comment]
It looks like somehow Chromedriver is not responding. It's likely not an Appium issue but maybe there's something we can do to work around it (maybe restarting chromedriver instead of reusing it, for example). I'll add this to our backlog.

**Comment by davidrova** [comment]
Hi @jlipps, 

I have been investigating this issue and found what is happening. I will try to explain shortly.

- When the test project starts there is no chromedriver process
- The first time the test wants to access a webview context Appium creates a chromedriver instance and starts a webview session. Appium caches the webview name and its session.
- When the test makes logout, the application restart the webview (probably it is not 100% correct)
- chromedriver process is not killed when the SUT kills the webview; there is another webview created, the google search widget
- In the second access to the application, when you login and try to change to your webview context, Appium detects the webview name is cached and tries to change to that context, but the webview reject the request because it is not a valid session for him

And as you recommend, if you kill chromedriver after logout, when you change to webview context, Appium doesn't detect the chromedriver and creates a new instance, so creates a new session with the new webview. And works!!

When do you decide to reuse chromedriver or restart it? Are you able to detect the webviews opened by the SUT?

Thanks for your great support!!! 

Kind regards

pd: if you need logs let me know.

**Comment by jlipps** [comment]
@davidrova can you please try running your test with the `recreateChromeDriverSessions` capability set to `true`?

**Comment by jlipps** [comment]
fantastic! this issue was beginning to sound familiar :-)
