### ISSUE TITLE
Cannot click in a Image in the Gallery using Android N 7.0

### ISSUE THREAD

**Issue by luisromanwp** [appium/appium#7735]
## The problem

In my app, when I try to select an image from the Android N 7.0 Gallery (Recent photos) to upload Appium says that the click happened but in the device the image wasn't selected. When I try with the same code or with Android Inspector in another Android with a different OS it works. (Worked in 6.0 and 7.1.1)

## Environment

* Appium 1.6.3
* Desktop OS/version used to run Appium: MacOS 
* Mobile platform/version under test: Android N 7.0
* Real device or emulator/simulator: Nexus 5 (Android N 7.0) and Nexus 6 (Android N 7.0) Emulator

**Comment by jlipps** [comment]
As the issue prompt requests, please link to a gist of your full appium log.

**Comment by LukasLewandowski** [comment]
Hi,

I got the same problem. I am using real device - Samsung Galaxy S7 with Android 7.0. I have tried clicking, tapping, tapping x,y coordinates and Appium thinks that actions were performed correctly, but nothing happened in application.

**Comment by jlipps** [comment]
Hi @LukasLewandowski unfortunately if Appium said the click was successful, that means that according to the UiAutomator engine, the click went through. I would recommend perhaps seeing if there's anything inside that View element, since it seems weird to try and just click on a View like that. Otherwise I would take a look at uiautomatorviewer to see if there could be any issue with the hierarchy. Finally you could try the UiAutomator2 driver rather than the older UiAutomator1 driver you're currently using.
