### ISSUE TITLE
Strange Warning in appium console 

### ISSUE THREAD

**Issue by shapovalovei** [appium/appium#7799]
## The problem

In console log i have strange warnings(errors)
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): TypeError: this.specialHandlers.Page.frameNavigated is not a function`
`DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): TypeError: this.pageLoad is not a function`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 v 
* Desktop OS/version used to run Appium: OS X Sierra 
* Node.js version (unless using Appium.app|exe): v7.5.0 and v6.9.5 LTS
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/shapovalovei/b510ec31e2de6cfee6af3583a67ba781

**Comment by imurchie** [comment]
This is fixed in 1.6.4-beta.

**Comment by shapovalovei** [comment]
@imurchie Thank you man !

**Comment by arrk-shch** [comment]
Hi,
Now sure whether to raise new issue. Hence, adding comment here.
I am using Appium v1.6.4-beta
On executing scripts for several days, I am getting following issue. To resolve space issue, tried to clear disk space but end up by formatting mac pro couple of times.
Here is appium log:
MacBook-Pro:~ developer$ appium
(node:41190) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: ENOSPC: no space left on device, mkdir '/var/folders/lm/k5ffrcs941q6db827yhtp2gc0000gp/T/201723-41190-1plw0ei.68ltwvzpvi'
(node:41190) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
Due to this, simulator is not running as no space left
I am really stuck now. How should I deal with this? Is appium logs eating up disk space? if yes then how I can clear it?
Thanks

**Comment by mykola-mokhnach** [comment]
@arrk-shch The space is allocated by XCTest logs. You may delete the content of

```
~/Library/Developer/Xcode/DerivedData/WebDriverAgent*
```

folder to free up the space and then set _preventWDAAttachments_ capability to **true** (the default setting since https://github.com/appium/appium/issues/7933 was merged) to avoid further space issues.

**Comment by arrk-shch** [comment]
@mykola-mokhnach Thank for the quick reply.
