### ISSUE TITLE
Improve retries for 'Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled'

### ISSUE THREAD

**Issue by ohadschn** [appium/appium#7828]
This notorious `xcodebuild` issue has been around for over 1.5 years (https://github.com/travis-ci/travis-ci/issues/4725), and apparently it is hasn't been resolved yet. It looks like this:
```
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: ...
[debug] [WebDriverAgent] Device: Feb  8 18:35:31 ...[919] <Notice>: Running tests...
[Xcode] 2017-02-08 18:37:23.593 xcodebuild[46629:525281] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Canceling tests due to timeout in Checking test manager availability... If you believe this error represents a bug, please attach the log file at ..." UserInfo={NSLocalizedDescription=Canceling tests due to timeout in Checking test manager availability... If you believe this error represents a bug, please attach the log file at ...}
[Xcode] 2017-02-08 18:37:23.595 xcodebuild[46629:525611] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fcade50c720>
```

It seems that appium is already retrying it (`xcodebuild failure warrants retry. Retrying...`),  however it quickly runs into the following error:
```
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /...
[debug] [WebDriverAgent] Device: Feb  8 18:37:37 ... XCTRunner[923] <Notice>: Running tests...
[Xcode] 2017-02-08 18:38:42.048 xcodebuild[46670:525672] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "The operation couldnâ€™t be completed. (DTXProxyChannel error 1.)
```

According to said ticket, sleeping before retrying might work around this issue. It's not clear how much sleep is needed, the advice there ranges from 5 to 20 seconds, so I suppose 10 seconds would be a good compromise.

Also, it might be wise to retry more than once (specifically if the second error I mentioned is encountered).

**Comment by imurchie** [comment]
Thanks for passing along the issue to look at. I'll check it out!

**Comment by kbalakumar99** [comment]
@imurchie  I am also Facing the same issue. Is this resolved?

**Comment by imurchie** [comment]
No.

**Comment by imurchie** [comment]
The latest `appium-xcuitest-driver` (2.9.0) introduces the capabilities `wdaStartupRetries` and `wdaStartupRetryInterval` to manipulate the number of retries (the former capability) and the pause between them (the latter capability).

**Comment by yodaqua** [comment]
Hi there

I'm experiencing the same issue. I've set wdaStartupRetries to 4 and wdaStartupRetryInterval to 20000, to no avail.

Please help.

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone 6","udid":"e5e9475fdb2af31bac09b20b45b891e4e26696d1","automationName":"XCUITest","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","wdaStartupRetries":4,"browserName":"","platformVersion":"10.2.1","wdaStartupRetryInterval":20000,"platformName":"iOS","app":"/Users/yodaqua/Dropbox/KineticSkunk/Business/Clients/Cobi Interactive/Apps/TupucaStaging_v1.1.0.bld17.ipa"},{},null,null,null,null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone 6'
[Appium]   udid: 'e5e9475fdb2af31bac09b20b45b891e4e26696d1'
[Appium]   automationName: 'XCUITest'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   wdaStartupRetries: 4
[Appium]   browserName: ''
[Appium]   platformVersion: '10.2.1'
[Appium]   wdaStartupRetryInterval: 20000
[Appium]   platformName: 'iOS'
[Appium]   app: '/Users/yodaqua/Dropbox/KineticSkunk/Business/Clients/Cobi Interactive/Apps/TupucaStaging_v1.1.0.bld17.ipa'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: wdaStartupRetries, wdaStartupRetryInterval.
[BaseDriver] Session created with session id: c7764ccd-8672-4f02-a3af-d7b272429ad0
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: e5e9475fdb2af31bac09b20b45b891e4e26696d1
[debug] [XCUITest] Creating iDevice object with udid e5e9475fdb2af31bac09b20b45b891e4e26696d1
[XCUITest] Determining device to run tests on: udid: 'e5e9475fdb2af31bac09b20b45b891e4e26696d1', real device: true
[BaseDriver] Using local app '/Users/yodaqua/Dropbox/KineticSkunk/Business/Clients/Cobi Interactive/Apps/TupucaStaging_v1.1.0.bld17.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-781-15rxe6v.p032vp9zfr/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-781-15rxe6v.p032vp9zfr/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-781-15rxe6v.p032vp9zfr/Payload/TupucaStaging.app'
[debug] [XCUITest] Checking whether app '/var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-781-15rxe6v.p032vp9zfr/Payload/TupucaStaging.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-781-15rxe6v.p032vp9zfr/Payload/TupucaStaging.app': 'com.eric.tupuca'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e5e9475fdb2af31bac09b20b45b891e4e26696d1 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Unable to get device time. Using local system time
[debug] [XCUITest] Output from idevicedate: Mon Feb 27 18:20:37 SAST 2017

[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/60BD033D-19C7-4A21-BAE1-1E12763B6C28/Session-WebDriverAgentRunner-2017-02-27_182042-kWhxme.log
[Xcode] 2017-02-27 18:20:43.584 xcodebuild[1229:29714] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/60BD033D-19C7-4A21-BAE1-1E12763B6C28/Session-WebDriverAgentRunner-2017-02-27_182042-kWhxme.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/60BD033D-19C7-4A21-BAE1-1E12763B6C28/Session-WebDriverAgentRunner-2017-02-27_182042-kWhxme.log}

[Xcode]
Testing failed:
	'RoutingHTTPServer/RoutingHTTPServer.h' file not found
** TEST FAILED **


The following build commands failed:
	CompileC /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBHTTPOverUSBServer.o WebDriverAgentLib/Routing/FBHTTPOverUSBServer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

[Xcode] (1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] xcodebuild failure warrants retry. Retrying...
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 1235)
[XCUITest] System log exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e5e9475fdb2af31bac09b20b45b891e4e26696d1 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Unable to get device time. Using local system time
[debug] [XCUITest] Output from idevicedate: Mon Feb 27 18:20:44 SAST 2017

[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/1B2AABCF-5146-484F-9E3C-939D35CAF264/Session-WebDriverAgentRunner-2017-02-27_182045-9drKBe.log
[Xcode] 2017-02-27 18:20:46.286 xcodebuild[1283:29839] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/1B2AABCF-5146-484F-9E3C-939D35CAF264/Session-WebDriverAgentRunner-2017-02-27_182045-9drKBe.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/1B2AABCF-5146-484F-9E3C-939D35CAF264/Session-WebDriverAgentRunner-2017-02-27_182045-9drKBe.log}

[Xcode] 2017-02-27 18:20:46.288 xcodebuild[1283:29908] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fbb84228c00>

[Xcode]
Testing failed:
	'RoutingHTTPServer/RoutingHTTPServer.h' file not found
** TEST FAILED **


The following build commands failed:
	CompileC /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBHTTPOverUSBServer.o WebDriverAgentLib/Routing/FBHTTPOverUSBServer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:192:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:192:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 1290)
[XCUITest] System log exited with code 'null'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:192:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[HTTP] <-- POST /wd/hub/session 500 11446 ms - 167
[Session-WebDriverAgentRunner-2017-02-27_182409-4LZZEl.log.zip](https://github.com/appium/appium/files/804274/Session-WebDriverAgentRunner-2017-02-27_182409-4LZZEl.log.zip)

**Comment by imurchie** [comment]
Neither of those capabilities work for your version of Appium. 
```
[BaseDriver] The following capabilities were provided, but are not recognized by appium: wdaStartupRetries, wdaStartupRetryInterval.
```
I'm not sure they will fix your situation, but upgrading to Appium 1.6.4-beta would be a start (`npm uninstall -g appium && npm install -g appium@beta`).

**Comment by yodaqua** [comment]
Hi Imurchie,

Thanks for the prompt response. Most appreciated.

I've followed the instructions (npm uninstall -g appium && npm install -g appium@beta). However I now get a new error:

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone 6","udid":"e5e9475fdb2af31bac09b20b45b891e4e26696d1","automationName":"XCUITest","wdaStartupRetries":5,"browserName":"","platformVersion":"10.2.1","wdaStartupRetryInterval":50000,"platformName":"iOS","app":"/Users/yodaqua/Dropbox/KineticSkunk/Business/Clients/Cobi Interactive/Apps/TupucaStaging_v1.1.0.bld17.ipa"},{},null,null,null]
[Appium] Creating new XCUITestDriver (v2.12.1) session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone 6'
[Appium]   udid: 'e5e9475fdb2af31bac09b20b45b891e4e26696d1'
[Appium]   automationName: 'XCUITest'
[Appium]   wdaStartupRetries: 5
[Appium]   browserName: ''
[Appium]   platformVersion: '10.2.1'
[Appium]   wdaStartupRetryInterval: 50000
[Appium]   platformName: 'iOS'
[Appium]   app: '/Users/yodaqua/Dropbox/KineticSkunk/Business/Clients/Cobi Interactive/Apps/TupucaStaging_v1.1.0.bld17.ipa'
[debug] [XCUITest] XCUITestDriver version: 2.12.1
[BaseDriver] Session created with session id: e8984d1b-1170-4f56-bf68-fcd8e51c75d6
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: e5e9475fdb2af31bac09b20b45b891e4e26696d1
[debug] [XCUITest] Creating iDevice object with udid 'e5e9475fdb2af31bac09b20b45b891e4e26696d1'
[XCUITest] Determining device to run tests on: udid: 'e5e9475fdb2af31bac09b20b45b891e4e26696d1', real device: true
[BaseDriver] Using local app '/Users/yodaqua/Dropbox/KineticSkunk/Business/Clients/Cobi Interactive/Apps/TupucaStaging_v1.1.0.bld17.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-2046-10maevz.zk42dl5wmi/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-2046-10maevz.zk42dl5wmi/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-2046-10maevz.zk42dl5wmi/Payload/TupucaStaging.app'
[debug] [XCUITest] Checking whether app '/var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-2046-10maevz.zk42dl5wmi/Payload/TupucaStaging.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-2046-10maevz.zk42dl5wmi/Payload/TupucaStaging.app': 'com.eric.tupuca'
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] Reset requested. Removing app with id 'com.eric.tupuca' from the device
[debug] [XCUITest] Installing '/var/folders/30/_75gw7qd3zd_s6d0jvjxlzlh0000gn/T/2017127-2046-10maevz.zk42dl5wmi/Payload/TupucaStaging.app' on device with UUID 'e5e9475fdb2af31bac09b20b45b891e4e26696d1'...
[debug] [XCUITest] The app has been installed successfully.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e5e9475fdb2af31bac09b20b45b891e4e26696d1 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [XCUITest] Log file for xcodebuild test: /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/64896DCC-F783-43DF-B139-BD601B2DFD21/Session-WebDriverAgentRunner-2017-02-27_185439-igK5xN.log
[Xcode] 2017-02-27 18:54:39.387 xcodebuild[2238:74024] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f8b957a0d30 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode]
[Xcode] 2017-02-27 18:54:39.387 xcodebuild[2238:74024] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode]
[Xcode] ** TEST EXECUTE FAILED **
[Xcode]
[Xcode]
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 2237)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e5e9475fdb2af31bac09b20b45b891e4e26696d1 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [XCUITest] Log file for xcodebuild test: /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/29C18338-33D8-4118-BC7A-DB08CFFB188D/Session-WebDriverAgentRunner-2017-02-27_185536-7H9AJQ.log
[Xcode] 2017-02-27 18:55:36.353 xcodebuild[2270:78813] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f982becd110 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode]
[Xcode] 2017-02-27 18:55:36.353 xcodebuild[2270:78813] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode]
[Xcode] ** TEST EXECUTE FAILED **
[Xcode]
[Xcode]
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 2269)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e5e9475fdb2af31bac09b20b45b891e4e26696d1 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [XCUITest] Log file for xcodebuild test: /Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/76F74866-E11C-4E13-AF65-BA370F97463F/Session-WebDriverAgentRunner-2017-02-27_185633-rHjK8H.log
[Xcode] 2017-02-27 18:56:33.335 xcodebuild[2303:85116] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fa2435775b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-02-27 18:56:33.336 xcodebuild[2303:85116] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode]
[Xcode] ** TEST EXECUTE FAILED **
[Xcode]
[Xcode]
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 2302)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device

**Comment by yodaqua** [comment]
I noticed that the realDeviceLogger capability is not supported in 1.6.4-beta. So I removed it and reran the test. I got the same issue.

**Comment by imurchie** [comment]
There is an error in building the WebDriverAgent for your device. You can see more by either adding the `showXcodeLog` capability (set to `true`), _or_ manually running the xcodebuild command
```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e5e9475fdb2af31bac09b20b45b891e4e26696d1 -configuration Debug
```

**Comment by yodaqua** [comment]
Done that and noticed this '
"**The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file.**" in the output.

Is this same issue: https://github.com/appium/appium/issues/7747

Donovans-MBP:~ yodaqua$ clear
Donovans-MBP:~ yodaqua$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
Donovans-MBP:WebDriverAgent yodaqua$ xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e5e9475fdb2af31bac09b20b45b891e4e26696d1 -configuration Debug
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies
Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.2'
Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.2'
Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.2'
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.2'

** TEST BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
2017-02-27 19:20:20.818 xcodebuild[2410:110294]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/9A88EF9F-08E9-4461-87CD-BF6A763A1BFC/Session-WebDriverAgentRunner-2017-02-27_192020-ZZe2N2.log
2017-02-27 19:20:20.819 xcodebuild[2410:110280] [MT] IDETestOperationsObserverDebug: (C114FAEA-249A-4B35-AF39-87F08132784D) Beginning test session WebDriverAgentRunner-C114FAEA-249A-4B35-AF39-87F08132784D at 2017-02-27 19:20:20.817 with Xcode 8C1002 on target <DVTiOSDevice: 0x7ff5adfe1870> {
		deviceSerialNumber:         F73P691LG5N0
		identifier:                 e5e9475fdb2af31bac09b20b45b891e4e26696d1
		deviceClass:                iPhone
		deviceName:                 Kinetic Skunk iPhone 6
		deviceIdentifier:           e5e9475fdb2af31bac09b20b45b891e4e26696d1
		productVersion:             10.2.1
		buildVersion:               14D27
		deviceSoftwareVersion:      10.2.1 (14D27)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        121734008832
		deviceAvailableCapacity:    50710454272
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7ff5addd93a0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.2.1 (14D27))
2017-02-27 19:20:20.835 xcodebuild[2410:110280] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/yodaqua/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7ff5ae43f340 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2017-02-27 19:20:20.835 xcodebuild[2410:110280] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
** TEST EXECUTE FAILED **

**Comment by imurchie** [comment]
That is xcodebuild not being able to sign the WebDriverAgent app. Please see https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by yodaqua** [comment]
Shoo, what a mission. Followed the "Full manual configuration" and added the capabilities: xcodeOrgId" and "xcodeSigningId" and it's working :)

Thanks a million!

**Comment by vikramvi** [comment]
@triager please close per last comment
