### ISSUE TITLE
Unsupported MIME type error

### ISSUE THREAD

**Issue by priyankshah217** [appium/appium#7853]
## The problem

The nature of our application is media app which deals with live content. I was trying to capture screenshot during application run and come across different scenarios which include capturing screenshot during video replay. so while doing this application closed automatically and did not complete further actions.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3/1.6.4-Beta (Java_Client - 5.0.0-BETA2)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OSX El-Capitan
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: Samsung Galaxy J7 Prime (API -23)
* Real device or emulator/simulator: Real Deivce
* Appium CLI or Appium.app|exe: N/A

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/priyankshah217/2dc441d23166d5ac88cb6c29b4d10a72

## Code To Reproduce Issue [ Good To Have ]
```
        File screenshot = driver.getScreenshotAs(OutputType.FILE);  ## Line which causes problem
        screenshot.renameTo(new File(savedFileName + ".jpg"));
```

Please let me know, if any other information required.

**Comment by mykola-mokhnach** [comment]
1. All files produced by _driver.getScreenshotAs_ are always in .png format
2. What if you try to get the screenshot as bytes and then write it into a local file:

```java
....
byte[] screenshot = getDriver().getScreenshotAs(OutputType.BYTES);
Path desiredPicturePath = Paths.get(path.toString(), fileName + ".png");
Files.write(desiredPicturePath, screenshot);
```

**Comment by priyankshah217** [comment]
Issue resolved.

**Comment by grvermeulen** [comment]
Hi, I'm using Version 1.0.2-beta.2 (1.0.2-beta.2) of Appium on Mac Sierra 10.12.3 but every time I try to start a session with an android device (tried multiple devices using Genymotion and different Android and API versions) I'm getting this error: 
[takeScreenshot()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Unsupported MIME type:

with the following log: 
[MJSONWP] Encountered internal error running command: Error: Unsupported MIME type: 
    at Jimp.throwError (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:82:43)
    at Jimp.parseBitmap (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:307:31)
    at /Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:200:29
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

I can see it tries to make a screenshot and place it here: 
/private/var/folders/yx/y8w389_x74l7by5gs4myt47c0000gn/appium11751-3374-1cof226.25raglow29.png for example. But the file 0 bites. 

Who can help me?

**Comment by priyankshah217** [comment]
Can u please try with latest appium version?

**Comment by grvermeulen** [comment]
https://github.com/appium/appium-desktop/releases/tag/v1.0.2-beta.2 is the latest release right? So I'm running on the latest version already. Am I right?

**Comment by jossets** [comment]
I encountered the same problem with appium-desktop this morning.
When the screenshot file is invalid (on my app this an UI component fault) the Jimp library is unable to process the png file and generate an Error.

I patched the file /Application/Appium.app/contents/Resources/app/node_modules/appium/node_modules/jimp/index.js

Now, when function parseBitmap(data, mime, cb), dont know the file format, instead of generating an Error , it returns a green 1080x1920 image.
It's really ugly and need to be improved but it does the job for my device.

Work with appium-desktop v1.0.2-beta..2
line 273
Changes in bold in the case/default: part

// parses a bitmap from the constructor to the JIMP bitmap property
function parseBitmap(data, mime, cb) {
var that = this;
this._originalMime = mime;

switch (mime.toLowerCase()) {
case Jimp.MIME_PNG:
var png = new PNG();
png.parse(data, function(err, data) {
if (err) return throwError.call(that, err, cb);
that.bitmap = {
data: new Buffer(data.data),
width: data.width,
height: data.height
};
return cb.call(that, null, that);
});
break;

case Jimp.MIME_JPEG:
try {
this.bitmap = JPEG.decode(data);
exifRotate(this, data); // EXIF data
return cb.call(this, null, this);
} catch(err) {
return cb.call(this, err, this);
}

case Jimp.MIME_BMP:
this.bitmap = BMP.decode(data);
return cb.call(this, null, this);

default:
**this._originalMime = "Qk06AAAAAAAAADYAAAAoAAAAAQAAAAEAAAABABgAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAEf8F/w==";
var buf = Buffer(this._originalMime, 'base64');
this.bitmap = BMP.decode(buf);
this.resize(1080,1920);
return cb.call(this, null, this);
//return throwError.call(this, "Unsupported MIME type: " + mime, cb);**
}
}

**Comment by mykola-mokhnach** [comment]
@jossets Can you please create a new issue in https://github.com/appium/appium-desktop/issues, since it's definitely desktop app issue and it has nothing to do with Appium server itself?

**Comment by mykola-mokhnach** [comment]
@dpgraham FYI

**Comment by jossets** [comment]
Thanks @mykola-mokhnach ,
created : https://github.com/appium/appium-desktop/issues/213
@grvermeulen can you test the proposed workaround ?

**Comment by grvermeulen** [comment]
Going to test it and get back to you! thnx
