### ISSUE TITLE
Unable to sendkeys to form on real iOS device using XCUITest

### ISSUE THREAD

**Issue by CABellamy** [appium/appium#7868]
## The problem

When sending keys to an input field on real iOS device under the old UIAutomation pathway this would work fine. Text would be entered. The same test fixture using the XCUITest throws the following error:

An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}

If I interact with the device during the test and tap on the input field then the keyboard will appear and the test fixture can send keys to the input. There is either a bug in the way that click events are handled on real device or XCUITest driver is unable to instantiate a keyboard on the device. 

## Environment

* Appium version 1.6.3
* Last Appium version that did not exhibit the issue (if applicable) UIAutomation Instruments driver
* Desktop OS/version used to run Appium: OS X
* Node.js version (unless using Appium.app|exe) : 7.4.0
* Mobile platform/version under test: iOS iPhone6S 9.3.3 
* Real device
* Appium CLI

Logs: [debug] [XCUITest] Log file for xcodebuild test: /
[debug] [WebDriverAgent] Device: Feb 14 14:22:27 iPhone XCTRunner[240] <Warning>: Listening on USB
[debug] [WebDriverAgent] Device: Feb 14 14:22:27 iPhone SpringBoard[58] <Warning>: HW kbd: Failed to set (null) as keyboard focus

debug] [RemoteDebugger] Received result for atom 'click' execution: null
[debug] [MJSONWP] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/cc20529d-de71-4cba-83a1-aa1b51340d8a/element/5001/click 200 514 ms - 76
[HTTP] --> POST /wd/hub/session/cc20529d-de71-4cba-83a1-aa1b51340d8a/element/5001/clear {}
[debug] [MJSONWP] Calling AppiumDriver.clear() with args: ["5001","cc20529d-de71-4cba-83a1-aa1b51340d8a"]

[debug] [XCUITest] Executing command 'keys'
[debug] [JSONWP Proxy] Proxying [POST /keys] to [POST http://localhost:8100/session/0A81BE91-0CCA-490F-8AE9-9A8EFA4C6CDE/keys] with body: {"value":["T","E","S","T","B","0","0","1"]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}","sessionId":"0A81BE91-0CCA-490F-8AE9-9A8EFA4C6CDE","status":13}

**Comment by mykola-mokhnach** [comment]
This is expected, that a string cannot be entered if the keyboard is not visible.

I'd rather check the application code or the automated test on why the keyboard is not invoked before typing anything.

**Comment by CABellamy** [comment]
I am doing a click event but the keyboard is not appearing. I have also tried to invoking it manually by posting to the end point of appium and still nothing.

**Comment by mykola-mokhnach** [comment]
May it be a bug in your app under test?

**Comment by CABellamy** [comment]
I'm using mobilesafari. Also I have recreated the issue outside of my code so I know it's not my test code that is the problem.

**Comment by aaronbriel** [comment]
@CABellamy Did you ever find a resolution to this issue? I'm seeing the same thing with iOS 10 or 10.2. Oddly the issue does NOT occur with iOS 9.3.

**Comment by CABellamy** [comment]
I had the same issue on ios 10. If I drive the device manually by sending click events via XCUITest driver over cURL (the same one that Appium uses) then the click event opens the keyboard correctly and I can sendkeys to it.

**Comment by jlipps** [comment]
@CABellamy why are you executing the `driver.keys` command rather than sending keys to the specific element? Then you shouldn't even need to click. What you're doing now is mixing hybrid commands and native commands (click via JS in the webview, keys via WDA in the native layer), so I'm not surprised something is amiss.

**Comment by EdgarReza** [comment]
if sendkesys is not working for appium 1.6.3 what could be a workaround or other command to send? Please help me.

**Comment by Brian-Watson** [comment]
@EdgarReza sendKeys() is working in Appium 1.6.4.  Are you on iOS or Android?  Is it a native app?  Have you tried sending keys through the Appium-Desktop 1.0.0 Inspector???

**Comment by EdgarReza** [comment]
Hi i am working with IOS is an external application. For this appium 1.6.3 what could be a workaround in order to send values. Thank you very much.

**Comment by Brian-Watson** [comment]
Go here and install the latest desktop and try sending keys from there...

https://github.com/appium/appium-desktop

**Comment by EdgarReza** [comment]
Thank you, how can i upgrade from my appium 1.6.3 to 1.6.4?. What i need to do?. Thank you very much.

**Comment by EdgarReza** [comment]
Hi everyone i could install appium 1.6.4 but the command senkeys continue without working. This is my code:

driver.findElementByName("Número Celular").sendKeys("11111");

It doesnt send the value . 

Cant you help me?

**Comment by imurchie** [comment]
@EdgarReza Can you provide the Appium server logs as a link to a [gist](https://gist.github.com).

**Comment by EdgarReza** [comment]
Hi @imurchie  i register in this https://gist.github.com/EdgarReza/0fa2af20cc891211bc9e6e2a774f56a5

Thank you very much

**Comment by imurchie** [comment]
Can you try setting the `shouldUseSingletonTestManager` desired capability to `false`?

**Comment by EdgarReza** [comment]
Not working, this is my Desired Capabilitties

esiredCapabilities capabilities = new DesiredCapabilities();
	    capabilities.setCapability("appium-version", "1.6");	
	    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
	    capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.0"); 
	    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Seguridad BBVA"); 
	    capabilities.setCapability(MobileCapabilityType.UDID, "ebe52ce850d2854f361988c4311c459997360f65");
	    capabilities.setCapability("shouldUseSingletonTestManager", "false");
		capabilities.setCapability(MobileCapabilityType.APP,"/Users/gustavolopezjimenez/Downloads/Bancomer 10.600.ipa");
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,AutomationName.IOS_XCUI_TEST);

THIS IS THE LOG 

debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["name","Número Celular","782eedd7-1af8-43d1-8c60-787d2b584b3e"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 60000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/430C736A-CF8F-46D1-847A-00877B3A0167/element] with body: {"using":"name","value":"Número Celular"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5","type":"XCUIElementTypeTextField","label":""},"sessionId":"430C736A-CF8F-46D1-847A-00877B3A0167","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5","type":"XCUIElementTypeTextField","label":""}
[HTTP] <-- POST /wd/hub/session/782eedd7-1af8-43d1-8c60-787d2b584b3e/element 200 788 ms - 167 
[HTTP] --> POST /wd/hub/session/782eedd7-1af8-43d1-8c60-787d2b584b3e/element/C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5/value {"id":"C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5","value":["11111"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["11111"],"C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5","782eedd7-1af8-43d1-8c60-787d2b584b3e"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [POST /element/C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5/value] to [POST http://localhost:8100/session/430C736A-CF8F-46D1-847A-00877B3A0167/element/C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5/value] with body: {"value":["1","1","1","1","1"]}
[Xcode] Test Suite 'All tests' started at 2017-04-12 09:51:21.658
[Xcode] Test Suite 'WebDriverAgentRunner.xctest' started at 2017-04-12 09:51:21.659
[Xcode] Test Suite 'UITestingUITests' started at 2017-04-12 09:51:21.660
[Xcode] Test Case '-[UITestingUITests testRunner]' started.
[Xcode]     t =     0.00s     Start Test at 2017-04-12 09:51:21.662
[Xcode]     t =     0.01s     Set Up
[Xcode]     t =     0.57s     Launch com.bancomer.bbva.bancomermovil
[Xcode]     t =     3.55s         Wait for app to idle
[Xcode]     t =     6.91s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     6.92s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     7.11s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     7.11s         Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     7.12s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     7.12s         Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     7.19s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     7.19s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     7.26s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     7.26s         Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     7.26s     Set device orientation to Portrait
[Xcode]     t =     7.64s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     7.64s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     7.94s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     7.94s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.02s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     8.02s         Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.02s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     8.02s         Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.03s     Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.03s     Find: Descendants matching type Any
[Xcode]     t =     8.03s     Find: Elements matching predicate '"Número Celular" IN identifiers'
[Xcode]     t =     8.03s     Find: Element at index 0
[Xcode]     t =     8.04s     Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.04s     Find: Descendants matching type Alert
[Xcode]     t =     8.04s     Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.04s     Find: Descendants matching type Sheet
[Xcode]     t =     8.05s     Find the Application "com.apple.springboard" 0x1742c0c40
[Xcode]     t =     8.05s         Snapshot accessibility hierarchy for com.apple.springboard
[Xcode]     t =     8.19s     Use cached accessibility hierarchy for com.apple.springboard
[Xcode]     t =     8.19s     Find: Descendants matching type Alert
[Xcode]     t =     8.20s     Use cached accessibility hierarchy for com.apple.springboard
[Xcode]     t =     8.20s     Find: Descendants matching type Sheet
[Xcode]     t =     8.20s     Find the "Número Celular" Any
[Xcode]     t =     8.20s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.27s         Find: Descendants matching type Any
[Xcode]     t =     8.27s         Find: Elements matching predicate '"Número Celular" IN identifiers'
[Xcode]     t =     8.27s         Find: Element at index 0
[Xcode]     t =     8.34s     Find the TextField
[Xcode]     t =     8.34s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.40s         Find: Descendants matching type Any
[Xcode]     t =     8.40s         Find: Elements matching predicate '"Número Celular" IN identifiers'
[Xcode]     t =     8.41s         Find: Element at index 0
[Xcode]     t =     8.41s     Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.41s     Find: Descendants matching type Alert
[Xcode]     t =     8.41s     Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.41s     Find: Descendants matching type Sheet
[Xcode]     t =     8.42s     Find the Application "com.apple.springboard" 0x1742c0c40
[Xcode]     t =     8.43s         Snapshot accessibility hierarchy for com.apple.springboard
[Xcode]     t =     8.54s     Use cached accessibility hierarchy for com.apple.springboard
[Xcode]     t =     8.54s     Find: Descendants matching type Alert
[Xcode]     t =     8.54s     Use cached accessibility hierarchy for com.apple.springboard
[Xcode]     t =     8.55s     Find: Descendants matching type Sheet
[Xcode]     t =     8.65s     Find the TextField
[Xcode]     t =     8.65s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.72s         Find: Descendants matching type Any
[Xcode]     t =     8.72s         Find: Elements matching predicate '"Número Celular" IN identifiers'
[Xcode]     t =     8.72s         Find: Element at index 0
[Xcode]     t =     8.83s     Find the TextField
[Xcode]     t =     8.83s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     8.92s         Find: Descendants matching type Any
[Xcode]     t =     8.92s         Find: Elements matching predicate '"Número Celular" IN identifiers'
[Xcode]     t =     8.92s         Find: Element at index 0
[Xcode]     t =     8.92s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     8.92s         Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     9.11s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     9.11s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     9.51s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     9.51s         Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     9.51s     Find the Application "com.bancomer.bbva.bancomermovil" 0x1700de920
[Xcode]     t =     9.51s         Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     9.51s     Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     9.52s     Find: Descendants matching type Any
[Xcode]     t =     9.52s     Find: Elements matching predicate '"Número Celular" IN identifiers'
[Xcode]     t =     9.52s     Find: Element at index 0
[Xcode]     t =     9.52s     Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     9.52s     Find: Descendants matching type Alert
[Xcode]     t =     9.52s     Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     9.53s     Find: Descendants matching type Sheet
[Xcode]     t =     9.53s     Find the Application "com.apple.springboard" 0x1742c0c40
[Xcode]     t =     9.53s         Snapshot accessibility hierarchy for com.apple.springboard
[Xcode]     t =     9.63s     Use cached accessibility hierarchy for com.apple.springboard
[Xcode]     t =     9.63s     Find: Descendants matching type Alert
[Xcode]     t =     9.63s     Use cached accessibility hierarchy for com.apple.springboard
[Xcode]     t =     9.64s     Find: Descendants matching type Sheet
[Xcode]     t =     9.64s     Find the "Número Celular" Any
[Xcode]     t =     9.64s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =     9.80s         Find: Descendants matching type Any
[Xcode]     t =     9.81s         Find: Elements matching predicate '"Número Celular" IN identifiers'
[Xcode]     t =     9.81s         Find: Element at index 0
[Xcode]     t =     9.92s     Find the TextField
[Xcode]     t =     9.92s         Snapshot accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =    10.17s         Find: Descendants matching type Any
[Xcode]     t =    10.17s         Find: Elements matching predicate '"Número Celular" IN identifiers'
[Xcode]     t =    10.17s         Find: Element at index 0
[Xcode]     t =    10.18s     Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =    10.18s     Find: Descendants matching type Alert
[Xcode]     t =    10.18s     Use cached accessibility hierarchy for com.bancomer.bbva.bancomermovil
[Xcode]     t =    10.18s     Find: Descendants matching type Sheet
[Xcode]     t =    10.19s     Find the Applicat
[debug] [JSONWP Proxy] Got response with status 200: {"value":"-[XCTestDriver managerProxy]: unrecognized selector sent to instance 0x174247ef0\n\n(\n\t0   CoreFoundation                      0x00000001816751d0 <redacted> + 148\n\t1   libobjc.A.dylib                     0x00000001800ac55c objc_exception_throw + 56\n\t2   CoreFoundation                      0x000000018167c268 <redacted> + 0\n\t3   CoreFoundation                      0x0000000181679270 <redacted> + 916\n\t4   CoreFoundation                      0x000000018157280c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x0000000101a0fed4 __29+[FBKeyboard typeText:error:]_block_invoke + 136\n\t6   WebDriverAgentLib                   0x0000000101a14854 +[FBRunLoopSpinner spinUntilCompletion:] + 172\n\t7   WebDriverAgentLib                   0x0000000101a0fcbc +[FBKeyboard typeText:error:] + 372\n\t8   WebDriverAgentLib                   0x0000000101a1e284 -[XCUIElement(FBTyping) fb_typeText:error:] + 168\n\t9   WebDriverAgentLib                   0x0000000101a294c0 +[FBElementComman...
[debug] [JSONWP Proxy] Proxying [GET /element/C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5/attribute/type] to [GET http://localhost:8100/session/430C736A-CF8F-46D1-847A-00877B3A0167/element/C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5/attribute/type] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeTextField\",\n  \"sessionId\" : \"430C736A-CF8F-46D1-847A-00877B3A0167\",\n  \"status\" : 0\n}"
[XCUITest] Cannot type in the text field because of UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCTestDriver managerProxy]: unrecognized selector sent to instance 0x174247ef0

(
	0   CoreFoundation                      0x00000001816751d0 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001800ac55c objc_exception_throw + 56
	2   CoreFoundation                      0x000000018167c268 <redacted> + 0
	3   CoreFoundation                      0x0000000181679270 <redacted> + 916
	4   CoreFoundation                      0x000000018157280c _CF_forwarding_prep_0 + 92
	5   WebDriverAgentLib                   0x0000000101a0fed4 __29+[FBKeyboard typeText:error:]_block_invoke + 136
	6   WebDriverAgentLib                   0x0000000101a14854 +[FBRunLoopSpinner spinUntilCompletion:] + 172
	7   WebDriverAgentLib                   0x0000000101a0fcbc +[FBKeyboard typeText:error:] + 372
	8   WebDriverAgentLib                   0x0000000101a1e284 -[XCUIElement(FBTyping) fb_typeText:error:] + 168
	9   WebDriverAgentLib                   0x0000000101a294c0 +[FBElementCommands handleSetValue:] + 860
	10  WebDriverAgentLib                   0x0000000101a13848 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208
	11  WebDriverAgentLib                   0x0000000101a0b328 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496
	12  RoutingHTTPServer                   0x0000000101aa63cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
	13  RoutingHTTPServer                   0x0000000101aa6b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
	14  libdispatch.dylib                   0x00000001804fe1bc <redacted> + 16
	15  libdispatch.dylib                   0x000000018050f084 <redacted> + 320
	16  libdispatch.dylib                   0x00000001804fe1bc <redacted> + 16
	17  libdispatch.dylib                   0x0000000180502d68 _dispatch_main_queue_callback_4CF + 1000
	18  CoreFoundation                      0x0000000181622810 <redacted> + 12
	19  CoreFoundation                      0x00000001816203fc <redacted> + 1660
	20  CoreFoundation                      0x000000018154e2b8 CFRunLoopRunSpecific + 444
	21  Foundation                          0x000000018208b26c <redacted> + 304
	22  Foundation                          0x00000001820dfaa0 <redacted> + 88
	23  WebDriverAgentLib                   0x0000000101a0a378 -[FBWebServer startServing] + 320
	24  WebDriverAgentRunner                0x00000001007b3ed0 -[UITestingUITests testRunner] + 120
	25  CoreFoundation                      0x000000018167b150 <redacted> + 144
	26  CoreFoundation                      0x000000018156deac <redacted> + 284
	27  XCTest                              0x00000001001eca30 __24-[XCTestCase invokeTest]_block_invoke.237 + 48
	28  XCTest                              0x00000001001ec67c __24-[XCTestCase invokeTest]_block_invoke_2 + 564
	29  XCTest                              0x0000000100227dac -[XCTestContext performInScope:] + 208
	30  XCTest                              0x00000001001ec430 -[XCTestCase invokeTest] + 268
	31  XCTest                              0x00000001001ecd80 -[XCTestCase performTest:] + 536
	32  XCTest                              0x00000001001e9f44 __27-[XCTestSuite performTest:]_block_invoke + 240
	33  XCTest                              0x00000001001e9b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	34  XCTest                              0x00000001001e9d54 -[XCTestSuite performTest:] + 200
	35  XCTest                              0x00000001001e9f44 __27-[XCTestSuite performTest:]_block_invoke + 240
	36  XCTest                              0x00000001001e9b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	37  XCTest                              0x00000001001e9d54 -[XCTestSuite performTest:] + 200
	38  XCTest                              0x00000001001e9f44 __27-[XCTestSuite performTest:]_block_invoke + 240
	39  XCTest                              0x00000001001e9b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	40  XCTest                              0x00000001001e9d54 -[XCTestSuite performTest:] + 200
	41  XCTest                              0x0000000100235a14 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 44
	42  XCTest                              0x00000001001f88dc -[XCTestObservationCenter _observeTestExecutionForBlock:] + 520
	43  XCTest                              0x0000000100235894 -[XCTTestRunSession runTestsAndReturnError:] + 292
	44  XCTest                              0x00000001001d4f70 -[XCTestDriver runTestsAndReturnError:] + 252
	45  XCTest                              0x000000010022b6f8 _XCTestMain + 548
	46  CoreFoundation                      0x0000000181622a44 <redacted> + 20
	47  CoreFoundation                      0x0000000181622240 <redacted> + 288
	48  CoreFoundation                      0x0000000181620094 <redacted> + 788
	49  CoreFoundation                      0x000000018154e2b8 CFRunLoopRunSpecific + 444
	50  GraphicsServices                    0x0000000183002198 GSEventRunModal + 180
	51  UIKit                               0x00000001875957fc <redacted> + 684
	52  UIKit                               0x0000000187590534 UIApplicationMain + 208
	53  XCTRunner                           0x00000001000a0474 XCTRunner + 33908
	54  libdyld.dylib                       0x00000001805315b8 <redacted> + 4
).
Trying to apply a workaround...
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/430C736A-CF8F-46D1-847A-00877B3A0167/element] with body: {"using":"class name","value":"XCUIElementTypeKeyboard"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"C56CBC5C-7F6F-4281-9417-235DBF4CBB89","type":"XCUIElementTypeKeyboard","label":null},"sessionId":"430C736A-CF8F-46D1-847A-00877B3A0167","status":0}
[debug] [XCUITest] Keyboard found. Continuing with text input.
[debug] [BaseDriver] Set implicit wait to 60000ms
[debug] [JSONWP Proxy] Proxying [POST /element/C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5/value] to [POST http://localhost:8100/session/430C736A-CF8F-46D1-847A-00877B3A0167/element/C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5/value] with body: {"value":["1","1","1","1","1"]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"-[XCTestDriver managerProxy]: unrecognized selector sent to instance 0x174247ef0\n\n(\n\t0   CoreFoundation                      0x00000001816751d0 <redacted> + 148\n\t1   libobjc.A.dylib                     0x00000001800ac55c objc_exception_throw + 56\n\t2   CoreFoundation                      0x000000018167c268 <redacted> + 0\n\t3   CoreFoundation                      0x0000000181679270 <redacted> + 916\n\t4   CoreFoundation                      0x000000018157280c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x0000000101a0fed4 __29+[FBKeyboard typeText:error:]_block_invoke + 136\n\t6   WebDriverAgentLib                   0x0000000101a14854 +[FBRunLoopSpinner spinUntilCompletion:] + 172\n\t7   WebDriverAgentLib                   0x0000000101a0fcbc +[FBKeyboard typeText:error:] + 372\n\t8   WebDriverAgentLib                   0x0000000101a1e284 -[XCUIElement(FBTyping) fb_typeText:error:] + 168\n\t9   WebDriverAgentLib                   0x0000000101a294c0 +[FBElementComman...
[HTTP] <-- POST /wd/hub/session/782eedd7-1af8-43d1-8c60-787d2b584b3e/element/C5F0A71B-E32E-4B83-A0FF-1EF94603EDD5/value 500 4124 ms - 5636 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted

**Comment by EdgarReza** [comment]
The server send a message that the operation is not permitted. @imurchie thank you very  much

**Comment by mathias21** [comment]
Hi @CABellamy 

We had a problem with Xcode 8.3 with edittexts not being able to write. Moving to Xcode 8.2.1 solved it. I think Xcode 8.3 is changing a bit how views are reflected in Appium or how id's are set. Try to downgrade to Xcode 8.2.1 if you are in the latest version.

**Comment by MukulHK** [comment]
Use sendKeyStrategy = oneByOne capability. It will resolve the issue
