### ISSUE TITLE
Appium start and element related operations are slow.

### ISSUE THREAD

**Issue by DSJsoul** [appium/appium#7932]
## The problem

1. Appium starts slow when it shows that it is trying to recreate WDA session.
2. Element related operations are a bit slow such as find, tap, click. And they all  take about 2 seconds.

## Environment

os: mac OS 10.12
appium : 1.6.4-beta
iOS : 10.0
node: v6.9.1
mobile platform: iOS(real device)
client: python client

## Details
Problem1:
When start a test case, it always shows the following information and charges a lot time to launch app. Is there any way to improve it?
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Failed to create WDA session. Retrying...

Problem2:
python code:
print(datetime.datetime.now())
element=wd.find_element_by_xpath("//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTabBar[1]/XCUIElementTypeButton[2]")
print(datetime.datetime.now())
element.click()
print(datetime.datetime.now())
time.sleep(5)
    print(datetime.datetime.now())
print("search element")
    element2=wd.find_element_by_name("首页")
    print(datetime.datetime.now())
 element.click()
    print(datetime.datetime.now())
    wd.tap([(130,600)])
    print("coordinate tap")
    print(datetime.datetime.now())

the output:
2017-02-25 20:51:25.520854
2017-02-25 20:51:27.070733
2017-02-25 20:51:28.976249
search element
2017-02-25 20:51:33.976766
2017-02-25 20:51:34.965622
2017-02-25 20:51:37.323825
coordinate tap
2017-02-25 20:51:43.824901

As can be seen from the above, finding element needs at least 1 second, the click action takes 2 seconds or more.When I use "action = TouchAction(driver)  action.tap(element).perform()", the result is almost the same. It makes me very tangled. 

Thank you very much for reading!! 😊

**Comment by mykola-mokhnach** [comment]
Sometimes session creation fails because of some Apple issues, which we cannot workaround. That is why we retry it several times. You may try to play with driver capabilities like:
usePrebuiltWDA, useNewWDA, wdaLaunchTimeout, wdaConnectionTimeout, wdaStartupRetries, wdaStartupRetryInterval

to make it faster. Or you could create your own PR to xcuitest driver component or WDA itself if you know better/faster way to initialise it.

Regarding performance:
You could try to implement your automated test using pure XCTest framework and measure these durations there. I expect your results will be quite close to what you get with Appium.
What I want to say is that main delay is made by XCTest framework itself and there is little we can do to make it faster "from the outside".

**Comment by vikramvi** [comment]
@triager please close per above comment

**Comment by vikramvi** [comment]
For benefit of others who may land on this page https://www.npmjs.com/package/appium-xcuitest-driver - check "Desired Capabilities" table
