### ISSUE TITLE
Unable to launch on Real device - Error: Unknown device or simulator UDID: '!@#$%^'

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium#7965]
Hello,

I recently downloaded the Appium desktop version and trying to launch my app in iOS 10.2.1 (real device) but I am getting an error. My desired capabilities is as below

{
"automationName": "XCUITest",
"deviceName": "iPad",
"platformName": "iOS",
"app": "/xxxxxx.ipa",
"platformVersion": "10.2.1",
"udid": "XXXXXXXXX",
"xcodeOrgId": "XXXXXXX",
"xcodeSigningId": "iPhone Developer"
}

FYI - I have installed the latest ideviceinstaller and libimobiledevice. And running the "idevice_id -l" command in the terminal displays a list of connected devices

The appium log is attached
[gistfile1.txt](https://github.com/appium/appium/files/813391/gistfile1.txt)

**Comment by imurchie** [comment]
Are you running Appium through another process? Perhaps where the PATH is not set?

**Comment by wenshi11019** [comment]
@imurchie When I use Eclipse to run Appium, I have the same question. It doesn't happen before. But run in IDEA, it's successed.

**Comment by imurchie** [comment]
Then it seems like the environment is not set up right in Eclipse. I don't know how to configure that, but it must be possible.

**Comment by wenshi11019** [comment]
But I use the same environment in eclipse, it can success when i use xcuitest driver version 2.5.3

**Comment by wenshi11019** [comment]
But failed in 2.12.0

**Comment by MaciejCiach** [comment]
I have the same error 

   [XCUITest] XCUITestDriver version: 2.9.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: version.
[BaseDriver] Session created with session id: 3dd466bc-51ed-4581-b73f-4a614cb00299
[XCUITest] Xcode version set to '8.2.1'
[XCUITest] iOS SDK Version set to '10.2'
[XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'
[XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: 
my UDID here

It's weird because I have idevice_id installed

**Comment by imurchie** [comment]
There was a problem with the first version of the appium-desktop that did not replicate the command line environment into the app. So things on the PATH were not findable. There has been a fix for this.

**Comment by wenshi11019** [comment]
@imurchie I have the same error from MaciejCiach

**Comment by poorvikamahesh** [comment]
@imurchie, the app path is correct, so is the UDID, version, etc
Currently I switched to Appium GUI 1.5.2 and using external Appium Package 1.6.4Beta. This works fine

But due to a known bug, the server shuts down every 60 secs (new command timeout is not taken from the settings but is 60s by default) which is really irritating.

**Comment by imurchie** [comment]
The fix was published last night. You will need to upgrade `appium-desktop` to get it. Sorry for the inconvenience.

**Comment by poorvikamahesh** [comment]
@imurchie Thanks.
I upgraded to Beta.2. Its working now.
👍
