### ISSUE TITLE
Unable to launch WebDriver agent : [MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: EROFS: read-only file system, mkdir '/private/var/folders/vf/8l3g6qvs3d3cw87x53y_w10h0000gn/T/AppTranslocation/38D52102-AFB7-4037-ADE9-F546BD636993/d/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources'

### ISSUE THREAD

**Issue by sachinistkiran** [appium/appium#8033]
[appium logs.txt](https://github.com/appium/appium/files/840828/appium.logs.txt)

Xcode :8.2
Appium : 1.6.4 beta

1.Capabilities : 
caps.setCapability("platformName", "iOS");
		caps.setCapability("platformVersion", "10.2");
		//caps.setCapability("appActivity", "Splash_Screen");
		//caps.setCapability("automationName", "XCUITest");
		caps.setCapability("udid",
				"654D7BC2-422A-4856-9384-0B558B3A9ABB");
		caps.setCapability("deviceName", "iPhone 6s Plus");
		caps.setCapability("useNewWDA", "false");
		caps.setCapability("bundleId", “com.testing.test");
		caps.setCapability("app", "/Users/kiran/Desktop/test.app");
		driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), caps);
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

2.Carthage Installed.
@imurchie

**Comment by mykola-mokhnach** [comment]
The owner of appium daemon process does not have write permissions to the folder mentioned above. You need to either change permissions to that folder or execute appium daemon from a different folder.

**Comment by sachinistkiran** [comment]
Thanks @mykola-mokhnach  
Its working!!!

**Comment by GURVARINDER** [comment]
Just started setting up appium desktop and i am having a similar issue, i am not sure how to give the write permissions to the owner of appium daemon. Please help
`[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] *** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
[XCUITest] *** Skipped installing RoutingHTTPServer.framework binary due to the error:
[XCUITest] 	"Failed to write to /private/var/folders/vj/dv5p0my11t51t02d9bkpf4rw0000gn/T/AppTranslocation/DB896B94-E82E-43D3-84B4-D6866A5198BC/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “iOS” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/vj/dv5p0my11t51t02d9bkpf4rw0000gn/T/AppTranslocation/DB896B94-E82E-43D3-84B4-D6866A5198BC/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7f9bc8f86c50 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}}"
[XCUITest] *** Checking out RoutingHTTPServer at "v1.0.1"
[XCUITest] Failed to check out repository into /private/var/folders/vj/dv5p0my11t51t02d9bkpf4rw0000gn/T/AppTranslocation/DB896B94-E82E-43D3-84B4-D6866A5198BC/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=642 "You can’t save the file “RoutingHTTPServer” because the volume is read only." UserInfo={NSFilePath=/private/var/folders/vj/dv5p0my11t51t02d9bkpf4rw0000gn/T/AppTranslocation/DB896B94-E82E-43D3-84B4-D6866A5198BC/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer, NSUnderlyingError=0x7f9bc8f8fb70 {Error Domain=NSPOSIXErrorDomain Code=30 "Read-only file system"}})`

**Comment by GURVARINDER** [comment]
Following are the desired capabilities set:
{"desiredCapabilities":{"app":"/Users/SINGH/Desktop/MintChip.app","deviceName":"iPhone Simulator","noReset":true,"platformName":"iOS","platformVersion":"10.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}

**Comment by sachinistkiran** [comment]
The owner of appium daemon process does not have write permissions to the folder mentioned above. You need to either change permissions to that folder or execute appium daemon from a different folder.

**Comment by GURVARINDER** [comment]
@sachinistkiran i tried `chown -R `whoami` /private/var/folders/vj/dv5p0my11t51t02d9bkpf4rw0000gn/T/AppTranslocation/DB896B94-E82E-43D3-84B4-D6866A5198BC/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent`
but still got the same error, do i need to do something else?

**Comment by sachinistkiran** [comment]
@GURVARINDER  does /private/var/folders/vj/dv5p0my11t51t02d9bkpf4rw0000gn/T/AppTranslocation/DB896B94-E82E-43D3-84B4-D6866A5198BC/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/ 
folder has write permission.

**Comment by treetopdevs** [comment]
I encountered this precise error, and solved it by moving the Appium.app file to the Applications folder.

**Comment by AutomationProjects** [comment]
@treetopdevs WAOW YOUR A LEGEND THANKS ALOT.

**Comment by sarozNep** [comment]
@mykola-mokhnach  i am having this issue and i dont know how to execute appium daemon from a different folder

**Comment by DylanLacey** [comment]
@treetopdevs I think you've probably clocked why so many are having this issue!

**Comment by ameyparab85** [comment]
Just move Appium.app. Its a permissions issue

**Comment by imurchie** [comment]
https://github.com/appium/appium-desktop#download-appium-desktop

**Comment by acahet** [comment]
@treetopdevs, dude.. thank you!!! you're a legendx2

**Comment by majdukovic** [comment]
@treetopdevs awesome dude, thank you! :D

**Comment by vchhedaisi** [comment]
My Appium.app is already under /Applications, but still getting the above issue. Please help?

**Comment by imurchie** [comment]
@vchhedaisi Can you provide the Appium server logs, as a link to a [gist](https://gist.github.com), so we can help?

**Comment by vchhedaisi** [comment]
Got it to work. Thanks for your reply.

Vaishnavi Desai
Manager in Software Test | Intuitive Surgical, Inc. | 1020 Kifer Road, Sunnyvale, CA 94086 |
vaishnavi.desai@intusurg.com<mailto:vaishnavi.desai@intusurg.com> | www.davincisurgery.com<http://www.davincisurgery.com/> | www.davincisurgerycommunity.com<http://www.davincisurgerycommunity.com/> | www.intuitivesurgical.com<http://www.intuitivesurgical.com/>

**Comment by arpitkup** [comment]
Hello, I upgraded to latest appium v1.13.0. But after upgrading, I am getting below error. 
Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1

Tried to run it against appium client as well but getting the same error. I already tried to uninstall and reinstall carthage but it did not help. Any help on this would be greatly appreciated. 
Logs:

rmap3000:WebDriverAgent arpit$ appium
[Appium] Welcome to Appium v1.13.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"platformName":"iOS","platformVersion":"12.0","deviceName":"iPhone X","automationName":"XCUITest","waitForQuiescence":false,"useNewWDA":true,"app":"/Users/arpit/Downloads/QUAL TABtouch.app"},"capabilities":{"firstMatch":[{"platformName":"iOS"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"12.0","deviceName":"iPhone X","automationName":"XCUITest","waitForQuiescence":false,"useNewWDA":true,"app":"/Users/arpit/Downloads/QUAL TABtouch.app"},null,{"firstMatch":[{"platformName":"iOS"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1557814827720 (14:20:27 GMT+0800 (Australian Western Standard Time))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The capabilities ["platformVersion","deviceName","automationName","waitForQuiescence","useNewWDA","app"] are not standard capabilities and should have an extension prefix
[Appium] Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[Appium] Capabilities:
[Appium]   platformVersion: 12.0
[Appium]   deviceName: iPhone X
[Appium]   automationName: XCUITest
[Appium]   waitForQuiescence: false
[Appium]   useNewWDA: true
[Appium]   app: /Users/arpit/Downloads/QUAL TABtouch.app
[Appium]   platformName: iOS
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"appium:pla... and MJSONWP desired capabilities {"platformName":"iOS","plat... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"appium:pla...
[BaseDriver] Session created with session id: 872b7a8e-5c71-4357-b97b-7b765c2ff412
[debug] [XCUITest] Current user: 'arpit'
[iOSSim] Constructing iOS simulator for Xcode version 10.0 with udid '289F35D8-E639-4BFB-A701-B488E08EEAEB'
[XCUITest] Determining device to run tests on: udid: '289F35D8-E639-4BFB-A701-B488E08EEAEB', real device: false
[XCUITest] iOS SDK Version set to '12.0'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1557814848585 (14:20:48 GMT+0800 (Australian Western Standard Time))
[BaseDriver] Using local app '/Users/arpit/Downloads/QUAL TABtouch.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1557814848617 (14:20:48 GMT+0800 (Australian Western Standard Time))
[debug] [XCUITest] Checking whether app '/Users/arpit/Downloads/QUAL TABtouch.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/Users/arpit/Downloads/QUAL TABtouch.app': 'rwwa.com.au.TABtouch.QUAL'
[debug] [BaseDriver] Event 'resetStarted' logged at 1557814848655 (14:20:48 GMT+0800 (Australian Western Standard Time))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1557814849702 (14:20:49 GMT+0800 (Australian Western Standard Time))
[debug] [XCUITest] Starting log capture for iOS Simulator with udid '289F35D8-E639-4BFB-A701-B488E08EEAEB', using 'xcrun simctl spawn 289F35D8-E639-4BFB-A701-B488E08EEAEB log stream --style compact'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1557814851482 (14:20:51 GMT+0800 (Australian Western Standard Time))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSSim] Setting preferences of 289F35D8-E639-4BFB-A701-B488E08EEAEB Simulator to {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Updated 289F35D8-E639-4BFB-A701-B488E08EEAEB Simulator preferences at '/Users/arpit/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"289F35D8-E639-4BFB-A701-B488E08EEAEB":{"ConnectHardwareKeyboard":false}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Got Simulator UI client PID: 596
[iOSSim] Both Simulator with UDID 289F35D8-E639-4BFB-A701-B488E08EEAEB and the UI client are currently running
[debug] [BaseDriver] Event 'simStarted' logged at 1557814852427 (14:20:52 GMT+0800 (Australian Western Standard Time))
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneSimulator"]
[debug] [XCUITest] Cleaning installd cache to save the disk space
[debug] [XCUITest] Installing '/Users/arpit/Downloads/QUAL TABtouch.app' on Simulator with UUID '289F35D8-E639-4BFB-A701-B488E08EEAEB'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1557814867784 (14:21:07 GMT+0800 (Australian Western Standard Time))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [XCUITest] Capability 'useNewWDA' set to true, so uninstalling WDA before proceeding
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaUninstalled' logged at 1557814875214 (14:21:15 GMT+0800 (Australian Western Standard Time))
[debug] [XCUITest] Trying to start WebDriverAgent 2 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1557814875216 (14:21:15 GMT+0800 (Australian Western Standard Time))
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] Usage: simctl list [-j | --json] [devices|devicetypes|runtimes|pairs]
[XCUITest] Traceback (most recent call last):
[XCUITest]   File "<string>", line 1, in <module>
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
[XCUITest]     **kw)
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
[XCUITest]     return _default_decoder.decode(s)
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
[XCUITest]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
[XCUITest]     raise ValueError("No JSON object could be decoded")
[XCUITest] ValueError: No JSON object could be decoded
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] Usage: simctl list [-j | --json] [devices|devicetypes|runtimes|pairs]
[XCUITest] Traceback (most recent call last):
[XCUITest]   File "<string>", line 1, in <module>
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
[XCUITest]     **kw)
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
[XCUITest]     return _default_decoder.decode(s)
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
[XCUITest]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
[XCUITest]     raise ValueError("No JSON object could be decoded")
[XCUITest] ValueError: No JSON object could be decoded
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1557814884291 (14:21:24 GMT+0800 (Australian Western Standard Time))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1557814896136 (14:21:36 GMT+0800 (Australian Western Standard Time))
[XCUITest] Retrying WDA startup (2 of 2)
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] Usage: simctl list [-j | --json] [devices|devicetypes|runtimes|pairs]
[XCUITest] Traceback (most recent call last):
[XCUITest]   File "<string>", line 1, in <module>
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
[XCUITest]     **kw)
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
[XCUITest]     return _default_decoder.decode(s)
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
[XCUITest]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
[XCUITest]     raise ValueError("No JSON object could be decoded")
[XCUITest] ValueError: No JSON object could be decoded
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Fetching dependencies
[XCUITest] Usage: simctl list [-j | --json] [devices|devicetypes|runtimes|pairs]
[XCUITest] Traceback (most recent call last):
[XCUITest]   File "<string>", line 1, in <module>
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
[XCUITest]     **kw)
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
[XCUITest]     return _default_decoder.decode(s)
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
[XCUITest]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[XCUITest]   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
[XCUITest]     raise ValueError("No JSON object could be decoded")
[XCUITest] ValueError: No JSON object could be decoded
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1557814900261 (14:21:40 GMT+0800 (Australian Western Standard Time))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[XCUITest]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:501:15)
[debug] [XCUITest] Parsed BUILD_DIR configuration value: '/Users/arpit/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products'
[debug] [XCUITest] Got derived data root: '/Users/arpit/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1557814919337 (14:21:59 GMT+0800 (Australian Western Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[debug] [W3C]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:501:15)
[HTTP] <-- POST /wd/hub/session 500 91767 ms - 727
[HTTP]
