### ISSUE TITLE
appium 1.6.4 beta use name strategy which element's label attribute is null, return label: null

### ISSUE THREAD

**Issue by songzcn** [appium/appium#8088]
## The problem

Hi Appium Team,
 i have trouble when i use name locator strategy to locate element which label attribute is null, appium log return label:null.
If  i use name locator strategy to locate element which label attribute isn't null , appium will locate element with label.
As i know after appium 1.5, long-deprecated name locator strategy is removed. I'm confused why i can use name locator strategy in appium 1.6.4 beta.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 beta
* Desktop OS/version used to run Appium: OSX 10.12
* Node.js version (unless using Appium.app|exe):  7.0.0
* Mobile platform/version under test: ios 10.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium Desktop 1.0.0 beta 4

## Link to Appium logs

https://gist.github.com/songzcn/8cc40324de6b867b5da38be2c447e14c

**Comment by mykola-mokhnach** [comment]
This happens because WebDriverAgent, which we use on the lower level, still supports the **name** strategy. It simply maps it to the same call, as for **id**. Although, I'd advice to always use **MobileBy.AccessibilityId** rather than **By.name**, especially if your locators tend to be used by multiple platforms and you want them to be supported in the future Appium versions.

**Comment by songzcn** [comment]
@mykola-mokhnach thanks! I will use accessibility-id instead of name.
