### ISSUE TITLE
Test Appium on iOS 10.3

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#8105]
iOS 10.3 was released. Need to test `appium-xcuitest-driver` with the latest Xcode.

**Comment by vsadineni1** [comment]
@dpgraham @jlipps 
What is the appium version required for Testing Hybrid applications on iOS10.3?
We have an app that is accessed through:
a. iOS Safari browser on iPhone\iPad
b. Hybrid App.
What is the appium version required for iOs10.3?
For iOS 10.0 we are using appium 1.6.3.

**Comment by dpgraham** [comment]
I think Appium 1.6.3 should work but I recommend upgrade to 1.6.4-beta

**Comment by jlipps** [comment]
@vsadineni1 we're running a full suite of tests on 10.3 and will update this issue with findings

**Comment by dpgraham** [comment]
I just ran all of the e2e tests and they passed on 10.3 without any issues.

We should be good to use iOS 10.3 with Appium 1.6.4-beta

**Comment by Krunaltthakkar13** [comment]
Hi geeks
after updating xcode 8.3 facing this issue 

The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1

anyone knows let me know

**Comment by dpgraham** [comment]
Can you show me the Appium logs?

**Comment by Krunaltthakkar13** [comment]
@dpgraham appium logs

Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/user/Documents/Demoappium 2017-04-04 17-18-20/Demoappium.ipa'
[Appium]   Device ID: '07FA88C8-AE77-4C8C-832C-302A47E13BB3'
[Appium]   newCommandTimeout: 200
[Appium]   platformVersion: '10.3'
[Appium]   appiumVersion: '1.6.3'
[Appium]   BundlieId: 'isteer.Demoappium'
[Appium]   deviceOrientation: 'portrait'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 5s'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: Device ID, appiumVersion, BundlieId, deviceOrientation.
[BaseDriver] Session created with session id: 8b21f9af-e34d-493a-a35e-f8da9bd2f351
[debug] [XCUITest] Xcode version set to '8.3'
[debug] [XCUITest] iOS SDK Version set to '10.3'
[iOSSim] Constructing iOS simulator for Xcode version 8.3 with udid 'A16D8F9D-B113-4821-8D44-9C39EF1EC106'
[XCUITest] Determining device to run tests on: udid: 'A16D8F9D-B113-4821-8D44-9C39EF1EC106', real device: false
[BaseDriver] Using local app '/Users/user/Documents/Demoappium 2017-04-04 17-18-20/Demoappium.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/sm/sbx_yj156bz8vpkk2qmlyprr0000gn/T/201735-2625-1akbv0k.0uvnjc3di/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/sm/sbx_yj156bz8vpkk2qmlyprr0000gn/T/201735-2625-1akbv0k.0uvnjc3di/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/sm/sbx_yj156bz8vpkk2qmlyprr0000gn/T/201735-2625-1akbv0k.0uvnjc3di/Payload/Demoappium.app'
[debug] [XCUITest] Checking whether app '/var/folders/sm/sbx_yj156bz8vpkk2qmlyprr0000gn/T/201735-2625-1akbv0k.0uvnjc3di/Payload/Demoappium.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/var/folders/sm/sbx_yj156bz8vpkk2qmlyprr0000gn/T/201735-2625-1akbv0k.0uvnjc3di/Payload/Demoappium.app': 'isteer.Demoappium'
[debug] [iOSLog] Starting iOS 10.3 simulator log capture
[debug] [iOSLog] System log path: /Users/user/Library/Logs/CoreSimulator/A16D8F9D-B113-4821-8D44-9C39EF1EC106/system.log
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid 'A16D8F9D-B113-4821-8D44-9C39EF1EC106' already booted
[debug] [XCUITest] Installing app '/var/folders/sm/sbx_yj156bz8vpkk2qmlyprr0000gn/T/201735-2625-1akbv0k.0uvnjc3di/Payload/Demoappium.app' on device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=A16D8F9D-B113-4821-8D44-9C39EF1EC106 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/86626A95-D32F-45AD-AB24-67CA57627471/Session-WebDriverAgentRunner-2017-04-05_114927-zmvDVX.log
[debug] [WebDriverAgent] Sim: Apr  5 11:49:27 iSteermac CoreSimulatorBridge[1021]: Requesting installation of file:///Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app with options: {
[debug] [WebDriverAgent] Sim: 	    CFBundleIdentifier = "com.apple.test.WebDriverAgentRunner-Runner";
[debug] [WebDriverAgent] Sim: 	    PackageType = Developer;
[debug] [WebDriverAgent] Sim: 	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
[debug] [WebDriverAgent] Sim: 	    SimulatorUserPath = "/Users/user/Library/Developer/CoreSimulator/Devices/A16D8F9D-B113-4821-8D44-9C39EF1EC106/data";
[debug] [WebDriverAgent] Sim: 	}
[debug] [WebDriverAgent] Sim: Apr  5 11:49:32 iSteermac CoreSimulatorBridge[1021]: Requesting launch of com.apple.test.WebDriverAgentRunner-Runner with options: {
[debug] [WebDriverAgent] Sim: 	    arguments =     (
[debug] [WebDriverAgent] Sim: 	        "-NSTreatUnknownArgumentsAsOpen",
[debug] [WebDriverAgent] Sim: 	        NO,
[debug] [WebDriverAgent] Sim: 	        "-ApplePersistenceIgnoreState",
[debug] [WebDriverAgent] Sim: 	        YES
[debug] [WebDriverAgent] Sim: 	    );
[debug] [WebDriverAgent] Sim: 	    environment =     {
[debug] [WebDriverAgent] Sim: 	        "DYLD_FRAMEWORK_PATH" = "/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator:/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Developer/Library/PrivateFrameworks";
[debug] [WebDriverAgent] Sim: 	        "DYLD_LIBRARY_PATH" = "/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator:/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Developer/Library/PrivateFrameworks";
[debug] [WebDriverAgent] Sim: 	        NSUnbufferedIO = YES;
[debug] [WebDriverAgent] Sim: 	        "OS_ACTIVITY_DT_MODE" = YES;
[debug] [WebDriverAgent] Sim: 	        "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
[debug] [WebDriverAgent] Sim: 	        XCTestConfigurationFilePath = "/var/folders/sm/sbx_yj156bz8vpkk2qmlyprr0000gn/T/com.apple.dt.XCTest/7820889F-8223-4597-ADC2-5786EC688EC0/remote-container/tmp/WebDriverAgentRunner-7820889F-8223-4597-ADC2-5786EC688EC0.xctestconfiguration";
[debug] [WebDriverAgent] Sim: 	        "__XCODE_BUILT_PRODUCTS_DIR_PATHS" = "/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator";
[debug] [WebDriverAgent] Sim: 	        "__XPC_DYLD_FRAMEWORK_PATH" = "/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator";
[debug] [WebDriverAgent] Sim: 	        "__XPC_DYLD_LIBRARY_PATH" = "/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator";
[debug] [WebDriverAgent] Sim: 	    };
[debug] [WebDriverAgent] Sim: 	    stderr = "/dev/ttys001";
[debug] [WebDriverAgent] Sim: 	    stdout = "/dev/ttys001";
[debug] [WebDriverAgent] Sim: 	    "wait_for_debugger" = 0;
[debug] [WebDriverAgent] Sim: 	}
[debug] [WebDriverAgent] Sim: Apr  5 11:49:32 iSteermac CoreSimulatorBridge[1021]: Beginning launch sequence for bundle 'com.apple.test.WebDriverAgentRunner-Runner'
[debug] [WebDriverAgent] Sim: 		retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
[debug] [WebDriverAgent] Sim: 		bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
[debug] [WebDriverAgent] Sim: 		bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
[debug] [WebDriverAgent] Sim: 		Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
[debug] [WebDriverAgent] Sim: 	Simulator booted at: 2017-04-04 12:25:07 +0000
[debug] [WebDriverAgent] Sim: 	Current time: 2017-04-05 06:19:32 +0000
[debug] [WebDriverAgent] Sim: 	Within boot leeway: NO
[debug] [WebDriverAgent] Sim: Apr  5 11:49:32 iSteermac CoreSimulatorBridge[1021]: Launch attempt #0 for bundle 'com.apple.test.WebDriverAgentRunner-Runner', have been trying to launch for 0 seconds. Modern launch services = YES
[debug] [WebDriverAgent] Sim: Apr  5 11:49:32 iSteermac CoreSimulatorBridge[1021]: Got LSBundleProxy for 'com.apple.test.WebDriverAgentRunner-Runner', sequenceNumber 304, cacheGUID D8526AB8-1075-4E30-A9C8-E9C822A2917E
[debug] [WebDriverAgent] Sim: Apr  5 11:49:32 iSteermac CoreSimulatorBridge[1021]: [Common] [FBSSystemService][0xbd20] Sending request to open "com.apple.test.WebDriverAgentRunner-Runner"
[debug] [WebDriverAgent] Sim: Apr  5 11:49:32 iSteermac CoreSimulatorBridge[1021]: [Common] [FBSSystemService][0xbd20] Request successful: <BSProcessHandle: 0x7fda18c19e70; XCTRunner:2709; valid: YES>
[debug] [WebDriverAgent] Sim: Apr  5 11:49:32 iSteermac CoreSimulatorBridge[1021]: Launch successful for 'com.apple.test.WebDriverAgentRunner-Runner'
[debug] [WebDriverAgent] Sim: Apr  5 11:49:32 iSteermac XCTRunner[2709]: assertion failed: 16D32 14E269: libxpc.dylib + 64131 [624BAF4F-2E03-34F8-ACBA-970B04637786]: 0x7d
[debug] [WebDriverAgent] Sim: Apr  5 11:49:33 iSteermac XCTRunner[2709]: Running tests...
[debug] [WebDriverAgent] Sim: Apr  5 11:49:34 iSteermac XCTRunner[2709]: Continuing to run tests in the background with task ID 1
[debug] [WebDriverAgent] Sim: Apr  5 11:49:35 iSteermac XCTRunner[2709]: Built at Apr  3 2017 11:10:35
[XCUITest] Detected that WebDriverAgent is running at url 'http://192.168.2.69:8100'
[debug] [WebDriverAgent] Sim: Apr  5 11:49:35 iSteermac XCTRunner[2709]: ServerURLHere->http://192.168.2.69:8100<-ServerURLHere
[XCUITest] WebDriverAgent started at url 'http://192.168.2.69:8100'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"isteer.Demoappium","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}
[debug] [WebDriverAgent] Sim: Apr  5 11:49:36 iSteermac XCTRunner[2709]: Enqueue Failure: Failed to launch isteer.Demoappium: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1

**Comment by imurchie** [comment]
You'll most likely need to upgrade. You're running a fairly old version of the beta.

**Comment by Krunaltthakkar13** [comment]
@imurchie Ok thanks

**Comment by vasyl-n** [comment]
Hi, I am having the exactly the same issue 
APPIUM 1.6.4-beta.2
IOS 10.3

**Comment by antonys1** [comment]
After updating to Xcode 8.3.2 (iOS 10.3) and Appium 1.6.4 on macOS 10.12.4, tests that use `runAppInBackground(int)` throw an exception:
```
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
at io.appium.java_client.AppiumDriver.runAppInBackground(AppiumDriver.java:290)
```
Looks like an existing issue https://github.com/appium/appium/issues/5737

**Comment by imurchie** [comment]
This is completely unrelated to #5737. @antonys1 please open a new issue with all the information requested (including the _full_ Appium server logs as a link to a [gist](https://gist.github.com))?
