### ISSUE TITLE
Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

### ISSUE THREAD

**Issue by Ibnfarooqvlm** [appium/appium#8121]
## The problem
I have installed the following dependecies:

```
brew install ideviceinstaller
brew install Carthage
npm install -g ios-deploy
npm install -g deviceconsole
gem install xcpretty
brew install libimobiledevice —HEAD
brew install libimobiledevice

mkdir -p Resources/WebDriverAgent.bundle
sh ./Scripts/bootstrap.sh -d
```

I then opened the WebDriverAgent in XCode and am able to build WebDriverAgentLib and WebDriverAgentRunner successfully but when I install it with the below command:<br/>
`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=2288f18b7713a79ee3c86xxxxxxxxxxxx' test`
<br/>
it is failing with the following error message:

> 2017-03-29 12:18:24.944 xcodebuild[30468:1719080] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
> 
> Testing failed:
> 	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
> ** TEST FAILED **

<br/>
And this has installed WebDriverAgentRunner in the phone. I then run one sample appium code, but it also got failed with the same error.<br/>
My aim is to perform Mobile Web Automation in iOS Safari browser.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 (beta)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OSx 10.12.3
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Please find the WebDriverAgentRunner Installation logs and Appium logs [HERE](https://gist.github.com/Ibnfarooqvlm/31a34e4e806b474ce9f2d46295db10f0)
https://gist.github.com/Ibnfarooqvlm/31a34e4e806b474ce9f2d46295db10f0

##Capabilities:
```
capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, MobileBrowserType.SAFARI);
capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.3");
capabilities.setCapability(MobileCapabilityType.UDID, MyUDID);
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
capabilities.setCapability("startIWDP", true);
driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"),
				capabilities);
```

**Comment by mykola-mokhnach** [comment]
1. Make sure the source is properly signed and can be installed and executed manually from Xcode
2. Do not use old 32-bit iDevices for automation (<= iPhone5)
3. Reboot the device

**Comment by Ibnfarooqvlm** [comment]
Thanks for the comment mykola.
1. I don't know how to check whether its properly signed or not. Could you please help?
2. This is the only phone I got for automation.
3. I rebooted several times.

**Comment by Ibnfarooqvlm** [comment]
Reinstalled the appium and now WebDriverAgent got installed. During installation, this was the last line:


> 
> writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/mb/fr7_nwq974730b3bcp82nq_40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/8049a3b653a63c65396a60bb65d0240b/2288f18b7713a79ee3c868720abe794bc77b891a/ManifestCache.plist
> Test Suite 'All tests' started at 2017-03-29 19:43:26.850
> Test Suite 'WebDriverAgentRunner.xctest' started at 2017-03-29 19:43:26.853
> Test Suite 'UITestingUITests' started at 2017-03-29 19:43:26.855
> Test Case '-[UITestingUITests testRunner]' started.
>     t =     0.00s     Start Test at 2017-03-29 19:43:26.859
>     t =     0.01s     Set Up

I didn't get any proper message as "Build Succeeded" or "Build Failed".

Then I launch the webpage, the webpage got opened but its not identifying many elements. The same code is running fine in Android but not working in ios. Any idea?

This is my code:

```
By byAccount = By.cssSelector("li[class = account-icon-block]");
driver.findElement(byAccount)
```

Please help.

**Comment by skumar1122** [comment]
Hey ,

I am also facing same error and this is after I did update to my Xcode and appium-xcuitest-driver/WebDriverAgent.

I am using following :
Xcode - 8.2.1
Appium - 1.6@Beta
iOS - 10.2
Device - iPhone6 , iPhone7

When I am trying to build manually or from terminal I am getting same error mentioned below,

> CompileC /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBConfiguration.o WebDriverAgentLib/Utilities/FBConfiguration.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
>     cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
>     export LANG=en_US.US-ASCII
>     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/skumar/Library/Android/sdk/tools:/Users/skumar/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch arm64 -fmessage-length=148 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/skumar/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/skumar/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Wmissing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Warc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wunused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -pedantic -Wshadow -Wno-four-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wassign-enum -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=10.2 -g -Wno-sign-conversion -Winfinite-recursion -iquote /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-generated-files.hmap -I/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-own-target-headers.hmap -I/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-all-target-headers.hmap -iquote /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-project-headers.hmap -I/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/usr/include/libxml2 -I/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Modules -I/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/DerivedSources/arm64 -I/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/DerivedSources -Weverything -Wno-objc-missing-property-synthesis -Wno-unused-macros -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-language-extension-token -Wno-overriding-method-mismatch -Wno-missing-variable-declarations -Rno-module-build -Wno-auto-import -Wno-objc-interface-ivars -Wno-documentation-unknown-command -Wno-reserved-id-macro -Wno-unused-parameter -Wno-gnu-conditional-omitted-operand -Wno-explicit-ownership-type -Wno-date-time -Wno-cast-align -Wno-cstring-format-directive -Wno-double-promotion -F/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS -F/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/Mac -MMD -MT dependencies -MF /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBConfiguration.d --serialize-diagnostics /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBConfiguration.dia -c /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBConfiguration.m -o /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBConfiguration.o
> 
> 2017-03-29 18:57:01.455 xcodebuild[42075:4966368] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/91081213-BF45-450B-B486-4E6971FAA8F9/Session-WebDriverAgentRunner-2017-03-29_185658-mkDpaA.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/91081213-BF45-450B-B486-4E6971FAA8F9/Session-WebDriverAgentRunner-2017-03-29_185658-mkDpaA.log}
> 
> Testing failed:
> 	'openURL:' is deprecated: first deprecated in iOS 10.0 - Please use openURL:options:completionHandler: instead
> ** TEST FAILED **
> 
> 
> The following build commands failed:
> 	CompileC /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBSessionCommands.o WebDriverAgentLib/Commands/FBSessionCommands.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)

And In XCODE same error , please check Screenshot :

![image](https://cloud.githubusercontent.com/assets/20112173/24475450/c5a657ae-14c7-11e7-9017-968ecc407b9a.png)

Any Suggestions ?

Thanks
SK

**Comment by imurchie** [comment]
RE-install the Appium beta to get the latest fixes. This is fixed.

**Comment by 9SumeetMourya** [comment]
I am using appium 1.6.3 but having same issue :
Sumeet-MacBook-Pro:~ sumeet$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
Sumeet-MacBook-Pro:WebDriverAgent sumeet$ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=b51010f0f6f1e8eb8cf253a908fdd9c4aed2d63b' test
2017-07-11 11:35:25.268 xcodebuild[17966:183821] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-07-11 11:35:28.693 xcodebuild[17966:183941]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/sumeet/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/7B7CCD4A-017F-4A37-9FFD-90FCF447ED10/Session-WebDriverAgentRunner-2017-07-11_113528-xYf5xG.log
2017-07-11 11:35:28.693 xcodebuild[17966:183821] [MT] IDETestOperationsObserverDebug: (F2A5C9DE-2B15-4E5F-99F3-0343E6C4CFE4) Beginning test session WebDriverAgentRunner-F2A5C9DE-2B15-4E5F-99F3-0343E6C4CFE4 at 2017-07-11 11:35:28.693 with Xcode 8E162 on target <DVTiOSDevice: 0x7f7fe17b8cb0> {
		deviceSerialNumber:         DNRJMVAPDTTN
		identifier:                 b51010f0f6f1e8eb8cf253a908fdd9c4aed2d63b
		deviceClass:                iPhone
		deviceName:                 24Alife iPhone
		deviceIdentifier:           b51010f0f6f1e8eb8cf253a908fdd9c4aed2d63b
		productVersion:             10.0.2
		buildVersion:               14A456
		deviceSoftwareVersion:      10.0.2 (14A456)
		deviceArchitecture:         armv7s
		deviceTotalCapacity:        13104246784
		deviceAvailableCapacity:    5863903232
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f7fe168dee0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.0.2 (14A456))
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/nd/kh6lz6g50nd8vv4_4g3b96bc0000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/9268e04ab29a518579a1fc7494118b6c/b51010f0f6f1e8eb8cf253a908fdd9c4aed2d63b/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/sumeet/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/nd/kh6lz6g50nd8vv4_4g3b96bc0000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.tFn6sc/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/nd/kh6lz6g50nd8vv4_4g3b96bc0000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.tFn6sc/WebDriverAgentRunner-Runner.app_sparse.ipa
__MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/nd/kh6lz6g50nd8vv4_4g3b96bc0000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.tFn6sc/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/nd/kh6lz6g50nd8vv4_4g3b96bc0000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.tFn6sc/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2017-07-11 11:35:37.336634 XCTRunner[222:6630] Running tests...
2017-07-11 11:35:37.558854 XCTRunner[222:6630] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2017-07-11 11:35:37.563697 XCTRunner[222:6630] (dlopen_preflight(/var/containers/Bundle/Application/794E9A17-21E5-4207-A94A-4A4EBE99CBC5/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
  Referenced from: /private/var/containers/Bundle/Application/794E9A17-21E5-4207-A94A-4A4EBE99CBC5/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/794E9A17-21E5-4207-A94A-4A4EBE99CBC5/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/794E9A17-21E5-4207-A94A-4A4EBE99CBC5/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.f)
2017-07-11 11:35:37.647 xcodebuild[17966:183821] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

**Comment by KovtunOleg** [comment]
In our case the problem was that there wasn't enough space left on the disk.
