### ISSUE TITLE
WebDriverAgent taking too long to open. Simulator closes when App finally loads

### ISSUE THREAD

**Issue by jbuoncri1** [appium/appium#8161]
## The problem
On iOS, when I try to start appium the webdriver agent and app take a very long time to load. The webdriver and app eventually loads, simulator shuts down before script runs. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 (exe)
* Desktop OS/version used to run Appium: OSX 10.12.4
* Mobile platform/version under test: iPhone 7 w/ 10.3
* Real device or emulator/simulator: Xcode 8.3

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/jbuoncri1/3ca7f4ec77585bcbb5370c08cb6e3b12

**Comment by dpgraham** [comment]
Have you tried increasing `newCommandTimeout`?

Also, have you tried using version 1.6.4-beta?

**Comment by jbuoncri1** [comment]
Yes, I have tried to set the newCommandTimeout to 180, but still defaults to 120000 ms

I haven't tried 1.6.4-beta. Will give an update soon

**Comment by imurchie** [comment]
I'm confused. I don't see any problem in the logs you post. The session starts fine and accepts commands afterward.

**Comment by jbuoncri1** [comment]
@imurchie It accepts the commands in the beginning, but the iOS simulator closes abruptly. 

I would post a screen recording, but the file is over 400MB

**Comment by imurchie** [comment]
Can you provide the logs with `--log-timestamp` command line flag on, so we can see where the time is being spent?

**Comment by jbuoncri1** [comment]
@imurchie about when I start the appium server will --log-timestamp start as well?

**Comment by jlipps** [comment]
@jbuoncri1: @imurchie was asking you to add the `--log-timestamp` command when you start appium, like:

    appium --log-timestamp

**Comment by rcuyugan** [comment]
By gosh! I just updated my devices for testing to 10.3.1 because of the annoying message that keeps telling me to update my iOS. Now my WDA takes forever as well. I did set my timeout > 180 and it still times out and closes out the testing.

BTW still works like a charm on my old iPad mini 9.3 device.

logs:

[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   device: 'iPad Air 2'
[Appium]   deviceName: 'iPad Air 2'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   udid: '92c19219b4086307cbd49ebb6e21b34d6xxxxxxxxx'
[Appium]   app: '/Users/rcuyugan/Documents/qa/Renovate America-2.7.318-release-v2-7.ipa'
[Appium]   automationName: 'XCUITest'
[Appium]   xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/ProjectSettings.xcconfig'
[Appium]   xCodeOrgId: 'X'
[Appium]   CodeSigningId: 'iPhone Developer'
[Appium]   fullReset: true
[Appium]   usePrebuiltWDA: true
[Appium]   useNewWDA: true
[Appium]   showXcodeLog: true
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: device, xCodeOrgId, CodeSigningId, useNewWDA.
[BaseDriver] Session created with session id: c998b88e-7528-4c27-b719-3a8014523f87
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: 92c19219b4086307cbd49ebb6e21b34d61e66253
[debug] [XCUITest] Creating iDevice object with udid 92c19219b4086307cbd49ebb6e21b34d61e66253
[XCUITest] Determining device to run tests on: udid: '92c19219b4086307cbd49ebb6e21b34d61e66253', real device: true
[BaseDriver] Using local app '/Users/rcuyugan/Documents/qa/Renovate America-2.7.318-release-v2-7.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/r2/7f2tj7ns5yg9tfr80y0b3q2508xrb_/T/2017317-21839-1czoom1.acq785xw29/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/r2/7f2tj7ns5yg9tfr80y0b3q2508xrb_/T/2017317-21839-1czoom1.acq785xw29/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/r2/7f2tj7ns5yg9tfr80y0b3q2508xrb_/T/2017317-21839-1czoom1.acq785xw29/Payload/Renovate America.app'
[debug] [XCUITest] Checking whether app '/var/folders/r2/7f2tj7ns5yg9tfr80y0b3q2508xrb_/T/2017317-21839-1czoom1.acq785xw29/Payload/Renovate America.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/var/folders/r2/7f2tj7ns5yg9tfr80y0b3q2508xrb_/T/2017317-21839-1czoom1.acq785xw29/Payload/Renovate America.app': 'com.ra.mobile.creditapp'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] Error checking install status: Command 'ios-deploy --exists --id 92c19219b4086307cbd49ebb6e21b34d61e66253 --bundle_id com.ra.mobile.creditapp' exited with code 255
[debug] [XCUITest] App is not installed. Will try to install.
[debug] [XCUITest] App installed successfully.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Using Xcode configuration file: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/ProjectSettings.xcconfig'
[XCUITest] 'usePrebuiltWDA' set, but on real device, so skipping
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=92c19219b4086307cbd49ebb6e21b34d61e66253 -configuration Debug -xcconfig /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/ProjectSettings.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[Xcode] Build settings from configuration file '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/ProjectSettings.xcconfig':

[XCUITest] Waiting for WebDriverAgent to start on device
[Xcode]     CODE_SIGN_IDENTITY = Stripped intentionally
    DEVELOPMENT_TEAM = Stripped intentionally


[Xcode] xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ id:92c19219b4086307cbd49ebb6e21b34d61e66253 }

	Unsupported device specifier option.
	The device “My Mac” does not support the following options: id
	Please supply only supported device specifier options.

	Available destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS, id:92c19219b4086307cbd49ebb6e21b34d61e66253, name:RAOC ipad }
		{ platform:iOS Simulator, id:C308F7F0-8266-401F-9BE4-D3353E499636, OS:10.2, name:iPad Air }
		{ platform:iOS Simulator, id:77DD888E-15CA-4DF6-B14F-F4FBC6255445, OS:10.2, name:iPad Air 2 }
		{ platform:iOS Simulator, id:97AABD75-2685-4725-B9D4-D33CA9D0E276, OS:10.2, name:iPad Pro (9.7 inch) }
		{ platform:iOS Simulator, id:72CDC814-27B4-4963-BAD0-7C4D64EA29AC, OS:10.2, name:iPad Pro (12.9 inch) }
		{ platform:iOS Simulator, id:4D3671B1-5F11-4820-857A-A7377890AA7C, OS:10.2, name:iPad Retina }
		{ platform:iOS Simulator, id:BC7B2ADA-61A3-46D6-AF1B-3CAA5A2A5256, OS:10.2, name:iPhone 5 }
		{ platform:iOS Simulator, id:EF40A17C-9426-4777-A93B-ABB2970BE0FF, OS:10.2, name:iPhone 5s }
		{ platform:iOS Simulator, id:6E1B0AB3-F324-4167-AAA4-A06C72840A2B, OS:10.2, name:iPhone 6 }
		{ platform:iOS Simulator, id:F1F97164-618A-45E0-B48C-558CC5E9247B, OS:10.2, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:02339D00-738A-4908-95B1-9FB91274DEE5, OS:10.2, name:iPhone 6s }
		{ platform:iOS Simulator, id:BCE6EAD3-B6B1-4C21-973F-66E266596F9A, OS:10.2, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:46538732-597E-4D72-BBBD-AC5F1E4C8172, OS:10.2, name:iPhone 7 }
		{ platform:iOS Simulator, id:FEC83816-347C-410A-AEC3-17EA3B3A2DD3, OS:10.2, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:98AAD2B0-6DC8-4072-900B-2E44F920AB4C, OS:10.2, name:iPhone SE }

	Ineligible destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }

[XCUITest] xcodebuild exited with code '70' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 22072)
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Full reset requested. Will try to uninstall the app 'com.ra.mobile.creditapp'.
[debug] [XCUITest] Removed 'com.ra.mobile.creditapp'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by jlipps** [comment]
@rcuyugan you're describing a different issue than the one reported here. please create a new issue with your details.

**Comment by rcuyugan** [comment]
Jonathan,

Thank you for getting back with me, I posted this as I thought that the
title on the ticket is similar to the issue I am having. However in my
search I did found a couple of issues around this with the iOS 10.3.1
upgrade that have been closed.

https://github.com/appium/appium/issues/7192
https://github.com/appium/appium/issues/8192

Ran into this issue just yesterday and I haven't researched a fix or
workaround yet. FYI, we are in the process of evaluating Appium and
SauceLabs for our ATF and recently exchanged emails with Jack King from
SauceLabs on where we are currently in the evaluation process. and would be
interested in exploring this further once we've identified Appium/SauceLabs
to be the solution. I appreciate any advise and look forward to hearing
from you.


Best Regards,

Robert Cuyugan
QA Architect @ Renovate America


p.s: I posted this on my personal gmail. My company email where we can
communicate is rcuyugan@renovateamerica.com. Feel free to email me if you
have any questions or comments.

**Comment by imurchie** [comment]
@rcuyugan The problem in the logs you've provided is that Xcode 8.2 does not understand anything about iOS 10.3. You will need to upgrade to the latest Xcode (8.3.1) in order for it to be able to find a real device with iOS 10.3.1.

**Comment by rcuyugan** [comment]
Hmmm.. Ok, thanks for getting back with me. A few weeks back I upgraded to
XCode 8.3 and it broke my automation, the WDA had issues locating elements
(text fields). I was able to fix it by reverting XCode back to 8.2 and
recomplied the WDA. I am going to try your suggestion and hopefully not
have to refactor or break the current automation we have.

On Tue, Apr 18, 2017 at 12:15 PM, Isaac A. Murchie <notifications@github.com

**Comment by rcuyugan** [comment]
Device can now be found as you suggested (Isaac). However since I upgraded
as I as suspected, my automation is now again broken. Please attached
snapshot. Any advise would be appreciated. Thanks!

**Comment by imurchie** [comment]
Not sure what "Please attached snapshot" means.

Can you post a link to a [gist](https://gist.github.com) of the Appium server logs when you perform a run with the `showXcodeLog` capability set to `true`?

**Comment by rcuyugan** [comment]
Sorry, typo. Should be "see attached..." I have attached a tiff with the
error. showXcodeLog is already set to true. If you can't see it please let
me know. Thanks. BTW, following the thread on discuss.appium.io today and
seems to be a known issue. Here's my current environment, just updated
Appium to 1.6.4-beta (cli), downloaded Facebook/wda, recompiled WDA, no
issue recompiling, WDA deployed on iOS devices. Resulted to same error
​.

**Comment by imurchie** [comment]
I don't see any image anywhere. The logs, in a [gist](https://gist.github.com) would be most helpful. Not a picture of them.

**Comment by rcuyugan** [comment]
<script src="
https://gist.github.com/rcuyugan/cf6afb306ebc726d92fd374e8249788f.js
"></script>

Please see line 88.

Thanks appreciate all the help!

**Comment by imurchie** [comment]
This is entirely different than the original error in this issue. I'm not sure why it is here. If you look through the issues you will find this particular one discussed.

**Comment by rcuyugan** [comment]
Yep. This started off with the WDA issue on iOS 10.3 upgrade. But going
through the postings on discuss.appium.io "this" (my issue) issue has been
in discussion for a while and I can't seem this find a resolution for it.
If you are aware of any work around please let me know. As it stands, we
can't utilize our current iOS automation anymore. I will continue to look
around the threads to see if I find anything that will help me resolve this.
