### ISSUE TITLE
Appium XCUITest run are aborting

### ISSUE THREAD

**Issue by qakapil** [appium/appium#8168]
## The problem

This is happening consistently on a couple of my mac machines. When running test suites with xcuitest the test runs get aborted in the middle of the run. This happens when a test case fails and in the teardown we try to reset the webdriver. I have tried on both appium-1.6.4-beta and appium-1.6.4-beta2

## Environment

* Appium version : appium-1.6.4-beta2
* Desktop OS/version used to run Appium: El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): v6.7.0
* Mobile platform/version under test: iOS9.3 and iOS10.2
* Real device or emulator/simulator: Read device
* XCODE version - 8.2.1

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/qakapil/54d73ab87522ac4c33d84bcc1e476b30

**Comment by mykola-mokhnach** [comment]
Full appium log is needed

**Comment by qakapil** [comment]
@mykola-mokhnach  - there are 623195 in the full appium log file :-)
Shall I copy the last 20% ?

**Comment by mykola-mokhnach** [comment]
BTW, I'd rather start and quit appium session between tests - this is faster and more reliable in comparison to reset (which does the same stuff inside)

**Comment by qakapil** [comment]
@mykola-mokhnach I will try that too. Here are the appium logs...almost full logs - 
https://gist.github.com/qakapil/ca9501f781fa59b3b94d68554d07028e

**Comment by mykola-mokhnach** [comment]
I've checked the log and I can say the issue has nothing to do with Appium reset. The problem is, that WDA itself stops responding after multiple restarts (check https://github.com/appium/appium/issues/8083 for more details). This is an XCTest issue on real devices and we cannot do anything about it. 
You could try to either play with **webDriverAgentUrl**, **useNewWDA** and **usePrebuiltWDA** capabilities  to avoid multiple WDA reinstalls or move your tests to Simulator.
