### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by MaisGurbanov** [appium/appium#8175]
Hello guys.

There is interesting situation. Yesterday appium was working fine without any problem. But today there is the mentioned error. The interesting side that I did not change anything in desired capabilities or on appium's configuration. 

Appium 1.6.4-beta.2
XCode 8.3
iPhone 5s 10.0.1

https://gist.github.com/MaisGurbanov/d60cbde332765b2b42c8fe170a10c251

Thanks in advance

**Comment by imurchie** [comment]
Try specifying a `platformVersion` in your desired capabilities.

**Comment by MaisGurbanov** [comment]
@imurchie thanks for quick response. I tried as you mentioned but unfortunately there is not successful result: https://gist.github.com/MaisGurbanov/098b163626ca60bd4a305347c42e8c89

**Comment by saikrishna321** [comment]
@MaisGurbanov can you also pls post the device logs ?

**Comment by mykola-mokhnach** [comment]
Try to reboot the phone. Check https://github.com/appium/appium/issues/8083 for more details

**Comment by imurchie** [comment]
For more information, also set the `showXcodeLog` capability to `true` to get the full logs of trying to build the system.

**Comment by MaisGurbanov** [comment]
@mykola-mokhnach I rebooted the device, unfortunately it does not help. 

@imurchie please see the follow gist after adding showXcodeLog capability: https://gist.github.com/MaisGurbanov/ebc6d4e1658690fb43ce9aee964c009e 

@saikrishna321 please can you tell me where I can find the device logs?

**Comment by imurchie** [comment]
It seems to have already built, so maybe something is clashing. Can you remove the old builds and try again?
```
rm -rf /Users/magistechnology/Library/Developer/Xcode/DerivedData/WebDriverAgent-*
```

**Comment by MaisGurbanov** [comment]
@imurchie I tried as you suggested, but it is failed again: https://gist.github.com/MaisGurbanov/7599746355c54efe47c3969d45fbaac6

**Comment by imurchie** [comment]
The build step still seems truncated. Can you run
```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=1844b8fe8ea572dbfb13b016d7ed0b9c71a44fc9 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.0 -xcconfig /var/folders/vf/5b92p0_n7r58ffcjk6y0pjvm0000gn/T/201735-3277-1izi9ob.t7q2xogvi/appium-temp.xcconfig
```

**Comment by MaisGurbanov** [comment]
@imurchie please see the gist: https://gist.github.com/MaisGurbanov/9d31cb3c4bc8380d60364798c92bf75b

**Comment by mykola-mokhnach** [comment]
> Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'

It's broken. Make sure codesigning works as expected

**Comment by imurchie** [comment]
But `com.facebook.WebDriverAgentRunner` should have been overwritten by their updated WDA bundle id.

**Comment by MaisGurbanov** [comment]
@mykola-mokhnach As desired capability for xcodeOrgId and signingId I added the correct information of my enterprise account. I followed according to instruction of Basic (manual) Configuration as decribed in https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md . As I wrote above, yesterday it was working without any problem and I did not change anything.

@imurchie what do you suggest to do? uninstall and install appium again?

**Comment by mykola-mokhnach** [comment]
Everything can happen. Are you able to compile and deploy WDA to the device from Xcode?

**Comment by Manikanta29** [comment]
@imurchie I am also facing the same issue. Still, the issue is persisting #8192

**Comment by mayureshshirodkar** [comment]
Facing the same issue as @MaisGurbanov. it worked the first few times and then lead me to nable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

**Comment by Manikanta29** [comment]
@mayureshshirodkar just cross check the WDA provisioning profile in xcode and re-run the following cmd in terminal " xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test "  for the real device.  working fine for me.

**Comment by SamyQAZ** [comment]
I do face the same issue. 
I am able to run the tests few times, later leading to error code 65.
Once restart device, tests runs successfully few times followed by error code 65.
I am using iPhone 5(10.3.2), Xcode 8.3.3, Appium 1.1.0-beta.4 
Also, my setup mentioned ```https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md``` in here is properly done.
Please help to share the solution.

**Comment by sarozNep** [comment]
@imurchie 

i am having same problem and my log is below >

[Appium] Welcome to Appium v1.6.5
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 8 ms - 40 
[HTTP] --> DELETE /wd/hub/session {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 3 ms - 57 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/sd/Desktop/Astro-iOS.DEV copy.app","bundleId":"com.sd.ios.astro.DEV","deviceName":"iPhone 5s","noReset":true,"platformName":"iOS","platformVersion":"10.0.2","udid":"2a76e49bb8c9ad5a983e007ea8d2ded23f7bd5c2","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/Desktop/Allianz-iOS.DEV copy.app","bundleId":"com.sd.ios.allianz.smarthome.DEV","deviceName":"iPhone 5s","noReset":true,"platformName":"iOS","platformVersion":"10.0.2","udid":"2a76e49bb8c9ad5a983e007ea8d2ded23f7bd5c2","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1502360291694 (11:18:11 GMT+0100 (WEST))
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/muzzley/Desktop/Allianz-iOS.DEV copy.app'
[Appium]   bundleId: 'com.muzzley.ios.astro.DEV'
[Appium]   deviceName: 'iPhone 5s'
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.0.2'
[Appium]   udid: '2a76e49bb8c9ad5a983e007ea8d2ded23f7bd5c2'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: b9131ae7-f624-459f-8c65-7477c3bf03ed
[XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1502360291840 (11:18:11 GMT+0100 (WEST))
[XCUITest] Available devices: 2a76e49bb8c9ad5a983e007ea8d2ded23f7bd5c2
[XCUITest] Creating iDevice object with udid '2a76e49bb8c9ad5a983e007ea8d2ded23f7bd5c2'
[XCUITest] Determining device to run tests on: udid: '2a76e49bb8c9ad5a983e007ea8d2ded23f7bd5c2', real device: true
[BaseDriver] Using local app '/Users/sd/Desktop/Allianz-iOS.DEV copy.app'
[BaseDriver] Event 'appConfigured' logged at 1502360292207 (11:18:12 GMT+0100 (WEST))
[XCUITest] Checking whether app '/Users/sd/Desktop/Allianz-iOS.DEV copy.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1502360292209 (11:18:12 GMT+0100 (WEST))
[XCUITest] Reset: fullReset not set. Leaving as is
[BaseDriver] Event 'resetComplete' logged at 1502360292209 (11:18:12 GMT+0100 (WEST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1502360292357 (11:18:12 GMT+0100 (WEST))
[XCUITest] Setting up real device
[XCUITest] App 'com.muzzley.ios.astro.DEV' is already installed. No need to reinstall.
[BaseDriver] Event 'appInstalled' logged at 1502360292556 (11:18:12 GMT+0100 (WEST))
[BaseDriver] Event 'wdaStartAttempted' logged at 1502360292557 (11:18:12 GMT+0100 (WEST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=2a76e49bb8c9ad5a983e007ea8d2ded23f7bd5c2 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.0' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/muzzley/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/ADAC2A04-EDF8-4B44-88B4-2EFAABFCD0C0/Session-WebDriverAgentRunner-2017-08-10_111820-p9FCzH.log
[Xcode] 2017-08-10 11:18:20.708 xcodebuild[1752:29824] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fd52dd58de0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-08-10 11:18:20.708 xcodebuild[1752:29824] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1502360300747 (11:18:20 GMT+0100 (WEST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 1751)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[BaseDriver] Event 'wdaStartAttempted' logged at 1502360311025 (11:18:31 GMT+0100 (WEST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=2a76e49bb8c9ad5a983e007ea8d2ded23f7bd5c2 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.0' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/sd/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/A632EC82-B0C9-4AFA-B9B5-66A19C1D52F0/Session-WebDriverAgentRunner-2017-08-10_111840-P9HQfv.log
[Xcode] 2017-08-10 11:18:40.435 xcodebuild[1780:30083] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fc2d5b16650 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-08-10 11:18:40.435 xcodebuild[1780:30083] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1502360320464 (11:18:40 GMT+0100 (WEST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 1779)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:15)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 39052 ms - 230

**Comment by imurchie** [comment]
@sarozNep This is a code signing issue. Please go through https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by TamtamSangani** [comment]
@imurchie your link doesn't work please can you re post it or direct me to correct path.

**Comment by imurchie** [comment]
https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md
