### ISSUE TITLE
Error finding elements in windows dialogs.

### ISSUE THREAD

**Issue by pvila89** [appium/appium#8283]
Hi,

I am not able to get an element from an upload windows dialog generated by a windows app.

![image](https://cloud.githubusercontent.com/assets/3186791/25178954/2b5e73d8-2508-11e7-997c-284c10623e15.png)

I am using the following code:

![image](https://cloud.githubusercontent.com/assets/3186791/25179142/e1f94582-2508-11e7-9bf8-8dedce9e9d72.png)

I even looked for the element using the id provided by inspector.

![image](https://cloud.githubusercontent.com/assets/3186791/25179158/f3a3dca2-2508-11e7-9fdf-68354ff8a6fb.png)

and the error given is:

An element could not be located on the page using the given search parameters.

I can find all the elements in the windows application but not the elements comming from windows dialogs.

Could you help me?
Thanks in advance.

**Comment by dpgraham** [comment]
A few things you can try:
* Calling `driver.GetPageSource()` when the windows open to look for the element
* Open inspector in Appium Desktop (https://github.com/appium/appium-desktop/releases/latest) so that you can inspect the contents of your app

Also, I'm not an expert on Windows, but I would suspect that to access a dialog you would need to change contexts.
