### ISSUE TITLE
xcodebuild failed with code 65 error while running on real device with Appium 1.6.4

### ISSUE THREAD

**Issue by shanthi2016** [appium/appium#8298]
Getting: "Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65" while running the test on real device iOS 10.2.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac OS 10.12
* Node.js version (unless using Appium.app|exe): 6.10.2
* Mobile platform/version under test: 10.2.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:Appium.app

Here is the link to appium logs:
https://gist.github.com/shanthi2016/e2a2567a46796d40bbbf77714f88f697

**Comment by dpgraham** [comment]
Are you able to build and deploy the WebDriverAgent project (`/Applications/Appium_1.6.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj`) from xcode?

**Comment by mykola-mokhnach** [comment]
Please attach the log with **showXcodeLog** option enabled. Usually error 65 means there problems with signing.
Might be a duplicate of https://github.com/appium/appium/issues/8297

**Comment by shanthi2016** [comment]
Please find below the logs with showXcodeLog capabiltity set to true: https://gist.github.com/shanthi2016/12e21c577df3df878a502f371ea5d7e6

 @dpgraham I am able to build and deploy the WDA project

**Comment by mykola-mokhnach** [comment]
> Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'

It's quite clear what the problem is

**Comment by shanthi2016** [comment]
Does giving one's own apple ID doesn't work for the signing

**Comment by mykola-mokhnach** [comment]
There are bunch of capabilities that can solve signing issues:

- xcodeOrgId
- xcodeSigningId
- xcodeConfigFile
- updatedWDABundleId
- keychainPath
- keychainPassword

Try them and see if this helps

**Comment by imurchie** [comment]
Please refer to https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by shanthi2016** [comment]
It works after giving the xcodeOrgId with the team ID provided by Apple and xcodeSigningId

**Comment by MathuMarques** [comment]
How did you find your xcodeOrgId and your xcodeSigningId?

**Comment by imurchie** [comment]
https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md#basic-automatic-configuration

**Comment by narendra-chandratre** [comment]
Hi Team,
Facing same issue.

Scenario :
I am able to launch my application on Simulator with iOS version 9.3 But when I am trying to inspect element I am getting error :
"xcodebuild failed with code 65".

**Below are my logs:**
[debug] [XCUITest] Removing WDA application from device[debug] [BaseDriver] Event 'wdaUninstalled' logged at 1545744128456 (18:52:08 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1545744128456 (18:52:08 GMT+0530 (IST))
[info] [XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*9DB129D1-28B4-47A3-AB13-2AA118D672D6, iproxy 8100, 9DB129D1-28B4-47A3-AB13-2AA118D672D6.*XCTRunner' for the device 9DB129D1-28B4-47A3-AB13-2AA118D672D6...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*9DB129D1-28B4-47A3-AB13-2AA118D672D6' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif 9DB129D1-28B4-47A3-AB13-2AA118D672D6.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Using Xcode 9.2, so fixing WDA codebase
[debug] [XCUITest] Beginning test with command 'xcodebuild test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=9DB129D1-28B4-47A3-AB13-2AA118D672D6 IPHONEOS_DEPLOYMENT_TARGET=9.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/6_/7sj7myss6gzfg70g73dy905h0000gp/T/com.apple.dt.XCTest/IDETestRunSession-FF883AD1-5886-47D7-9337-1DD41F50F878/WebDriverAgentRunner-1930EB9B-E1C1-428C-A53A-BD484D3FB069/Session-WebDriverAgentRunner-2018-12-25_185211-M4CYnM.log[info] [Xcode] 2018-12-25 18:52:11.665 xcodebuild[39958:1375567] Error Domain=IDEFoundationErrorDomain Code=1 "Cannot launch simulated executable: no file found at /Users/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app" UserInfo={NSLocalizedDescription=Cannot launch simulated executable: no file found at /Users/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app}
[info] [Xcode] 2018-12-25 18:52:11.665 xcodebuild[39958:1375567] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[info] [Xcode]
[info] [Xcode] 2018-12-25 18:52:11.667 xcodebuild[39958:1375583] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fdefd5a3600>
[info] [Xcode]
[info] [Xcode] ** TEST EXECUTE FAILED **
[info] [Xcode]
[info] [Xcode]
[info] [XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1545744131689 (18:52:11 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[info] [XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1545744141896 (18:52:21 GMT+0530 (IST))
[info] [XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*9DB129D1-28B4-47A3-AB13-2AA118D672D6, iproxy 8100, 9DB129D1-28B4-47A3-AB13-2AA118D672D6.*XCTRunner' for the device 9DB129D1-28B4-47A3-AB13-2AA118D672D6...

**Comment by asifetisalat** [comment]
Hi Team,

I am also facing the same issue.

**Scenario :**
I am trying to test app but each time when I run, webDriverAgentRunner app is getting installed on my mobile and getting disappear/deleted. After that getting an error saying Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".

**System Info:**
Mac OS: 10.14.2 (Mojave)
Appium v1.10.0
Mobile : 12.1.2


NOTE: I trusted webDriverAgentRunner app as well but after running the test webDriverAgentRunner app is getting disappear/deleted. This is happening each time when I run the test. 

Please see the logs attached
[log1.txt](https://github.com/appium/appium/files/2758421/log1.txt)
