### ISSUE TITLE
Application crashes when running via  iOS Simulator/Webdriver

### ISSUE THREAD

**Issue by ssrinivasan4ip** [appium/appium#8360]
## The problem

Application crashes when running via Simulator/Webdriver

## Environment

* Appium version (or git revision) that exhibits the issue:  1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.6.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

The app exits automatically when running via an Simulator

## Link to Appium logs
```
xcodebuild build-for-testing test-without-building -project /Users/ipmobile/Downloads/New Folder With Items/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=8F80745A-3603-411F-9831-8E75F54A1B7A -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Users/ipmobile/Downloads/New Folder With Items/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/ipmobile/Library/Developer/Xcode/DerivedData/WebDriverAgent-hdgqmaqxpiykoxauroolbvygfxnl/Logs/Test/B035DD4B-37CB-4783-BD19-C7376E4D93A6/Session-WebDriverAgentRunner-2017-05-02_171949-pwjEdQ.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.3\",\n      \"ip\" : \"192.168.75.106\"\n    },\n    \"build\" : {\n      \"time\" : \"May  2 2017 16:46:47\"\n    }\n  },\n  \"sessionId\" : \"987488C0-9EBE-4E4D-9C66-1DEA877AC9F1\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '192.168.75.106'
[XCUITest] WebDriverAgent successfully started after 7589ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493725795793 (17:19:55 GMT+0530 (IST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.ip.mobilepos","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.ip.mobilepos application","sessionId":"987488C0-9EBE-4E4D-9C66-1DEA877AC9F1","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1493726038188 (17:23:58 GMT+0530 (IST))
```

## Code To Reproduce Issue 

Running appium desktop with the following  json representation
```
{
  "platformName": "iOS",
  "platformVersion": "10.3",
  "deviceName": "iPhone Simulator",
  "automationName": "XCUITest",
  "app": "/Users/ipmobile/Downloads/MobilePos.ipa"
}
```

**Comment by mykola-mokhnach** [comment]
How application crash is related to Appium?

**Comment by ssrinivasan4ip** [comment]
Sorry not to be clear.. The Simulation app exits as soon as it gets launched. 

I mean appium opens the app in the simulator and it automatically exits

**Comment by mykola-mokhnach** [comment]
Can you attach the full Appium log then?

**Comment by imurchie** [comment]
Probably not a simulator build of the app.

**Comment by dpgraham** [comment]
`/Users/ipmobile/Downloads/MobilePos.ipa` won't run on a Simulator. You need the .app file.

**Comment by mykola-mokhnach** [comment]
Closed as non Appium-realted issue

**Comment by sachitanandkumar** [comment]
Hi, @dpgraham 

I m using .app file, but issue(app is crashing still)

[info] [Appium] Welcome to Appium v1.8.1
[info] [Appium] Non-default server args:
[info] [Appium]   address: 127.0.0.1
[info] [Appium] Appium REST http interface listener started on 127.0.0.1:4723[info] [HTTP] --> POST /wd/hub/session
[info] [HTTP] {"desiredCapabilities":{"AutomationName":"XCUITest","app":"/Users/testmachine/Desktop/sachit/Payload2/FuturePay.app","browserName":"","deviceName":"iPhone Simultor","newCommandTimeout":100000,"platformName":"iOS","platformVersion":"11.3","udid":"C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C","useNewWDA":true},"capabilities":{"desiredCapabilities":{"AutomationName":"XCUITest","app":"/Users/testmachine/Desktop/sachit/Payload2/FuturePay.app","browserName":"","deviceName":"iPhone Simultor","newCommandTimeout":100000,"platformName":"iOS","platformVersion":"11.3","udid":"C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C","useNewWDA":true},"firstMatch":[{"browserName":"","platformName":"ios"}]}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"AutomationName":"XCUITest","app":"/Users/testmachine/Desktop/sachit/Payload2/FuturePay.app","browserName":"","deviceName":"iPhone Simultor","newCommandTimeout":100000,"platformName":"iOS","platformVersion":"11.3","udid":"C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C","useNewWDA":true},null,{"desiredCapabilities":{"AutomationName":"XCUITest","app":"/Users/testmachine/Desktop/sachit/Payload2/FuturePay.app","browserName":"","deviceName":"iPhone Simultor","newCommandTimeout":100000,"platformName":"iOS","platformVersion":"11.3","udid":"C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C","useNewWDA":true},"firstMatch":[{"browserName":"","platformName":"ios"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1536320582542 (17:13:02 GMT+0530 (IST))
[warn] [Appium] Could not parse W3C capabilities: 'deviceName' can't be blank. Falling back to JSONWP protocol.
[warn] [Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["AutomationName","app","browserName","deviceName","newCommandTimeout","platformName","platformVersion","udid","useNewWDA"]. Falling back to JSONWP protocol.
[info] [Appium] Requested iOS support with version >= 10, using 'xcuitest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[info] [Appium] Creating new XCUITestDriver (v2.84.0) session
[info] [Appium] Capabilities:
[info] [Appium]   AutomationName: XCUITest
[info] [Appium]   app: /Users/testmachine/Desktop/sachit/Payload2/FuturePay.app
[info] [Appium]   browserName: 
[info] [Appium]   deviceName: iPhone Simultor
[info] [Appium]   newCommandTimeout: 100000
[info] [Appium]   platformName: iOS
[info] [Appium]   platformVersion: 11.3
[info] [Appium]   udid: C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C
[info] [Appium]   useNewWDA: true
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {"AutomationName":"XCUITest...
[warn] [BaseDriver] The following capabilities were provided, but are not recognized by appium: AutomationName.
[info] [BaseDriver] Session created with session id: c91ae8cd-4198-40c1-944b-93b3000f9a80
[debug] [XCUITest] Current user: 'testmachine'[debug] [XCUITest] Xcode version set to '9.3' (tools v9.3.0.0.1.1521514116)
[debug] [XCUITest] iOS SDK Version set to '11.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1536320583369 (17:13:03 GMT+0530 (IST))[info] [iOSSim] Constructing iOS simulator for Xcode version 9.3 with udid 'C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C'
[info] [XCUITest] Determining device to run tests on: udid: 'C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C', real device: false
[info] [BaseDriver] Using local app '/Users/testmachine/Desktop/sachit/Payload2/FuturePay.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1536320584625 (17:13:04 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/Users/testmachine/Desktop/sachit/Payload2/FuturePay.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/Users/testmachine/Desktop/sachit/Payload2/FuturePay.app': 'com.futuregroup.futurepay'
[debug] [BaseDriver] Event 'resetStarted' logged at 1536320584626 (17:13:04 GMT+0530 (IST))[info] [XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1536320584800 (17:13:04 GMT+0530 (IST))
[debug] [XCUITest] Starting log capture for iOS Simulator with udid 'C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C', using 'xcrun simctl spawn C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C log stream --style compact'[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1536320585411 (17:13:05 GMT+0530 (IST))
[info] [XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSSim] Matched 1 Simulator cache item for cleanup: /Users/testmachine/Library/Developer/CoreSimulator/Devices/C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C/data/Library/Caches/com.apple.mobile.installd.staging
[debug] [iOSSim] Setting preferences of C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C Simulator to {"ConnectHardwareKeyboard":false}
[debug] [iOSSim] Setting common Simulator preferences to {"ConnectHardwareKeyboard":false}[debug] [iOSSim] Updated C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C Simulator preferences at '/Users/testmachine/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C":{"ConnectHardwareKeyboard":false}},"ConnectHardwareKeyboard":false}[debug] [iOSSim] The count of running Simulator UI client instances is 1
[info] [iOSSim] Both Simulator with UDID C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C and the UI client are currently running
[debug] [BaseDriver] Event 'simStarted' logged at 1536320587575 (17:13:07 GMT+0530 (IST))
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[warn] [XCUITest] *********************************
[warn] [XCUITest] Simulator architecture appears to be unsupported by the '/Users/testmachine/Desktop/sachit/Payload2/FuturePay.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[warn] [XCUITest] Don't be surprised if the application fails to launch.
[warn] [XCUITest] *********************************[debug] [XCUITest] Installing '/Users/testmachine/Desktop/sachit/Payload2/FuturePay.app' on Simulator with UUID 'C5CAF5B7-82C2-4074-8DC5-A37A5F833F3C'...[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1536320601453 (17:13:21 GMT+0530 (IST))[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.futuregroup.easydayrealstate application","sessionId":"7FA49BE4-70B2-49C6-A50D-887DBCCAC6A0","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1536320648582 (17:14:08 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.futuregroup.easydayrealstate","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
