### ISSUE TITLE
Does Appium desktop automatically update node modules of Appium server such as appium-android-driver or appium-xcuitest-driver?

### ISSUE THREAD

**Issue by qual** [appium/appium#8615]
Can someone please explain the Appium architecture from release and update perspective ?

We know that Appium desktop installs all the required node modules on its own.

Does Appium desktop update also handle the update of its node modules in its beta or stable releases.?
OR 
Are we supposed to update node modules manually using npm?

**It would be great if some high level documentation on Appium's deployment architecture and how to perform product updates is shared.**

**Comment by mykola-mokhnach** [comment]
Appium desktop contains all the server modules inside the package and they are updated together with the application itself. However Appium server (especially beta branch) is updated much more often than UI application. 

In genera,l Appium Desktop application was NEVER designed to be used in production environment and is only suitable for debugging and automated test creation purposes. Production automation server should always use Appium server binaries installed from Node repository (for example using NPM tool).

**Comment by qual** [comment]
OK. Thanks. just to confirm my understanding, suppose If Appium desktop 1.0.0 is deployed with appium-xcuitest-driver 2.27 and Appium desktop is updated to 1.0.2-beta, or 1.1 stable version and lets say, appium-xcuitest-driver 2.28 stable is out, Appium desktop 1.1 update will contain appium-xcuitest-driver 2.28
Is my assumption correct ?

**Comment by mykola-mokhnach** [comment]
> So in this case, Appium desktop update (to 1.1-stable) will contain appium-xcuitest-driver 2.28
Is my assumption correct ?

I don't know such details, but I know a person who knows :)
@imurchie 

> Also, If I don't want to wait for Appium desktop update, can I manually update appium-xcuitest-driver module using npm ?

Yes you can and you should. But is would be better to update not only this driver, but the whole Appium,  since new changes may have cross-module dependencies.

**Comment by imurchie** [comment]
Versions of `appium-desktop` are tied to a particular version of `appium` (the server). And particular versions of `appium` have a set of drivers that are tied down to particular versions when the server is published (unless the version is a "beta", in which the drivers are set at install-time instead of publish-time).

So it is not that the latest driver will be there for a fresh install of the server inside the desktop application, unfortunately (this is done because sometimes there are changes that need coordination, as Mykola mentioned, and so we don't want them updating willy-nilly). If the latest driver is needed, installing the latest "beta" release (which is possible with `npm uninstall -g appium && npm cache clean && npm install -g appium@beta`) is the way to go.

I'm not entirely sure how to update the server and have the `appium-desktop` app use it.

**Comment by qual** [comment]
Thanks @imurchie for clarifying. So this means that we have 2 approaches with the Appium installation and updates.

1. Don't use Appium desktop and use Appium (server) command line version. Update Appium using npm.

2. Use Appium Desktop and be dependent on it for Appium updates. Update of Appium Desktop stable will also update the Appium version (Not necessary to Appium stable version?)

Could you please confirm if above 2 points are correct ?

**Comment by imurchie** [comment]
Yes.

**Comment by dpgraham** [comment]
There's also option 3. Use the command line version of Appium and then point Appium Desktop to the command line version

(see https://github.com/appium/appium-desktop/issues/116 for instructions)
