### ISSUE TITLE
New Appium didn't work for old Script which working on appium1.4

### ISSUE THREAD

**Issue by vpkhachane** [appium/appium#8616]
I have written some Test Cases and I have successfully executed these test cases by using appium 1.4 . But now i have download latest appium (Version: 1.0.2-beta.2) set up and installed it and try to execute script but the script is not working. Please help me.

**Comment by mykola-mokhnach** [comment]
Since iOS 9.3 Apple introduced XCTest as a replacement for instruments automation framework. Many things works differently now. Appium tries to make the switch smooth, but there are some things mandatory to change. Read https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md for more details.
