### ISSUE TITLE
why appium delete find_by_name,if I want to find element by name,how?

### ISSUE THREAD

**Issue by melissalu** [appium/appium#8749]
I use appium a long time,a lot of case find by name,how I find this element?why delete

**Comment by gkvappium** [comment]
This was deprecated long back. You can use something like this wherein you pass the name with the XPATH

//XCUIElementTypeStaticText[@name='name of the element']

**Comment by mykola-mokhnach** [comment]
By.name locator has been replaced with MobileBy.AcccessibilityId, which better reflects the purpose of it in mobile environment. 

> This was deprecated long back. You can use something like this wherein you pass the name with the XPATH.

Try NOT to use xpath locators for with XCTest-backed automation, since these are not natively supported and thus slow. It is highly recommended to use only native-supported locators, like accessibility id, class name and predicate. Read https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md for more details.
