### ISSUE TITLE
Android: UIAutomator command fails by server but action happens correctly

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#8841]
## The problem

when i what to scroll like: "new UiScrollable(new UiSelector()).scrollForward()" then scroll happens correctly BUT server gives error. as work around i just added try catch and continue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.6beta
* Last Appium version that did not exhibit the issue (if applicable): unkown
* Desktop OS/version used to run Appium: mac OS 10.12.4
* Mobile platform/version under test: Android
* Real device or emulator/simulator: real

## Details

driver.findElement(MobileBy.AndroidUIAutomator(
                        "new UiScrollable(new UiSelector().resourceIdMatches(\".*id/view_payment_form\")).scrollForward()"));

-> 

org.openqa.selenium.UnsupportedCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. (WARNING: The server did not provide any stacktrace information)
...

*** Element info: {Using=-android uiautomator, value=new UiScrollable(new UiSelector().resourceIdMatches(".*id/view_payment_form")).scrollForward()}

**Comment by dpgraham** [comment]
Can you provide the Appium logs?

**Comment by amedvedjev** [comment]
@dpgraham here is full log https://gist.github.com/amedvedjev/d7121f534800a6fa89f91c4e3dc92bab

**Comment by dpgraham** [comment]
Thanks @amedvedjev.

This is where the exception is being thrown:

https://github.com/appium/appium-android-bootstrap/blob/b67e1d2dee0f8fea79f6ee375b9f6cf3954ff174/bootstrap/src/io/appium/android/bootstrap/handler/Find.java#L370

Appium passes the UiSelector text into `uiAutomatorParser.parse` and then logs any exceptions that are thrown

In your case, it looks the exception is `methods must return UiScrollable or UiObject instances` which makes me think that you need to refactor your UiSelector so that it returns a UiScrollable instance, or to just keep using your workaround.

I'm going to close this though because there isn't anything to fix on Appium.
