### ISSUE TITLE
Appium 1.6.5 performance is very slow for iOS

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium#8894]
I recently upgraded to Appium 1.6.5 and have noticed that the performance is extremely slow.

In another post, they suggested that the issue is with the xpaths I was using. So we migrated all our xpaths to iOS Predicates or Class chains. But the performance is still slow compared to Appium 1.6.4

We are automating a Hybrid app on iOS 10.2.1

**Comment by SrinivasanTarget** [comment]
@poorvikamahesh Can you provide more information in ticket, which xcode version and iOS version both the appium versions ran your scripts, Logs from both versions, etc. .

**Comment by dpgraham** [comment]
Which version of XCode are you using?

**Comment by dpgraham** [comment]
This is a known issue. We're looking into improving XPath performance. I think it's a WebDriverAgent problem.

**Comment by djwgit** [comment]
@dpgraham 
generally, locating element using xpath is slow, 
this is usually happen when the screen has a complicate ui structure, say, a long list..
while, in interactive arc mode, when `source`, it returns the tree structure not that slow...while when do a xpath search, it takes so long... don't think the xml query should be that slow???  
you mention, it is webdriver agent problem... just curious, the improvement is on the way, soon?  seems this is an issue bother most of us using appium... thanks...

**Comment by jlipps** [comment]
@djwgit doing an xpath search on xml is not slow. linking the found xml node with the actual automation node is a much bigger problem that potentially involves recursively walking a hierarchy. that's what's slow.

**Comment by ptsiakos77** [comment]
I agree with @poorvikamahesh the performance of Xpath locator in appium 1.6.5 and up (including beta versions) is significant lower. In some cases in long list is up to 60 times slower!!!. 
Is there some significant change regarding XPath from 1.6.5 and after.? This fact is very strange since Xpath was not very fast but not even close to what we experience with 1.6.5

**Comment by mykola-mokhnach** [comment]
Version 1.6.5+ is different, because it includes WDA snapshot, where generated source includes _visibility_ attribute. Previously it was not included because of performance and stability reasons.

Element visibility "calculation" in XCTest is quite painful and expensive operation. And, since xpath lookup is not supported natively, it is necessary to build the whole UI hierarchy tree (which is more or less fast) and calculate attributes for each node (which is the slowest operation, especially for _visible_ attribute, and heavily depends on the actual count of nodes in the tree/accessibility elements). Then we execute xpath query on this generated document (fast operation) and match the found item(s) to the existing accessibility object(s) (was slow before, but now the performance of this operation is quite OK).

That's why I would only advice to use xpath for really complicated locators, where usage of advanced  query features, like functions and axes, cannot be avoided. And even in that situation one has to think about redesigning his locator and replacing with one or multiple class chain/predicate/id locators, which are supported natively and don't need the source tree to be rebuilt/attributes reread every time when a lookup request is executed.

**Comment by wsndy163** [comment]
https://github.com/wsndy163/WebDriverAgent
修复swipe引起的列表卡顿问题
