### ISSUE TITLE
Tap action is not firing any event on ionic2 application.

### ISSUE THREAD

**Issue by MajdAlyaseer** [appium/appium#8905]
I have a problem with touch actions on ionic 2 application on both android and IOS devices.
I'm using appium with selenium only (without protractor) I've tried to simulate the tap on a button but neither "tap" nor "click" actions are working, i've tried the below:
- Using selenium: driver.findElementByCssSelector("xxx").click();
- Using JS: document.getElementById("xxx").click();
- Using touch action: TouchAction touchAction = new TouchAction(driver);
	                             touchAction.tap(driver.findElementByCssSelector("xxx")).perform();
- I have errors when using JS hammer event.

**What else can i use to tap on the button?**

**Environment:**
* Appium version : 1.6.4
* Desktop OS/version used to run Appium: - Mac with IOS 10.3.1
                                                                         - Windows with android 5.1.1
* Node.js version : v7.3.0
* Test on real device
* Mobile application: Built with ionic2 / Angular 2

**Comment by mykola-mokhnach** [comment]
Try to perform tap in native context. Note, that css selectors cannot be used in this context.

**Comment by MajdAlyaseer** [comment]
@mykola-mokhnach  Thanks for your suggestion, but the button is in the webview context so i can't access it in the native context and (org.openqa.selenium.NoSuchElementException) error is displayed if i switch to the native.

**Comment by mykola-mokhnach** [comment]
You can remember button coordinates and then perform tap by these coordinates

**Comment by MajdAlyaseer** [comment]
@mykola-mokhnach Still have no luck, moreover, i need to run the script on different devices with different size so that won't be accurate.

**Comment by mykola-mokhnach** [comment]
I'm not talking about putting coordinates to constants. 
Nevertheless, it might be the click happens, but it is not delivered to application controls because of, for example, some invisible top layer over them. I'd add some global click listener to the web page under test to check where the click actually happens and to which controls the corresponding event is fired.

**Comment by MajdAlyaseer** [comment]
Thanks for your effort, the below js code worked with me perfectly:
var de = ng.probe(loginBTN);
de.triggerEventHandler('tap');

**Comment by jlipps** [comment]
@MajdAlyaseer the issue is that your app is probably sensitive to a particular event, not the one generated by Appium's default javascript event firing mechanism. This is a limitation of using the Selenium Atoms for web automation. You have two solutions:

1. Fire the event your app is listening for yourself (as you figured out)
2. Set the `nativeWebTap` capability to true. This calculates the element coordinates and performs a native touch event, which usually ends up doing the right thing inside safari.
