### ISSUE TITLE
Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65.

### ISSUE THREAD

**Issue by SamyQAZ** [appium/appium#8910]
## The problem

Xcode build failure with error code 65.
I am able to run the tests few times, later leading to error code 65.
Once restart device, tests runs successfully few times followed by error code 65.
I am using iPhone 5(10.3.2), Xcode 8.3.3, Appium 1.1.0-beta.4
Also, my setup mentioned https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md in here is properly done.
Please help to share the solution.

## Environment
Real device- iPhone 5(10.3.2)
Xcode 8.3.3
Appium 1.1.0-beta.4
Running test on MacOS Sierra(10.12.5)
node.js- v7.10.0

## Details

If necessary, describe the problem you have been experiencing in more detail.

Appium + Xcode logs
https://gist.github.com/SamyQAZ/7f50ed6d2dc7243a61e74ab6aedca0ac#file-appium_xcode-logs

**Comment by mykola-mokhnach** [comment]
> [Xcode] 2017-07-25 11:56:49.631 xcodebuild[8085:43376470] Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(

The problem lies here. This is known XCTest issue and it happens after WDA client is restarted several times on a real device. Also, it happens more often on older 32-bit devices like iPhone5. 
Rebooting the device helps, but only for a while. You can also try to run WDA server [separately](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md) to avoid unexpected restarts.

See https://github.com/facebook/WebDriverAgent/issues/507 for the refernce.

Closed as duplicate

**Comment by swachhab** [comment]
This is code signing issue, it happens when setup for appium have some problem in configuring webdriver-agent in appium library, you can even configure webdriver-agent with free apple developer account as well, follow these steps in video: https://www.youtube.com/watch?v=dyijACVRQOc It worked for me, hope it will help everybody here!
