### ISSUE TITLE
Could not detect idle state.

### ISSUE THREAD

**Issue by bennid** [appium/appium#8929]
## The problem

The issue is not visible in tests or ui, but when viewing logcat we're inundated with the following stack over and over

`W/UiAutomatorBridge( 5793): Could not detect idle state.
W/UiAutomatorBridge( 5793): java.util.concurrent.TimeoutException: No idle state with idle timeout: 500 within global timeout: 10000
W/UiAutomatorBridge( 5793): 	at android.app.UiAutomation.waitForIdle(UiAutomation.java:590)
W/UiAutomatorBridge( 5793): 	at com.android.uiautomator.core.UiAutomatorBridge.waitForIdle(UiAutomatorBridge.java:96)
W/UiAutomatorBridge( 5793): 	at com.android.uiautomator.core.UiAutomatorBridge.waitForIdle(UiAutomatorBridge.java:91)
W/UiAutomatorBridge( 5793): 	at com.android.uiautomator.core.QueryController.findAccessibilityNodeInfo(QueryController.java:143)
W/UiAutomatorBridge( 5793): 	at com.android.uiautomator.core.QueryController.findAccessibilityNodeInfo(QueryController.java:138)
W/UiAutomatorBridge( 5793): 	at com.android.uiautomator.core.UiObject.findAccessibilityNodeInfo(UiObject.java:168)
W/UiAutomatorBridge( 5793): 	at com.android.uiautomator.core.UiObject.waitForExists(UiObject.java:848)
W/UiAutomatorBridge( 5793): 	at com.android.uiautomator.core.UiObject.exists(UiObject.java:899)
W/UiAutomatorBridge( 5793): 	at io.appium.android.bootstrap.utils.TheWatchers.isDialogPresent(TheWatchers.java:51)
W/UiAutomatorBridge( 5793): 	at io.appium.android.bootstrap.utils.TheWatchers.check(TheWatchers.java:42)
W/UiAutomatorBridge( 5793): 	at io.appium.android.bootstrap.SocketServer$1.run(SocketServer.java:140)
W/UiAutomatorBridge( 5793): 	at java.util.Timer$TimerImpl.run(Timer.java:284)`

## Environment

* Appium version: 1.6.4
* Node.js version: 6.10.3
* Mobile platform/version under test: Android api-22
* Real device or emulator/simulator: Emulator
* Appium CLI

## Details

I saw this error listed as https://github.com/appium/appium/issues/5764.  But the answer was upgrade to appium 1.5.0

## Link to Appium logs

https://gist.github.com/bennid/7e512d17878c13cf59bddf6d88324ad9

## Code To Reproduce Issue [ Good To Have ]

I have not been able to narrow this down to a general reproduction issue, and my code is large and proprietary unfortunatelly.  I will attach more information if I get down to it

**Comment by mykola-mokhnach** [comment]
As far I I remember UIAutomator-based driver is waiting for the UI to be in idle state with 10 seconds timeout before starting element lookup. I assume it is done this way because elements state might be unstable while on-screen transition animations are running. This might become a problem if your app has some constant background animations that never stop. 
You may try to switch to UIA2 driver as a workaround.

**Comment by jlipps** [comment]
As @mykola-mokhnach I would try to switch to UiAutomator2. This error is logging from the UI watching code in our UiAutomator1 driver, but unfortunately Google isn't really supporting UiAutomator1 anymore. Otherwise, you could try commenting out the Watcher code in the appium-android-bootstrap project and repackaging Appium. That should silence these errors, though you wouldn't get the benefit of the dialog checking that comes with the watchers.

**Comment by Klouse** [comment]
Hello, 
I am experiencing this same issue when using UiAutomator2 with Android on Appium 1.6.5. There is a constant background animation that I assume is causing the error. Would there be another work around since I am already on UiAutomator2?

**Comment by jlipps** [comment]
@sravanmedarapu do you have any ideas why this logging is spewing out during animations?

**Comment by ajeeshvl** [comment]
Experiencing similar issue in video player. Any work arounds?
https://github.com/appium/appium/issues/9147

**Comment by Mcfli** [comment]
Also having this issue using UiAutomator2 with Android running Appium 1.7.1.  Are there any updates on this?

**Comment by Klouse** [comment]
Any updates here? This has been plaguing us for months.

**Comment by shuoyoung** [comment]
I change "appium-uiautomator2-server/app/src/main/java/io/appium/uiautomator2/utils/Device.java:58" to "getUiDevice().waitForIdle(**_3000_**);",  and generate apks to replace the appium's. 

Now most of actions can start within 5 seconds with warning "java.util.concurrent.TimeoutException: No idle state with idle timeout: 500 within global timeout: **_3000_**".

But it doesn't work for  key event such as "back" and "home"  because they use different code.

Maybe this will help someone.

**Comment by mykola-mokhnach** [comment]
The feature works for UIAutomator2. I don't think that we are going to revisit this implementation for UIA1, since it is obsolete
