### ISSUE TITLE
Unable to set URL in native context on iOS real device

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#9066]
## The problem
Attempting to open a deep link from a native app context on a real device, per 1.6.5 release notes. 

`Allow setting url in native context, for opening deep links.`

When i call driver.get(deeplink), simctl returns an error saying my UDID is an invalid device. Seems it's assuming my target device is a simulator.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.6-beta.4
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac Sierra
* Node.js version (unless using Appium.app|exe): 8.4.0
* Mobile platform/version under test: iOS 10.3.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
I changed deeplink and udid. They are both valid, just removed them for privacy.
https://gist.github.com/jamesvanhorn/a43f9865a688077be1f0affe17b08a2a

## Code To Reproduce Issue [ Good To Have ]
driver.get("some deeplink");

**Comment by imurchie** [comment]
Hmm. That does seem like an issue. Investigating.

**Comment by imurchie** [comment]
Yes, currently this only supports simulators. Not sure how to do this on real devices, but I'll add it to our backlog.

**Comment by mykola-mokhnach** [comment]
The fix has been merged to Appium beta and is available in xcuitest driver since version 2.46.0

**Comment by jamesvanhorn** [comment]
Maybe its something with our app, but this isnt working after updating to 2.46.0. The server just returns a 500 error saying failed to open URL <app>://targetScreen. It did work once randomly, however tapping on the "open" button from within the app didnt redirect the user to appropriate page. I tried background the app first, then setting the url, but that doesn't work either. Maybe this is best left as a simulator only test?

**Comment by mykola-mokhnach** [comment]
It would be useful to see the updated log. There is no magic there - we just pass the given URL to the standard UIApplication's openUrl method

**Comment by CathyUhhh** [comment]
@mykola-mokhnach @imurchie hi,I call driver.get(urlstring),that doesn't work on iOS real device,but simulator works well.
I had update Appium beta,my "appium-xcuitest-driver/lib/commands/general.js" contains 
```
commands.setUrl = async function (url) {
  if (this.isRealDevice()) {
    return await this.proxyCommand('/url', 'POST', {url});
  }
  return await iosCommands.general.setUrl.call(this, url);
};
```
this is error msg:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Failed to open urlString(WARNING: The server did not provide any stacktrace information) 

at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:364)

**Comment by mykola-mokhnach** [comment]
@CathyUhhhIt looks like this is known XCTest limitation for real devices. See https://stackoverflow.com/questions/26224290/using-an-url-scheme-in-xctestcase for more details.

**Comment by jamesvanhorn** [comment]
Thanks for finding that @mykola-mokhnach We know for sure now this feature is simulator only.

**Comment by yangheng** [comment]
@mykola-mokhnach  no ! I tried on real device ,the feature is OK .But on other mac ,it's not OK . Do you install node by n or nvm ?

**Comment by CathyUhhh** [comment]
😨😨😨😨Did you tried ```driver.get(urlstring)```to implement ```open URL```in iOS？？？

**Comment by yangheng** [comment]
@CathyUhhh  Yes ,I did.

**Comment by yangheng** [comment]
@mykola-mokhnach @CathyUhhh  It does no matter about nvm or n .  Do you install java JDK before install appium ? Because  I tried failed on two MAC that don't hava Java environment，and I test success on three MAC that have java JDK .

**Comment by CathyUhhh** [comment]
@yangheng sure.I'm using java-client 5.0.0-BETA9..

**Comment by yangheng** [comment]
Maybe you can try use javascript as client . I used npm to install appium@1.6.5 ,first of all ,your mac should had JDK . And  every api will be done. I had tested success.  [There is my auto install script](https://github.com/yangheng/auto-ui-test) 。 
First , you should install nodejs ,then you should upgrade npm to npm@latest .
After these two steps,you should clone my project and cd &,  command' npm run init'

```javascript
npm run init
```
This script will install appium dependent packages。
I hope these will help you

**Comment by degamer106** [comment]
I'm trying to deep link to my Expo app (native context) using Appium 1.7.2 and wd.js 1.6.1 but when I call driver.get('exp://localhost:80'), the Appium server is throwing an exception saying that "url.match()" is not a function.

**Comment by degamer106** [comment]
Any one else run into this issue?

**Comment by mykola-mokhnach** [comment]
@degamer106 Please report your issue to Appium issues along with the full server log. Probably, it can be fixed

**Comment by degamer106** [comment]
`import wd from 'wd';
import { UrlUtils } from 'xdl';

jasmine.DEFAULT_TIMEOUT_INTERVAL = 180000;
const PORT = 4723;
const config = {
  platformName: 'iOS',
  deviceName: 'iPhone Simulator',
  xcodeOrgId: '58HKZG8YVV',
  xcodeSigningId: 'iPhone Developer',
  updatedWDABundleId: 'com.trinet.WebDriverAgentRunner',
  automationName: 'XCUITest',
  app: '/Users/alin/.expo/ios-simulator-app-cache/Exponent-2.3.0.app'
};

let url;
const getAppUrl = async () => {
  if (!url) {
    url = await UrlUtils.constructManifestUrlAsync(process.cwd());
  }

  return url;
};

const driver = wd.promiseChainRemote('localhost', PORT);

beforeAll(async () => {
  await driver.init(config);
  await driver.sleep(2000); // wait for app to load
  await driver.get(getAppUrl(), (err) => console.log(err));
});

...`

Server Log:
https://gist.github.com/degamer106/7c03b0c5af1c9a7b43c873b7dad3e153.js

I tried bringing the Automation configuration from another testing framework, Detox, to Appium found in this blog: https://medium.com/async-la/e2e-testing-react-native-with-detox-screenshots-595146073863.  Basically, it works by:

1. Running the Expo app on the Simluator to generate a .app file in the ~/.expo/... folder
2. Copying over that Expo.app file over to the Automation project directory
3. Executing the detox script
4. Script starts by getting the URL that the expo app is being run on (i.e. exp://localhost:19000) using UrlUtils from the xdl npm library.
5. Calls the detox's device.launchApp({ url: url }) method to deep link into the Expo.app file and open your RN native app within Expo.
6. Executes the test cases

The main issue for the Appium script is that the deep linking using the latest version of Appium and wd.js fail when being executed in the Native Context on the iOS sim.  This works perfectly in Detox.  However, our company has a lot of work invested into Appium and we'd like to use this instead of picking up another framework.

**Comment by mykola-mokhnach** [comment]
@degamer106 Please create a separate issue for it, so it is easier to track it.

Regarding deep linking support - there is a known bug in Apple's XCTest, which prevents to open such links from native context. We've created a workaround for it in appium@beta by passing such link to Siri service, so it can find a corresponding app, which is able to open it.

**Comment by mykola-mokhnach** [comment]
> [HTTP] --> POST /wd/hub/session/fc47841c-0721-409c-9214-c44428cc9cec/url {"url":{"_40":0,"_65":0,"_55":null,"_72":null}}

Are you sure the URL value passed to Appium is correct?

**Comment by a-en** [comment]
@mykola-mokhnach could you clarify the current state of this functionality - is deep linking expected to work on real iPhone with iOS >= 11? I have Appium ver 1.8.0 and iPhone with iOS 11.2, but it doesn't work in expected way and driver.get(url) does nothing in fact.

**Comment by mykola-mokhnach** [comment]
@a-en 

It is only guaranteed to work on Simulator. On real devices `openUrl` method has a known bug, which prevents it to work properly: https://forums.developer.apple.com/thread/25355

**Comment by a-en** [comment]
@mykola-mokhnach thanks for reply. You have also mentioned workaround with Siri - is it expected to be available with any further release or it doesn't help to overcome the original issue?

**Comment by Nasen** [comment]
@mykola-mokhnach I have tested on iOS12 real device with Appium@1.8.2beta, it send commands "Open {url}" to Siri, but it can not open safari. You may need to change the command to "Open Safari {url}", it will auto launch Safari.

**Comment by mykola-mokhnach** [comment]
deep links are not always need to be opened by Safari. Try to change it locally and check if the change works for your app

**Comment by MrajaTauseef** [comment]
I am unable to open deeplink on IOS native app with real device.But deeplinks are opening fine on simulator.is there any solution for deeplinks to run on real devices.Please help
Appium version 1.8.1
Device iphone 6
java client 6.0.

**Comment by tritethunder** [comment]
@mykola-mokhnach I am trying to use driver.get(URL) in 1.9.1 and still facing the issue when running on the real device is there any workaround for this.

**Comment by emzubair** [comment]
Hi!
I'm using appium version `1.15.1`, can't open url on real device, works fine on simulator but or real device it opens `siri`. Is there any alternate ?

**Comment by khubaib321** [comment]
On iOS Real device it looks like we can't open deep-link using `driver.get(...)` method. We have to open Safari and enter the URL in it. Then click on the Open dialog button which will switch to back AUT and deep-link effect will be applied.

**Comment by satoshinosekai** [comment]
"Then click on the Open dialog button which will switch to back to AUT and deep-link effect will be applied."
How can do it programmatically? :)

**Comment by khubaib321** [comment]
@satoshinosekai If you see the `Open` button when you open url in safari, then you can do it like this: In the url string you can directly use your app bundle name with the url path.

For example, instead of opening this url `https://www.example.com/path/to/url`,
you can try opening safari with a url like this `<app_bundle_name>://path/to/url` and this should go straight into the app.

If this doesn't work then your only option might be to inspect the safari page and get the `Open` button by ID/Xpath and click on it.

Hope this helps.

**Comment by jlipps** [comment]
There is an Appium Pro article on this as well: https://appiumpro.com/editions/84-reliably-opening-deep-links-across-platforms-and-devices

**Comment by tgthao** [comment]
HI everyone, i'm testing deeplink. when i use add to test, the app don't need login. But when i testing deeplink with code in automation with appium. The app request login. How can i resolve it
  HashMap<String, String> deepUrl = new HashMap<>();
                deepUrl.put("url", url);
                deepUrl.put("package", "com.fishidy.debug");
                driver.executeScript("mobile: deepLink", deepUrl);
