### ISSUE TITLE
This operation is only execute once per element in iOS phone

### ISSUE THREAD

**Issue by xiaolong520lei** [appium/appium#9115]
## The problem

firstly，this is a number keyboard in my test page.(please see the attachment)
i want to enter a string of numbers (et. 755009895)
but when i execute click event that can only enter 75098. 
i have to see the appium log ,there is not any error occurs。

below is my python script 👍:
bikeNo = '755009895'
    def enter_bikeNo(self):
        for i in .bikeNo:
            driver.find_element_by_accessibility_id(i).click()
            sleep(1)

## Environment
appium 1.6.5
iphone 5s   10.3

so please help me solve the problem ,thanks!

**Comment by mykola-mokhnach** [comment]
Please attach Appium log and the output of driver.getPageSource command.

**Comment by xiaolong520lei** [comment]
thank for you feedback !
please see the attach files !
[page_source.txt](https://github.com/appium/appium/files/1262716/page_source.txt)
[appium_log.txt](https://github.com/appium/appium/files/1262719/appium_log.txt)

**Comment by mykola-mokhnach** [comment]
Does it work properly if you use the app manually? 
What if you tap by absolute coordinates instead of sending click to an element?

BTW, search by xpath is slow with XCTest. Locate the necessary by accessibility id and put it into a cache to speed up the execution.

**Comment by xiaolong520lei** [comment]
it's worked by tap app manually.
i have not try to  use absolute coordinates, but i have use accessibility id and the effect is the same。
this keyboard is used system keyboard(the keyboard type is Key), so i think when click this keyboard will have some restrictions or other. but i don't know.

by appium log i can't analyze the reason!
But thank you all the same！

**Comment by rajfidel** [comment]
Hi @xiaolong520lei  The appium_log.txt attached shows that the numbers "7" etc are being recognized using xpath with name attribute, and not really using accessibility identifier (perhaps accessibility is not implemented?). It looks like none of the duplicate keypad keys (for example the second 5, second 0 etc) are being clicked because the second findElement is probably finding the element '5' on the field where clicked keypad elements are displayed. So if you enter 75(5)0(0)98(9)(5), the numbers within braces are probably being found as an element before the keypad key element since these keys within braces have already been entered? If you get the page source of the page after you run the code snippet you mentioned in the original post, it would clarify the issue.

**Comment by xiaolong520lei** [comment]
Hi @rajfidel  ,thank you very very much!
you are right, it's really exist duplicate accessibility id(such as in keyboard "1" and input field "1" is same)， so it's no problem now when change the input field number of accessibility id.
thanks a lot !
