### ISSUE TITLE
iOS 10.x + Appium 1.7.0beta + iPhone SE PageSource has error value 'AX error -25205' for some attribute values

### ISSUE THREAD

**Issue by rajfidel** [appium/appium#9174]
## The problem

PageSource has issues on iPhone SE + Appium 1.7.0 beta + iOS 10.x. It displays some of the values as 'AX error -25205'
Non-iPhone SE + iOS 11 + Appium 1.7.0 beta works fine. 
Couldn't check iPhone SE with iOS 11 since I do not have a device with this configuration to check.
iPhone SE + Appium 1.6.5 + iOS 10.x works fine as well.

## Logs

The following logs were captured on the iOS Settings app (com.apple.Preferences)

### On Appium 1.7.0 beta

iPhone 6s, Appium Logs [here](https://gist.github.com/rajfidel/6e97801e8281b799c20ddea7f5fb8f03), Page Source [here](https://gist.github.com/rajfidel/f8eea115ec8e4168b4e62785901f637f)
iPhone SE, Appium Logs [here](https://gist.github.com/rajfidel/476dbd829ff3cc07b55b3b0327987935), Page Source [here](https://gist.github.com/rajfidel/c83a080e985a2f70ea8bee4d75277eb2)
**Confirmed on another iPhone SE as well to be the same case.**

From the above logs can be seen that only iPhone SE exhibits this issue with Appium 1.7.0 beta.

### On Appium 1.6.5

iPhone SE, Appium Logs [here](https://gist.github.com/rajfidel/21cff8fdf4699fa22140833efa456748), Page Source [here](https://gist.github.com/rajfidel/1b5b929739b83c701acd56bb61e7d183)

From the above logs can be seen that iPhone SE does not exhibit this issue with Appium 1.6.5

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.1.4
* Mobile platform/version under test: 10.2.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Please report the issue to WebDriverAgent project. There is nothing we can do about it on Appium side.

**Comment by rajfidel** [comment]
Reported issue [here](https://github.com/facebook/WebDriverAgent/issues/703)

**Comment by tfcardoso** [comment]
@mykola-mokhnach I tested several iOS10.X devices and although some errors are different in the end none can automate fully with XCode9.2 (mainly when on native iOS views).

Since marekcirkos closed the issue on WebDriverAgent project side with:
"Closing since this is iOS 10.x related issue on Apple side."

Shouldn't Appium have an indication that in order to obtain better results is advisable to have XCode8.X for iOS10.X and Xcode9.X for iOS11.X in this page (https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest.md#requirements-and-support) ?

This is because, although I'm stating that to a client that will be using iOS10 and iOS11, they claim that information doesn't match Appium requirements present on above page.

**Comment by mykola-mokhnach** [comment]
We don't know all the conditions, which cause this issue and I'm sure Apple will not care much about it since we use private API.

**Comment by tfcardoso** [comment]
Yes, that's why I say it would be nice if we have it as "advisable to have XCode8.X for iOS10.X" and not as mandatory requirement.

I'm aware that Apple would not care about it, probably even if we used public API, so... :)
