### ISSUE TITLE
Redirect from webview to native app within the app leads to errors when calling getContexts

### ISSUE THREAD

**Issue by lanzelot1989** [appium/appium#9320]
## The problem

After clicking a certain button my app redirects from a web view back to the native app context. However, after trying to call the available contexts an error is thrown and the actions fail.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: macOS 10.12.6
* Node.js version (unless using Appium.app|exe): 4.2.0
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Simulator (iPhone 6S)
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Here you can see the corresponding logs https://gist.github.com/lanzelot1989/941d2cdf3ac464d4139bc1baf112c77f

## Code To Reproduce Issue

In appium-dotnet-driver 
```
Driver.Context = Driver.Contexts.First(x => x.Equals("NATIVE_APP"));
// or
Driver.Contexts
```
leads to the problem after being redirected from a webview to the native app.

**Comment by lanzelot1989** [comment]
It seems that the problem is more generally reproducible when trying to change the context after the context has been changed to perform actions against a web view.

**Comment by lanzelot1989** [comment]
I was able to solve the problem by stopping a second Appium server that was running against the same simulator on a different port.

This has been no problem in the past, but seems to have become on after the mentioned Appium/XCode update.

Ticket can probably be closed.

**Comment by SergheiRidico** [comment]
**(can not tap Return to App button in Safari**
I faced the same issue after I had installed XCode9.
Test scenario:
1. tap the link in native app
2. check webview in safari browser
3. tap **Return to App** button in browser
4. check if user is back into application 

While using xcode 8.3.3, I could check elements from webview without using _ios-webkit-debug-proxy._
After I had installed xcode 9, my test failed because webview element was not found.
Then I started to use _ios-webkit-debug-proxy_ and I could locate webview element, but I could not tap **Return to App** button in browser. 
 Return to App button is present in PageSource and context switch works properly, but tap is not executed and I get NoSuchElementException.

**Comment by lanzelot1989** [comment]
It seems that a reinstall of XCode solved my problem. (I also created a new simulator before, but that did not have any effect with the old XCode).

**Comment by SergheiRidico** [comment]
@mykola-mokhnach what do you think about issue with Return to App button.
Could you please suggest me something.

**Comment by Aurel1981** [comment]
I think, I have the same issue with my real device iPad Air.

1-  Launch Safari
2- Go to url   => OK
3- Swipe on screen UP to DOWN then LEFT to Right to go to NATIVE_APP
=> When we try to click on an icon, icon is not seen by appium

=> Same issue with inspector
      When we refresh page on NATIVE_APP, Elements shown come from Safari browser and not NATIVE_APP.

In my code, I have no error when I use :  switch to context

Appium version (or git revision) that exhibits the issue: 1.7.1
Desktop OS/version used to run Appium: macOS 10.12.6
Mobile platform/version under test: iOS 10.3
Real device : iPad Air
Xcode 9
ios-webkit-debug-proxy 1.8


Same code works well on ios 10.3.3 and appium 1.6.5
xcode 8.3.2
