### ISSUE TITLE
[Android][1.7.1] Strings containing \n cannot be matched

### ISSUE THREAD

**Issue by welnanick** [appium/appium#9428]
## The problem

Strings that contain \n in them cannot be matched using any method in appium

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.5.0
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

In the Android app there are strings defined like so: `<string>word1\nword2</string>`. When trying to lookup a TextView containing that string I must do a partial match, only searching for `word1` or `word2`, as trying to search for `word1\nword2` does not match the TextView.

## Link to Appium logs

The string I am searching in the app contains sensitive information, so I can't post a log. If you want I can throw together a quick Demo App that reproduces the bug and post the logs from that.

**Comment by dpgraham** [comment]
Appium proxies through to Android UiAutomator selectors (see https://developer.android.com/reference/android/support/test/uiautomator/By.html for reference). The issue is likely that the Android library is matching it incorrectly.

For the element that contains the text `word1\nword2`, what is it's value (e.g.:  what does `System.out.println(element. getText());` log to the console)?

**Comment by welnanick** [comment]
Just checked in the debugger. `element.getText()` returns the value `word1\nword2`

**Comment by dpgraham** [comment]
Yeah if that matcher doesn't work I don't think we'll be able to make a workaround for it.

I assume you're using the `ByAndroidUiAutomator` selector? (http://appium.github.io/java-client/io/appium/java_client/MobileBy.ByAndroidUIAutomator.html)

**Comment by welnanick** [comment]
I am using `@AndroidFindBy(uiAutomator = "new UiSelector().text(\"word1\nword2\")")` in the java client, however I also am able to reproduce this issue using appium-desktop as well so I know it isn't the client. I have also tried xpath, `//android.widget.TextView[@text='word1\nword2']`, with no luck as well. Should I try to dig in the logs and see if appium is receiving the correct thing?

**Comment by welnanick** [comment]
Could this be causing issues?: `[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/1dce0cea-fc65-4bf7-bca7-70c366bf249c/elements] with body: {"strategy":"-android uiautomator","selector":"new UiSelector().text(\"word1\\nword2\")","context":"","multiple":true}`

Its escaping the \ in \n, which could be what's causing the issue.

**Comment by welnanick** [comment]
For reference this is what I typed into appium-desktop to search: `new UiSelector().text("word1\nword2")`

**Comment by welnanick** [comment]
@dpgraham Given my findings I really don't think it is an issue with the matcher, I think its due to appium escaping the \n when it shouldn't. What do you think?

**Comment by dpgraham** [comment]
@welnanick Yeah I think you're right. The string is being altered along the way.

I don't know when we'd be able to get to this issue, but if you're interested we do accept pull requests. My guess is that the problem is in this Java method https://github.com/appium/appium-uiautomator2-server/blob/84dfac17fd86d957c4cfd7c62005db7bc3540d65/app/src/main/java/io/appium/uiautomator2/handler/FindElement.java#L183

**Comment by welnanick** [comment]
I'll look into it when I have time! With any luck you'll see a pull request from me soon.

**Comment by mykola-mokhnach** [comment]
The xpath standard does not allow line breaks to be present in attribute values. Thus we replace these with question marks by default. So the lookup is still possible.
