### ISSUE TITLE
FindByImage Support

### ISSUE THREAD

**Issue by penguinho** [appium/appium#943]
From:
https://groups.google.com/forum/#!topic/appium-discuss/2AtfiTX3l-U

f one were to implement image recognition addon/support for Appium, this would be my thought on location strategy:
- a custom find by method/type if not retrofitting against the existing ones (XPath, CSS selector, ID/name).
- locator can be defined as path to archived image to find on screen
- if retrofitting location strategy, find by ID/name could be name of image relative to default image location (specified in some config file or hard coded) and find by XPath/CSS can be just an alias for providing path to full image path or relatvie e.g. "/myPathTo/Image.png", "C:\myPathTo\image.png".
- could also consider being able to provide the find by value as base64 encoded string of the actual image rather than specifiying an image path or name. At Appium side, the data is then decoded back to image (and saved to temp directory on local disk as needed) to be used for image recognition.
- for specifying image by path/name, it would be local to machine running Appium, unless we deviate from JSONWireProtocol and extend it with Appium specific commands, since there's no official API to send files from WebDriver client to server remotely besides what's used internally for sendKeys() for file uploads, and when sending over FirefoxProfile remotely as part of desired capabilities. Though one could consider defining a new desired capability option for say passing over a zip file of images to be used for image recognition, encoded as base64 - it is then decoded, unzipped and deployed to temp directory for use at Appium server side. Then the tests can reference images by name relative to the image archive sent over as part of desired capability.

On Sunday, July 28, 2013 8:28:43 AM UTC-7, Dan Cuellar wrote:
Shifting the conversation back to Sikuli briefly. I think it would be a very powerful add-on for appium to have some find and click this image sort of behavior. Some controls are not accessible (e.g maps, videos, etc.) and it'd be nice to have some sort of openCV-ish capabilities for when the accessibility layer is totally clueless.

**Comment by Simon-Kaz** [comment]
@amedvedjev have you got any sample code for this? I find this topic (OCR in Appium) very interesting and would like to join the research.

**Comment by amedvedjev** [comment]
@Simon-Kaz 
1) first need import opencv library (with Mac OS we used special - opencv-2.4.10-0.9.1-20141109.113201-4-macosx-x86_64.jar)
2) then we created 3 functions:

one is in loop calling second one for given amount of time
second finding region on screenshot
third taking screenshot (if it is in landscape mode also does image rotation)

public ScreenRegion getRegion(String targetFileLocation, int waitTime) { //time in sec
        //System.out.println("   getRegion for: "+targetFileLocation);
        int startTime;
        ScreenRegion region;
        startTime = getTimeInSec();

        if (targetFileLocation == null) {
            System.err.println("   no target file name");
            try {
                Thread.sleep(100);
            } catch (Exception e) {
            }
            return null;
        } else if (new File(targetFileLocation).exists() && !new File(targetFileLocation).isDirectory()) {
            do {
                try {
                    region = findRegion(targetFileLocation);
                    region.getCenter();
                    return region;
                } catch (Exception e) {
                    System.err.println("    no target image found in shot. retrying...");
                }
                try {
                    Thread.sleep(200);
                } catch (Exception e) {
                }
            } while (!checkTime(startTime, waitTime));
        } else {
            System.err.println("   file not exits: " + targetFileLocation);
            try {
                Thread.sleep(100);
            } catch (Exception e) {
            }
            return null;
        }

        return null;
    }

public ScreenRegion findRegion(String targetFileLocation) {
        Target target = new ImageTarget(new File(targetFileLocation));
        target.setMinScore(0.90); //0.7 default
        ScreenRegion screenRegion = new StaticImageScreenRegion(takeShot()).find(target);
        return screenRegion;
    }

    public BufferedImage takeShot() {
        for (int i = 0; i < 5; i++) {
            if (driver.manage().window().getSize().getHeight() > driver.manage().window().getSize().getWidth()) {
                System.out.println("   takeShot: portrait mode w: " + driver.manage().window().getSize().getWidth()
                        + ", h: " + driver.manage().window().getSize().getHeight());
                try {
                    return ImageIO.read(((AppiumDriver) driver).getScreenshotAs(OutputType.FILE));
                } catch (Exception e) {
                }
            } else {
                System.out.println("   takeShot: landscape mode w: " + driver.manage().window().getSize().getWidth()
                        + ", h: " + driver.manage().window().getSize().getHeight());
                BufferedImage image = null;
                try {
                    image = ImageIO.read(((AppiumDriver) driver).getScreenshotAs(OutputType.FILE));
                } catch (Exception e) {
                    System.err.println("    get screenshot failed.");
                }
                if(image!=null) {
                    //System.out.println("    original image height: "+image.getHeight()+", width: "+image.getWidth());
                    int diff = (image.getHeight() - image.getWidth());
                    diff = diff / 2;
                    //System.out.println("   diff: "+diff);

                    AffineTransform tx = new AffineTransform();
                    tx.rotate(Math.PI * 1.5, image.getHeight() / 2, image.getWidth() / 2);//(radian,arbit_X,arbit_Y)
                    AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_BILINEAR);
                    image = op.filter(image, null);//(source,destination)
                    //System.out.println("    rotated image height: "+image.getHeight()+", width: "+image.getWidth());

                    image = image.getSubimage(diff, diff, image.getWidth() - diff, image.getHeight() - diff);
                    //System.out.println("    result image height: "+image.getHeight()+", width: "+image.getWidth());
                    return image;
                }
            }
        }
        return null;
    }

**Comment by Simon-Kaz** [comment]
Sikuli has been "rebranded" as Sikuli X and so the API has changed. It is being rewritten, and while the required functionality isn't there yet, it's something to keep in mind, as regular sikuli-api is no longer maintained.

https://github.com/RaiMan/SikuliX-2014

From the looks of it, the API will be much cleaner and more readable, I'll keep updating this thread with my findings.

**Comment by 907howard** [comment]
Hi simon any update on the latest version of Sikuli API which can be integrated with appium on eclipse, i want to automate a android game so need help in this..

**Comment by 907howard** [comment]
Hello can any one guide here.. how should i use sikuliX on eclipse altogether with appium to automate games using image recognization...please help, I have sikulix ,from where i wil get the jar file so i can place it in the reference library.. can any body guide from scratch..

**Comment by daluu** [comment]
@907howard 

From the discussion so far, there doesn't appear to be any integration sample code of Sikuli (or even OpenCV) with Appium. You'll have to build your own. The closest was this comment: https://github.com/appium/appium/issues/943#issuecomment-76963366

For a novice, the best option to start with is treat Sikuli and Appium as separate tools/libraries but use them together in your test (code) to achieve what you want to test. e.g. create an instance of Appium (driver) and an instance of Sikuli. In the test, have Appium do it's thing, then when you need Sikuli help because of Appium limitations, run the Sikuli code before resuming Appium code. When you get something like that working, then you can think about merging the codebase (if you're good enough to edit/hack Appium code).

That suggestion works best if you work with Appium (and Sikuli) in Java, or Python/Jython, maybe Ruby/JRuby. Likely going to be harder with any other language due to Sikuli being Java-centric. And it works best if you are knowledgeable enough to work with Sikuli and Appium APIs. It's not going to work if you just blindly copy & paste code and follow tutorial blog posts or Youtube videos.

And for what I recommend, an example of how you mix or integrate separate tools into a test can be seen here, just replace WebDriver with Appium and AutoItDriver(Server) with Sikuli (API) in terms of methodology/technique in the analogy: 

https://github.com/daluu/AutoItDriverServer/blob/master/sample-code/SeleniumIntegrationTest.java

https://github.com/daluu/AutoItDriverServer/blob/master/sample-code/SeleniumIntegrationWithAutoItDriver.py

Bear in mind, Sikuli and Appium integration won't be quite like that example because there is no SikuliDriverServer (yet) to expose/wrap a WebDriver/JSONWireProtocol API to Sikuli's API. Maybe someone can help with that (I didn't get far and have yet to resume work on it).

**Comment by 907howard** [comment]
Hi David,


Thanks a lot for your kind suggestions,i will try you suggestion, what i am
confused is in what jars should i used in the project on eclipse.

On Tue, Nov 17, 2015 at 2:01 PM, David Luu <notifications@github.com> wrote:

> @907howard <https://github.com/907howard>
>
> From the discussion so far, there doesn't appear to be any integration
> sample code of Sikuli (or even OpenCV) with Appium. You'll have to build
> your own. The closest was this comment: #943 (comment)
> <https://github.com/appium/appium/issues/943#issuecomment-76963366>
>
> For a novice, the best option to start with is treat Sikuli and Appium as
> separate tools/libraries but use them together in your test (code) to
> achieve what you want to test. e.g. create an instance of Appium (driver)
> and an instance of Sikuli. In the test, have Appium do it's thing, then
> when you need Sikuli help because of Appium limitations, run the Sikuli
> code before resuming Appium code. When you get something like that working,
> then you can think about merging the codebase (if you're good enough to
> edit/hack Appium code).
>
> That suggestion works best if you work with Appium (and Sikuli) in Java,
> or Python/Jython, maybe Ruby/JRuby. Likely going to be harder with any
> other language due to Sikuli being Java-centric. And it works best if you
> are knowledgeable enough to work with Sikuli and Appium APIs. It's not
> going to work if you just blindly copy & paste code and follow tutorial
> blog posts or Youtube videos.
>
> And for what I recommend, an example of how you mix or integrate separate
> tools into a test can be seen here, just replace WebDriver with Appium and
> AutoItDriver(Server) with Sikuli (API) in terms of methodology/technique in
> the analogy:
>
>
> https://github.com/daluu/AutoItDriverServer/blob/master/sample-code/SeleniumIntegrationTest.java
>
>
> https://github.com/daluu/AutoItDriverServer/blob/master/sample-code/SeleniumIntegrationWithAutoItDriver.py
>
> Bear in mind, Sikuli and Appium integration won't be quite like that
> example because there is no SikuliDriverServer (yet) to expose/wrap a
> WebDriver/JSONWireProtocol API to Sikuli's API. Maybe someone can help with
> that (I didn't get far and have yet to resume work on it).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/943#issuecomment-157307973>.
>



-- 

Diana J Howard
QA Analyst
in.linkedin.com/in/dianajenniferhoward
Phone: +919740232254
Email: 907howard@gmail.com

**Comment by CiFinbar** [comment]
@907howard 
The following is an extremely rough hashed out example of how you can launch an app, look for login button and tap when found using sikuli and Appium client all in Java. Do not expect this to work if you run it, it's untested and very, very rough but will hopefully point you in the right direction. Anyone who want's to jump in and correct or add to the following, in anyway, is more than welcome :)

Use maven, add the following to your pom
```xml
        <dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.5.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>3.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.sikuli</groupId>
			<artifactId>sikuli-api</artifactId>
			<version>1.2.0</version>
		</dependency>
		<dependency>
  			<groupId>com.sikulix</groupId>
		    <artifactId>sikulixapi</artifactId>
		    <version>1.1.0</version>
		</dependency>
```
```
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;

import java.awt.image.BufferedImage;

import java.io.File;
import java.io.IOException;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.concurrent.TimeUnit;

import javax.imageio.ImageIO;

import org.apache.commons.io.FileUtils;

import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.remote.DesiredCapabilities;

import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import org.sikuli.script.Finder;
import org.sikuli.script.Location;
import org.sikuli.script.Pattern;
import org.sikuli.script.Region;

public class Login {
	
	private AppiumDriver<AndroidElement> droid;
	private int TIMEOUT = 90;
	private int count = 0;
	
	@BeforeClass
	public void setUp() throws MalformedURLException {
		
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("platformVersion", "4.4");
		capabilities.setCapability("deviceName", "1234567890");
		capabilities.setCapability("app", "/path/to/apk/OR/ipa");
		droid = new AndroidDriver<AndroidElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
		droid.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		
	}

	@Test(description="Launch app -> push login in button -> quit app")
	public void LoginInTest() throws InterruptedException {

		Finder loginFinder;
		Pattern buttonImg = new Pattern(Path/to/ImageOfButton.png);
		button.similar((float) 0.3);       //1.0 exact match, 0.3 70% less picky about exact matches

		//wait until login screen -> push login button if found
		for (int i=0; i<TIMEOUT; i++) {    //90 second timeout
			if (i%10 == 0) {       // check for button every 10 secs
				try {
					File currentScreen = getScreenShot();      //returns a file object
					BufferedImage bimg = ImageIO.read(currentScreen);
					loginFinder = new Finder(
							currentScreen.getAbsolutePath(),
							new Region(0, 0, bimg.getWidth(), bimg.getHeight()));
					loginFinder.find(buttonImg);
					if (loginFinder.hasNext()) {
						System.out.println("Success");
				                Location targetLocation = (loginFinder.next()).getTarget();
                                                droid.tap(1, targetLocation.x, targetLocation.y, 1);
						break;
					} else {
						continue;
					}
				} catch (IOException e) {
					e.printStackTrace();
				}
			} else {
				continue;
			}
			Thread.sleep(1*1000); //sleep 1 sec
		}
	@AfterClass
	public void tearDown() throws Exception {
		droid.quit();
	}
```

**Comment by daluu** [comment]
@CiFinbar thanks for sharing that sample code, will be useful to the community in the interim.

@907howard & others, if one has trouble using and integrating Sikuli (or OpenCV) with Appium for a test in the interim, one can try https://github.com/msanders/autopy, optionally with https://github.com/daluu/AutoPyDriverServer, as a workaround. Though that requires use of Python for tests unless one uses AutoPyDriverServer to drive it over RemoteWebDriver in any language rather than Python.

**Comment by dzaiats** [comment]
Hi, here is example of how to go with Sikuli and Appium.

**Comment by 907howard** [comment]
Hi where is the example please tell me?

On Mon, Dec 21, 2015 at 1:03 PM, Denys Zaiats <notifications@github.com>
wrote:

> Hi, here is example of how to go with Sikuli and Appium.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/943#issuecomment-166223333>.
>



-- 

Diana J Howard
QA Analyst
in.linkedin.com/in/dianajenniferhoward
Phone: +919740232254
Email: 907howard@gmail.com

**Comment by 907howard** [comment]
Ok I replied from my mail where there was no lin visible that you posted on
github.. Thanks il check the same

On Mon, Dec 21, 2015 at 1:05 PM, Diana J Howard <907howard@gmail.com> wrote:

> Hi where is the example please tell me?
>
> On Mon, Dec 21, 2015 at 1:03 PM, Denys Zaiats <notifications@github.com>
> wrote:
>
>> Hi, here is example of how to go with Sikuli and Appium.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/appium/appium/issues/943#issuecomment-166223333>.
>>
>
>
>
> --
>
> Diana J Howard
> QA Analyst
> in.linkedin.com/in/dianajenniferhoward
> Phone: +919740232254
> Email: 907howard@gmail.com
>



-- 

Diana J Howard
QA Analyst
in.linkedin.com/in/dianajenniferhoward
Phone: +919740232254
Email: 907howard@gmail.com

**Comment by dzaiats** [comment]
Link is specified in the comment. I updated the comment. Sorry for missing the link:)

**Comment by 907howard** [comment]
Ok I have genymotion emulator and there are games I have installed in the
emulator from playstore on it, so will I be able to automate them using
this method that you have shared here?

On Mon, Dec 21, 2015 at 1:07 PM, Denys Zaiats <notifications@github.com>
wrote:

> Link is specified in the comment. I updated the comment. Sorry for missing
> the link:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/943#issuecomment-166223703>.
>



-- 

Diana J Howard
QA Analyst
in.linkedin.com/in/dianajenniferhoward
Phone: +919740232254
Email: 907howard@gmail.com

**Comment by dzaiats** [comment]
Yes. You just need to specify correct flag to run tests with no app. Need to specify correct app name and package. And need to take correct part of pictures which You need to find on the screen.
You have to take different part of pictures for different sizes of the screen as it's described.
Anyway - You can play with this solution and modify it as You want for Your purposes.

**Comment by 907howard** [comment]
Hi @dzaiats ,I am not able to understand this part where in you mentioned the given below line:
How to run
"To run the sample test need to have pre-installed Maven 3 and Java 1.8 and need to execute next command from command line (example):

PLATFORM_NAME="android" APPIUM_VERSION="1.4.13" NAME="MyReaction" PLATFORM_VERSION="4.4" DEVICE="Nexus 5" APP="/Developing/Android/SignedApp/MyReaction.apk" mvn clean install"

How do I do that through command line? I have eclipse

**Comment by dzaiats** [comment]
Hi @907howard, You should download and setup Maven on Your computer and also be sure that Java version 1.8 is installed.
After You did correct configuration You have to open a command line and run the command specified in example. Just don't forget to change the path to the apk file which is in folder "./app/MyReaction.apk" because in example I specified this path to my local location.
To run everything from eclipse - just run it with TestNG plugin, like always for Appium tests.

**Comment by sayom88** [comment]
can anybody plz tell me how can i do image comparision using this Appium-Sikuli interface.

I have a scenerio wherein I need to capture an image from the app under test, preserve that image as a baseline image and then capture another image from that app under test and then perform an image comparison between these two images.

Can anyone guide me how to do this please.

**Comment by dzaiats** [comment]
Hi sayom88, You can use this framework http://dzaiats.github.io/appium-sikuli-driver/ 

But instead of looking for part of images which are collected in some folder You need programatically to take a screenshot, save it with some name and then use this screenshot for comparison. Also You can set similarity value in Sikuli for better matching.

**Comment by SnigdhaSuchismitaDash** [comment]
Hi Deny, I have downloaded the framework and try to run it. But it could
not find the image of left hand.

**Comment by dzaiats** [comment]
Hi SnigdhaSuchismitaDash, the example works only for devices with  screen resolutions specified in example.

**Comment by SnigdhaSuchismitaDash** [comment]
Hi Denys, Thanks for the quick reply.
How to know screen resolution of a device. I am using Galaxy Tab S.

**Comment by dzaiats** [comment]
Hi SnigdhaSuchismitaDash, 
As I found in google - resolution for this device is 2560x1600. You need to prepare Your own part of pictures that should be found

**Comment by SnigdhaSuchismitaDash** [comment]
Thanks Denys. can I use this code for an image which has black background
and white font colur

**Comment by dzaiats** [comment]
SnigdhaSuchismitaDash, to be honest, I don't know. Need to check. I know that it's working with different type of images. I would be greatful if You can verify it and post the result information to this topic.
Thank You!

**Comment by superkhung** [comment]
For python users, here's my sample code that using OpenCV Template Matching with defined template and buffered screenshot

```python
#Find image's x, y within screenshot with a defined template and return a centre point to click
def findByImage(imgBuff, templateImg):
    array = numpy.frombuffer(b64decode(imgBuff), dtype='uint8')
    img = cv2.imdecode(array, 0)
    template = cv2.imread(templateImg, 0)
    w, h = template.shape[::-1]
    res = cv2.matchTemplate(img, template, cv2.TM_CCOEFF)
    _, _, _, maxLoc = cv2.minMaxLoc(res)
    centre = (maxLoc[0] + (w / 2), maxLoc[1] + (h / 2))

    return centre
```
You can use it like this
```python
#Take ss as base64 buffer to avoid file saving to disk
ssBuff = self.driver.get_screenshot_as_base64()
#Find location to click with a template
loc = findByImage(ssBuff, 'template/template.png')
#Click on found location
self.driver.tap([loc])
```

For Mac users, you can test this easily by just install OpenCV from HomeBrew
`#brew install homebrew/science/opencv3`

**Comment by hardik-d** [comment]
any examples in ruby?

**Comment by drothlis** [comment]
If you're going to implement this in Appium directly, I'd recommend having a look at [**stb-tester**](https://stb-tester.com)'s image-matching implementation (in Python) [here](https://github.com/stb-tester/stb-tester/blob/v26/_stbt/core.py#L751-L801) for inspiration (source code is light on comments but `git annotate` has loads & loads of details). Stb-tester's matching algorithm has the following features:

* Uses OpenCV's [matchTemplate](http://docs.opencv.org/2.4/modules/imgproc/doc/object_detection.html?highlight=matchtemplate#matchtemplate) function which searches the entire frame and is very fast.
* Wraps the above in a Pyramid algorithm (i.e. trying the match at 3 different screenshot sizes) as an optimisation improvement (this brings the performance on Full HD frames to <40ms, i.e. real time for 25fps video).
* After the location is identified by OpenCV's `matchTemplate`, it runs an extra confirmation pass to eliminate false positives.
* Can find multiple matches if the image is present several times on the screen (good for finding buttons, menus, etc).

Stb-tester's API looks like this:

* [match](https://stb-tester.com/manual/python-api#stbt.match) returns a [MatchResult](https://stb-tester.com/manual/python-api#stbt.MatchResult) which is truthy or falsy depending on whether the image was found. It also has the coordinates of the match.
* You would pass the coordinates from the MatchResult into your `tap` function. This seems more composable than a separate `tapByImage` function.
* We have a function [wait_until](https://stb-tester.com/manual/python-api#stbt.wait_until) so that you can wait for an image to appear with `wait_until(lambda: match(...))`, you can wait for an image to disappear with `wait_until(lambda: not match(...))`. This is more composable than having separate "wait for image to appear" and "wait for image to disappear" functions. It's just very useful; you can wait for particular properties of your Page Objects to become true with `wait_until(lambda: MyLoginScreen().is_visible)` etc etc.
* [match_all](https://stb-tester.com/manual/python-api#stbt.match_all) returns a lazy list of matches if the image is present multiple times (in a single frame of video).

If you're writing your Selenium tests in Python you can use this today, at least on Linux -- see https://stb-tester.com/blog/2016/09/20/add-visual-verification-to-your-selenium-tests-with-stb-tester

For an Appium-native solution, a quick google shows that there are NodeJS OpenCV bindings out there. I imagine that it would be much easier to implement `match` in Appium than to integrate with Sikuli.

**Comment by jlipps** [comment]
@drothlis this is very helpful, thank you!

**Comment by pavanbachu0604** [comment]
@jlipps  I am considering of applying an image recognition framework to mine existing framework. Can you please guide me how to implement with Java Client

**Comment by saikrishna321** [comment]
@pavanbachu0604 there is no implementation on appium end. You can try something as @drothlis mentioned above or look into nakal( java and ruby client for image comparison)  

https://github.com/saikrishna321/nakal_java
https://github.com/rajdeepv/nakal

**Comment by mykola-mokhnach** [comment]
server implementation is finished. Client implementation is in progress:
https://github.com/appium/appium-base-driver/pull/235
https://github.com/appium/java-client/pull/990
https://github.com/appium/ruby_lib_core/pull/119
