### ISSUE TITLE
Common Android/Apple driver

### ISSUE THREAD

**Issue by WoodPlank** [appium/appium#9476]
## The problem

Is it possible to have a common android/apple driver object? Instead of managing two code bases I'd like to use the same driver for both android and apple. Is this possible?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.2.3
* Mobile platform/version under test: Android 7/iOS 11
* Real device or emulator/simulator: Real devices

**Comment by dpgraham** [comment]
The two are separate because they both use separate underlying technologies (XCUI for IOS and UIAutomator for Android). We have them as separate repos so that we can develop them and test them separately. The only way I could see us having a common driver would be if we wrote a driver for a cross platform technology (like React Native).

**Comment by WoodPlank** [comment]
Thanks, @dpgraham !
