### ISSUE TITLE
 Appium - Connection refused (Connection refused)

### ISSUE THREAD

**Issue by MaddySinghMaddy** [appium/appium#9518]
## The problem
I run my test scripts all the time on my machine using Appium server, but I getting the following issue every 2 to 3 weeks and it corrects itself automatically. There is not time limit on when it will correct itself. Following is the error - 

"org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 0.0.0.0:4723 [/0.0.0.0] failed: Connection refused (Connection refused)"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.2.0-beta.3 (1.2.0-beta.3)
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacBook Pro (Retina, 15-inch, Early 2013)
* Node.js version (unless using Appium.app|exe): v6.11.1
* Mobile platform/version under test:IOS - 10.3
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: 1.6.4

**Comment by mykola-mokhnach** [comment]
`Connection refused ` means the Appium server cannot handle the incoming request due to some reasons. It's hardly possible to find a reason for this, since it might be also related so some network/firewall issues or resource leaks.

I'd start with updating the server to the most recent available version.
