### ISSUE TITLE
Unable to rotate real iOS device after test runs

### ISSUE THREAD

**Issue by Nintendot** [appium/appium#9641]
## The problem

After running tests(Nightwatch) on real iOS devices, the orientation is locked even though the setting via UI indicates it's not

## Environment

* Appium version (or git revision) that exhibits the issue: **1.6.6**
* Desktop OS/version used to run Appium: **OSX 10.12.6**
* Node.js version (unless using Appium.app|exe): **8.4.0**
* Mobile platform/version under test: **iOS 10.3.3**
* Real device or emulator/simulator: **Real Device**
* Appium CLI or Appium.app|exe: **CLI**

## Appium log

https://gist.github.com/Nintendot/31291602d54dcce3eb34d354ce153cbd

**Comment by mykola-mokhnach** [comment]
I don't get what the problem is. You cannot change the device orientation manually after automation test has been executed or you cannot do in your test?

**Comment by Nintendot** [comment]
@mykola-mokhnach 
> You cannot change the device orientation manually after automation test has been executed

You got it

**Comment by mykola-mokhnach** [comment]
I don't think that anything can be done on Appium side in order to change then, since WDA anyway uses the XCTest methods, that Apple provides, in order to change the display orientation. There is only one thing, which can be changed:

```js
  async setInitialOrientation (orientation) {
    if (typeof orientation !== 'string') {
      orientation = 'PORTRAIT';
    }
```

this means that portrait orientation is set forcefully if it is not set explicitly in capabilities. Should we remove this default behaviour @imurchie ?

**Comment by imurchie** [comment]
We could. This was their to mirror how it worked with Instruments.
