### ISSUE TITLE
Appium 1.7.2 Android 7.0 do not support element.type key + "\n" and text(key).click

### ISSUE THREAD

**Issue by julia0423** [appium/appium#9687]
## The problem
The following methods do not work on Appium 1.7.2 Android 7.0(already update to uiautomator2), but they work on Android 6.0 or 5.0.
1.element.type(key + "\n") can not work

2.text("key").click can not work 

3.webview search list can not refresh

## Environment

* Appium version (or git revision) that exhibits the issue:1.7.2beta
* Last Appium version that did not exhibit the issue (if applicable):1.7.2beta
* Desktop OS/version used to run Appium:Mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:Android 7.0
* Real device or emulator/simulator:Real device and emulator
* Appium CLI or Appium.app|exe:Appium CLI

## Details
After trying, i find another methods instead the two issues which can work now except the third one.
1. element.type(key + '\n') can work instead of element.type(key + "\n")

2. xpath("//*[content-desc=key]").click can work instead of text("key").click 

3.when search list is webview can not refresh, the detail information:
the first time search with ".jpg" shows webview list result, but search with ".mp4" the webview still shows the previous result, only enter keyboard search button can refresh

## Link to Appium logs
https://gist.github.com/julia0423/7a6300b399cd74b9813d932c66db0f29

## Code To Reproduce Issue [ Good To Have ]
1.id('com.sap.jam.android:id/search_edtx').type ".jpg" + "\n"
2.text("Groups").click
3.id('com.sap.jam.android:id/search_edtx').type ".mp4" + '\n'

**Comment by mykola-mokhnach** [comment]
This is by design.

Regarding the frist issue - just check the source code and you'll understand what is happening there:
https://github.com/appium/appium-uiautomator2-server/blob/8774414fdd6b5b3b846039af12de78c9bd3b2bbd/app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java#L60

```java
            boolean pressEnter = false;
            if (text.endsWith("\\n")) {
                pressEnter = true;
                text = text.replace("\\n", "");
                Logger.debug("Will press enter after setting text");
            }
```

Regarding the second one: search implementation in UIAutomation1 was kind of hacky with different workarounds that were applied if the original locator didn't match anything. This has been deliberately deprecated in UIA2.
