### ISSUE TITLE
Unable to start WebDriverAgent session because of xcodebuild failure: "Could not proxy command to remote server

### ISSUE THREAD

**Issue by cappaji** [appium/appium#9741]
## The problem
Failed to create WDA session. Retrying... 
Followed the Steps provided in log by uninstalling the app and web driver agent from the device and reboot the device - Still not working.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6 
* Node.js version (unless using Appium.app|exe): v8.9.1
* Mobile platform/version under test: iPhone 6s platform: v11.1.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

Runs the IntegrationApp when build using Xcode but fails to run the Web Driver agent when the Test code is run against the Device

## Link to Appium logs
https://gist.github.com/anonymous/49cece2d57c1e16cd83f33bc832571df

## Code To Reproduce Issue [ Good To Have ]
Robot Framework Code using:

*** Settings ***

Library           AppiumLibrary

*** Variables ***
${REMOTE_URL}     http://127.0.0.1:4723/wd/hub      # URL to appium server
${PLATFORM_NAME}    iOS
${PLATFORM_VERSION}    11.1.2
${DEVICE_NAME}    iPhone
${APP_LOCATION}        /Users/cappaji/Desktop/IntegrationApp.app
${UDID}         ff54085a93c888d23ff24ee01884f30d3dbf44b3

*** Keywords ***
Open App
     Open Application    ${REMOTE_URL}    platformName=${PLATFORM_NAME}    platformVersion=${PLATFORM_VERSION}    deviceName=${DEVICE_NAME}    app=${APP_LOCATION}    automationName=appium    udid=${UDID}
Close All Apps
     Close All Applications

*** Test Cases ***
test_demo
     Open App
     Close All Apps

**Comment by mykola-mokhnach** [comment]
Add `showXcodeLog` capability to see Xcode output there.

**Comment by cappaji** [comment]
Please find the below gist which shows the Xcodelog as well. Thanks.

https://gist.github.com/anonymous/91dabaaed7324e1f650133212d919d4c

**Comment by ochubey** [comment]
1. Since real device is used - are you providing `xcodeOrgId` and `xcodeSigningId` as per [real-device-config](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) ? Because from the command it looks like you do not: `'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=ff54085a93c888d23ff24ee01884f30d3dbf44b3 IPHONEOS_DEPLOYMENT_TARGET=11.1' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'`;
2. Have you tried, in additiona to the fact that WDA was deleted from the device, reboot the device itself? Try `idevicediagnostics -u ff54085a93c888d23ff24ee01884f30d3dbf44b3 restart`

**Comment by cappaji** [comment]
I tried to add xcodeOrgId and xcodeSigningId. After that I have error -  Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". 
Please find the latest logs attached below.

https://gist.github.com/cappaji/fa7ed4110f1305e9e44f935306297193

**Comment by cappaji** [comment]
Even after manually configuring the Code signing as per - Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. I am unable to start WDA.
Below is the latest Xcode log attached. Please help me in resolving the issue.

https://gist.github.com/cappaji/91247942ca45ca164609c6c68fbc0349

**Comment by ochubey** [comment]
Have you tried to:
`ios-deploy --uninstall_only --id ff54085a93c888d23ff24ee01884f30d3dbf44b3 --bundle_id com.apple.test.WebDriverAgentRunner-Runner`

`idevicediagnostics -u ff54085a93c888d23ff24ee01884f30d3dbf44b3 restart`
