### ISSUE TITLE
npm install -g appium: Could not find Java's 'jar' executable on your PATH.

### ISSUE THREAD

**Issue by staplesj** [appium/appium#9835]
## The problem

I am trying to install Appium for the first time. I have downloaded npm 8.9.3.LTS and installed it.

Then, using the Node.js command prompt, I entered the following:

`npm install - appium `

(as described here: http://appium.io/introduction.html)

The system responds with an error:

`ERR! Selendroid Could not find Java's 'jar' executable on your PATH. Please ensure it is present and try running install again`

Question: what jar files is it expecting, and what PATH is it expected to be on?

## Environment

* Appium version (or git revision) that exhibits the issue: not known
* Last Appium version that did not exhibit the issue (if applicable): not applicable
* Desktop OS/version used to run Appium: OS Build: 16299.125
* Node.js version (unless using Appium.app|exe): 8.9.3
* Mobile platform/version under test: not applicable
* Real device or emulator/simulator: not applicable
* Appium CLI or Appium.app|exe: not applicable

**Comment by imurchie** [comment]
It is not, at this point, looking for any jar files, but rather the Java `jar` program. It needs to be available to to be executed, and to do that its location needs to be in the list of places the system looks for programs, the [PATH](https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them).

**Comment by staplesj** [comment]
More specifically - what file is it looking for?

**Comment by staplesj** [comment]
I have installed programs on my system:
Java 8 Update 151
Java 9.01 (64-bit)
Java(TM) SE Development Kit 9.0.1 (64-bit)

**Comment by staplesj** [comment]
OK. Have decided to close the issue. Installed with appium-desktop-Setup-1.2.7.exe instead.

**Comment by krissdap** [comment]
Hi,
I just got the same error message trying to install Appium on Windows 10.

Since this post is the first result showed up on Google search, I'd like to share a fix here, hope that you don't mind.

I simply had to add <code>"C:\Program Files\Java\jdk1.7.0_80\bin"</code> to Windows' <code>PATH</code> variable.
That is where <code>jar.exe</code> is located on Windows (yours may differs, depending on JDK version, etc.)

You'd have to start a new command prompt (assuming you're using Windows'<code>cmd</code>) for the new PATH variable to reflect the change.
