### ISSUE TITLE
Code stopped when AppinBackground is running

### ISSUE THREAD

**Issue by NateZ7** [appium/appium#9858]
## The problem

I want to send a notification from an Android device to an iOS one.
I login with both Android and iOS (Real devices), then I put app int bacgkround with the iOS and I want to sent the notification using the Android. The problem is when the app is in background in the iOS the Test doesn't continue until the duration of the appinbackground is done.

## Environment

appium 1.7.1 CLI
Mac

I would like to put AppinBackground for around a minute, and continue the code with the Android in order to send the notification while app is still in BG.

Any ideas ? Thanks !

**Comment by mykola-mokhnach** [comment]
Since Xcode9/iOS11 XCTest does provide some endpoints, which allow to work with multiple applications in scope of a single sessions. Some of these endpoints are currently available in appium@beta. Check https://github.com/mykola-mokhnach/appium/blob/cc5dd06829c5972cd7fbd62584c16f77583c7a73/docs/en/writing-running-appium/ios/ios-xctest-mobile-apps-management.md for more details.

Also, for your particular case, it might be useful to execute runInBackground method in a separate thread on the client side, so it does not block the stuff for Android.

**Comment by NateZ7** [comment]
@mykola-mokhnach  Thanks ! I used Threads and I'm currently able to do that. I have another problem now. When I scroll down for the notifications, Appium inspector shows me the elements of the screen below, but not the notification's one. I have to state that it worked and I messed something up. Thanks !

**Comment by mykola-mokhnach** [comment]
> I have another problem now.

Please create a separate topic for it in appium forum (since this is the place for issues).
