### ISSUE TITLE
Could not determine Xcode version

### ISSUE THREAD

**Issue by bbaitikova** [appium/appium#9874]
## The problem
Not able to run Appium for IOS platform. 

> WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.1
* Last Appium version that did not exhibit the issue (if applicable): first time run for IOS 
* Desktop OS/version used to run Appium: Mac sierra 10.12.6 (16G29)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: IOS 11.0.1
* Real device or emulator/simulator: Real Iphone X 
* Xcode version: Version 9.1 (9B55)

## Link to Appium logs

[Gist] : <script src="https://gist.github.com/bbaitikova/30825a1f58e88946ecb7b69c9fa8e737.js"></script>

```
    def setUp(self):
        desired_caps = {
            'noSign': True,
            'platformName': 'iOS',
            'platformVersion\n': "11.0.1",
            'deviceName': "My iPhone",
            'automationName': 'XCUITest',
            'app': self.mobile_app_md,
            'newCommandTimeout': 180,
            "autoGrantPermissions": True,
            # 'no-reset': False,
            #'udid': '2a4be1754edadbf09d5eb226d8893ca8b3e154a6',
            'full-reset': True
        }

        self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
        self.driver.implicitly_wait(100)
```

**Comment by bbaitikova** [comment]
I tried to restart my appium and xcode, even my computer. Still have error and have no idea what is wrong. Please, take a look and let me know what i am doing wrong.

**Comment by mykola-mokhnach** [comment]
Apple has recently changed some internal Xcode stuff related to version detection. You could downgrade Xcode or get the most recent beta version of Appium containing `appium-xcode` module version 3.4.1+

**Comment by anilwithrrs** [comment]
Hi @bbaitikova @mykola-mokhnach ,

I had resolved this same issue on my machine when i upgraded the appium version from 1.6.4 to 1.7.x and Xcode from version 8.2.x to Xcode 9.x

This issue comes when appium is not able to locate the current Xcode version.
For the resolution: First move all your Xcode from Applications to Trash, then install fresh 9.x Xcode version and move it to Applications, then restart your system, after that open terminal and do as mentioned below:

Run below mentioned command to check the installation and linking(active developer directory) of current Xcode version in Applications
xcode-select --install 
if Output of above is : command line tools are already installed, use "Software Update" to install updates 
then it is ok Otherwise install them using :
xcode-select —install , (this command opens a dialog for installation of the command line developer tools) 
After that, check current path of Xcode linking(active developer directory) in Applications
xcode-select -p
if the output says : /Applications/Xcode.app/Contents/Developer
Then it is ok otherwise, 

do as mentioned below:
Run this command in terminal with sudo to reset the Xcode linking=>
sudo xcode-select -r , this command resets to the default command line tools path

Now start your appium and enjoy :)

Regards,
anil

**Comment by bbaitikova** [comment]
@anilwithrrs, Thank you so much for your response. I followed your instructions and it works :) you save my time. 
Now it is failing with other error, but it is different bug. So, we can close this ticket. 

Thanks again. 
Happy New Year.

**Comment by siddhantraut** [comment]
@anilwithrrs perfect solution 

i did "sudo xcode-select -r" work sucessfully.

Thanks.

**Comment by siddhushettar** [comment]
You can set for 'Command line tool' in xcode.

<img width="409" alt="screen shot 2018-06-01 at 4 25 38 pm" src="https://user-images.githubusercontent.com/15659205/40867434-dff561ac-65b8-11e8-8c60-24348cf90d7a.png">

**Comment by sravanimadineni** [comment]
check the Appium version and Xcode version.
after you check for xcode-select --install(command line tools are already installed )and you have still same issue
removing the old tools ($ rm -rf /Library/Developer/CommandLineTools)
install xcode command line tools again ($ xcode-select --install).
uninstall Appium and install  then it will work
