### ISSUE TITLE
Document Appium W3C implementation for Appium stakeholders

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#9952]
Hello all. I wrote a document on my personal repo explaining how the W3C spec will work on Appium: https://github.com/dpgraham/appium-w3c-explanation/blob/master/README.md

It explains how to create sessions and what the expected REQUESTS are and what the RESPONSES will be. Feel free to have a look over and if you have an questions/concerns or feel that there things in the document that incorrect, leave a comment on this issue.

(cc: @imurchie @jlipps @mykola-mokhnach @KazuCocoa @TikhomirovSergey @sah @SrinivasanTarget @vmaxim)

**Comment by dpgraham** [comment]
If anyone thinks there is anyone else who needs to see this, mention them in this issue.

**Comment by KazuCocoa** [comment]
Looks good!
I think if we support `firstMatch` following the documentation, we need to implement it in client side since Python client and Ruby client put `{ [] }` as the `firstMatch` due to inherit selenium-webdriver. (as well as other clients?)

FYI: for `appium:` prefix
In Ruby and Python clients, `appium:` prefix will be added automatically except for W3C spec's capabilities. (If already added the prefix, they don't add the additional prefix.)

- Ruby: https://github.com/appium/ruby_lib_core/blob/c6f652817b9d1ad104002d067bfb0452074653aa/lib/appium_lib_core/common/base/bridge.rb#L119
- Python: After merging https://github.com/appium/python-client/pull/196
